### ISSUE TITLE
Error message in version 1.1

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#1]
![error](https://user-images.githubusercontent.com/25118004/47896588-77a6f780-de6e-11e8-9b37-96a422aedc9d.PNG)

I have the correct executable, and it was installed correctly in v. 1.0.

**Comment by Sh0wdown** [comment]
Oh, I renamed the backup-file-ending so if you still had v1.0 installed, v1.1 cannot find the original version anymore. That's an oversight from me.
How to fix: Renaming "Stronghold Crusader.exe.ori" into "Stronghold Crusader.exe" (overwrite) and reapplying v1.1 should work.
