### ISSUE TITLE
Another recruitment speed setting for the AI

### ISSUE THREAD

**Issue by Flechador** [Sh0wdown/UnofficialCrusaderPatch#10]
Hello, you currently released an recruitment speed setting for the AI's which allow all AI's to recruit as fast as the rat do. I like the idea of boosting the AI recruitment Speed but (as you already noted) some do lose their personalitys. Especially the Sultan. 
My question is now, if you could do an other recruitment speed setting which boost every individual recruitment Speed of the AI's a bit but not as fast as the rat's. With that, every AI would keep their personality and also would recruit a bit faster.

**Comment by Sh0wdown** [comment]
I agree, maybe I will add a slider where you can change it in like five steps or so.

**Comment by PitchNeeded** [comment]
Excellent, Sh0wdown! I actually recently made a new castle for myself for Sultan with a stronger economy (loads of poleturner workshops to sell spears and make money) and the idea was that I wanted him now to produce as many Arabian swordsmen as the Emir but because his recruitment speed is lower than Emir's, he doesn't really.

**Comment by Flechador** [comment]
> I agree, maybe I will add a slider where you can change it in like five steps or so.
That's an really neat idea, sounds pretty fascinating.

> I am worried though that some of the Arabian AIs who have expensive armies and already have fast recruitment speeds, Emir and Wazir particularly, would run out of gold if their recruitment was any faster, I don't think it would be good for their economies to hire troops any faster.
I cant say if that would be the case but some AI Lords do recruit a bit too slow for my taste, Sheriff for example.

**Comment by ByBurton** [comment]
This can be achieved via the aic files.
