### ISSUE TITLE
New AI opponent. Edit the old AI.

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#100]
Is it possible to create a new enemy AI? Well, or edit the old AI.

**Comment by PitchNeeded** [comment]
I would love to see a new AI opponent being made. I am sure if editing of AI troop types trained can be done, then all you would have to do is copy and paste all the coding for the economics and tactics of an existing AI, and change the troop types made and you would have a new AI.

**Comment by Lolasik011** [comment]
@PitchNeeded I also really want to see the new AI. I don't know how real it is.

**Comment by Panbutt** [comment]
Seeing if the existing AI behavior (troop types and industry buildings) can be changed or not first is a good stepping stone in that direction tbh.

**Comment by Lolasik011** [comment]
@Panbutt I hope Sh0wdown will come up with something.

**Comment by Sh0wdown** [comment]
Adding a new AI enemy seems too complex from my findings. Changing troops etc of the existing AIs should be possible though. Already existing posts about enhancing AIs:
https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/28
https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/8

**Comment by PitchNeeded** [comment]
Do we want to change troops of existing AIs too much though? They would lose their personalities, I think! I think mostly the troops they train are are OK as they are, but here are some changes that would be good though I think:

- Sultan if he is besieging an enemy with a moat, actually sending slaves to dig up that moat!
- Slightly larger groups of raiding pikemen for Richard and Wolf. Slightly larger groups of raiding macemen for Sheriff and Pig.
- Much larger groups of raiding monks for Abbot - big lines of monks to raid, up to 50 monks at a time to raid if he has a lot of gold.
- As mentioned before, Abbot creating a few fire ballistae in sieges, and maybe creating them at his castle every so often too and rolling up forward towards the enemy to destroy enemy buildings.
- Phillip's sieges need improved - he was King of France after all and seems too weak at sieging.  Archers and catapults to support the spearmen at least along with a few rams to try and breach the gatehouse so they can let the raiding knights in!
- Maybe a few assassins for Snake, that would fit with his personality as has been mentioned. However not too many as Snake's economy isn't that great so he wouldn't be able to afford too many expensive units.
- Some occasional assassin raids for Saladin so he can finally destroy more buildings.
- Emir's big Arabian swordsmen raids going directly to try and kill a lord if that lord is weak enough, chopping down walls to reach the lord if necessary. 
- Phillip using more defensive knights as has been mentioned before on another issue on here, he has enough stables to have more knights at a time than he does at the minute.
- Caliph sending a few horse archers to provide protection for his slave raids if he has enough gold

**Comment by PitchNeeded** [comment]
The best AI tactic change to introduce first would be Sultan sending slaves to dig up moats, I would like to see this in the next patch! Sultan is the only AI lord who doesn't send any units that can dig up moats and this definitely needs to change.

The slaves would advance alongside the Arabian archers to protect them.
