### ISSUE TITLE
 I got a bug !

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#102]
I received an error when installing the patch on the Russian version Stronghold Crusade !
![bug](https://user-images.githubusercontent.com/41998977/49677262-e7705980-fa8e-11e8-9c4f-716886e10660.png)

**Comment by Sh0wdown** [comment]
The Russian version has its own .exe? If you could send it to me via (on my [profile](https://github.com/Sh0wdown)) I could take a look.

**Comment by Lolasik011** [comment]
@Sh0wdown Ok.

**Comment by Lolasik011** [comment]
Could not throw on email, threw on the disk https://drive.google.com/open?id=10Yy17SWisdmP4e2by1gp1rdH3HDR0v01

**Comment by Sh0wdown** [comment]
Okay, I got it.

**Comment by Lolasik011** [comment]
@Sh0wdown 
You already took them.

**Comment by Lolasik011** [comment]
Is done ;)

**Comment by Lolasik011** [comment]
@Sh0wdown  What should I do?

**Comment by Lolasik011** [comment]
@Sh0wdown What about my bug ?

**Comment by Sh0wdown** [comment]
Will be fixed in the next Release.
