### ISSUE TITLE
Trader post free of cost

### ISSUE THREAD

**Issue by Sh0wdown** [Sh0wdown/UnofficialCrusaderPatch#106]
What would you think about removing the building costs (5 wood) of the trader post and making it completely free? I just spectated a game where Wolf's trader post was destroyed and his stockpile was full of stone, so he was unable to do anything.

**Comment by Lolasik011** [comment]
@Sh0wdown  Yes, a very good idea. As in Stronghold 2.

**Comment by Lolasik011** [comment]
It would be possible to create a mode so that all AIs have free buildings. :D

**Comment by ByBurton** [comment]
@Sh0wdown I think it would be a great idea.

**Comment by Sh0wdown** [comment]
Both

> @Sh0wdown just one Question. Free for Player and AI or only for AI?

Both

**Comment by Halbarad1** [comment]
Sounds really good. Especially for AI Battles it would be very usefull.

**Comment by Sh0wdown** [comment]
Will be included in the next release.
