### ISSUE TITLE
Autospeichern im Singleplayermodus

### ISSUE THREAD

**Issue by Halbarad1** [Sh0wdown/UnofficialCrusaderPatch#109]
Hi, 
nach dem neuen Video von Udwin ist mir aufgefallen, dass das reglmäßige Speichern deutlich vereinfacht werden könnte, wenn man auch im Einzelspielermodus Autospeichern könnte.  
Gleiches gilt für den Modus "Keine Eile", der ja eventuell auch eingefügt werden könnte.
Viele Grüße und weiter so! :)

**Comment by Sh0wdown** [comment]
Der nächste Release wird Quicksaves mit sich bringen.
