### ISSUE TITLE
Mod Version Display Improvement: Configuration Hash

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#11]
The mod version already is displayed ingame next to the game version, yet a single version of the mod yields many different possible configurations as any user may (de)select various different settings while installing the mod. 

Hence, it might be cool to have some sort of additional display that reflects what configuration is in effect. Especially in order to find out reasons for "compatibility issues" between different same-version configurations in multiplayer, being able to perform a quick "sanity check", i.e. compare the configuration values for players experiencing issues could help quickly clear up what went wrong. 

As it would be very hard to get a full configuration list to appear ingame, maybe some sort of short hash value of all options could work? 
The hash values only need to be unique/different (and (alpha)numeric and not too long, to make display and comparison by humans feasible, but that should be a fairly easy to solve requirement) for every possible configuration of the same version of the mod. They may or may not change "arbitrarily" from version to version, as in that case comparing the version number is enough for players to know there's some difference.

**Comment by Sh0wdown** [comment]
Meh, too much work . :P
