### ISSUE TITLE
Allgemeine Verbesserungen für Stronhold Crusader

### ISSUE THREAD

**Issue by Xander10alpha** [Sh0wdown/UnofficialCrusaderPatch#110]
#110 Stronghold Crusader Verbeserungen by Xander10alpha

WICHTIGE Verbesserungen:

- Grabverhalten der KI verbessern. Ich meine damit, dass Truppen der KI nur ein Paar zu ausgraben
geschickt werden und das Wellenweise. Sie soll alle/mehr Truppen zum Ausgraben schicken.

- Mehr Truppen sollen graben können besonders Arabische: Mönche, Schleuder-
Schützen, Arabische Bogenschützen sollen graben können.
(Einige KIs können gegen einen Graben nichts machen z.B. Sultan, Emir)

- Direktes Abziehen von Truppen nach einem Kill. Die KI zieht ihre
Truppen erst sehr spät ab (Beispiel Sultan) nachdem sie jemand getötet hat.
Dabei gehen viele Truppen down, was vollkommen unnötig ist.
Beispiel siehe die Videos von Tatha unten.

- Supportverhalten der KIs: Die KIs sollen untereinander Güter und Geld verschicken
können. Ebenso kann der Spieler Geld anfordern. Z.B. kann man als Restriktion (damit
KI nicht Pleite geht und selbst kaputt geht) das die KI mindestend 10000 oder 5000 Gold
nachden angeforterten Betrag hat: Beispiel Abt hat 20000 Gold Spieler/KI fordert 5000 
Gold an und bekommt dies, da 15000 Gold übrig bleibt. KI soll auch den Spieler Gold 
anfordern können.

- Hilfeforderungen unter KIs: Die KI soll anderen KIs Hilfe anfordern können. Ist sie
stark unterdruck bekommt der Spieler eine Forderung zur Hilfe, diese sollen auch die
anderen KIs im selben Team bekommen. Annehm- und Ablehnverhalten ähnlich oder genauso,
wie beim Spieler.

- Bogenschützen verhalten verbessern: Bestes Beispiel sind die Videos von Tatha in Teil 2
besser und öfters zusehen, das die KI sinnlos ihre Bogenschützen verheißt, obwohl sie
diesen vor dann Schießen und dann wieder vorrücken move machen können. Vielleicht ist es
möglich dies zu modifizieren besonders bei angriffen.
Hier sind die Videos von Tatha, wo es gut zu erkennen ist.
Teil 1: https://youtu.be/ZV5Ft3KOKg8
Teil 2: https://youtu.be/zAufjxEB-Xs

- Bugfix des unendlichen Spawen versuchen zu beheben, sodass das auch nicht nur nachdem Laden
wieder funktioniert sondern sonst auch. Aber dies hat Zeit

- KI soll ihre Türme reparieren können. Hat sie genung Stein soll sie die Türme und Torhäuser
reparieren können.

- Der Angriff der KI soll noch fokussierter auf (besonders auf) Torhäuser und Türme gehen statt Mauern.

- Die Angriffe der KIs werden immer stärker aber irgenwann ist das Fernkämpfer Limit erreicht. Kann man
das erhöhen oder auf unedlich setzen? Fernkämpfer sollen allgemein mehr sein für angriffe. Das macht
die KI deutlich gefährlicher. Beispiel setzt das Schwein kaum bis keine Armbrustschützen ein für ein 
Angriff das mach ihn ziemlich schwach, da die Burgverteidigung voll da ist und nicht geschwächt wird.

- Kombiangriffe: Wenn die KI angreift, soll sei einen Angriffs Befehl an alle anderen KIs und Spieler
senden im selben Team senden. Soll ähnlich bis genauso funktionieren, als wenn ein Spieler die KIs einen 
Angriffsbefehl gibt. Will oder kann die KI nicht angreifen soll die andere KI trotzdem angreifen.
Sendet sie ein Jahr greift sie trotzdem an ohne zu warten. (Ich denke mit warten wäre das sehr schwierig
dashalb lass ich es raus, wäre aber extrem cool wenn die eine auf die andere Wartet)

- Notfallrekurtierung: Wenn die KI in Gefahr ist, soll sie alles in Truppen und Waffen investieren.
Sozusagen für einen letzte Verteidigungsarmee. Es ist schon oft vorgekommen, das die KI einen Angriff startet und selbst angegriffen wird und stirbt. Da sie währenddessen keinen Truppen Rekurtiert und Geld spart. Wenn sie aber in Gefahr ist soll sie trotz des Angriff Truppen Rekurtieren zur Verteidigung. Das mit den Zurückziehen soll so bleiben nur das mit den Rekurtieren zur Verteidigung soll eingefügt werden.

KI-Stärkungen:
Hier weiß ich leider nicht, ob das auch verändert werden kann oder ob das mit Burgen verändert
werden können:

- Allgeimeines Trumgeräte Einsschränken von 3 auf unedlich setzen, sodass jede KI Theoretisch
unedlich viele bauen kann.

- Philipp: In fehlt ein Steinbruch, da er sonst komplett nutzlos ist und sich die Steine
für seine Türme und Tore kaufen muss. Er baut schon sehr viel Stein daher fehlt im mindestens
einen Steinbruch. Ich würde zwei bevorzugen aber das sollte man testen.

- Marshall: Fehlt ebenfalls einen Steinbruch, um effektiv zu werden und schneller Angriffe
zu fahren. Es dauert einfach zu lange.

- Sultan: 3 oder 2 Apfelfarmen geben, damit er sich nicht alles kaufen muss.
er ist schon so schwach daher ist diese Unterstützung angemessen ist. Es ist ebenfalls 
nicht ausreichend, davon alleinen die Bevölkerung ZUfrieden zustellen.

**Comment by Monsterfisch** [comment]
mit dem tool hier kannst du die dateien öffnen anschauen exportieren importieren etc =) 

http://stronghold.heavengames.com/downloads/showfile.php?fileid=4474&ci=5122df26e9510b99813b1ed9be24e13fYToxOntpOjA7YToyOntpOjA7czoxNDoiU2VhcmNoIFJlc3VsdHMiO2k6MTtzOjM1OiJsaXN0ZXIucGhwP3N0YXJ0PTAmYW1wO3NlYXJjaD1pbWFnZSI7fX0=

**Comment by Xander10alpha** [comment]
Danke dir Monsterfisch :)

Ich glaub ich erstelle mal einzelnen Issues, damit es übersichtlich bleibt.

**Comment by Sh0wdown** [comment]
> Ich glaub ich erstelle mal einzelnen Issues, damit es übersichtlich bleibt.

Ich bitte darum. :P
