### ISSUE TITLE
Still stehen - Während des Angriffs

### ISSUE THREAD

**Issue by Swartonf** [Sh0wdown/UnofficialCrusaderPatch#112]
Ein weiteres Problem existiert mit den Angriffen, vielleicht kann man dies relativ leicht fixen.
Ein Angriff sieht folgendermaßen aus:

1) Angriff formiert sich irgendwo
2) Belagerungsgeräte werden vor die gegnerische Burg gesetzt, weitere Einheiten folgen dicht hinter ihr.
3) Ca. 4 Sekunden nachdem die Katapulte und Triböcke zerstört sind  (was auch dauert), greift die infantry an. 

--> Problem hier: Da die Infaterie direkt hinter den Belagerungseinheiten stand und wartet bis diese zerstört werden, bekommt sie riesige Verluste während sie auf ihren Einsatz wartet. Sie wird kontinuierlich von gegnerischen Einheiten getroffen, ohne dass sie ihren Angriff startet. Bei meinem Wolfkampf, den ich eben simuliert habe, war es der Fall, dass er nur mit 50% der Ursprungseinheiten angegriffen hat. Die anderen wurden stillstehend bereits getötet.

Lösung? Lasst die Infanterie und die Belagerungseinheiten zeitgleich angreifen. Falls die Katapulte ein Loch in die Burg schießen, reagiert die Infanterie eh darauf. Zeitgleich gehen sie dann in den Kampf, ohne erstmal 15 Sekunden lang von den Feinden stillstehend dezimiert worden zu sein.

Vielleicht lässt sich das auch mit dem Bereits angesprochenen Bogenschützen-Bug koppeln. Das Bogenschützen ihren Angriff nicht beenden und somit die AI keine Soldaten mehr rekrutiert.

**Comment by Halbarad1** [comment]
Naja also grundsätzlich finde ich das System wie es ist nicht schlecht, denn ansonsten schießen die KIs immer wieder ihre eigenen Einheiten mit Katapulten ab. Außerdem wird der Angriff mit Nahkämpfern verlustärmer, wenn bereits vorher feindliche Türme mit Bogenschützen zerstört wurden (was halt seine Zeit dauert). Außerdem verhindern die Nahkämpfer, dass der Feind mit einem Ausfall direkt die Belagerungsgeräte zerstören kann. 

Problem ist in deinem Fall wohl eher gewesen, dass die Katapulte in Reichweite der feindlichen Bogenschützen und damit zu nah an der feindlichen Burg gebaut wurden?!

**Comment by Swartonf** [comment]
Die Katapulte auf dem Boden haben nicht die größte Reichweite.
 In einem 1-1 Match werden die gegnerischen Einheiten stehend von Turm-Ballisten, S

**Comment by Monsterfisch** [comment]
ich denke das hauptproblem bei angriffen ist nicht das die truppern durch beschuss verher reduziert werden sondern welche burg sie meistenst versuchen anzugreifen denn oftmals ist es nicht die am "nächsten" ist sondern eine inmitten von weiteren gegnern die die einheiten dann einfach abschießen können die ki sollte also demnach versuchen den die mauern/gener anzugreifen auf den sie zu erst trifft nicht der der am nächsten zu ihrem bergfired sietzt da dieser durch gelände nur durch umwegen und andere gegener erreichbar ist. (Vorrausgesetzt das dies so einfach möglich wäre) man könnte dann auch noch versuchen dafür zu sorgen das die belagerungsgeräte und einheiten weiter von den gegnerischen struckturen entfernt stehen um feinbeschuss zu minimieren. was denke ich sehr sinnvoll wäre bedenkt man das ab und an die ki ire belagerungsgeräte und einheiten entweder viel zu nah oder außer reichwete aufstellt was den angriff so gu wie nutzlos macht

**Comment by Krarilotus** [comment]
Parameter unknown130 is responsible for the waiting delay after siege equipment has been constructed. Apart from that, the bug that AI's troops idle or get stuck on attacks can be discussed in#104
