### ISSUE TITLE
Make Caliph, Wazir and Emir horse archers move around in front of walls during sieges.

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#114]
You have probably noticed that Caliph, Wazir and Emir just keep their siege horse archers in one place in front of the wall during a siege, unless there is a gap in the enemy castle wall. It would be good if it could be made so they could move them around a bit during a siege in front of the enemy walls, it would make it harder for defending missile troops to kill them.

**Comment by ByBurton** [comment]
You know. Why limit that to those ai lords?
I would let every ai lord do that. No matter if Rat, Wolf or Marshal.
Every lord that uses ranged units during sieges should also attack with them, and not just protect the siege engines and troops while gathering.

**Comment by PitchNeeded** [comment]
> You know. Why limit that to those ai lords?
> I would let every ai lord do that. No matter if Rat, Wolf or Marshal.
> Every lord that uses ranged units during sieges should also attack with them, and not just protect the siege engines and troops while gathering.

I mentioned Caliph, Emir and Wazir as they use horse archers which can fire while moving, and even if their horse archers are advanced properly they just keep them in one position during sieges in front of the enemy wall (meaning they are easy for defending missile troops to kill) rather than moving them around like Saladin in front of the enemy wall. It would be better if they moved them around more during sieges.

**Comment by ByBurton** [comment]
Ah okay, now it makes more sense to me. But still, my addition is kind of related to this issue.
Because it is the same mechanism.

**Comment by ByBurton** [comment]
This can be closed as there is a value in the aic file that you can edit to do that.

**Comment by PitchNeeded** [comment]
Which one is this aic value?

**Comment by ByBurton** [comment]
Just set the "AttUnitRangedPush" (oder in meiner Version vom ucp: "AttUnitPatrol")

**Comment by ByBurton** [comment]
Closing this as you can just easily do this with aic files.
