### ISSUE TITLE
AI should recruit more units for castle defence

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#117]
As probably everyone here knows, all AI lords, but some especially, are pretty weird when it  comes to static castle defenders.

Let us take the Rat for example: It seems to put some men on the walls when the game starts, and then some more the first 5 minutes. But then later in the game they seem to almost never be replaced when killed. Also they are just too few.
This seems to be the case for every AI lord, although some seem to be able to put more men on the towers / walls.
Now, I would love if this behaviour would be improved.
Have the AI always try to replace their dead defenders as soon as possible. Highest priority probably.
Increase the number of units each ai opponent places on the walls / towers. Especially for: Rat, Philip, Richard.

I have already mentioned that in #5 . But I feel like it reaches more people here.

Edit: I know this could be bad for AI vs AI matches, as they already have difficulties sieging each other.
Improving their defensive power would just lengthen most matches. But I believe it would still be a very nice addition.

**Comment by Panbutt** [comment]
Agreed. Certain AIs simply take waaaaaaay too long to retrain killed tower crew. Sheriff, Marshal and Saladin also suffer from this where they simply take so dang long to to retrain tower archers that they might as well not.

Something else to consider (Somewhat Off Topic) is to remove the hard limit of ranged units certain AIs can train for attack forces. This can be observed with Richard, Rat and Marshal. They train very little archers even if they have an extremely large army, removing that weird limit could allow them to counter tower crews better. Balance out better defenses with better sieges.

**Comment by PitchNeeded** [comment]
It would also be good if Saladin, Emir and Wazir could use some slingers on their towers alongside their archers. Slingers are cheap and quite good against melee troops attacking walls below compared to archers. Slingers would also be good against any enemy horse archers that came too close to the walls.

**Comment by ByBurton** [comment]
> It would also be good if Saladin, Emir and Wazir could use some slingers on their towers alongside their archers. Slingers are cheap and quite good against melee troops attacking walls below. Slingers would also be good against any enemy horse archers that came too close to the walls.

The Caliph was meant to use them.

**Comment by PitchNeeded** [comment]
> > It would also be good if Saladin, Emir and Wazir could use some slingers on their towers alongside their archers. Slingers are cheap and quite good against melee troops attacking walls below. Slingers would also be good against any enemy horse archers that came too close to the walls.
> 
> The Caliph was meant to use them.

I think I remember now seeing that on his AIV castles before.

I am thinking that some slingers on towers along with the archers would be good for Emir particularly, as he struggles to fire at units attacking his walls and doesn't have pitch or moats in his vanilla castles. Wazir, Saladin and Sheriff could also benefit from some too!

**Comment by ByBurton** [comment]
Every single AI would be much harder to siege, if they had decent manned walls & towers. 
And if they would give defensive units priority above everything else.
(If a defensive unit is missing, replace it instead of recruiting for a siege, harassment or economy defence squad)

**Comment by PitchNeeded** [comment]
They could also use portable shields on towers too, like many human players do!

**Comment by ByBurton** [comment]
> Yep all of them apart from Nizar, Snake and Marshall (who already man their towers well)


That is actually not completely true. Nazir only mans the view towers he has well. Not exceptionally well.
I would still say ALL of them should increase their defensive units and focus more on retraining lost ones.

**Comment by Sh0wdown** [comment]
Fixed in v2.11 and now editable with AICs.
