### ISSUE TITLE
Zu wenig Truppen Graben aus

### ISSUE THREAD

**Issue by Xander10alpha** [Sh0wdown/UnofficialCrusaderPatch#118]
Mir ist aufgefallen beim Kosequenten testen, dass die KI maximal 3-5 Gräber schickt. Die versuchen dann auszugraben.... Das ist einfach zu wenig. Kann man nicht einfach die Anzahl erhöhen oder einfach alle losschicke die ausgraben können? Okay vielleicht wenig bis keine Fernkämpfer außer die KI hat nichts anderes z.B. Friedrich...

Interessant ist nur das die KI überhaupt Gräber schickt außer Sultan... Obwohl das muss ich noch ausführlicher testen, wer überhaupt keine Gräber losschickt außer er.

**Comment by Heroesflorian** [comment]
> Interessant ist nur das die KI überhaupt Gräber schickt außer Sultan... Obwohl das muss ich noch ausführlicher testen, wer überhaupt keine Gräber losschickt außer er.

Ratte, Richard, Schwein graben z.B. allesamt nicht, obwohl ihre Truppen prinzipiell könnten. 

Sultan schickt im Gegensatz dazu sogar sehr wohl Truppen zum Graben los. Wenn seine Burg Burggräben enthält, bildet er speziell dafür 2 Sklaven aus (die er falls nötig auch zeitnah wieder ersetzt), die dann buddeln, sogar bei Verbündeten.

**Comment by Xander10alpha** [comment]
> Ratte, Richard, Schwein graben z.B. allesamt nicht, obwohl ihre Truppen prinzipiell könnten.
> 
> Sultan schickt im Gegensatz dazu sogar sehr wohl Truppen zum Graben los. Wenn seine Burg Burggräben enthält, bildet er speziell dafür 2 Sklaven aus (die er falls nötig auch zeitnah wieder ersetzt), die dann buddeln, sogar bei Verbündeten.

Ich bin nochmal jede KI durchgegangen. Ich habe eine eigene Test Map erstellt, wo die KI graben muss um den Lord zu besiegen.
Alle haben ihn besiegt außer Sultan. Er hat nie Sklaven ausgebildet. Alle andern sind durch gekommen.

Spiele mit der Steam Version 1.41.

**Comment by Xander10alpha** [comment]
Kann ich schließen, da es in der AIC gelöst wurde.
