### ISSUE TITLE
Absolute Notfallrekurtierung beim Angriff

### ISSUE THREAD

**Issue by Xander10alpha** [Sh0wdown/UnofficialCrusaderPatch#119]
Sehr oft ist es schon passiert, das die KI angegriffen hat und kurz danach durch einen anderen Angriff stirbt. Ich finde es gut das die KI allgemein nicht ausbildet. Und ist sie stark unterdruck bricht sie ihren Angriff ab und zieht die Truppen zurück. Aber das ist zu langsam...
Ich finde sie soll trotzdem ausbilden aber nur, wenn sie in Gefahr trotz, wenn sie Angreift.

Ich beschreibe das als absolute **Notfall Rekurtierung**. Sie soll alle Ressourcen für ihr überleben ausgeben und einfach nur Truppen rekurtieren.

**Comment by Xander10alpha** [comment]
Dann muss ich nochmal genauer testen.
Im Normalfall tut sie das auch, außer sie ist gerade am angreifen.
Vielleicht hatte die KI ja auch kein Geld mehr und ich hab das nicht mitbekommen.
Ich geh der Sache nochmal auf dem Grund.

**Comment by Heroesflorian** [comment]
> Macht die KI das nicht schon? Sobald sie sich bedroht fühlt, zieht sie sämtlich Angriffstruppen zurück. Normalerweise spammt sie dann auch Truppen, was man daran erkennen kann, dass europäische Lords immer +5 Waffen kaufen. Tut sie das etwa nicht beim Angriffsabbruch?

Es kommt jedenfalls teilweise vor, dass sich die KI eben einfach nicht bedroht fühlt, wenn sie den eigenen Angriff gerade erst gestartet hat - frei nach dem Motto "ich hab ja noch genug eigene Truppen, um mich nicht bedroht zu fühlen" - und schickt dann genau diese eigenen Angriffstruppen eben weg, und hat dann ggf. tödliche Probleme.
