### ISSUE TITLE
AI - Wachstumsrate der Angriffe

### ISSUE THREAD

**Issue by Swartonf** [Sh0wdown/UnofficialCrusaderPatch#12]
Moin,

mit dem vorletzten Update wurde die maximale Angriffstärke der KI's erhöht, indem man das Truppenlimit aufgestockt hat. Das Problem ist hierbei aber noch, dass das Wachstum der Angriffe gleich geblieben ist. 

Mir ist derzeit noch nicht bewusst wie diese Angriffstärke steigt, es könnte prozentualer Natur sein (z.B. 5% Wachstum) oder flacher natur (z.B.) 7 Einheiten mehr pro Angriff. 

In jedem Fall brauchen die KI's jedoch unglaublich lang, um eine höhere Gruppenanzahl aufzustellen. Das habe ich in einigen Tests zumindest feststellen können. Darum würde ich es vorschlagen, dass die Angriffe schneller  auf ein gefährliches Niveau kommen, als dass die AI's weiterhin ihr Geld in minimal größere Angriffe verschwenden. 

Falls jemand das ähnlich sieht könnten hier wir über Vorschläge dieser Wachstumsrate reden.

lg

**Comment by Heroesflorian** [comment]
Was das angeht, hielte ich, natürlich nur falls machbar, auch eine Koppelung der Wachstumsrate für Armeegrößen an A) KI-Typ und/oder B) Goldvorräte für sinnvoll. 
Mit 40k Startgold (und entsprechend noch recht hohen Goldvorräten, nachdem die Burg steht) kann eine KI schließlich durchaus flotter an Angriffsstärke zulegen (und sollte es auch, der ein oder andere Gegner hat mit 40k Startgold ja auch sehr schnell eine gute Defensive hochgezimmert, die kleinere Angriffe schlichtweg schluckt, ohne mit der Wimper zu zucken). Wenn eine KI dagegen erstmal mit wenig Rohstoffen lange Zeit gerade so am Existenzminimum herumdümpelt und sich schon anstrengen muss, um überhaupt mal angreifen zu können, sind kleinere Angriffe (bzw niedrigere Wachstumsraten) sinnvoller. 
Und auch im Endgame haben einige KIs oftmals zig- und gar hunderttausende Goldmünzen ungenutzt rumliegen, greifen aber trotzdem noch sehr lange / oft mit vergleichsweise geringen Armeen an. 
Dazu kommt, dass manche KIs (z.B. Ratte, Schlange, Sultan, Abt) verhältnismäßig schwache Truppen aber dafür in großer Zahl verwenden. Für die ist eine höhere Wachstumsrate nötig, als für beispielsweise Richard, der allein dadurch, dass er schwergepanzerte Truppen und viele Belagerungsgeräte einsetzt, auch mit kleineren Armeen schon ordentlich Schaden anrichten kann und zudem stark von schnelleren/häufigeren Angriffen profitiert als z.B. eine Ratte, deren kleinere Angriffe in der Regel gar nicht erst die feindliche Burg erreichen, bevor sie bereits zerschlagen sind.

**Comment by Swartonf** [comment]
Ich habe auch mal fleißig nachgezählt. In einem Kampf gegen die Ratte, beide 10k Gold, hat sie durchschnittlich jeden Kampf ihre Angriffstruppenzahl um 6 erhöht. Einmal ganz zu anfang um 12, ein mal gleichbleibend, die anderen male 6.
Sie startete mit 21 Truppen. 

--> Nach 10 Angriffen ist sie ca 80 Mann Stark
--> Nach ewigen 100 Angriffen wird sie eine Truppenstärke von ca. 620 haben

Mein Verbesserungsvorschlag ist, die KI's Truppenanzahl Prozentual bei jeder KI zu erhöhen, anstelle sie Linear mit 6 zu steigern. Bei einem Wert von 15% Steigerung pro Angriff sähe es so aus: 21* (1,15^x)

Erster Angriff =   21 Truppen
Zweiter Angriff = 24 Truppen
Zehnter Angriff= 84 Truppen
Zwanzigster Angriff = 347 Truppen
25ter Angriff =     691 Truppen


Natürlich wäre eine 20%-Steigerung pro Angriff auch möglich, um schneller auf genannte Gruppengrößen zu kommen. Das Earlygame könnte mit 15% zu einfach sein.

**Comment by Sh0wdown** [comment]
Mit 2.04 können jetzt die Raten der zusätzlichen Angriffstruppen verdoppelt werden.
https://github.com/Sh0wdown/UnofficialCrusaderPatch/releases/tag/v2.04

Meinen Nachforschungen zufolge agiert die KI im Allgemeinen so:

Die Mindestanzahl von Truppen für den nächsten Angriff wird einmal nach jedem Angriff festgelegt, und zwar wie folgt:

Hat die AI über 10000 Gold?
=> Mindestanzahl = Anfangszahl + 7 * Angriffsnummer
Wenn nicht dann
=> Mindestanzahl = Anfangszahl + 5 * Angriffsnummer

Die Angriffsnummer wird selbstverständlich nach jedem Angriff um 1 erhöht.
In 2.04 wurden die Werte von 7 auf 16 und 5 auf 8 gesetzt.
Die Anfangszahlen betragen:

- rat => 20
- snake => 30
- pig => 10
- wolf => 40
- saladin => 50
- kalif => 15
- sultan => 10
- richard => 20
- frederick => 30
- philipp => 10
- wazir => 40
- emir => 30
- nizar => 40
- sheriff => 50
- marshal => 10
- abbot => 50

**Comment by MarcusVipsaniusAgrippa** [comment]
That is a really great feature! It now means that every AI will be a challenge to the player from now on, even if it's "just" a snake! 
Is there any chance you'll find out how to scale the amount of siege equipment and the support troops (e.g. assassins, archers and crossbowmen etc.)?

**Comment by PitchNeeded** [comment]
> That is a really great feature! It now means that every AI will be a challenge to even the strongest AI or the player from now on, even if it's "just" a snake!

Yep tested it out with some of the AIs and after a while, saw a big line of about 40 or 50 Arabian swordsmen coming for my ally Caliph, assumed it was Emir who was also on the enemy side but it was actually the humble Sultan when I checked the troop colour! 😄 Even he can be a big threat now!
