### ISSUE TITLE
Warenlager menge pro platz erhöhen ?

### ISSUE THREAD

**Issue by Blade1243** [Sh0wdown/UnofficialCrusaderPatch#121]
Grüße dich :D 

ich hatte mal gefragt ob man eine art auto sell option für den marktplatz machen kann wenn mann z.b. 50 einheiten von einer ware hat. dies war ja nicht möglich weil es hart gecoded war wemm ich mich recht erinnere :3 

ich hab mich letztes mal beim spielen von crusader mal ausgelassen und eine ziemlich große wirtschaft aufgebaut 120+ siedler. und wenn man da in im spiel tempo 90 und drüber spielt ist es einfach nicht mehr möglich sich um seinen lager platz und waren zu kümmern sie zu verkaufen und und und xD

lange rede kurzer sinn XD mir kam derf einfall jedes lager hat 4 plätze für waren die mit einer gewissen menge waren gefüllt werden kann. 

kann man den lagerplatz pro ware erhöhen ? sagen wir mal keine ahnung 100 pro waren platz ? (oder mehr das liegt ja schluss entlich bei dir xD )

oder ist das auch hardgecoded oder wie man das nennt ?

liebe grüße

**Comment by Sh0wdown** [comment]
Das was der Patch macht ist das "hardgecodete" zu ändern. ;)
Den Auto-Marktplatz-Thread hast du ja schon entdeckt, sowas ist nur leider recht kompliziert.
Den Platz erweitern werde ich denke ich nicht machen, bau doch einfach mehr Lagerplätze. :P

**Comment by Heroesflorian** [comment]
Die Lagermenge pro Platz zu ändern fände ich persönlich auch nicht so gut. 
Zum einen kann man ja eben einfach mehr Lager bauen, zum andern sieht man derzeit genau, wie viele Waren in den einzelnen Warenstapeln liegen. Erhöht man das jetzt einfach, kann man das nicht mehr sehen bzw. abschätzen, und das würde sich für mich irgendwie kaputt anfühlen. 
Und last but not least... das Rohstoffmanagement gehört eben auch zum Spiel. Aktuell kann man es sich ja bereits halbwegs leicht machen, wenn man ein großes Lager baut, aber das komplett irrelevant zu machen... nee, finde ich nicht so gut.
