### ISSUE TITLE
Bug-report/Vorschlaege

### ISSUE THREAD

**Issue by EchoRevora** [Sh0wdown/UnofficialCrusaderPatch#125]
Hi, erstmal muss ich echt den Hut ziehen, einfach genial was du hier erreicht hast. Habe hier einen Bugreport und einen Vorschlag:

[Bug]
Spielerfarbe:
- Wenn man eine andere Farbe als rot hat, sind Einheiten anfangs in rot und faerben sich dann innerhalb von einer Sekunde in die gewaehlte Farbe um. Ebenso, wenn die Truppen in Tuerme/Torhaeuser gehen. Dasselbe passiert auch bei der KI, die rot uebernommen hat, nur diesmal umgekehrt. Die Tribok-Baumeisterfarbe ist ausserdem immer Blau - soweit ich gelesen habe aber bereits bekannt.

[Vorschlag]
- Starteinheiten(+anzahl) waehlen/aendern koennte noch ein interessantes Feature sein, sofern dies moeglich ist

**Comment by Sh0wdown** [comment]
Das mit den Spielerfarben ist im kommenden Patch gefixt.

Für deinen Vorschlag habe ich mal einen separaten Issue erstellt https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/156
