### ISSUE TITLE
Wird mit A nicht standardmäßig die Waffenkammer ausgewählt? (Konflikt mit WASD für Kamera)

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#126]

**Comment by Sh0wdown** [comment]
Joa, und mit S normalerweise die Wegweiser. Aber mit der aktivierten Option ist das nicht mehr der Fall.

**Comment by StrongholdFan** [comment]
Könnte man eventuell noch eine Option in den Patcher einbauen, dass wenn die WASD-Steuerung aktiviert ist, mit der Taste "Q" die Waffenkammer angewählt wird und mit der Taste "E" der Wegweiser? 
Wäre denke ich eine gute Optionslösung, da "Q" über der Taste "A" liegt, die eigentlich für die Waffenkammer zuständig ist und "E" schräg über "S". :)

**Comment by Monsterfisch** [comment]
Wie wäre es denn andere navigations steuerungen in die nähe von wasd zu legen da die momentanen sehr ineefizient auf der tastertur verteilt liegen.

Meine vorschläge hierzu
Q ansicht nach links drehen 
E ansicht nach rechts drehen
R rein raus zoomen
F gebäude senken (derzeit auf V)

**Comment by ByBurton** [comment]
Für mich machen Buchstaben die Sinn machen ... mehr Sinn.
Z für Zoom ist doch wunderbar. B für barracks auch. etc.

**Comment by Monsterfisch** [comment]
geht darum die funktionstasten näher zusammen zu rücken damit man nicht jedesmal kunstturnübungen mit seinen händen veranstalten muss um zu navigieren ich persöhnlich würde ja auch ausschließlich die navigationssteuerung ändern um sie mit wasd in einklang zu bringen das dadurch funktionstasten wie a für armory umgelegt werden müssten ist dafür gleube ich ein geringfügiges übel so muss. am besten ist wie gesagt man kann sich sein tasterturlayout selber festlegen dann kann sich auch keiner mehr beschweren außer über zu viele optionen

**Comment by Sh0wdown** [comment]
Hätte nicht gedacht dass jemand den Wegweiser- und Waffenkammer-Knöpfen nachtrauert. :D
Aber ja, auf Q und E zu verlegen ist eine gute Idee. Richtig modifizierbare Shortcuts einzufügen könnte teilweise etwas aufwändig werden.

**Comment by ByBurton** [comment]
> Hätte nicht gedacht dass jemand den Wegweiser- und Waffenkammer-Knöpfen nachtrauert. :D

Es gab einen Shortcut für Wegweiser.... man lernt nie aus :D

**Comment by Monsterfisch** [comment]
anscheinend gabs in stronghold schon strg modifications kürzel für die pfeiltasten die jetzt natürlich mit dem autospeichern konkurieren da strg s laut der standart aufmachung für das gebäude senken zuständig ist ist freilich nicht sonderlich schlimm da strg s nicht weit von v entfernt ist aber auf jeden fall was das man in der zukunft im hinterkopf behalten sollte

**Comment by Monsterfisch** [comment]
Keine Frage Pfeiltasten sind leider immer unpraktisch weil sie am anderen Ende der Tastertur liegen und man meistens die Hand von der Maus nehmen muss um effectiveüber die Karte zu huschen. für mich persöhnlich da ich oftmals durch das vertikale Bewegen auf der Tastertur nicht immer xc&v 100% treffe  begrüße ungemein die wasd änderng dadurch muss ich meine Hand nicht mal mehr bewegen abgesehen. Immerhin liegt mein Daumen ganz allgemeingesehen sowiesoschon von Arbeitswegen her imer auf strg. ^^ Aber wie scho gesagt wenn man sich das alles persöhnliuch einstellen könnte wäre das freilicham Gold wert.

**Comment by Heroesflorian** [comment]
Sicher, oftmals sind die Pfeiltasten etwas weiter weg. 
Aber andererseits kann man ja auch per Maus am Bildschirmrand oder per Klick auf die Minimap auf der Karte navigieren, oder per Wegpunkten (selten verwendet aber vorhanden), oder springt zu gruppierten Einheiten per Tastenkürzel, oder navigiert indem man mit Tastenkürzeln direkt zu wichtigen Gebäuden springt. 
Oder man spart sich teilweise das Karte hin- und zurückverschieben ganz und öffnet z.B. direkt Gebäudemenüs ohne hinzuscrollen (Strg + jeweiliges Gebäudekürzel). 

Insofern ist aktuell die WASD-Steuerung, gerade im Hinblick auf das "Waffenkammer-A" zumindest für mich persönlich eher hinderlich als förderlich... das umzugewöhnen ist nicht einfach^^ 
Was ich daher noch cool fände wäre eine Option, die WASD-Steuerung... öh, quasi "push to WASD" zu machen, um dann z.B. per Shift+WASD zu navigieren, und ohne Shift ganz normal die üblichen Shortcuts zu verwenden. 

Und noch etwas: Auf englischen Tastaturen ist es ja durchaus sinnvoll, unten mit Z, X, C, V, Leertaste alle "Rechtsklick-Navigationsoptionen" (Karte drehen, flach, "halbflach", zoomen) gebündelt zu haben. 
Aber auf deutschen Tastaturen sind ja Z und Y andersrum, womit das Z relativ einsam und alleine oben ist. Ich persönlich finde das Z durchaus unbequem und in längeren Sessions echt unangenehm in der Verwendung, weil man entweder die Finger ziemlich spreizen, oder die ganze Hand einmal komplett verschieben muss, um zu zoomen, was bei häufiger Nutzung der ganzen anderen Tastenkürzel alles andere als ideal ist. 
Darum fände ich es toll, wenn man die Zoomfunktion optional von Z auf Y verlegen (oder duplizieren) könnte und der Z-Finger-Spagat somit wegfallen würde.

**Comment by Krarilotus** [comment]
Lets discuss all hotkey related issues in this hotkey configfile issue here: #432 which would aolve all custom hotkey suggestions!
