### ISSUE TITLE
Deutsche Übersetzung

### ISSUE THREAD

**Issue by StrongholdFan** [Sh0wdown/UnofficialCrusaderPatch#129]
So, hier mal ein Thema, um die deutsche Übersetzung anzusprechen, falls man Fehler findet; was mir gerade passiert ist.

"Immer nähesten Gegner angreifen" - Das Wort "nähesten" ist nicht richtig, da funktioniert die Flexion anders. Es müsste "nächsten" heißen. :)

**Comment by Sh0wdown** [comment]
Also ich wäre ja eher dafür die deutsche Sprache stattdessen zu ändern und "am nähesten" als Superlativ für "nah" einzuführen, um Verwechslungen mit "am nächsten" im Sinne von "darauffolgend" zu vermeiden. :P

**Comment by TheSnowyChickens** [comment]
Wenn man grad schon bei dem Thema ist, Ingame sind auch einige KI Texte nicht passend zudem, das gesagt wird, (hab grad kein Beispiel, weil das schon länger her ist, als ich das bemerkt hatte)

**Comment by Heroesflorian** [comment]
Im Zweifelsfall könnte man auch - zugegeben, ist etwas länger - "nächstgelegenen" nehmen.

**Comment by StrongholdFan** [comment]
Patch 2.08: Unter "Kein KI-Angriffszielwechsel während Belagerung" ist ein kleiner Fehler vorhanden. In Zeile 4, steht "nichtmehr", das schreibt man allerdings getrennt, also "nicht mehr".
