### ISSUE TITLE
Friedeszeit

### ISSUE THREAD

**Issue by StrongholdFan** [Sh0wdown/UnofficialCrusaderPatch#130]
Wäre es möglich, sowas wie in den neueren Stronghold-Teilen einzubauen, sprich, es zu Beginn eines Matches eine sogenannte Friedenszeit gibt, in der man nicht von der KI angegriffen wird bzw. die KI nicht angreifen kann?

**Comment by Heroesflorian** [comment]
Für Mehrspieler-Partien gibt es so eine Art Friedenszeit auch in Crusader 1 bereits: Man kann einstellen, dass dort in den ersten 5/10/20/... Minuten keinerlei Truppen rekrutierbar sind (auch die Starttruppen spawnen dann erst nach Ende der Friedenszeit). 
Diese Option aus dem Mehrspieler auch in Einzelspieler-Matches zu übernehmen, wäre vielleicht sogar durchaus machbar.

**Comment by Sh0wdown** [comment]
Ich mach hier mal zu. Weitere Diskussionen dazu bitte hier fortführen: https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/171
