### ISSUE TITLE
Make boiling oil engineers pour automatically.

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#132]
It is hard to use boiling oil pot engineers as a human player, you have to manually pour the oil in a certain direction which makes them a poor option for defence compared with fire throwers, as it takes a lot of time to manually make several oil pot throwers use their oil, when there may be other things you need to do with castle defense such as recruiting new troops. It would be good if you could have the option to put oil pot engineers on aggressive mode and they would automatically pour the oil if units were in range, then they would automatically return and get oil and go back to their position.

**Comment by Heroesflorian** [comment]
Actually, you **_can_** do that! 

On aggressive mode, they will pour their oil as soon as 1 enemy unit is in range, and on defensive mode they will pour their oil as soon as 3 enemy units are in range. 

Right after they emptied their oil pot, they will run back to the oil smelter, get their pot filled up again and then return to their previous position on some wall/tower/gate.

**Comment by PitchNeeded** [comment]
Oops, had the original pre-Warchest version of Stronghold Crusader where the oil engineers didn't appear to autopour and haven't used oil engineers since, didn't realise this was fixed now officially!
