### ISSUE TITLE
The editor doesn't work for me at all :(

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#133]
The editor doesn't work for me at all :(
![50058437-5b92b780-0189-11e9-9afa-45095b6c5986](https://user-images.githubusercontent.com/41998977/50058685-f3de6b80-018c-11e9-89f5-6d90540955f9.png)

**Comment by Sh0wdown** [comment]
Because I only attached the edited .exe
If you want to edit an aiv-castle you should get the official download first and then overwrite the .exe with the patched version.
http://stronghold.heavengames.com/downloads/showfile.php?fileid=7534#

**Comment by Lolasik011** [comment]
@Sh0wdown Ok Sorry
