### ISSUE TITLE
 Thanks for the new patch!!!!

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#135]
Thanks for making the game better.

**Comment by PitchNeeded** [comment]
Thanks a lot for the new patch indeed....

It was annoying when AIs went round another enemy to get to another one and I am glad this can be corrected by using the new mode where AIs always attack the nearest enemy. However I would still like an option in this new feature that if an enemy is weak enough (for example having under 75 troops for the strong AIs or under 120 for Snake or Abbot), the AIs will automatically attack them to try and finally defeat them and get the gold no matter how far away they are.

**Comment by Lolasik011** [comment]
@PitchNeeded
I also really want this function
