### ISSUE TITLE
insta close

### ISSUE THREAD

**Issue by Bruti** [Sh0wdown/UnofficialCrusaderPatch#138]
spiel stürtzt mach 10-20minuten ab...

ich bin nicht der einzige mit diesem problem, woran es liegen könnte habe ich allerdings nicht herrausgefunden

**Comment by Swartonf** [comment]
Nein, ich habe das auch und wiederholt! Wollte gerade ein Thread aufmachen :D

Jedes mal, wenn eine KI die andere mit vielen Einheiten angreift und ein Video kommt (kurz bevor jemand verliert), dann stürzt das Spiel ab.

Vermutlich hat es mit irgend einer Neuerung zu tun, dass keine Gebäude mehr eingerissen werden können und kein Schlafmodus mehr aktiviert wird. Das würden die KI's normaler weise tun wenn sie so unter Bedrängnis sind.

**Comment by TheSnowyChickens** [comment]
jip, hab das auch.

**Comment by Lolasik011** [comment]
I also got the same bugs :(

**Comment by Sh0wdown** [comment]
> scheint so, ich hab grad mal den patch ohne abreißen installiert und es ist nicht abgestürzt

Falls das noch mehr bestätigen könnten, wäre das hilfreich. Dieses verdammte Abreißen schon wieder... :D

**Comment by Sh0wdown** [comment]
Hab das Problem gefunden, hatte vergessen eine Datei zu aktualisieren. Hotfix kommt gleich...
