### ISSUE TITLE
Standard Spielgeschwindigkeit

### ISSUE THREAD

**Issue by gunthermann** [Sh0wdown/UnofficialCrusaderPatch#14]
Könnte man vielleicht die standart Spielgeschwindigkeit ändern (liegt glaub ich bei 40 ) ?
Denn wenn man ein Multiplayer Spiel lädt wird die Geschwindigkeit immer wieder auf 40 gesetzt was quasi ein weiterspielen nach Absturz unmöglich macht da das Spiel dann unerträglich langsam ist. 

90 oder zumindest 60 weil die Bauern Animationen usw. für Tempo 60 ausgelegt sind würde ich empfehlen

**Comment by ByBurton** [comment]
Closed because this is something you can just adjust ingame.
