### ISSUE TITLE
Türme/Torhäuser auf Einheiten bauen

### ISSUE THREAD

**Issue by Udoachim** [Sh0wdown/UnofficialCrusaderPatch#140]
Die KI ist in der Lage, Türme und Torhäuser auf ihren eigenen Einheiten zu bauen, sodass diese dann direkt das Gebäude bemannen. Wäre es möglich, das auch dem Spieler zu erlauben?

**Comment by SimonRebholz** [comment]
Warum? Das finde ich nicht nötig. Das tut der Realität des Spieles nicht gut

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Monsterfisch** [comment]
Wenn derSpieler nicht hinbekommt die Einheiten aus dem Weg zu räumen bevor er seinen Turm oder sein Tor baut dann spielt er das falsche Spiel ;)

**Comment by Krarilotus** [comment]
I dont think this will be worked on, there have been no more requests for this feature. If you still want to discuss it, feel free to reopen.
