### ISSUE TITLE
Gibt Philipp einen Steinbruch

### ISSUE THREAD

**Issue by Xander10alpha** [Sh0wdown/UnofficialCrusaderPatch#141]
Er ist so nutzlos das er kein hat. Er baut soviele Teure Türme und muss sonst alles kaufen...
Ich denke auch nicht das er OP wird, da er selbst sehr schlecht ist. Wäre das möglich, das er wenigstens einen Steinbruch baut?

Wer Philipp einen Steinbruch geben will ein Daumen hoch ;)

**Comment by TheSnowyChickens** [comment]
Nicht nur Steinbrüche braucht er!
NIEDER MIT DEN LANZENTRÄGER und HER mit den Pikinieren! :D

**Comment by Monsterfisch** [comment]
I würde eher vorschlagen anstelle von bogenschützen armbrustschützen zu verwenden im gleichen atemzug mehr eisenmienen für geld damit er sich die harnische und Armbrüste kaufen kann (armbrustschützen würden dann die gekauften söldner repräsentieren).

Im gleichen gedankengang könnte man dem abt könnt man dann noch die schweizer garde (pikiniere geben) rüstungen und piken könnte er sich ja mit seinem ganzen angehäuften geld kaufen anstatt sie zu produzieren

**Comment by Xander10alpha** [comment]
Hab eine Idee Kombinieren wir alles Philipp bekommt:
- Steinbrüche
- mehr Eisenminen
- Pikiniere statt Lanzenträger
- Armbrustschützen statt Bogenschützen
Dann ist er ein Philipp würdig xD

Bin auch dafür den Abt teure Einheiten zu gäben und einen positiven Angstfaktor, weil zu viel Geld und Truppen zu schwach.

**Comment by Aspire147** [comment]
Beim Abt würde ich die Verteidigung der Mönche gegenüber Pfeilen erhöhen also das Mönche mehr Schüsse überleben und das der Abt seine Türme mit mehr Bogenschützen bemannt statt 2 Bogenschützen mind. 5 oder 6

**Comment by ByBurton** [comment]
>           Beim Abt würde ich die Verteidigung der Mönche gegenüber Pfeilen erhöhen also das Mönche mehr Schüsse überleben und das der Abt seine Türme mit mehr Bogenschützen bemannt statt 2 Bogenschützen mind. 5 oder 6

Bitte beim Thema Philipp bleiben. Außerdem wären Mönche dazu noch stärker als sie es sowieso schon sind. Dafür müssten sie dann seeehr viel teuerer werden.

**Comment by Panbutt** [comment]
Honestly, Phillip is close to being in a very good spot. I like the idea of a semi-tough Lord that uses Spearmen as their main fighting force and Phillip uses tons of spearmen.

I would suggest:
+2 Quarries (To compensate, maybe lower his max wood cutter huts to 8?)
+3 'harassing' catapults (Atm he only uses 1, sometimes 2)
+Archers, Catapults and Trebuchets to support his attack forces. (I think a max of 2 catapults and 1 trebuchet would be fitting.)
+Training/retraining archers specifically for tower defense at a higher priority (Atm he only uses his starting archers and never retrains dead ones)

As Phillip buys/makes swords and armor, he could train swordsmen without needing AIV changes. To fit his spoiled, confident personality I think it'd be interesting if Phillip trained swordsmen bodyguards that protect the keep at all times. Purely used for defense. Maybe a max of 8-9?

**Comment by PitchNeeded** [comment]
Phillip could benefit from having 1 quarry, but it needs to be examined what impact the 1 quarry plus ox tethers has on his population and religion bonus.

As for Phillip militarily, he is fine using spearmen, but he needs to be able to siege effectively. With Phillip, I really do think tunnelers would be a great strategy for him as they could open up a gap in the wall through which he could send not only his spearmen but also any knight raids inside to destroy the granary and other buildings.

**Comment by Monsterfisch** [comment]
Not a fan of giving Phillip swordsman as that would take away from the contrast of having the aristocracy knights on horseback and the lowly peasant army. 
I do like the idea of tunnelers but, I would like the idea of the ai using shields, even more, to give their troops a better chance to reach the castle walls without being shot down before they even reach it particularly with spearman. granted giving him both would be even better.

The change I would, however, most encourage as it makes the most sense to me, for a  character of a French ruler at the time, would still be archers to crossbowmen, that way his defense would also be less of a joke as he is able to push back heavier attack with fewer men. On top of that, cheese farms would make sense for the French as well they do like their cheese quite a bit after all.

**Comment by ByBurton** [comment]
> On top of that, cheese farms would make sense for the French as well they do like their cheese quite a bit after all.

But they also do have apples and stuff. And apples are just much better.

**Comment by Monsterfisch** [comment]
gameplay wise yes but if you consider Phillip would need cheese farms for the crossbowman I am suggesting apples just don't work well for armor ;)

**Comment by PitchNeeded** [comment]
> The change I would, however, most encourage as it makes the most sense to me, for a character of a French ruler at the time, would still be archers to crossbowmen, that way his defense would also be less of a joke as he is able to push back heavier attack with fewer men. On top of that, cheese farms would make sense for the French as well they do like their cheese quite a bit after all.

That sounds great! Yes traditionally the French tended to use crossbows rather than normal bows. so this would fit historically.

**Comment by Sh0wdown** [comment]
Editable with the AIC files.
