### ISSUE TITLE
Sultan Nahrungsproduktion

### ISSUE THREAD

**Issue by Xander10alpha** [Sh0wdown/UnofficialCrusaderPatch#142]
Ich weiß das soll so sein, dass er die Nahrung kauft. Aber der Vanilla Sultan oder auch der von Tatha, der ja auch eine Lanzen Produktion hat ist zu wenig, um den Nahrungs kauft zu kompensieren (5 Nahrung = 40 Gold). Dadurch das er generell nur eine Geringe Produktion hat.
Ich schlage ein Kompromiss vor:
Der Sultan soll 2 - 3 Apfelfarmen bekommen. Damit muss er trotzdem Nachrung sagen, weil es zu wenig ist. 
Aber er muss nicht komplett alles kaufen. Damit wird er gebufft, sodass er auch mal eine Armee losschicken kann. Und zu stark wird er auch nicht.

**Comment by PitchNeeded** [comment]
No, Sultan I think would be better with a third quarry, and get rid of a few of his woodcutters to make way (he builds too many woodcutters I think).

Sultan could also do with buying in small quantities (batches of 5 for each food type) of all 4 types of food as has been mentioned on here before.

**Comment by Xander10alpha** [comment]
Coole Idee aber du hast mein Gedankengang verstanden?

Ich will nur einen etwas stärkeren Sultan und allgemein stärkere KIs.

**Comment by Aspire147** [comment]
Ja ich würde auch eine etwas stärke Wirtschaft gut finden vorallem beim Sultan, Phillip und Marshall

**Comment by Lolasik011** [comment]
@PitchNeeded  Suggest this idea @Sh0wdown

**Comment by TheSnowyChickens** [comment]
Würde es nicht gehen, wenn man eine custom Burg im Editor machen würde, die Obst Gärten und so als bauplatz mit eingespeichert hat und dann die Burg auf komplett Graß Maps bauen zulassen?

**Comment by Sh0wdown** [comment]
Editable through AIC edits now.
