### ISSUE TITLE
Angriffsziel und Rekrutierungstempo

### ISSUE THREAD

**Issue by EinfachKurt** [Sh0wdown/UnofficialCrusaderPatch#146]
Hallo, wäre es möglich dass man diese beiden Optionen für jede KI individuell ändern kann?
Ich würde nämlich gerne kleine Änderungen machen und nicht dass jede KI hinterher die gleichen Eigenschaften hat. Z.B. ergibt es für mich kein Sinn dass das Schwein den stärksten angreift weil die Angriffe einfach zu schwach dafür sind. Oder ich würde gerne das Rekrutierungstempo vom Sheriff leicht erhöhen. Wäre es möglich für jede KI einen Schieberegler zu implementieren?

**Comment by Monsterfisch** [comment]
Wäre es möglich anstatt alle auf nächsten Gegner zu stellen es so zu machen das wenn die Option aktiviert ist das die Ki's weiterhin ihrer bevorzugten Ziele angreifen aber sobald sie eine andere Burg dafür passieren müssen stattdessen diese angreifen? Oder ist das coding teschnisch nicht ohne weiteres möglich immerhin wäre das meines Verständnisses nach schon ein bisschen aufwändiger da Computer das während der Sammelphase entscheiden müsste.

stimme mit dem rekrutierungstemps vollkommen zu der einzige grund warum ich das bisher noch nicht benutzt habe ist weil es in gewisser weise durch sein vereinheitlichen die Balance der KI's stört.  Denke aber das es eventuell mehr Arbeit wäre als sich tatsächlich lohnt immerhin kann man das "Rekrutierungstempo" mit einer besseren Wirtschaft schon ganz gut unterstützen. 
Das ganze ist auch mit Vorsicht zu genießen immerhin solle man eventuell erstmal andere Faktoren verbessern die eventuell das Problem mit der geringen angriffs Effektivität lösen könnten zb effektivere nutzung der EInheiten und nutzung von Schilden um die Wertvollen Einheiten besser zu schützen.

**Comment by PitchNeeded** [comment]
> agree with the recruiting tempo completely the only reason why I have not used that yet is because it disturbs the balance of AI in some ways by unifying it. But think that it might be more work than actually worth it, after all, you can support the "recruitment speed" with a better economy quite well. 

Which is why having increased recruitment speed is only good for economically boosted AIVs though, for vanilla AIVs or Evrey's improved AIVs, I would think that any AI apart from Abbot will struggle economically if they have a faster recruitment speed than they currently do. So I haven't used it yet either.

I suppose Saladin maybe would be OK though with a slightly higher recruitment speed, as I don't know what his vanilla recruitment speed is, but he seems to have a lower recruitment speed than Emir or Wazir but has as good an economy as them.

**Comment by Heroesflorian** [comment]
> Which is why having increased recruitment speed is only good for economically boosted AIVs though, for vanilla AIVs or Evrey's improved AIVs, I would think that any AI apart from Abbot will struggle economically if they have a faster recruitment speed than they currently do. So I haven't used it yet either.

There are a couple other AI characters that usually do have lots of unused (effectively useless) gold, though. E.g. Emir, Saladin, Frederick and (depending on map resources) the Wolf as well. 

Besides, many characters already have high recruiting speed without the patch, and thus are currently not affected by the change at all. Even AI characters with weaker economy, such as Marshal or Rat, and to some extent Richard Lionheart, have maximum recruitment speed already.

**Comment by Sh0wdown** [comment]
It's possible to change this with AIC edits now.
