### ISSUE TITLE
**WIR BENÖTIGEN HOLZ**

### ISSUE THREAD

**Issue by TheSnowyChickens** [Sh0wdown/UnofficialCrusaderPatch#147]
Wie man sehen kann, **Benötigen wir Holz** um eine Holzfälle Hütte, die 3 Holz kostet, zubauen.
Wie man auch sehen kann, HAB ICH 3 HOLZ, aber *wir benötigen* ja *Holz.*
Edit: Grad noch gesehen, das das die **erste** Holz Hütte ist, die ja eig. Kostenlos seien muss.

Patch: 2.07a
(Da der Maus Zeiger nicht aufgenommen wird, siehts so aus, als würde ichs da platziert haben, aber ne. Das ist nur das hower overlay)

![grafik](https://user-images.githubusercontent.com/29357962/50124328-62422d00-0264-11e9-93d0-cfdba3080565.png)

__Optionen__:
- Freier Marktplatz ist an
- +2 Holz für KI's ist an
- und mehr

**Comment by ByBurton** [comment]
Das habe ich auch schon festgestellt, mit allen Gebäuden die Holz kosten. Man braucht immer 2 mehr Holz um eines zu bauen.

Die kostenlose Holzfällerhütte, die nichtmehr kostenlos ist, ist allerdings ein riesiges Problem...

**Comment by ByBurton** [comment]
Die erste Hütte ist nur kostenlos, wenn nicht genug Holz vorhanden ist.

**Comment by Sh0wdown** [comment]
Upps, liegt wohl am +2 Holz für die KIs. Anscheinend wird die Funktion die ich dort editiert habe auch für den Spieler irgendwie genutzt. :D

**Comment by ByBurton** [comment]
I actually found that out on your first commit with the lumber change. I was just afraid to say anything, because I tested "unfinished" stuff.
And then I did not test it again...

**Comment by Blade1243** [comment]
@Sh0wdown 

das kann nicht daran liegen das er ne andere farbe hat als rot ?

ich kaufe immer mehr holz als nötig xD

**Comment by ByBurton** [comment]
> das kann nicht daran liegen das er ne andere farbe hat als rot ?

Nein, es liegt daran, dass das Spiel denkt, es braucht 2 Holz mehr als üblich. Aber beim platzieren wird trotzdem nur die ursprünglichen Kosten abgezogen.
Beispiel: Eisenmine: 20 Holz. Wir haben: 20 Holz
Wollen Eisenmine platzieren: Nicht genug Holz, Sire.
Kaufen 5 Holz mehr.
Wollen Eisenmine erneut platzieren: Funktioniert. 
Im Lager sind noch 5 Holz.

**Comment by TheSnowyChickens** [comment]
Und es hängt definitive nicht daran, das die 3 Planks nicht auf einem Stapel sind ?

**Comment by Sh0wdown** [comment]
Ist im kommenden Release gefixt.

**Comment by TheSnowyChickens** [comment]
Nice, ty.
