### ISSUE TITLE
Abt Verstärkung

### ISSUE THREAD

**Issue by Xander10alpha** [Sh0wdown/UnofficialCrusaderPatch#148]
Beim Abt, der ja bekannterweise sehr viel Geld macht, würde ich es toll finden, wenn er einen positiven Angstfaktor von +5 bekommt. Irgendwie hindert den Abt den negativ Angstfaktor, da seine schwachen Truppen noch schwächer sind und er nochmehr Geld scheffelt (Bessere Wirtschaft).
Positive dämmt sein Geldwachstum deutlich ein.

**Comment by Monsterfisch** [comment]
Das muss nicht mit dem Mod gemacht werden dafür kannst du einfach den AIV Editor zur Hand nehmen dem Abt positive Sachen bauen lassen und testen ob das besser ist. 

Was ich persöhnlich cooler fände wäre wenn der Abt sein Geld mit seinen Teamkameraden teilen würde. So wie die Kirche sich Verbündete erkauft hat die ihr zur Seite stehen und mit ihr angreifen bzw sie verteidigen.
was ich persöhnlich für den Abt noch cool fände was auch geschichtlich passt wäre ihm Pikeniere [schweizer Garde] zu geben, waffen dafür kann er ja kaufen ist bei der Schweizer garde ja auch alles nur gekauft ;)

**Comment by Xander10alpha** [comment]
Ich probiere es mal aus

**Comment by EchoRevora** [comment]
Dein Argument macht zwar Sinn, allerdings passt positiver Angstfaktor mal ueberhaupt nicht zur Personalitaet des Abts... ^^

**Comment by Xander10alpha** [comment]
Da hast du vollkommen recht :)
Ich gehe aber immer davon aus, was das beste wäre für die jeweilige KI ist. Damit es schwerer und interresanter wird.
