### ISSUE TITLE
market

### ISSUE THREAD

**Issue by Ninjaa17** [Sh0wdown/UnofficialCrusaderPatch#150]
I do not know if this is feasible, but what do you say about something like a bot to the market? As you know, when there are a lot of iron quarry quarries and resources + from the patch of high speed, selling at the marketplace is cumbersome, because you have to constantly sell something, you can not do something about it? Perhaps the setting below / above, for example, 50 pieces of everything and would still maintain this value, or the greater amount of resources sold. During the siege or games at a higher pace, you would not have to look at the marketplace all the time

**Comment by ByBurton** [comment]
God damnit, can you people please check previous and closed issues before creating new ones?

**Comment by ByBurton** [comment]
Look at issue #36 . Okay, it is in German, but still...

**Comment by Sh0wdown** [comment]
> edit: I was not really angry. Just facepalming
Even if you weren't, your message seemed kinda gruff. Maybe you should've posted [this](https://www.youtube.com/watch?v=3O8J2locx5o) along with it. :P
Also, there are so many issues I can understand if people miss already existing ones. Nevertheless, I agree that people should at least try to check previous ones.

> Okay, it is in German, but still...
Maybe that's the problem ;) 

Closing this anyway, please continue discussions about an auto-sell feature in issue https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/36
