### ISSUE TITLE
Zugbrücken schließen oftmals zu spät 

### ISSUE THREAD

**Issue by Monsterfisch** [Sh0wdown/UnofficialCrusaderPatch#154]
Wenn zb Streitkolbenkämpfer (schnelle Einheiten) attakieren, das hängt vermutlich damit zusammen das tore sehr knapp vor eintreffen der gegner geschlossen sind kann es oft passieren das sie einfach über die zugbrücke zum toor laufen.
Ich würde daher vorschlagen den radius des Torhausschließens ein kleines bisschen zu erhöhen damit Zugbrücken auch rechzeitig geschlossen werden.

**Comment by Sh0wdown** [comment]
Ist das auch in Vanilla so, oder kam das erst durch den Tor-Edit des Patches?

**Comment by irgendein-alf** [comment]
Ich kann es bestätigen, dies ist erst seit der Verbesserung des Torhauses der Fall. 
Ich würde allerdings dem Vorschlag von Monsterfisch widersprechen und die Geschwindigkeit/den Radius des Schließens der Zugbrücke erhöhen, den Radius des Torhauses jedoch so lassen. 
Ein größerer Radius des Torhausschließens wäre meiner Meinung nach ein Rückschritt, da wenige KI's von Zugbrücken profitieren und im Gegenzug beinahe alle KI's wieder das alte Problem hätten.

**Comment by Monsterfisch** [comment]
Am besten wäre natürlich wenn das Torhaus erkennen würde, das es ne Zugbrücke hat und darum nen größeren Radius zum schließen benutzt, aber ich schätze mal das wäre nicht ohne weiteres möglich da es ja bisher keine Funktion gibt die das differenziert.

**Comment by J0J0Jo** [comment]
> 
> 
> Bei Udwins letztem KI Kampf kann man das gut sehen. (beim Kaiser)

War es nicht so dass da einfach jemand auf der Zugbrücke stand und sie deswegen nicht zugegangen ist?

**Comment by Monsterfisch** [comment]
Wenn Einheiten auf der Brücke gestanden hätten, hätte ich das Thema nicht angesprochen und ja es waren große Truppenmenge von Streitkolbenkämpfern die mal fix über die Brücke gelaufen sind. Natürlich haben es bei dem rüberlaufen nicht alle einheiten rübergeschafft da de Brücke direkt nach dem die Einheiten das Tor angreifen zerstört wird. insofern ists kein riesen problem da der Burggraben ja zurückbleibt allerdings werden so oftmals die truppen auf dem tor getötet da die Einheiten die über die Brücke kamen meistens reichen das toor zu zerstören.

**Comment by Monsterfisch** [comment]
Einziges was mir einfallen würde wäre wenn Dorfbewohner auf der Brücke gewesen waren die schlagartig getötet wurden das es mir nicht aufgefallen ist. Kann an den Burgendesigns liegen mit denen ich spiele die nur einen Eingang haben und dadurch viele Leute über die brücke schicken.

**Comment by Heroesflorian** [comment]
Mir ist es übrigens auch in der Vergangenheit (vor vielen Jahren) ohne Patch schon hin und wieder aufgefallen, dass Zugbrücken (irgendwie ja durchaus verständlicherweise) nicht hochgehen, wenn eben gerade noch Arbeiter oder Truppen drauf stehen. Hin und wieder hatte ich seinerzeit auch aktiv versucht, solche Situationen bewusst für mich zu nutzen, wenn ich angreife. 

Die KI achtet nur leider aktiv nicht darauf, die Brücke freizuräumen, und durch den geringereren Schließradius fällt das mit dem Patch eben häufiger auf bzw. es wird wahrscheinlicher, dass gegnerische Einheiten noch lange genug auf der Zugbrücke herumstehen oder -laufen, damit feindliche Truppen diese erreichen, bevor sie frei wird und hochgezogen werden kann. 

Allerdings - sofern nicht unabhängig davon doch noch ein Bug in dem Zusammenhang existieren sollte - würde mich das gar nicht so sehr stören: Wenn die KI so doof ist, die eigene Zugbrücke mit Einheiten zu blockieren, hat sie eben Pech gehabt. Ist ja bei vielen anderen Aspekten auch nicht anders - wenn die KI A regelmäßig ihre Patrouillenbogis in Turmballisten-Reichweite der Burg von KI B parkt, ist sie ja auch selbst schuld, wenn sie dann abgeschossen wird.

**Comment by TheSnowyChickens** [comment]
Eines sollte dabei aber dann noch verbessert werden:
- die KI soll nicht die Zugbrücke zerstören

Man hats ja bei Udwin gesehen, die Gegner waren drauf und am Torhaus und schwups, die Brücke war weg und der Wassergraben blieb zurück.

**Comment by Monsterfisch** [comment]
Selber schuld ja aber wenns verhindert werden kann würde ich das sehr begrüßen wie schon erwähnt wenn man differenziert erkennen könnte ob das Tor eine Zugbrücke hat oder nicht und diese dann auf größerer Distanz reagieren würde was dafür sorgen würde, das das Bauernvolk sich entweder in luft auflöst oder sich rechtzeitig nen anderen Weg ins Burginnere suchen mussfalls das nicht separiert möglich ist ists schade aber wie florian sagt kein Genickbruch da durch den zurückgelassenen Burggraben der Schaden schon in gewisser Weise eingedämmt wird. und die zugbrücke nicht zu zerstören wäre in dem falle fatal da dann schlicht die gesammte Truppe die Brücke stürmen würde und omit den graben überspringen würde . Vorrausgesetzt das das Torhaus nicht direkt nach eintreffen der ersten gegner in sich zusammenfällt.

**Comment by Sh0wdown** [comment]
>  die zugbrücke nicht zu zerstören wäre in dem falle fatal da dann schlicht die gesammte Truppe die Brücke stürmen würde und omit den graben überspringen würde .

Dieses. Ich denke ich werde es einfach so belassen wie es ist.
