### ISSUE TITLE
A few enhancements

### ISSUE THREAD

**Issue by Mizo5119** [Sh0wdown/UnofficialCrusaderPatch#158]
I was thinking of more enhancements that are more quality of life in anything:

- is it possible to have the option "Stronger Walls" enabled that effectively doubles wall and tower HP?

- is it possible to have it so double clicking a siege engine does not disembark engineers from then? ( perhaps asigning that function to a different unused unit hotkey)

**Comment by Sh0wdown** [comment]
I will look into making the multiplayer settings available in single player as well, but I think your 2nd suggestion is too complex.

**Comment by Krarilotus** [comment]
#432 and #171 cover these suggestions, therefore closed
