### ISSUE TITLE
Horse archer attack BUG!!!

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#160]
I noticed that when Emir goes on the attack, he leaves the horse archers  and does not attack them.

**Comment by TheSnowyChickens** [comment]
He send the horse archers, if the way to the keep is free.

**Comment by PitchNeeded** [comment]
It doesn't just happen to Emir, it happens to other AI's too sometimes with their missile units they use in sieges. I think it is a pathfinding issue if there is rocky ground in a map. The most annoying is Sultan leaving his Arabian archers behind in the field meaning he can't attack again for ages until he recalls them or they get killed, and that his castle is poorly defended, as he won't make new Arabian archers for his keep while his siege Arabian archers are still out of his castle.

**Comment by Lolasik011** [comment]
@TheSnowyChickens It would be better if he killed the shooters on the walls than he waited for the wall to break .

**Comment by PitchNeeded** [comment]
But for Wolf, it would actually be better if the crossbowmen he sent in a siege waited for a while. They advance too soon I think. They would be better waiting and advancing when the pikemen and swordsmen start advancing. Therefore they could distract the enemy archers from firing on the pikemen and swordsmen and also manage to kill more missile troops, being supported in their advance by the melee troops.

**Comment by Heroesflorian** [comment]
> But for Wolf, it would actually be better if the crossbowmen he sent in a siege waited for a while. They advance too soon I think. They would be better waiting and advancing when the pikemen and swordsmen start advancing. Therefore they could distract the enemy archers from firing on the pikemen and swordsmen and also manage to kill more missile troops, being supported in their advance by the melee troops.

That, aaand potentially less surviving defenders after Wolf's siege engines (fire ballista, catapults, trebuchets) did a bit of work to destroy some towers. 

Generally speaking, I hate when the AI sends in a bunch of archers alone early on as they then get easily picked off by defenders. 
On the other hand, letting the archers (or crossbowmen) wait until all other troops are dead, and then waiting even some more until eventually retreating without using them at all, is equally bad (worse in terms of the attack, but better in terms of economy and defense in some situations - troops that didn't fight but survive the battle are troops that do not need to be replaced). 
And of course, the worst case is waiting out of own attack range, but then getting sniped off slowly but surely by some opponent tower ballista... but that fate is shared by many defensive patrol troops too. 

Ideally, the AI would march / approach with melee units at the frontline, behind that archers/crossbowmen, behind that siege engineers. And then attack with siege engines - behind own melee troops protecting them, as can currently be seen for Wolf with some troops who patrol his trebuchets, very nice detail that should be expanded imho^^ - and then wait some for the siege engines to do some damage, then advance with melee troops to attack the walls or directly enter a gap if possible, and advance archers right behind the melee troops.
