### ISSUE TITLE
Can the patch work with the Stronghold Medieval England Mod?

### ISSUE THREAD

**Issue by GutentagderHerr** [Sh0wdown/UnofficialCrusaderPatch#164]
Wollte wissen, ob es i-wie möglich ist, den Stronghold Medieval England HD Mod mit dem Patch zu installieren.

**Comment by Sh0wdown** [comment]
Theoretisch könnte es funktionieren indem du erst Medieval England und dann den Patch installierst.
Die Entwickler hatten mich auch schon angeschrieben, also werde ich das mal irgendwann unter die Lupe nehmen und größtmögliche Kompatibilität herzustellen.

**Comment by GutentagderHerr** [comment]
Hat bei mir leider nicht funktoniert. Aber Danke für die schnelle Antwort

**Comment by Sh0wdown** [comment]
Was genau hat denn nicht funktioniert?

**Comment by Sh0wdown** [comment]
Wie startet man denn die Mod? Der Patch editiert immer die "Stronghold Crusader.exe" Datei. Falls der Mod eine eigene .exe Datei mitbringt zum Starten, z.B. "MedievalEngland.exe" dann könntest du mal Folgendes versuchen:
- "Stronghold Crusader.exe" (und falls vorhanden "Stronghold Crusader.exe.ucp_backup" löschen oder in einen anderen Ordner kopieren als Backup
- "MedievalEngland.exe" in "Stronghold Crusader.exe" umbenennen
- Den Patch anwenden
- die jetzt gepatchte .exe zurück in "MedievalEngland.exe" umbenennen und ausführen

**Comment by GutentagderHerr** [comment]
Hat nicht funktoniert, da steht, dass Stronghold im Angegeben Pfad nicht gefunden wird.

Der Europe Mod hat eine eigene .exe Datei

**Comment by Sh0wdown** [comment]
Du musst in dem Patch den Pfad angeben in dem die in "Stronghold Crusader.exe" umbenannte .exe der Europe Mod ist.

**Comment by Monsterfisch** [comment]
bei mir hat es funktioniert so wie es sh0wdown beschrieben hat bin ich auch vorgegangen. ich würde hier aber auf jeden fall vorschlagen anstatt das verzeichnis für die modinstallierung anzugeben direct auf die exe zu verweisen um zu patchen das würde situationen wie diese auf jeden fall vereinfachen

**Comment by Krarilotus** [comment]
Compatibility is there, and no further information has been requested for a long time.
