### ISSUE TITLE
Rebuilding of guilds despite intact gathering places

### ISSUE THREAD

**Issue by Sh0wdown** [Sh0wdown/UnofficialCrusaderPatch#173]
In v2.08 I added the option for the AI to repair tower ruins and slightly damaged walls. Theoretically, this should also fix the bug where the AI does not rebuild their engineer's guild, tunneler's guild or oil smelter because the gathering place is still intact. Can anybody confirm or rebut that this also happens?

**Comment by Monsterfisch** [comment]
can confirm. ever since the patch the guilds that kept breaking all over for my aiv are now being repaired accordingly =)

**Comment by Heroesflorian** [comment]
@Sh0wdown You can also check yourself quite effectively and unambiguously by creating an AIV that contains walled-in oil smelters and/or guilds, and little else (market, granary, some stockpiles). 

Without the patch, that setup yields perma-semi-destroyed stuff as soon as the walling-in is completed, within a second or so. 

With the patch, it should cause the AI to rebuild (and re-destroy) those buildings over and over if it works, which would be a) clearly noticeable as different from vanilla, and b) relates to the general question of what to do to prevent endless destroy-rebuild loops for buildings that are inaccessible for more than a short moment? 
(Yes, there's the other option to just never delete any inaccessible buildings at all, but I feel that is a little... too much in some cases, and can have unpleasant side effects.
And yes, that question is already there in general for any "access required" buildings, so probably shouldn't be discussed in here in particular...)

**Comment by Sh0wdown** [comment]
Thanks for the feedback!
