### ISSUE TITLE
Saving issues

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#177]
Currently, the patch can cause issues with entering a name for a savegame, presumably when the Option is enabled that adds WASD as alternative to the arrow keys: With A being "left", entering names that contain the letter A gives weird results, as the A is placed further to the left, due to the A key press being processed as "left arrow key" as well. 

Can be seen in action here: https://youtu.be/HpULJhf1TKM?t=573

At least this is my personal conclusion from seeing the footage above.

**Comment by Heroesflorian** [comment]
Oh, and presumable, D will have the opposite effect (i.e. jumping one letter to the right) when being added in the middle of a text.

**Comment by Sh0wdown** [comment]
Huh, thanks for the observation.

**Comment by Sh0wdown** [comment]
Fixed in [v2.09](https://github.com/Sh0wdown/UnofficialCrusaderPatch/releases/tag/v2.09).
