### ISSUE TITLE
Allow changing of game speed with non-numpad +/- keys as well

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#179]
For everyone lacking a proper, full keyboard with numpad, not being able to change the game speed with +/- is quite annoying, as currently the regular, non-numpad +/- keys cannot be used for this. 

Thus, it would be awesome to add an option to the patch that modifies the key binding in order to allow game speed changes with the non-numpad +/- keys as well. 

Currently, those keys are not used, i.e. the proposed change should produce no "collisions". I am not sure how the mapping of +/- keys behaves for different keyboard language layouts, though.

**Comment by Krarilotus** [comment]
#432

**Comment by patel-nikhil** [comment]
In pull request #746
