### ISSUE TITLE
KI Siege attacks

### ISSUE THREAD

**Issue by Derever** [Sh0wdown/UnofficialCrusaderPatch#183]
Is there any possibility to change what kind of siege equipment and in what amounts the KI is using? It would be nice if we could combine bigger amounts of catapults with portable shields and other siege equipment and in this way even trigger human player to go for a counterattack.

Also the assembly point for the siege equipment should might be quit a bit further away from the enemy castle.

**Comment by Sh0wdown** [comment]
Is now possible through AIC edits.
