### ISSUE TITLE
A question - which is your favourite of the AI lords?

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#185]
Just a slightly off-topic discussion, what is your favourite AI lord in Stronghold Crusader.

My favourite would have to be Emir, a good and friendly lord with a good personality and some excellent quotes, my favorite being, 'Hot rain, what a fight' :D , but one who is still a big threat to his enemies, both with raids and sieges. Even in vanilla Stronghold Crusader he could often have army sizes of over 300 troops in total.

My second favourite would be Sultan, his poetic quotes are great such as 'the olive branches weep at the Sultan's loss' whenever you destroy his gatehouse or one of his lookout towers and I like his lovely circular castle. I also like his military tactics, consisting of creating loads of slingers for defence and raiding. His sieges though can still be a threat. I wish his economy was better though :(

Phillip is my third favourite, I like his humorous personality and his unique mix of spearmen and knights. My fourth favourite is Frederick, I am glad he can now buy in weapons and attack more often because of the patch. 

Sheriff is my favourite of the evil lords, his castles are very different in design and he is quite humorous too.

My least favourite AI lord would be Nizar. His use of assassins is cool but I don't really like his personality much, I particularly I don't like it when he taunts me 'Does it please you to watch your castle fall about you', as that is quite a hard-hitting taunt!

**Comment by Lolasik011** [comment]
I think for me is Marshal ! In the new patch, he is very strong!

**Comment by TheSnowyChickens** [comment]
Wolf!

**Comment by ByBurton** [comment]
Easily the Rat, Duc de Puce.
I love the unit he uses and his labyrinthic castles. 
I love that he uses a minimalistic economy. 
The only thing I do not like about the Rat is, that he does not man his walls properly.

Also that he sucks too much. With only a few more archers on his walls and around his economy he would be fine.

**Comment by Heroesflorian** [comment]
I personally like... 
- Marshall: Nice guy, old ally from SH1, very long severely underestimated by most, but with modded castles decently strong even before the patch, and has hordes of knights. Also, while being terrible for economy and defense, I really like the visual style of his vanilla castles. 
- Sheriff: Bad guy, but with humour, very long severely underestimated by most, but also very strong with proper castles. His vanilla castles really have a great and unique style. He is a good attacker (and raider), and except the pig he is the only AI to use macemen. 
- Abbot: His personality is not likeable, but as an antagonist I think he is great, especially as he also is the only "church representative" in the game, and the church played a big role in the time period. Another long-underestimated character, with the potential to overwhelm many other AI characters if given proper castles, and the most-famous gold hoarder. And of course, he is the only one to use monks. 

- Saladin: Nice guy, represents power and wisdom and has quite impressive quotes. Also I'd say he's the most "complete" and serious of the Arabian Lords. 
- Richard: Uses highest amount of siege engines of any AI for his attacks, employs battering rams and tunnelors, uses the "rare" unit pikemen (as rare as macemen), and has quite atmospheric and enjoyable quotes, lover of flying rocks and iron bars! 
- Snake, Caliph: They both use slaves to harass, have some good lines and a "nicely evil" / sinister (although a bit sterotypic) personality, making them enjoyable enemies. And the Caliph is infamous for his pitch ditches among the infidels like noone else, of course!

**Comment by PitchNeeded** [comment]
My favourite AI for their castle style would have to be Wazir, his vanilla castles are beautiful and very unique I think. Now that (thanks to the patch) Wazir is no longer so stupid/evil to his peasants as to not buy food in when he runs out, I like him more.

Phillip's vanilla castles are also beautiful, very neatly laid out with nice placement of good things.

Emir's bigger castles are great too, more like a city than a castle and a real economic powerhouse.

**Comment by PitchNeeded** [comment]
> Easily the Rat, Duc de Puce.
> 
> I love the unit he uses and his labyrinthic castles.
> I love that he uses a minimalistic economy.
> The only thing I do not like about the Rat is, that he does not man his walls properly.
> 
> Also that he sucks too much. With only a few more archers on his walls and around his economy he would be fine.

It would good if he sent bigger sized groups of spearmen too in his raiding parties than he currently does, he doesn't send enough spearmen to raid at the minute I don't think.

Rat's vanilla castles are great.

**Comment by PitchNeeded** [comment]
> I think for me is Marshal ! In the new patch, he is very strong!

Yep and as well as attacking more frequently, he is also better defensively too, he can man his towers with more archers now, same with Emir, Frederick and Abbot now they can all buy bows. Marshall can have as many archers on his towers as Snake now I think.

Emir's lookout towers on his vanilla castles are actually very useful now for him defensively, and he can put up to 5 archers in each which very rarely happened before this patch.

**Comment by Krarilotus** [comment]
No issue and no further comments here. Highly oppinion based. Go checkout some discord or forum to take that discussion further!
