### ISSUE TITLE
[Possible Enhancement] Awkward Lord Stance and keep "carry" limit

### ISSUE THREAD

**Issue by EchoRevora** [Sh0wdown/UnofficialCrusaderPatch#188]
Hi, I have a handful of ideas. These are not game-breaking or deeply necessary, but I still want to throw them out there.

1. In skirmishes or Multiplayer games, the AI Lord, after moving him, has a really awkward pose - again, only for the human player. Is it possible to change it back to the default pose after he is sent back to his keep?

2. Is it possible to remove the limit of troops a player can send on his keep?

3. Maybe making it possible to set and edit a default selection in the launcher. 

Again, thank you for all your hard work. It's appreciated. I reckon that the above-listed suggestions are in no way important (or to some degree even necessary). However, maybe some day these things could be looked at. :)

**Comment by ByBurton** [comment]
@EchoRevora Please, try to check if an issue already exists. Keep facing has already been mentioned in issue #153 .
Please edit your issue so that only your third point is mentioned.

**Comment by EchoRevora** [comment]
> @EchoRevora Please, try to check if an issue already exists. Keep facing has already been mentioned in issue #153 .
> Please edit your issue so that only your third point is mentioned.

I actually did that quickly by typing in "keep" when opening an issue, and checking the suggested topics, your topic didn't show up. I'll do the necessary adjustments. I believe my second point is also not mentioned anywhere.

**Comment by Heroesflorian** [comment]
> Maybe making it possible to set and edit a default selection in the launcher.

+1!

**Comment by PitchNeeded** [comment]
> Is it possible to remove the limit of troops a player can send on his keep?

Yes the limit is annoying, if you set a rally point for units on the keep and create lots of these units then eventually some will start walking around your castle as they can't fit on the keep.

AI lords seem to be able to stack much many units on their keep than human players.

**Comment by Monsterfisch** [comment]
not a big fan of ai stacking units on the keep either here I mentioned a different approach [here ](https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/182#issuecomment-451233274) where the ai would split up his attack units around the castle before dispatching  which would result in less crowded/unrealistic keep and in faster dispatching times as the attack units won't have to all take the same patch and creating that notorious long line with the units at the end walking at a crawl.

**Comment by Heroesflorian** [comment]
Also, if a human player really wants to stack units on the keep, just build a single tile of wall adjacent to the back of the keep, and send units to that wall tile... I've already seen human players with 300 swordsmen + 200 crossbowmen piled up on their keep in multiplayer games. 
Personally, I am no fan of this at all, but anyone wanting that already can do it, so I do not see any reason to try and remove already-circumventable limitations in that regard.

**Comment by Krarilotus** [comment]
This has been covered by Monsterfish and Heroesflorians answers, therefore is redundant to other posts. I dont think changing how units stack on walls or towers or keeps will be changed, but feel free to open another issue if you want that.
Changing AI lord stance to default seems to be already in skirmishes? Correct me if i am wrong!
