### ISSUE TITLE
Vorschlag für zusätzliche Angriffstruppen

### ISSUE THREAD

**Issue by Silvergnom** [Sh0wdown/UnofficialCrusaderPatch#19]
Hallo,
wäre es möglich, die Angriffstruppen anderweitig zu erhöhen?
z.B dass die KI nach einem Angriff die zusätzlichen Truppen verdoppelt?
Sähe wie folgt aus:
Wolf greift beim zweiten Angriff mit 10 zusätzlichen Truppen an
Beim dritten mit 20, beim vierten mit 40 etc.
Für mich persönlich würde die KI dann nicht mehr so "festgefahren" wirken und menschliche (als auch Computer) Spieler würden schneller ins schwitzen geraten.

**Comment by ByBurton** [comment]
Das wurde doch bereits angepasst... Unnötig, das noch weiter Auszubauen. Es gibt mehr als genug andere Sachen zu tun...

**Comment by Sh0wdown** [comment]
In [2.04](https://github.com/Sh0wdown/UnofficialCrusaderPatch/releases/tag/v2.04) kannst du die zusätzlichen Angriffstruppen ca. verdoppeln. Ich plane aber noch evtl einen Schieberegler einzubauen, sodass man die zusätzlichen Truppen z.B. auch auf x3, x4 oder auch x1.5 einstellen kann.

**Comment by Silvergnom** [comment]
So wie ich das gelesen habe ist das gerade ein lineares Wachstum, und nicht prozentual.

**Comment by Sh0wdown** [comment]
Das stimmt, in Vanilla ist es linear. Quadratisch ginge bestimmt auch irgendwie, würde ich aber erstmal nicht priorisieren. Du musst auch bedenken, dass die Pausen zwischen den Angriffen auch massiv zunehmen werden.

**Comment by Silvergnom** [comment]
Ja, glaube dass wäre dann wirklich geschmackssache wie man es lieber hat. Da wäre ein Schieberegler wirklich eine gute Idee.

**Comment by ByBurton** [comment]
Wobei ich finde, dass nicht jede KI ihre Angriffe gleich stark erhöhen sollte...

Sonst fallen KI's, die gerne massig Einheiten einsetzen (Ratte, Schlange, Schwein, Phillip, Abt, Emir, Schwein) da zurück...

**Comment by Heroesflorian** [comment]
Und nicht zu vergessen: Bei 2k globalem Einheitenlimit und 8 Spielern sind das gerade mal 250 Einheiten pro Spieler, Bauern und Arbeiter sowie Tiere auf der Map (und wohl auch Ochsen, Kühe, ...) mit eingerechnet. 
Das reicht manchmal schon mit Vanilla-KIs nicht aus, geschweigedenn mit viel größeren Angriffen und stärkeren KI-Burgen.
