### ISSUE TITLE
Zwei Bugs mit v. 2.08

### ISSUE THREAD

**Issue by mceast** [Sh0wdown/UnofficialCrusaderPatch#194]
Hallo!
Ich habe zwei Bugs gefunden. Patch 2.08, maximale Einheiten auf 10 000 und Angriffswellenerhöhung der KI auf den Max - Wert von 60.

Ab einer gewissen Anzahl an Einheiten werden keine neuen Bauern mehr gebildet. Der Ring um das Feuer dreht sich zwar schön weiter, aber es kommt kein neuer Bauer mehr. Ich schätze, die KI hat das gleiche Problem, denn sie greift nicht mehr an, vermutlich weil sie ja auch eine größere Armee bilden muss, bis sie angreift. 
Screen:
https://www.bilder-upload.eu/bild-b7fb92-1546631577.png.html

Zudem war in dem genannten Spiel das Problem, dass es ab Spielgeschwindigkeit 600 extrem langsam wird - ich schätze, die Engine packt es nicht mehr. Bei 500 ist noch alles schön flink ;-) 

MfG

**Comment by ByBurton** [comment]
Dieser Bug ist nicht neu. Wurde bereits in einem anderen issue erwähnt.
Könntet ihr nicht bitte einfach mal alle issues durchgehen, bevor ihr neue postet?
Das wird unübersichtlich ohne Ende..

**Comment by Monsterfisch** [comment]
Das problem mit dem Bug ist das er in einem Kommentar erwähnt wurde und nicht als Bericht selbst. Insofern würde ich empfehlen den Teil mit der Spielgeschwindigkeit zu entfernen, da dieser tatsächlich mit der Engine zu tun hat, und den Bericht speziell auf das Einheiten limit zu reduzieren. =)

**Comment by Sh0wdown** [comment]
> Hallo!
> Ich habe zwei Bugs gefunden. Patch 2.08, maximale Einheiten auf 10 000 und Angriffswellenerhöhung der KI auf den Max - Wert von 60.
> 
> Ab einer gewissen Anzahl an Einheiten werden keine neuen Bauern mehr gebildet. Der Ring um das Feuer dreht sich zwar schön weiter, aber es kommt kein neuer Bauer mehr. Ich schätze, die KI hat das gleiche Problem, denn sie greift nicht mehr an, vermutlich weil sie ja auch eine größere Armee bilden muss, bis sie angreift.
> Screen:
> https://www.bilder-upload.eu/bild-b7fb92-1546631577.png.html

Ja, das konnte ich bisher noch nicht fixen. Vllt sollte ich es aber mal in den Setup hineinschreiben bis das gefixt ist, damit man weiß worauf man sich einlässt. Der Bug ist auch schon [hier](https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/81) gepostet, darum schließe ich hier mal.

> Zudem war in dem genannten Spiel das Problem, dass es ab Spielgeschwindigkeit 600 extrem langsam wird - ich schätze, die Engine packt es nicht mehr. Bei 500 ist noch alles schön flink ;-)

Na dann geh halt einfach nicht über 500. :P Ich glaube das hängt auch etwas mit der PC-Leistung zusammen, bei mir wird es nämlich auf 600 nochmal schneller und bleibt dann aber gleich für höhere Werte. Deswegen werde ich daran erstmal nichts ändern.
