### ISSUE TITLE
Pathing Fix

### ISSUE THREAD

**Issue by Kamiray** [Sh0wdown/UnofficialCrusaderPatch#2]
Sämtliche Einheiten und *ganz besonders die meuchelmörder* könnten in ihrer Wegfindung verbessert werden.  
Hier ein npaar Dinge, die nicht gut laufen:

- wenn meuchelmörder auf feindliche mauern geschickt werden versuchen sie stets durch das torhäuschen hoch zu kommen, solang es offen ist anstatt den kürzesten weg zu nehmen und ihre fähigkeit zu benutzen. (möglicher fix: man ermöglicht meuchelmördern die wand 'anzugreifen' und wandelt diesen befehl in 'hochklettern' um)

- wenn mehrere nahkampfeinheiten eine andere einheit angreifen sollen stellen sie sich nur im viereck um diese einheit herum anstatt sie tatsächlich anzugreifen

- wenn einheiten ihren weg zum ziel suchen beachten sie dabei nicht ob und wie weit sie durch 'langsames terrain' laufen (z.b. moor oder furt).  

- wenn einheiten eine mauer angreifen verteilen sie sich entlang der mauer, anstatt ihren angriff auf den bereich zu konzentrieren, der beim angriffsbefehl angeklickt wurde

- wenn meuchelmörder zum angriff auf ein weit entferntes ziel geschickt werden bleiben einige von ihnen auf dem weg dort hin einfach stehen und tun so als wären sie bereits 'angekommen'

Diese Sachen zu fixen wäre ein SEGEN für dieses Spiel!!
Ich hoffe du nimmst dir die Zeit diese Probleme mal anzuschauen. Wenn du Hilfe brauchst oder etwas 'nicht geht' meld dich gerne bei mir per Mail ;)

Grüße
Vincent

**Comment by Sh0wdown** [comment]
Das sind alles Dinge, die die KI mehr oder weniger komplett überarbeiten würden.
Ohne Zugang zum Source-Code ist mir das ehrlich gesagt zu aufwändig.

**Comment by ByBurton** [comment]
Ich würde auch sagen, dass dies erstmal nicht angegangen werden sollte.
Ich würde eher sagen, wirkliche bug fixes die möglich wären, wie z.B. das Gebäude abreißen der KI.
Oder so Sachen wie die Rekrutierungsgeschwindigkeit von manchen KI's erhöhen (z.B. Sheriff, Sultan)

**Comment by Kamiray** [comment]
ich hab leider zu wenig Ahnung von dem Code um sowas abschätzen zu können aber ich bin davon ausgegangen, dass bspw. das Hochklettern der Meuchelmörder einfacher zu verändern ist als das KI verhalten mit dem Gebäude abreißen.

Welche schritte müsste ich denn unternehmen um mich in die materie einzuarbeiten? Vielleicht bekomme ich das ja gelöst? =)

**Comment by Sh0wdown** [comment]
Nun, du müsstest Assemblersprache lernen und dir einen oder mehrere Disassembler/Debugger, wie zB. IDA, OllyDbg oder CheatEngine, zulegen.
