### ISSUE TITLE
Tor und Wall aus Holz für Crusader bzw. Stronghold Europe

### ISSUE THREAD

**Issue by Halbarad1** [Sh0wdown/UnofficialCrusaderPatch#20]
Hallo,
es gibt eine/ mehrere Modifikationen, die versuchen das Design von Stronghold auf Crusader zu übernehmen. Ursprünglich gab es eine deutsche und eine russische Version, deren Macher sich dann aber zusammengetan haben.
Wobei mir dort am meisten fehlt, dass Holzwälle und Holztore nicht vorhanden sind. Eventuell könntest du dich ja mit denen auseinandersetzen bzw. eine Funktion für das Spiel einfügen, die Holzwälle dem Orgiginal/ der Mod hinzufügt.

Hier mal ein paar Links:
https://www.strategie-zone.de/forum/viewtopic.php?t=22429
https://www.youtube.com/watch?v=g4rxX0pE284
Download der neusten Version (warum auch immer ohne arabische Lords) von Stronghold Europe:
https://www.moddb.com/mods/stronghold-europe/downloads

(die deutsche Mod heißt jetzt übrigens doch anders, ist aber auch noch unter dem alten Titel zu finden)
Viele Grüße und vielen Dank für die bisherigen Leistungen!

**Comment by dot3x3** [comment]
Makes me wonder why these are not ingame, because the graphics for wodden fences are present in the game...

**Comment by Halbarad1** [comment]
> Makes me wonder why these are not ingame, because the graphics for wodden fences are present in the game...

Graphics are ingame, but it seems to be more than just graphics, because they do work different then small walls:
- different costs and health points
- troops can't march on them
- new designs if you mix them up with stone walls (like here: http://stronghold.heavengames.com/maps/pix/palist1.jpg)

In one mod someone used the design of these walls for a ruin in Map Editor, but that surely doesn't come near to a real wood wall.

**Comment by Sh0wdown** [comment]
Too much to change for this.
