### ISSUE TITLE
Kleiner Fehler in 2.09?

### ISSUE THREAD

**Issue by GM-Fluffy** [Sh0wdown/UnofficialCrusaderPatch#203]
Moin,
erstmal großartige arbeit das du Healing in das Spiel implementiert hast. Hätte nie gedacht das man so einen Support für das Spiel noch mal sieht.
Ich hab mir heute mal den Patch angeguckt und habe bei mir festgestellt das die Ritter auf dem Pferd nicht von meinem Mediziner geheilt wurden. Habe das ganze mal ein wenig beobachtet und auch die Pferde sowie die Apotheke wo anders hin gesetzt. Beide male sollten nicht mal andere Einheiten in der nähe gewesen sein. Der Mediziner ist auch ganz normal durch die Einheiten gelaufen somit wäre ein Problem der Reichweite wohl auszuschließen. Ich weiß nicht ob es dazu schon irgendwelche berichte oder Erfahrungen gibt oder ob ich einen Fehler bei mir gemacht habe und wollte das nur mal Kommunizieren.

Ich wünsche einen angenehmen Tag
Fluffy

**Comment by Sh0wdown** [comment]
Ich habe gerade mal getestet und bei mir werden Ritter ganz normal geheilt. Könntest du das nochmal irgendwie überprüfen oder ein Save hochladen wo das der Fall ist?

**Comment by GM-Fluffy** [comment]
Okay ich habe gerade noch mal selbst nachgeschaut. Tatsächlich werden sie geheilt jedoch ziemlich langsam. Dann wird mir das vorhin wohl in der menge der Reiter nicht gleich aufgefallen sein. ;)

Dann war das mein Fehler Sorry ^^

**Comment by Sh0wdown** [comment]
Ritter haben auch ne Menge HP, da ist die relative Heilungsrate nicht so deutlich. :P
