### ISSUE TITLE
Ressourcen werden nicht ausgenutzt von der KI

### ISSUE THREAD

**Issue by Xander10alpha** [Sh0wdown/UnofficialCrusaderPatch#213]
Irgendwie baut die KI teilweise gar nicht ihre Produktion voll aus. Wenn Ressourcen, wie Stein oder Eisen zu weit weg sind baut sie da nichts hin, weshalb sie dann teilweise ohne z.B. Eisenminen da steht. Oder liegt es an was anderem? Ressourcen sind genug da sind nur leer.

Andere Frage kann man das platzieren der Ressourcen optimieren, sodass bei wenig Platz mehr gebaut werden kann oder das die Ochsenställe nähere am Stein sind?

**Comment by Heroesflorian** [comment]
Es gibt eine gewisse Maximalentfernung, ab der Ressourcen von der KI nicht mehr verwendet werden. 

Unabhängig davon platziert die KI insbesondere Eisenminen (und Pechgruben) aber auch in der Nähe nur an bestimmten Punkten. Wenn man das Eisen genau entsprechend platziert, wird es auch effektiv genutzt. 

Bei Ochsenjochen hilft es, wenn viel freier Platz (keine Bäume, Felsen oder Oase) um die Steinvorkommen herum ist. 

---
Bild 1: Eisenvorkommen auf der Map
![grafik](https://user-images.githubusercontent.com/12549394/51079909-28ccd800-16d1-11e9-9e69-7710a01332a9.png)
Bild 2: Eisenvorkommen mit eingezeichnetem Platzierungsgitter; die grünen Bereiche sind geeignet für KI-Eisenminen. 
![grafik](https://user-images.githubusercontent.com/12549394/51079960-8ada0d00-16d2-11e9-9093-d42d429d50e5.png)
Bild 3: KI-Eisenminen wurden platziert. Eisenvorkommen, die nicht am Platzierungsgitter ausgerichtet sind, werden ignoriert. Die KI braucht auf den am Gitter ausgerichteten Eisenminen-Positionen mindestens ca. 6-9 Eisenerz-Felder (je nach räumlicher Anordnung), um dort eine Eisenmine zu bauen. 
![grafik](https://user-images.githubusercontent.com/12549394/51079929-e35cda80-16d1-11e9-9fd3-dbd6f55277ed.png)

Empfohlene Vorgehensweise für Kartenersteller: 
1. 9x9-Felder großen Eisenblob auf der Karte platzieren
2. Spiel starten und merken, wo auf dem Blob Eisenminen platziert werden
3. Von den bekannten Eisenminen-Positionen ausgehend am Platzierungsgitter weitergehen - z.B. per Einzeichnen von Terrain-Strichen, am besten mit Lineal, oder per Aneinanderreihen von 5x5-Felder (entspricht einer 4x4 Eisenminen-Position + 1 Feld "Trennstrich") großen Gebäuden wie Schenken oder ähnlichem, oder ggf. per Platzieren von 4x4-Felder großen Felsen mit jeweils 1 Feld Abstand. 
4. Am Gitter angeordnete Eisenvorkommen dort auf der Karte erstellen, wo man gerne welche haben würde, und entsprechend genug Eisenerz-Felder pro Vorkommen platzieren. 
5. Gegebenenfalls auf den "Trennstrichen" zwischen mehreren Vorkommen, oder 1-2 Felder weiter weg am Rand noch "Hindernisse" platzieren, die dafür sorgen, dass menschliche Spieler dort nicht mehr Eisenminen platzieren können als die KI (4 Felder Eisenerz pro Eisenmine reichen ja eigentlich aus), und das Ganze ggf. noch etwas dekorieren. 
(Hinweis: Sträucher auf den Eisenminen-Positionen werden von der KI in der Regel problemlos überbaut, ggf. die Map nochmal kurz testen, wenn man sich im konkreten Fall nicht sicher ist.) 

Beispiel, wie das dann aussehen kann: 
![grafik](https://user-images.githubusercontent.com/12549394/51080015-e35dda00-16d3-11e9-9d76-02e321e9c55b.png)
![grafik](https://user-images.githubusercontent.com/12549394/51080029-56ffe700-16d4-11e9-91b5-abb7039f2b39.png)
Das bietet sowohl für menschliche als auch für KI-Spieler Platz für 8 Eisenminen. Die 8 Spots werden auch allesamt genutzt, sind kompakt angeordnet und optisch sehr "unaufdringlich".

**Comment by Xander10alpha** [comment]
Danke für diese umfangreiche Antwort habe nicht erwartet, dass sich jemand so viel Zeit nimmt. Danke.

**Comment by Heroesflorian** [comment]
> Danke für diese umfangreiche Antwort habe nicht erwartet, dass sich jemand so viel Zeit nimmt. Danke.

Ach was, die Antwort war nicht viel Zeit! :D 
Sowohl die Erstellung der Karte, als auch die "Eisen-Forschungen" (disclaimer: may be sponsored by **Richard Lionheart Iron Meals Inc.**) liegen schon ein Jahr zurück. 
Das einzige was "neu" ist, ist der Text oben sowie die Erklär-Screenshots mitsamt aufgemaltem Fluss-Gitter^^ 
Viel Zeit hat es seinerzeit gedauert, als ich mich bei einer anderen Karte rumgeärgert hatte, weil die KI das dortige Eisen nicht genutzt hatte... :S

**Comment by Xander10alpha** [comment]
Achso okay trotzdem Danke ;) Das erklärt einiges

**Comment by Sh0wdown** [comment]
Ich denke das Problem lässt sicher leichter mit guten Karten als nem Patch beheben. Ich mach hier mal zu.
