### ISSUE TITLE
Giving the Marshal pikemen instead of swordsmen

### ISSUE THREAD

**Issue by MarcusVipsaniusAgrippa** [Sh0wdown/UnofficialCrusaderPatch#215]
This has been discussed before, but I'd like to propose it again. 

I have two reasons why I think this change would make the Marshal a lot more attractive: 

1. Economy
The marshal has a very, very small economy: He only builds one stone quarry and his three iron mines are only good for supplying about 5 blacksmiths/armorers depending on distance and building (armorers work faster). On the other end he builds some of the most expensive units in the whole game, knights and swordsmen! 
What this results in is the Marshal being very slow in attacking compared to other ais. And no, I'm not saying that he never attacks or anything, it's just that he feels sooo sluggish and slow, he's constantly out of money because even when attacking he still recruits knights. He can hardly afford the recruitment costs and his limited iron decreases his weapon production significantly. 
By giving the Marshal pikemen instead of swordsmen you'd reduce the amount of iron he needs significantly. Moreover, the production of pikes can be quite profitable, so he'd be able to field a bigger industry because of the need for poleturners (which equal more weapons and troops in the long run). 
Would this make him op? Far from it imo since Swordsmen are far better fighters than Pikemen. However I'd rather have a Marshal that attacks more regularely and isn't constantly broke, barely able to afford his knights. This could allow him to save up money and also build catapults, something an ai only does when having 500 gold or more. 

2. Gameplay 
Let's be honest here: Does the Marshal attacking with knights and swordsmen (which are basically dismounted knights) really feel like it fits his character of the military commander? The highest military commander, granted, but nothing like a king. 
This guy isn't some big bad wolf or king/emperor to be able to afford a whole army solely consisting of the best fighters. Frederick does that, but it very much suits him as an emperor imo to have the money and power to field an army like this (compared to Lionheart who only can afford about half their army to be dismounted knights and the Wolf who has about 1/3 swordsmen). 
Giving him Pikemen would not only establish that rank-wise he's lower than a king, it would also give him a unique flavor since no other ai only uses Pikemen while at the same time making Frederick's army even more unique!

"But what about his knights?" I hear you say. Here's the thing: The character of the marshal is defined by his knights in crusader almost as much as philip is. Taking them away from him would be a big disservice and I think nobody would want that. 
If you want a logical explanation though then one could argue that the Marshal being the commander of the realm's cavalry is the reason why he has this many horses. 

Anyways, what do you guys think? The discrepancy between the Marshal's army cost and his economy always bothered me. Would you like Sh0wdown to implement such a change as an option (since the default castles wouldn't work one would have to design new castles or simply add some poleturners, but since this all would be optional I don't see why not)? 

I'd also be willing to donate a few bucks again for such a feature just to see it implemented.

**Comment by Lolasik011** [comment]
I fully support you .

**Comment by Monsterfisch** [comment]
Agreed in terms of it would be nice to have a character that uses pikeman as main strikeforce the only real problem I see here is that the marshall then would need additional workshops in his castle as he would need armors and swords for the knights and pole turners for the pikes. I would rather argue that Phillip would be suited to use some pikeman with his attacks (like 10% pikemen of the entire army) as he has the necessary production buildings in vanilla already and could certainly need a bit of an attack buff. 
The marshall himself can be helped by giving him a stronger economy either by having him build more farms so he can increase food consumption for taxes more quarries etc to support his financial situation. You can also give him pole turners in a custom aiv to give him additional gold (this trick also helps the sultan)  as he immediately sells them for money. overall it would be a good idea to see if the system for tax collection and popularity management of the aiv could be optimized for a better economy to support the current troop production.

**Comment by PitchNeeded** [comment]
I think Phillip should have some pikemen anyway.

Two stage melee attacks (where weak melee units have been sent first followed by stronger units) have been used by some AIs in newer Stronghold titles such as Stronghold Crusader 2, so it would be good to see Philip use this tactic in Stronghold Crusader.

**Comment by PitchNeeded** [comment]
Also the Marshall pikemen suggestion has got me thinking about another possible AI recruitment change:

I was thinking that perhaps from time to time one of Emir's three fletchers could switch from bow-making to crossbow-making and he could recruit a few crossbowmen for defence on his towers (only a few though). He could buy in the leather armour, which isn't too expensive, but he wouldn't buy in crossbows (as they are expensive to buy in), only make them.

It would make his defence a bit better, as well as making him more unique from other Arabian lords.

**Comment by Heroesflorian** [comment]
Regarding crossbowmen for Emir: If he already buys the leather, why not buy the crossbows as well, or permanently have him split production between bows/crossbows 50:50 (like Frederick)? He can definitely afford the occasional crossbow purchase for a few defenders, and he can also make (or save) more money from producing crossbows than bows. 
Not sure crossbowmen fit Emir in terms of character, though. 

---

Regarding the Marshal, I think with weapon purchases the lack of poleturners for his vanilla castles would not be that much of a deal breaker necessarily, and I do think pikemen would fit his character better than swordsmen. 
Sure, producing pikes would be a bit cheaper, but then again buying pikes is considerably cheaper than buying swords or armour (or even bows) as he usually does with his vanilla castles who are terrible in terms of both defense and economy anyway. The weapon production of his vanilla castles is way too small and inefficient - from fear factor to placement and protection against interruptions to a lack of iron every now and then - for supporting his recruitment. 
Giving the Marshal another quarry and/or another iron mine for some slight buff to his economy would be a welcome change as well, of course. 

---

Regarding Phillip, I agree he could also do with some pikemen. And a feeew archers or crossbowmen (not many, though). 
Also, elsewhere a few pikemen for the Abbot (like a Swiss Guard) have been suggested as well, also worth a thought. 
And with all those suggested pike users, I think some more users for macemen would also be nice.

**Comment by ByBurton** [comment]
I personally think the marshal should be sluggish and slow. He is a senil old guy.
Give him some peace.
And why would pikemen fit better? Knights do go well with swordsmen, same weapons, and slow but effective.

-----

Emir and crossbowmen: I would give my okay here, if they would be reduced in amount compared to the regular European archers.

-----

Philip: Pikemen yes, but not exclusively. I would still add regular spearmen to them. As main force.
Just add a few pikemen and he would be good.

**Comment by PitchNeeded** [comment]
> Emir and crossbowmen: I would give my okay here, if they would be reduced in amount compared to the regular European archers.
> Edit: As long as he BUYS the leather.
> 

Yes he would only train a few, and maybe put them on the keep just as a last ditch defence. 

> Regarding crossbowmen for Emir: If he already buys the leather, why not buy the crossbows as well, **or permanently have him split production between bows/crossbows 50:50 (like Frederick)**?

He would have to buy in more bows though (especially if he was intending to siege an enemy with a moat), but he could sell excess crossbows to make up for it.

Of course if Emir had a few crossbowmen, it wouldn't be too difficult to give Saladin some too, and maybe his metal armour and swords makers could be replaced with fletchers.

He can recruit crossbowmen plus sell crossbows for gold which would generate as much gold as his metal armour and swords.

**Comment by ByBurton** [comment]
> Of course if Emir had a few crossbowmen, it wouldn't be too difficult to give Saladin some too, and maybe his metal armour and swords makers could be replaced with fletchers.

Absolutely no. Saladin is supposed to only use Arabian units.

**Comment by PitchNeeded** [comment]
> > Of course if Emir had a few crossbowmen, it wouldn't be too difficult to give Saladin some too, and maybe his metal armour and swords makers could be replaced with fletchers.
> 
> Absolutely no. Saladin is supposed to only use Arabian units.

On reflection, you are probably right, actually! I was just thinking if Emir was given a few crossbowmen, Saladin should be boosted a bit too defensively. Maybe slingers on the keep would be better for him then as a defensive boost.

**Comment by ByBurton** [comment]
Firefly had planned to give Slingers to the Caliph. Why not to the mighty Saladin as well?
Also Saladin should probably also have defensive swordsmen (Arabian).

**Comment by ByBurton** [comment]
This issue should be deleted and go under #28

**Comment by PitchNeeded** [comment]
> Firefly had planned to give Slingers to the Caliph. Why not to the mighty Saladin as well?
> Also Saladin should probably also have defensive swordsmen (Arabian).

Saladin and Wazir having slingers and Emir having either slingers or a few crossbowmen or both would be great.

Does Saladin not already have defensive Arabian swordsmen? He does still keep some Arabian swordsmen on his keep after his siege force goes to siege someone, I thought?

Or do you mean he should have a larger counterattack force of Arabian swordsmen that he can send out to counter threats on farms like Emir does?

**Comment by ByBurton** [comment]
> Or do you mean he should have a larger counterattack force of Arabian swordsmen that he can send out to counter threats to economic buildings like Emir does?

I meant defensive units that he can use to patrol around his castle grounds. (Like the rat with spearmen, the pig with macemen)

**Comment by PitchNeeded** [comment]
> > Or do you mean he should have a larger counterattack force of Arabian swordsmen that he can send out to counter threats to economic buildings like Emir does?
> 
> I meant defensive units that he can use to patrol around his castle grounds. (Like the rat with spearmen, the pig with macemen)

Yeah I have seen Emir patrolling with Arabian swordsmen, I see sometimes a group of them coming off his keep and out the castle gates and along the side of his castle, and I initially think its one of his raiding parties or counterattack forces but then they re-enter the castle and go back to the keep.

It would be good if Saladin did this too, they might be able to intercept enemies such as raiding knights when patrolling just outside Saladin's castle.

**Comment by Panbutt** [comment]
I honestly think Marshal is in a good spot. Marshal is all about honor on the battlefield and brotherhood among soldiers, Knights and Swordsmen are the best unit for representing that. The only thing I would adjust is giving him Apple Farms and more Quarries to sustain his economy better.

**Comment by PitchNeeded** [comment]
Yeah I do kind of like how Marshall's main attacks are like a Crusader unit version of Sultan's!

**Comment by Halbarad1** [comment]
I also do like the Marshal the way he is (he could have some more eco-buildings outside his castle, but I wouldn't change his mechanics). The only AI I really don't like is Phillip. It would be really cool if Phillip would only build Pikeman in Lategame. He already got the right economy for Pikes and armors. 

**New Philip:**
_Beginning: Spearman
Middlegame: Spearman, few Pikeman and Knights
Lategame: Pikeman and Knights_

Philip already got the right economy (it could be made better, but it would work the way it is now) and Nizar is also an AI building troops at the beginning he doesn't really use in the end (Slaves), so that should be possible too.

**Comment by PitchNeeded** [comment]
This transition in unit types for Phillip as the game goes on sounds like a great idea!

Maybe Snake too could start hiring better units late game such as a few assassins or a few Arabian swordsmen.

As for Nizar, I think he needs to create fire ballistae if he has enough gold and roll them forward like Wazir does, and maybe Nizar could create a catapult occasionally too. He is the only AI who has an engineer's guild but never creates any siege engines apart from his defensive fire ballistae.

**Comment by Monsterfisch** [comment]
not sure what causes the transition of troops at the moment but I am almost certain it is not an intended feature of the game but more a bug where the ai forgets to recruit those units.

Based on that I would assume this mechanic would have to be built from scratch it sounds very cool though. however, I wouldn't have Phillip switch off spearman completely his main force should be spearman assisted by pikes that way it's more historically accurate to the French armies at the time. (in my humble opinion Phillip should use crossbowmen and cheese farms as well but that's a different story as it would fit his character be more historically accurate but would require his castles to be changed unless he would buy the crossbows)

**Comment by ByBurton** [comment]
Yes, his main force should still be spearmen.

**Comment by PitchNeeded** [comment]
Phillip definitively needs strengthened a bit with his sieges (come on, he is supposed to be a king of France after all!) and Sultan needs to recruit slaves if he has to dig up an enemy moat. These should be the two priorities first with changing AI units I think!

**Comment by Heroesflorian** [comment]
> Philip already got the right economy (it could be made better, but it would work the way it is now) and Nizar is also an AI building troops at the beginning he doesn't really use in the end (Slaves), so that should be possible too.

Phillip's economy is questionable imho... if he is left alone and has full access to farmland and iron, then yes he has enough gold, because spearmen are dirt-cheap, ranged troops he barely ever recruits, and some knights here and there are relatively cheap in smaller amounts when producing weapons rather than buying them. But when he is actively attacked and forced to replace buildings or towers (no quarries!), recruit troops more frequently, etc, then his gold can dwindle rather quickly. 

Anyway, Nizar DOES still recruit slaves in the lategame. He just happens to use slaves mainly for digging moat, and if his early-game slaves survive (as not uses offensively) and Nizar's moat isn't dug up by opponents, Nizar has no need to recruit more slaves later. When his existing moat-digger slaves die and his moat needs "repair", though, then he will recruit new slaves even in the lategame. 
Also, iirc, Nizar sends some slaves with his attack armies when the opponent has moats - even in the lategame. 
Thus, I cannot really agree with the hypothesis that "troop usage changes over time" really are a thing that is mechanically present or intended in the vanilla game. 
Even if occasionally it can "accidentally" occur (or seem that way) under certain circumstances... similar as for knight-using AI characters that might happen to not use knights in the early game simply because they don't have enough spare gold to construct stables early on. 

---

Now, this does not mean I would not like the idea as such - in fact, I do like the idea of troop compositions changing throughout a game - but I do not think this is mechanically supported out of the box. I do think this would have to be implemented "from scratch" by the patch author, which might be complicated.

**Comment by PitchNeeded** [comment]
> I do like the idea of troop compositions changing throughout a game - but I do not think this is mechanically supported out of the box. I do think this would have to be implemented "from scratch" by the patch author, which might be complicated.

Yes I like the idea of troop compositions changing throughout the game too, that's what could happen with the Emir and crossbowmen and Phillip and crossbowmen ideas, they would only start switching their bow production to crossbows from time to time and producing a few crossbowmen for defence later on in the game, when bigger enemy armies are likely to be attacking them. Also Nizar could start rolling forward fire ballistae later in the game too.

**Comment by Sh0wdown** [comment]
This is now possible through AIC edits.
