### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by Shatrico** [Sh0wdown/UnofficialCrusaderPatch#22]
will it be possible to create an installer which runs on Linux? because I can't run the installer with wine ( didn't start).

**Comment by ByBurton** [comment]
It won't start, it is a Windows application...

**Comment by Sh0wdown** [comment]
The installer is based on Microsoft's .NET Framework and, I guess, thus won't run on Linux.
So you could either run the setup on a windows machine and then just copy the modified "Stronghold Crusader.exe" binary to your Linux PC, or compile the source code of this GitHub repository with [Mono](https://www.mono-project.com/). https://www.codeproject.com/Articles/9407/Introduction-to-Mono-Your-first-Mono-app

**Comment by Evrey** [comment]
Another Linux user here for the statistics.

**Comment by funghetto** [comment]
I've been able to run the installer by installing with winetricks dotnet40.
