### ISSUE TITLE
New graphics mod , and retexture (ENB)

### ISSUE THREAD

**Issue by Grochuuu** [Sh0wdown/UnofficialCrusaderPatch#220]
pls add this xD

**Comment by StrongholdFan** [comment]
There are no real graphics mods for Crusader 1, only retextures. What do you mean by ENB? ENB series?

**Comment by Grochuuu** [comment]
> proszę podać więcej informacji i linki do treści, do których się odnosisz. Z takim oświadczeniem / takim żądaniem nikt nie wie, o co ci chodzi, a zatem nie będzie można go nawet rozważyć.

i don`t have information :(

**Comment by Monsterfisch** [comment]
what are you asking for then....its a bit confusing frankly

**Comment by Sh0wdown** [comment]
It's probably about improving Crusader's graphics. But I am no animator/graphic designer so unless someone else redraws Crusaders graphics it's not gonna happen.
