### ISSUE TITLE
Maximum Troop Limit Issue / Problem mit Maximalem Einheitenlimit

### ISSUE THREAD

**Issue by Triari1** [Sh0wdown/UnofficialCrusaderPatch#223]
Trotz mehrmaligem installieren des Patches (ebenso verschiedene Versionen) ist das Einheitenlimit bei mir auf ca. 1.600 begrenzt. Sobald ich also gegen mehrere KI's spiele, kommt es nach einiger Zeit zu einem Stillstand, da weder ich noch die KI Truppen rekrutieren kann. Mache ich irgendwas falsch oder geht es anderen auch so? (Im Installer ist das Limit auf das Maximum von 10.000 gesetzt.)

Danke im Voraus für jede Hilfe :)

________________________________________________________________________________________________________

Despite several installations of the patch (even with different versions) is the troop limit for me at a maximum of 1.600. So once I play against several AI opponents I reach a point where neither me nor the AI is able to recruit more troops. Anything I did wrong or is anyone experiencing a similar issue? (The limit on the Installer is set to the maximum of 10.000)

Thanks in advance for any help :)

**Comment by Monsterfisch** [comment]
das problem wurde bereits als [report  ](https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/81)aufgeführt wäre gut wenn du diesen Report hier schließt damits übersichtlich bleibt
