### ISSUE TITLE
Erhöhung der Belagerungsgeräte beim Angriff

### ISSUE THREAD

**Issue by GutentagderHerr** [Sh0wdown/UnofficialCrusaderPatch#225]
Wie oben steht ^^

Z.B. die Schlange hat max. nur ein Katapult, was ziemlich wenig ist. Wäre gut, dass man diese Anzahl (Pro Angriff) auch erhöhen könnte.

**Comment by PitchNeeded** [comment]
I suppose some increases in AI catapults in sieges would be good. All the AIs that use catapults in sieges could do with one or two more catapults. Wazir and Marshall could do with another trebuchet too.

As I said in another 'issue' on here, I do think Nizar might benefit from producing the occasional non siege catapult too and rolling it forward, along with producing non siege fire ballistae too. Only if he had enough money though.

**Comment by GutentagderHerr** [comment]
> 
> 
> Soll Friedrich etwa später mit 12 Triboken vor der Festung des Feindes stehen ? xd

Nein aber Kis die nur 1 bis 2 Katapulte haben, können ruhig im lategame mehr haben

**Comment by Monsterfisch** [comment]
die KI soll erstmal lernen seine katapulte in einem logischen abstand aufzubauen bevor man dem noch mehr gold in den tod schickt

**Comment by irgendein-alf** [comment]
in relation zu den truppenkosten ist 1 katapult wenig. zudem finde ich den abstand aktuell gut so, weil die ki damit die op-heit des katas nicht ausnutzt.

**Comment by Monsterfisch** [comment]
Deswegen soll die ki ja die katapulte gescheit einsetzten dann passt die "opheit" der katapulte auch zu der truppenmenge. Mit dem beiläufigen Effekt das die kis kompetenter erscheinen und so einen sieg über sie noch lohnenswerter ist. Immerhin ists ja auch nicht so das in damaligen belagerungen hunderte von katapulten verwendet wurden da reichten meist schon sehr wenige die durch dauerbeschuss die mauern zum bröckeln bringen immerhin zogen sie sich teils über monate-jahre.

**Comment by Halbarad1** [comment]
> Soll Friedrich etwa später mit 12 Triboken vor der Festung des Feindes stehen ? xd

fänd ich schon gerechtfertigt, gerade nach 2 Stunden Spielzeit wenn er mit 300 Schwertkämpfern ankommt, warum dann auch nicht mehr Triboke/ Katapulte? Ab einem bestimmten Zeitpunkt machen Sturmangriffe halt fast keinen wirklich deutlich stärkeren Schaden mehr,gerade wenn der Gegner Armbrustschützen, Feuerwerfer und/ oder Pechgräben platziert hat (eventuell sogar in Kombination mit Burggraben). Die arabischen Lords mit genügend berittenen Bogenschützen schaffen es eventuell die Türme zu leeren, aber die Europäer haben damit ziemlich große Probleme, gerade wenn keine Armbrustschützen für den Angriff verwendet werden. 
Und für mich als menschlichen Spieler besteht Crusader im Moment auch größtenteils nur daraus die Anfangsphase zu überstehen, da keine KI wirklich für mich gefährliche Angriffe führt. Wenn mit 3 Triboken geschossen wird habe ich genügend Zeit meine Türme zu reparieren und selbst wenn ich nicht repariere habe ich zum Teil die feindlichen Angrifftruppen erschossen bevor der Turm zerstört wurde.

Und gerade wenn eine KI wie der Abt im Lategame sowieso mal genug Geld hat kann sie es ja auch einmal gescheit einsetzen.

**Comment by Monsterfisch** [comment]
lategame ist es durchaus verständlich, dass die menge an Belagerungsgeräten ansteigt insofern sollte da ja niemand groß Einwände haben. Größeres Problem ist, denke ich eher wie die KI die Geräte vor der Festung platziert und welche teile der Burg beschossen werden (derzeit zielt die KI ja vorzugsweise auf die nächstgelegene mauer/Turm der jetzt aus der KI Perspektive direkt repariert wird, sofern Stein vorhanden. Würden die Geräte allerdings vorzugsweise türme anvisieren und in entsprechendem abständen platzieren wäre das sehr wünschenswert. Denke aber bevor einfach die Menge erhöht wird sollte dafür gesorgt werden das angriffe generell ein bisschen kluger vonstattengehen und eventuell auch Schilde zum Schützen von Belagerungsgeräten eingesetzt wird haben die devs im 1ten stronghold ja auch hinbekommen ;).

**Comment by Halbarad1** [comment]
Wenn ich dich jetzt richtig verstanden habe dann schön das wir dann einer Meinung sind, das die Erhöhung der Anzahl der Belagerungsgeräte eine gute Sache ist. Und ich stimme dir vollkommen zu dass das Nutzen der Belagerungsgeräte von KIs verbessert werden sollte. 
Auf die Diskussion wann die einzelnen Vorschläge eingebaut werden würde ich jetzt nicht weiter eingehen, da der Fall mit den Belagerungsgeräten doch sehr dem der normalen Truppen ähnelt:
Die Erhöhung der Rekrutierungsgeschwindigkeiten und Truppenzahlen von KIs und die Art, wie die KI sie einsetzt, wurde ja auch mal diskutiert. Beides wurde dann auch nacheinander eingefügt. 
Was jetzt zuerst eingefügt wird würde ich heute wie damals Sh0wdown überlassen wenn sowieso alle darin übereinstimmen, dass es hinzugefügt werden sollte. Wenn er bspw. über ein halbes Jahr den einen Vorschlag nicht umgesetzt kriegt sollte ihn das ja nicht davon abhalten den anderen, eventuell leichteren Vorschlag einzufügen.

**Comment by Sh0wdown** [comment]
Lässt sich jetzt durch die AIC-Dateien editieren.
