### ISSUE TITLE
AI starting gold

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#23]
It would be good to be able to have the AI be able to start a game with even more than 40,000 gold....maybe be able to change it to double that at least....especially as some of the AIs with big castles (Wolf, Emir, Saladin especially) can go down almost 20,000 gold at the start just to complete their castle and make their first attack force.

**Comment by Heroesflorian** [comment]
In Crusader Extreme one can easily create a full 20-mission custom skirmish trail, and the starting gold options there range up to 120k gold... achieving mod compatibility with Extreme would come in very handy there. 
Anyway, I am not really sure there is much need for 120k starting gold in practice - either the AI will run out of gold eventually no matter the starting gold, or it will pile up more gold than it spends...

**Comment by PitchNeeded** [comment]
You are right. However it would be really good (and really hard for the human player) to have a Normal Mode (with low troops and low starting goods) 3,000 gold human player, 40,000 gold AI option!

**Comment by Sh0wdown** [comment]
I feel this isn't really worth it.
