### ISSUE TITLE
Stronghold Crusader Patch 2.09 Installation error

### ISSUE THREAD

**Issue by garten25** [Sh0wdown/UnofficialCrusaderPatch#230]
![unbenannt](https://user-images.githubusercontent.com/47187632/51997957-149e1e80-24b8-11e9-9a7f-41a64ccc832a.PNG)
![unbenannt1](https://user-images.githubusercontent.com/47187632/51997958-149e1e80-24b8-11e9-923c-1ddca5de1840.PNG)
![unbenannt2](https://user-images.githubusercontent.com/47187632/51997960-149e1e80-24b8-11e9-9fc4-6c1e79113973.PNG)
![unbenannt3](https://user-images.githubusercontent.com/47187632/51997961-149e1e80-24b8-11e9-93a1-48883f7e3166.PNG)
![unbenannt4](https://user-images.githubusercontent.com/47187632/51997962-1536b500-24b8-11e9-9f66-bb79490c0fdf.PNG)
Here is what i choose in Installation and the resolving error code. Help pls

**Comment by Lolasik011** [comment]
https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/70

There is a small installation guide for mod.

**Comment by Sh0wdown** [comment]
Either something is accessing the file "Abbot1.aiv" in your Crusader folder, blocking the patcher from editing it (f.e. Crusader running in the background?), or the file has writing protection for some reason.
