### ISSUE TITLE
--Busy--

### ISSUE THREAD

**Issue by Sh0wdown** [Sh0wdown/UnofficialCrusaderPatch#231]
In case you're wondering why I became so quiet, I am busy with studying atm. So I don't know yet when I will find the time to work on another update, even though I'd like to.

**Comment by Monsterfisch** [comment]
Best of success with the studies, priorities need to be set after all! there will be plenty of material to dig through when/if you find time to look into it again so no worry there. ;)

**Comment by ByBurton** [comment]
Thank you for letting us know.
I guess I'll stop hitting F5 on this project for a while then ;)

**Comment by PitchNeeded** [comment]
Best of luck with your studies and as Monsterfisch said there will be lots of material to put into the new patch when it comes such as maybe the mosques and dry moat ideas. I shall maybe work on a new Crusader trail too, which is one of the few things I am capable of adding to the game (along with AIV edits) as I barely know anything about Stronghold Crusader coding :(

Btw when you do get the time to do the new patch, my vanilla AIVs apothecary edit is here to put on the new patch as a new AIV option https://drive.google.com/drive/folders/1gfqCyRqYK9LmV1YgTOeYntDp_N1Q__Dg?usp=sharing

**Comment by Lolasik011** [comment]
@PitchNeeded  Ty for Castle :)

**Comment by Heroesflorian** [comment]
Best wishes for your studies! 
In case you need some trebuchet reinforcements for a tough-to-crack exam, you know where you can find us! ;)
