### ISSUE TITLE
[Patch Bug] Laddermen costs, Leiterträger Kosten

### ISSUE THREAD

**Issue by Serpens66** [Sh0wdown/UnofficialCrusaderPatch#233]
I have the CD Version of Stronghold crusader+extreme.
I installed the official HD Patch first (v1.4.1) and then this unofficial patch.

The costs of Laddermen are still shown with "4", but when recruiting one, 38 is substracted.

Since nobody reported it yet, maybe my game version is to blame?

----
Ich habe die CD version von Stronghold crusader+extreme. Zuerst hab ich den offiziellen HD Patch (v1.4.1) installiert und danach diesen inoffiziellen patch.

Die Kosten von Leiterträgern werden immernoch mit "4" angezeigt, abgezogen werden beim Rekrutieren aber 38.

Da das noch keiner gemeldet zu haben scheint, könnte es wohl an meiner Stronghold version liegen?
Ich besitze das Spiel sonst auch noch bei GOG und könnte es damit nochmal installieren.
Ein 4tes mal, diesmal bei steam, würde ich mir das Spiel allerdings nicht kaufen wollen.

**Comment by Lolasik011** [comment]
In the Steam version, I'm fine.

**Comment by Halbarad1** [comment]
Ich spiele mit dem Patch 1.3, da 1.4 soweit ich weiß nichts verändert außer dass Werbung für Stronghold Crusader 2 im Ladebildschirm auftaucht und dass man (warum auch immer) sich keine Maps mehr im Multiplayer verschicken kann (und teilweise kamen bei mir auch andere Probleme auf wenn ich das Spiel z. B. auf nen anderen PC kopiert habe hat er dort nicht automatisch die Ordner erstellt oder aus irgendeinem anderen Grund nicht gestartet.

Aber wenn ich das richtig in Erinnerung habe ist der inoffizielle Patch sowieso auf Version 1.3 oder die Steam-Edition ausgelegt. Also probier erst Version 1.3

**Comment by Sh0wdown** [comment]
Ich spiele mit Steam HD und bei mir werden die Kosten gar nicht angezeigt. Kannst du mir mal deine Crusader.exe bei E-Mail oder so schicken? Dann kann ich da mal nachforschen.

**Comment by Serpens66** [comment]
Brauchst du die aktuelle exe (HD patch + 2.09) oder die Originale oder die 1.41 exe?
Hab hier erstmal meine aktuelle:
https://mega.nz/#!x14RlCQT!V1D_X_u8PEdimtFueY6ygqU_XLAXScs7QzwWLXkGcNE
("im browser downloaden" wählen)

PS:
danke für die schnelle antwort und viel erfolg weiterhin beim studium :)
Finde es toll dass es Leute wie dich gibt, hoffe du kannst vllt sogar einmal von spenden für solche aktionen leben (hättest es verdient und es braucht mehr die sowas machen :D) werde aufjedenfall morgen versuchen ne spende zu verschicken
