### ISSUE TITLE
Raise maximum army size

### ISSUE THREAD

**Issue by dot3x3** [Sh0wdown/UnofficialCrusaderPatch#24]
Would be nice to set the maximum army size to a higher number...

**Comment by PitchNeeded** [comment]
No I think it's fine as it is. If you are playing against 7 AIs all allied against you, the army size limit means that it is harder to defeat the first AI as you have less troops to attack them with (as you still have to have defensive troops too).

**Comment by dot3x3** [comment]
You don't have to enable it in the Mod...

**Comment by ByBurton** [comment]
Would be nice to set the maximum army size to a higher number...Would be nice to set the maximum army size to a higher number...

There is a maximum amount of units on a map, so this would limit that.
And if the limit is reached, other units will despawn.

**Comment by Sh0wdown** [comment]
Added in v2.05
