### ISSUE TITLE
Patch 2.10 berittene Bogenschützen Rush funktioniert nicht mehr 

### ISSUE THREAD

**Issue by J0J0Jo** [Sh0wdown/UnofficialCrusaderPatch#240]
Seit dem die Nahkämpfer zuverlässig den Bergfried stürmen, tuen dass die berittenen Bogenschützen nicht mehr so zuverlässig. 
Ich habe das in Extreme sowohl beim Wazir als auch Emir beobachtet. Sie stürmen normalerweise sobald der Weg zum Bergfried frei ist mit allen berittenen Bogenschützen. Jetzt passiert das höchstens noch nach und nach mit sehr wenigen.

**Comment by Sh0wdown** [comment]
Danke für die Info, hab schon ne Idee woran das liegen könnte.

**Comment by LordDerMoff** [comment]
Das liegt bestimmt daran dass berittene Einheiten nicht auf den Bergfried können und lieber ein Bewegungsbefehl statt einem Angriffsbefehl gegeben wurde, oder irre ich mich? Wie jeder weiß ist ein Angriffsbefehl auf den Lord sehr unsinnig 💯. Die Fernkampfinfanterie wird ja für gewöhnlich schon bevor ne Bresche geschlagen ist von den Verteidigern hingemetzelt. Kann es sein dass falls dem mal nicht so ist durch den Bewegungsbefehl nun auch die Fernkampfinfanteristen den Bergfried stürmen? Wär auch nur bedingt schlimm da die ja doch noch minimalistischen Schaden machen und beim Lord vor allem Masse entscheidend ist xD

**Comment by J0J0Jo** [comment]
@LordDerMoff Naja, was die infanterie Fernkämpfer machen ist glaube ich nicht so verbuggt. Die haben das meines Wissens schon immer gemacht (langsam in Richtung Bergfried zu laufen wenn es offen ist).

Allerdings sind hauptsächlich die Angriffe vom Emir, Wazir (vielleicht noch ein wenig Kalif und Saladin) damit um ein vielfaches schwächer, da sie normalerweise die Berittenen hinten stehen haben und mit gesamter Macht die Bresche stürmen.

**Comment by Sh0wdown** [comment]
Sollte in der kommenden Version 2.11 gefixt sein.
