### ISSUE TITLE
Thanks for the new patch...one note about it

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#243]
Many thanks for the new patch. 

One note about it though....

The description for my edit of Evrey's castles says it has added mangonels and ballistas but in fact that version doesn't have those but is the one with the added apothecaries and wells. My thinking was that some people may just want the added apothecaries to the vanilla castles and not the added ballistas and mangonels.

My fault really. I should have been more specific that my new edit of Evrey's vanilla castles didn't have the added ballistas and mangonels. I would like to do a new version for 1.11 which has those AND the apothecaries though, I shall start working on that for the next patch. I would like it to be a separate AIV option though!

**Comment by Sh0wdown** [comment]
Could you send me a version which includes both the ballista and apothecary changes? Since some of the translations are already done I would then use that version this patch and add more version in future patches.

**Comment by PitchNeeded** [comment]
> Could you send me a version which includes both the ballista and apothecary changes? Since some of the translations are already done I would then use that version this patch and add more variations in future patches.

I will do, I will start working on it and will send it to you in the next few days.

**Comment by J0J0Jo** [comment]
Hi Sh0wdown, I heard from Tatha that the patch is supposed to come out very soon. Will you release it in the near future or wait for PitchNeeded's AI edits and delay the patch for a few days? :)

**Comment by Sh0wdown** [comment]
Nevermind, I added to options in v2.11 now, one with wells&apothecaries and one with mangonels&ballistae.
