### ISSUE TITLE
No Rush in singleplayer? 

### ISSUE THREAD

**Issue by Fognar99** [Sh0wdown/UnofficialCrusaderPatch#247]
Hello!
I really like the feature "No Rush" from multiplayer, and I was wondering, is it possible to make it happen in Skrimish mode?

**Comment by ByBurton** [comment]
This issue already exists. #171 
Please delete this one.

**Comment by ByBurton** [comment]
Don't be mad at me, trying to help this guy.
We have way too many issues....
