### ISSUE TITLE
Larger maps than 400x400?

### ISSUE THREAD

**Issue by meisanon** [Sh0wdown/UnofficialCrusaderPatch#25]
I'm sure it's still in the realm of fantasy, but with all these nice new ai tweaks and fixes, it would be amazing if there was some way to increase the map size even further.

**Comment by Sh0wdown** [comment]
I have already looked into this and it seems very difficult to achieve through reverse-engineering (without access to the source code).

**Comment by PitchNeeded** [comment]
A map with more than 8 players on it would be amazing too!

**Comment by Evrey** [comment]
More than 8 players is yet even harder to modify. Too many statically allocated arrays for that.

**Comment by dot3x3** [comment]
> A map with more than 8 players on it would be amazing too!

well there is barely enough space for the existing 8 players... so larger map with 8 players would be awesome, but very unlikely to get. There is almost no information about the map files and you would have to change the code for the game and the map editor...

**Comment by nicholasjb89** [comment]
Can I tag onto this and ask. If one where to modify the .map data to allow for larger maps. Could the game handle it? Basically if the larger modified map appeared to be a legit map is there things like hard coded values in the way of playing the map?

**Comment by dot3x3** [comment]
afaik no one knows how to edit the map files for larger sizes, so it’s unknown weather the map can handle larger maps...

**Comment by Sh0wdown** [comment]
I managed to create larger maps ingame, but they were glitched out and crashed after a while in the editor.

**Comment by nicholasjb89** [comment]
Ok thank you. I might have a crack at the .map files anyways just because i'm curious but thank you for rhe quick response. I love the patch man!
