### ISSUE TITLE
Evreys modifzierte Burgen werden nicht gebaut

### ISSUE THREAD

**Issue by Zer0oZ** [Sh0wdown/UnofficialCrusaderPatch#252]
Hab soeben den neuen Patch getestet und alles funktioniert wie es sein sollte, allerdings fiel mir auf, dass Evreys modifizierte Burgen nicht gebaut werden - es werden weiterhin die Vanilla-Burgen errichtet. Hab daraufhin die anderen Option durchgetestet und der Rest scheint einwandfrei zu funktionieren, betrifft also nur Evreys Burgen.

**Comment by Sh0wdown** [comment]
Danke für die Info! Hab beim Verschieben in die neue Sektion ne Einstellung vergessen.
Ist jetzt gefixt in [v2.11a](https://github.com/Sh0wdown/UnofficialCrusaderPatch/releases/tag/v2.11a)
