### ISSUE TITLE
create fix with updated language please ...

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#253]
will be deleted

**Comment by Sh0wdown** [comment]
Done. Sorry, I wanted to get out the Release today and wasn't sure whether you would be around soon.
[v2.11b](https://github.com/Sh0wdown/UnofficialCrusaderPatch/releases/tag/v2.11b) Thanks for your help!

**Comment by Lolasik011** [comment]
No problem ! Thanks @Sh0wdown for the great patch !!!
