### ISSUE TITLE
Thanks @Sh0wdown for the great patch !!!

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#255]
Thanks @Sh0wdown for the great patch !!!

**Comment by Lolasik011** [comment]
Thanks @Sh0wdown for the great patch !!!

**Comment by PitchNeeded** [comment]
Thanks a lot Sh0wdown.

Hopefully Phillip will be less useless defensively now :D, a small group of swordsmen will no longer be enough to kill Rat and Richard won't have to rely so much on his heavily armoured troops so much now for defence. 

Can you please make an an option in the next patch to increase Abbot, Emir, Wazir and Saladin's defensive archers a little bit. These four AIs all have big castles and could benefit a few more defensive archers I think.

Suggested amounts: For Emir 2 more European archers per spot and 2 more Arabian archers per spot, for Wazir and Saladin 4 more Arabian archers per spot and for Abbot 4 more European archers per spot.

Also for Sheriff - 4 more crossbowmen per spot ideally.

**Comment by MarcusVipsaniusAgrippa** [comment]
> 
> 
> Thanks a lot Sh0wdown.
> 
> Hopefully Phillip will be less useless defensively now :D, a small group of swordsmen will no longer be enough to kill Rat and Richard won't have to rely so much on his heavily armoured troops so much now for defence.
> 
> Can you please make an an option in the next patch to increase Abbot, Emir, Wazir and Saladin's defensive archers a little bit. These four AIs all have big castles and could benefit a few more defensive archers I think.
> 
> Suggested amounts: For Emir 2 more European archers per spot and 2 more Arabian archers per spot, for Wazir and Saladin 4 more Arabian archers per spot and for Abbot 4 more European archers per spot.
> 
> Also for Sheriff - 4 more crossbowmen per spot ideally.

But, where is the love for the Sheriff? He has only 22 archers rn, that's ridiculous!
