### ISSUE TITLE
 The idea: fire arrows (damage) and animation of burning units.

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#256]
I have an idea :
I think it would be possible to do more damage to the fiery arrows and add animation of death from burning to units.

I think it looked realistic and would add more meaning in fiery arrows.
 
@Sh0wdown  Is it possible ?

**Comment by PitchNeeded** [comment]
Interesting topic.

Well it may be realistic if they did a little more damage to less armoured troop types I suppose but for swordsmen, Arabian swordsmen, pikemen and knights their heavy armour would protect them well against fire arrows.

However I suppose I would like the idea of, for example, Caliph's archers getting rid of their -5 fear factor attack penalty and being set back to normal because they use fire arrows though.

**Comment by Monsterfisch** [comment]
while it would sound right on the surface burning arrows don't really do more damage, in reality, it would actually be counterproductive as the hot arrow would close the wound after entering the body additionally the more clunky shape and weight of a fire arrow would also mean its reach would be reduced.  i personally would keep it the way it is particularly since braziers are free and this way every one and their grandmother would put braziers on their castle.

**Comment by Lolasik011** [comment]
I think this will look interesting.
We will hope @Sh0wdown  will like the idea and he realizes it.

**Comment by Panbutt** [comment]
Yeah there needs to be some sort of tradeoff to make both flaming arrows and standard arrows viable or else everyone is just going to use fire arrows. As Monsterfisch stated, braziers have no cost so a free upgrade to damage isn't balanced.

**Comment by Lolasik011** [comment]
Well, can put a limit on the number of braziers and add them a price.

**Comment by Monsterfisch** [comment]
another problem is with ai and how they place the braziers as they tend to spam them from time to time as can be seen here https://i.imgur.com/1dhf7Jp.png 

How expensive do you want to make them? 30-50 gold per brazier? appart from ai potentially ruining his treasury by placing them over abnd over again i still think that its still a logical misconception that fire arrows set you aflame when hit/doing more damage. using this video as reference at least  https://www.youtube.com/watch?v=zTd_0FRAwOQ

**Comment by LordDerMoff** [comment]
As monsterfisch already mentioned, fire arrows wouldn't be effective or setting people on fire in real life. And as the braizer are free (and as we all know the beautiful AI of Crusader they should stay so to reduce any risk of selfdestruction) they shouldn't do more damage either... the mod is modular at the end it doesn't matter if its implented or not in the first place. You could choose to tick or not to tick. Speaking of myself i would love to see burning man animations if they were killed by fire arrows - crusaders isn´t about historical accuracy (hence the existence of fire arrows in the first place) but authenticy and fun :)

**Comment by Heroesflorian** [comment]
I strongly second @Monsterfisch regarding the unfeasibility of fire arrows. Having them light stuff on fire with them is only realistic with stuff that is very very likely to burn anyway (oil / pitch), and pretty much nothing else really... 

On the other hand, one thing that might be interesting for pyromaniacs: Add pitch amphoras as a munition type for trebuchets and/or catapults! 
Just launching huge fireballs that way would be highly unrealistic of course. But launching a considerable amount of highly flammable material, along with a fuse of some sort, or a bit of glowing coals or other hot/burning stuff, separated by a layer of ceramics that falls apart upon landing, was a way to realize "fiery projectiles" to some extent, as far as I know. 
Those could be treated like the fire throwers' grenades: Hitting walls does nothing, but hitting the ground or flammable buildings with them will cause a bit of fire. 

- Does it come at a cost? Definitely! You pay with pitch amphorae (direct cost), and you cannot throw rocks and pitch at the same time, obviously, same as with cows ("opportunity cost"). 
- Does it have uses? Definitely! Fire is useful. 
- Does it look/feel cool? YES! 
- Does every AI use it by default? Nope, not necessarily: Similar to cows, some AI characters use it, some don't use it, and generally they will only throw pitch amphoras every now and then and not constantly, i.e. rocks will still be the main ammunition type.

**Comment by Sh0wdown** [comment]
As others already said, I think the damage of fire arrows should not be increased. But the fiery death animation is a nice idea.
