### ISSUE TITLE
Defensive Troops for Sheriff

### ISSUE THREAD

**Issue by Taddl2k** [Sh0wdown/UnofficialCrusaderPatch#258]
Like as you did with Richard, Rat and Philipp, Sheriff should also get increased defensive troops too because his defense is almost always very weak especially his frontal defense.
So doubling his defensive troops should make him a bit stronger.

**Comment by Lolasik011** [comment]
totally agree with you

**Comment by ByBurton** [comment]
Chill guys, you'll soon be able to adjust these values yourselves..

**Comment by Lolasik011** [comment]
waiting .... @ByBurton  thanks.

**Comment by PitchNeeded** [comment]
That sounds great.

Can you also give us an option to enable Sultan to be able to place Arabian archers on his walls and towers?

**Comment by PitchNeeded** [comment]
That sounds great. Only problem is with the high amounts is that perhaps AIs might struggle more to send archers to defend their farms early in the game and may take longer to send their first attack.
 
Can you also give us an option to enable Sultan to be able to place Arabian archers on his walls and towers?

**Comment by Sh0wdown** [comment]
This is now adjustable through AIC edits.
Maybe I will add an .aic which increases the defenses of all AIs slightly in the future.
