### ISSUE TITLE
Patch does not install for macos version of SC

### ISSUE THREAD

**Issue by johntam** [Sh0wdown/UnofficialCrusaderPatch#26]
I have the macos version of SC downloaded fromm GOG. It is a wineskin wrapper. When try to install the patch .exe file within the wineskin wrapper, it doesn't work and no files are changed. I suspect it is a pathing problem.

**Comment by Sh0wdown** [comment]
I can just copy my answer from somebody who tried to install it on Linux:

> The installer is based on Microsoft's .NET Framework and, I guess, thus won't run on Linux.
> So you could either run the setup on a Windows machine and then just copy the modified "Stronghold Crusader.exe" binary to your Linux PC or compile the source code of this GitHub repository with [Mono](https://www.mono-project.com/).
> https://www.codeproject.com/Articles/9407/Introduction-to-Mono-Your-first-Mono-app

Maybe I will eventually try to compile it with Mono for other OS. But feel free to try it yourself!

**Comment by Shatrico** [comment]
can you pls do it building with mono?
I every time get this error:
The entry point method could not be loaded due to Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
