### ISSUE TITLE
Caliph could do with a better economy

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#263]
I know the topic of improving certain AI's economy has been raised before but in terms of prioritizing I would suggest the first one that really could do with a boost is Caliph.

In terms of character it would fit that Caliph would be quite strong, but in AI vs AI contests, I have noticed that Caliph is let down by the fact he isn't good enough economically in my opinion. His troops are expensive and he does tend to struggle unless he is in the absolute best economic position on the map and he often takes ages to build up for the next siege (especially on 12 additional troops per siege setting)

To give him a bit more of a chance, I think he should have a few more iron mines or another stone quarry. Even a small increase in his mine/quarry amounts would make a big difference because of his -5 fear factor.

**Comment by ByBurton** [comment]
Caliph is fine as he is. He is supposed to be medium difficulty.

**Comment by Lolasik011** [comment]
Can make an improvement optionally.

**Comment by PitchNeeded** [comment]
> Caliph is fine as he is. He is supposed to be medium difficulty.

I think the problem is on maps with no oil available to build pitch rigs on, meaning it costs a lot for him to rebuild his pitch ditch if some gets burnt because of enemy sieges or enemy raiding troops. I think if possible on maps with no pitch supplies, Caliph should have one or two additional iron mines to make up for the lack of pitch supplies.

**Comment by Ralf-Schmidt** [comment]
The best way to push Caliph's economy is to give him lots of Breweries and -5 fear factor. All hops that is send to the stockpile will be dublicated and each good of beer that is produced, will be multiplied again.
You can give him up to 15 Breweries if you want, alternatively you can give him weapon production.

**Comment by MarcusVipsaniusAgrippa** [comment]
> 
> 
> The best way to push Caliph's economy is to give him lots of Breweries and -5 fear factor. All hops that is send to the stockpile will be dublicated and each good of beer that is produced, will be multiplied again.
> You can give him up to 15 Breweries if you want, alternatively you can give him weapon production.

You're right of course, but I always found it a bit cheatsy-doodly when the AI produces lances to sell, especially arabs that don't use these buildings in general. It's way more profitable than it has any right to be.

**Comment by Ralf-Schmidt** [comment]
,,I always found it a bit cheatsy-doodly when the AI produces lances to sell, especially arabs that don't use these buildings in general. It's way more profitable than it has any right to be."

I agree with that, so let him build a big number of Breweries =  https://prnt.sc/mzj3j4
(You can give him even more) Then Caliph's economy is okay.

**Comment by PitchNeeded** [comment]
I know you can improve AI economy through editing AIVs, but it would still be nice if Caliph was a bit better economically with his vanilla castle, especially on a map without pitch rigs.

**Comment by Panbutt** [comment]
Something interesting with Caliph is that when you give him Fletchers, he will manufacture Crossbows. With a -5 fear factor he can make crossbows pretty quickly. 1 Crossbow sells for 30 gold iirc and can give him a good boost.

**Comment by PitchNeeded** [comment]
To make Caliph a bit stronger, maybe he could send more slaves in sieges, and bring slaves for every siege and not just if he has to dig an enemy moat. He could try and burn enemy buildings with them and even attack walls with them. The slaves could be used as arrow fodder, as a distraction for the enemy so his other siege troops could survive longer.

**Comment by Sh0wdown** [comment]
This is now adjustable through AIC edits.
