### ISSUE TITLE
Make AI mangonels prioritise firing at enemy troops over enemy buildings

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#265]
Sometimes I notice an AI mangonel will just keep firing at an enemy farm or quarry within range even when enemy troops are approaching the castle. Can it be made that AI mangonels will always prioritise firing at enemy troops if they are present over any enemy buildings in range?

There is also the infamous 'AI mangonel firing at a dead lord's statue' bug (even if the dead lord was allied with them!) which is rather annoying!

**Comment by MarcusVipsaniusAgrippa** [comment]
I second that. Personally I'd even go as far as not having the mangonel fire at buildings at all, after all it's an anti-personal weapon. I'm fine either way though as long as it actually targets troops.

**Comment by Krarilotus** [comment]
closed to reduce dublicates, comment on newest issue regarding topic.
