### ISSUE TITLE
Have troops realize that gates will close when enhanced gate option is enabled

### ISSUE THREAD

**Issue by MarcusVipsaniusAgrippa** [Sh0wdown/UnofficialCrusaderPatch#266]
Some of you might have realized that some troops go to the gates figuring they're open only to stop after the gate closes later than usual. This usually ends with them standing in front of it for quite a long time instead of attacking for quite a long time. 

This could be circumvented with either disabling the troops tries to march through open gates altogether though this might mess with assassins opening gates? 

A better solution might be to decrease the distance in which troops go for an open gate similar on how the distance for the gates themselves got decreased. 

Really anything would be better than the current

**Comment by Krarilotus** [comment]
there is a new issue, lets close some duplicates
