### ISSUE TITLE
AIs should be able to buy in smaller amounts of hops and smaller amounts of wheat - a minimum of 20 at a time is too much

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#268]
I played an AI spectator match on a map where the AIs had less green oasis area but good supplies of stone and iron for each AI nearby. I noticed the ale producing AIs didn't seem to buy in hops when lacking, even when they had enough money to do so.

Maybe it was because they had to spend money on buying food occasionally too, but they still had enough money from selling stone and iron to recruit troops for the next siege. 

Maybe the problem is that AIs can only buy larger amounts of hops in at a time, like 20 hops (I don't know how many hops an AI can buy in at one time though). I think AIs should try and buy in small amounts of hops, like 2 hops or 5 hops at a time if lacking I think. Keeping inns working is important, it generates a lot of taxes and AIs sometimes can run for a while with no food if their inn is working.

Another point: the amount of wheat that bread producing AIs can buy in at one time when lacking wheat should be reduced. At the moment bread producing AIs can only buy in bundles of 20 wheat at a time if they are lacking in wheat. This costs quite a bit of gold. I propose allowing them to buy in 5 wheat at a time. Also maybe stop AIs buying 2 flour which isn't as good economically if it can be made that they are able to buy in smaller amounts of wheat.

**Comment by PitchNeeded** [comment]
Currently, Wazir will struggle at a position on a map without much oasis grass, even if it has stone and iron nearby. It would be interesting to see whether if he could buy in 5 wheat at a time, instead of having to have a lot of money to buy in the 20 wheat (which he can rarely do in such a situation) would he do better.

**Comment by Sh0wdown** [comment]
This is now adjustable through AIC edits.
I also reduced the amount of goods all AIs buy to 10 at most in the UCP-Bugfix.aic.
