### ISSUE TITLE
Sultan verbessern / Improving Sultan

### ISSUE THREAD

**Issue by Truetobi91** [Sh0wdown/UnofficialCrusaderPatch#269]
_(english below)_

### Nach einigen Tests mit dem Sultan sind mir folgende Eigenschaften auf- und Verbesserungsvorschläge eingefallen:

- Es kann passieren, dass Sultan nach Angriffen bei denen er keine arabischen Bogenschützen verliert, seine Armee ganz normal aufstockt anstatt vermehrt Schwertkämpfer auszubilden. Dies führt dazu, dass die nächste(n) Angriffswelle(n) nur eine aus einer handvoll arab. Schwertkämpfer besteht aber 100+ Bogenschützen. 

- Zurzeit setzte der Sultan seine Angriffsbogenschützen erst ein, wenn der gegnerische Bergfried direkt zugänglich wird. Kann eine Option eingefügt werden, dies auf Wazir Verhalten [Bogenschützen werden als Vorhut geschickt] zu ändern auch im Hinnblick auf o.g. "Fehler"?

- Der Sultan kann Feuerwerfer auf Wachposten abstellen, bildet diese aber nicht aus. Dies sollte er tun sobald Wachposten nachbesetzt werden können. 

- Die Bauschritte des Sultan sind so ziemlich mit Abstand die langsamsten im gesamten Spiel. Die Ratte führt in der Zeit 4-5 Bauanweisungen aus. Dies sollte deutlich erhöht werden, insbesondere da die Burgen des Sultan mit Rundungen überproportional viele Bauschritte erzeugen können. 

- Die vielen Holzfäller des Sultan führen schnell dazu, dass seine Holzproduktion komplett ausstirbt. In noch schlimmeren Fällen führt es dazu, dass seine Holzfällerlager komplett an den Gegner heranreichen. Da Holzfällerlager abgerissen und neu gebaut werden, sobald ein Holzfäller 2x in Folge getötet wurde, wird dies sogar zum Geldgrab für ihn. 

**Weitere bereits genannte Punkte die ich nur der Vollständigkeit halber noch einmal nenne:**

- _Arabische Bogenschützen sollten auch als Wachposten aufgestellt werden können. Zumindest 10-20 Stück._ 

- _Wenn der Sultan bereits 100% seiner Nahrung einkauft, sollte er auch verschiedene Nahrungsarten kaufen um wirtschaftlicher zu werden._

---

### After a couple of tests I noticed some things about the Sultan and found ideas to improve them. 

- It happens that after Sultan's attacks without loss of (m)any saracen archers his next attack(s) will have decreased numbers of saracen swordsmen because his maximum number of units for the next attack is filled up with ranged units more than with melee. 

- Currently Sultan only engages with his attack archers once the opponent's keep is accessable. It might be usefull to test an option that switches this Emir-behavious to a Wazir-behaviour which let's him use his archers as vanguard. 

- Sultan can put Fire Throwers from game start on defensive positions but he can't train them throughout the game. This should be fixed for the sake of filling empty defensive spots. 

- The time it takes for Sultan to execute a single building step takes way too long. Rat can easily execute 4-5 times that amount in the same time. This should be significantly accelerated for Sultan. 

- Sultan's numerous lumberjacks easy overchop any wood nearby which leads him to lose more gold over the course of a game. In some cases of heavily contested wood this leads to him building them in dangerous territory which again leads to the loss of wood/gold for buying wood because once a lumberjack dies 2 times in a row his hut will be demolished and build up again. Take this x12 and you have a significant amount of income lost unless you increase his income with modded castles. 

**Other points that have been brought up before but are mentioned for completeness:**
- _Sultan should be able to put saracen archers on defensive spots, at least up to 10-20._

- _Since Sultan buys 100% of his food anyway, he should be buying bread and cheese (and maybe meat if that's possible) on top of apples to be more effective.

**Comment by PitchNeeded** [comment]
> Sultan's numerous lumberjacks easy overchop any wood nearby which leads him to lose more gold over the course of a game. In some cases of heavily contested wood this leads to him building them in dangerous territory which again leads to the loss of wood/gold for buying wood because once a lumberjack dies 2 times in a row his hut will be demolished and build up again. Take this x12 and you have a significant amount of income lost unless you increase his income with modded castles.

Plus the gold lost by him repeatedly sending slingers there to try and defend them, only for them to get shot down by enemy archers.....

I agree that Sultan has too many lumberjacks. Whilst he does well in a well forested map, many maps are not so forested. He would definitively be better having a few less and having another quarry instead.

> Currently Sultan only engages with his attack archers once the opponent's keep is accessable. It might be usefull to test an option that switches this Emir-behavious to a Wazir-behaviour which let's him use his archers as vanguard.

Often I have found he does use his siege archers properly, like Emir's horse archers though, sometimes they get left behind due to pathfinding issues.

It would be better if tactically Sultan could advance the Arabian swordsmen first and then the archers instead of the other way round. That would mean both archers and Arabian swordsmen would arrive at the enemy castle at the same time.

> Sultan should be able to put saracen archers on defensive spots, at least up to 10-20.
> 
> _Since Sultan buys 100% of his food anyway, he should be buying bread and cheese (and maybe meat if that's possible) on top of apples to be more effective.
> 

Both of these would be great to be introduced. Archers on lookout towers can be very effective against enemy missile troops and horse archers, and yes Sultan should buy more food types (only small amounts though at a time of each so he can afford it, I suggest batches of 5 for apples, bread, cheese and meat).

A third point is Sultan is the only character that cannot dig up enemy moats, a few slaves would be good for him to bring on attacks if he is attacking an AI or human player with a moat.

**Comment by Lolasik011** [comment]
>Currently Sultan only engages with his attack archers once the opponent's keep is accessable. It might be usefull to test an option that switches this Emir-behavious to a Wazir-behaviour which let's him use his archers as vanguard.
@Truetobi91 I agree with you.

>Often I have found he does use his siege archers properly. Like Emir's horse archers though, sometimes they get left behind due to pathfinding issues. Hopefully these pathfinding issues can be fixed soon.
@PitchNeeded  Until the AI ​​finds a hole in the wall that blocks the passage to the Lord, he will not send his archers.

**Comment by PitchNeeded** [comment]
> @PitchNeeded Until the AI ​​finds a hole in the wall that blocks the passage to the Lord, he will not send his archers.

Well in my experience, _sometimes_ Emir and Sultan will use their missile troops properly during sieges, bringing them up within range of the enemy walls and towers. It seems to depend on the map - I find if there are any features such as cliffs, hills or rocks between the gathered siege force and the enemy castle this seems to block the path of the siege missile troops.

**Comment by Lolasik011** [comment]
>Well in my experience, sometimes Emir and Sultan will use their missile troops properly during sieges even if the enemy keep is enclosed properly, bringing them up within range of the enemy walls and towers. It seems to depend on the map - I find if there are any features such as cliffs, hills or rocks between the gathered siege force and the enemy castle this seems to block the path of the siege missile troops. 

Maybe this is due to the fact that the map is small and the AI ​​is forced to bring closer its troops to the walls of the enemy?

**Comment by Lolasik011** [comment]
@PitchNeeded  I think this bug will be fixed.

**Comment by PitchNeeded** [comment]
Yes its an annoying bug which I hope can be fixed. 

Another annoying bug is the AI oil pot engineers on the keep of Lionheart and Emir sometimes not working properly. Sometimes they pour the oil and it doesn't do anything, this seems to happen if they pour the oil too late and some enemy troops are already on the keep.

**Comment by Panbutt** [comment]
Honestly I think removing 50% of his woodcutter huts and replacing them with apple/cheese farms would make him economically stronger. No Arabian lord builds dairy farms also so Sultan building dairy farms would still make him unique.

Missile troops being left behind is a common bug that affects all the AIs, but it does affect the Sultan the greatest. I feel like it has to do with pathfinding and the AI trying to move in a position in range of the keep, but that position is inaccessible for whatever reason and therefore they're 'stuck'. The instances where Sultan moves his archers in to attack, he'll move them right at the foot of enemy towers resulting in them dying before they can even attack once.

**Comment by ByBurton** [comment]
Guys, please. just chill. You will be able to adjust most of these things yourself "soon"...

**Comment by Lolasik011** [comment]
@ByBurton Ок... Waiting ....
