### ISSUE TITLE
Wazir does not buy flour / wheat?

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#27]
I added that to the list of bugs still in game I think (issue #5 ), but I believe some AIs do not buy the mentioned things. I felt like making this a separate issue, because you mentioned in a comment in the  code, that the AI does use the market now, which flour and wheat would include.

**Comment by ByBurton** [comment]
>           From my observations he does buy wheat (20 at once) and flour (2 at once).

Weird .... very weird...
Okay then....
Gonna close this.

**Comment by Heroesflorian** [comment]
Saw this too late, but it is indeed the case - given Wazir has the necessary gold for those purchases.
