### ISSUE TITLE
Stronghold Europe HD + UnofficialCrusaderPatch ?

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#277]
Is it possible to combine Stronghold Europe HD with Unofficial Crusader Patch?
If yes, how?

**Comment by LordDerMoff** [comment]
I didn´t do it myself yet, but i think you could just rename the stronghold Europe exe to stronghold crusader.exe; doing the usual patch and rename it back to stronghold europe afterwards

**Comment by Lolasik011** [comment]
> I didn´t do it myself yet, but i think you could just rename the stronghold Europe exe to stronghold crusader.exe; doing the usual patch and rename it back to stronghold europe afterwards

OK I'll try
