### ISSUE TITLE
More siege weapons for AI .

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#281]
I know that this topic has already been raised but a new AI editing tool will appear soon.

I think the AI must use siege towers and shields. This will complicate the game vs AI. I 
think that this ability is in AI, it just does not use. I saw how the AI uses siege towers and shields in Siege Missions.In free construction, he also uses shields and siege towers.

@ByBurton  @Sh0wdown  Is it possible to realize this?

**Comment by ByBurton** [comment]
They can use shields (kind of, not very good) and siege towers.
You can select those as siege engine for attacks in the editor that I made, once we make it public.

**Comment by Lolasik011** [comment]
> They can use shields (kind of, not very good) and siege towers.
> You can select those as siege engine for attacks in the editor that I made, once we make it public.

0_0 
I can not wait ....

**Comment by PitchNeeded** [comment]
What about allowing portable shields on towers for AI? Will that be possible.

**Comment by ByBurton** [comment]
@PitchNeeded I ... don't think so? At least it is not planned. You can only put regular troops as defence. Try to open an issue for that after we released the tool, okay?

**Comment by J0J0Jo** [comment]
@ByBurton Can you give the AI more than 8 siege enignes? In your code I saw that it is called SiegeEngine1-8. Could I add SiegeEngine9, 10, ... ? 
Or if not, is there maybe some tricks to make the AI able to use more?

One example where more than 8 siege enignes could be usefull are portable shields. Some (strong) AI's could use them but not if they take up 1 out of 8 slots. 
Also it would be awesome for the late game if the strongest lords could keep on adding siege engines until even strong castles are threatened.

**Comment by ByBurton** [comment]
Nope, there are only 8 spots. But I am not sure if the AI just starts from the beginning of the list again if it has more engineers availabl.e

**Comment by J0J0Jo** [comment]
If the AI starts from the beginning that would be almost as good. Then you can just set the max engineers to a large number and the problem is basically solved. Thanks for the quick answer and your contribution :+1:
