### ISSUE TITLE
Beliebtheitsproblem

### ISSUE THREAD

**Issue by panda821** [Sh0wdown/UnofficialCrusaderPatch#288]
Kann man irgendwie dafür sorgen dass die KI nicht zu sehr mit der Beliebtheit spielt? Einige KIs haben das Gold, können es aber nicht so schnell ausgeben weil die Beliebtheit so weit unten ist und dadurch die Bauern so langsam spawnen.

**Comment by ByBurton** [comment]
I have some spare time tomorrow, I might look into the variables again. Thank you for bringing it to attention.

**Comment by Krarilotus** [comment]
yes, you can just setup taxMin, taxMax and the popularity variables in the aic, check the wiki:
https://github.com/Sh0wdown/UnofficialCrusaderPatch/wiki/AI-Personality
