### ISSUE TITLE
Suggestions for some unknownXXX values

### ISSUE THREAD

**Issue by RafaelPin** [Sh0wdown/UnofficialCrusaderPatch#289]
Hey I looked at your files and tried to suggest some of the unknown values.

Here some Ideas : 
CriticalPopularity 			//maybe also sets taxation to MaxPositivPop(Tax)
unknown007 : SetTaxTo[None]		//when at = [Amount] of popularity 
unknown008 : SetTaxTo[MaxNegPop(Tax)]	//when above = [Amount] of populity
unknown009 : MaxPositivPop(Tax) 	// positiv Tax = donation to folk at a rate of given positiv popularity , players can only do +1 -->+3...
unknown010 : MaxNegativPop(Tax)		// 10 could mean -10 popularity taxation , maybe the Ai can do -10 , players can only -8 --> -12...
unknown011 : SetFoodRatioToHalf  	//when at = [Amount] of food

**Comment by ByBurton** [comment]
I kinda doubt that, but not saying it's not possible.
@Sh0wdown what do you think?

**Comment by Rakso69** [comment]
Funny tho that AI can buy: cheese, bread and apple for the minimum, but I hadn't seen an option like that for meat.

**Comment by Sh0wdown** [comment]
Did you test these or are they just guesses?

**Comment by ByBurton** [comment]
I am curious as well. Because the tax things were correct, right?

**Comment by Evrey** [comment]
`Unknown123` is the maximum number of harassment catapults.

**Comment by ByBurton** [comment]
@Evrey hey, thank you!!!!!!!! I kinda looked for exactly that value for a long time now.

**Comment by Krarilotus** [comment]
those besides 011 have been solved, now we just need 011 to be solved, butthis thread can be closed.
