### ISSUE TITLE
[Discussion] Things you wanna know about the AICE

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#292]
So, I bet you guys are interested in what things are possible in this editor.
Well, instead of talking a whole lot, I'm gonna upload a few pictures of a modded wolf.
![Wolf](https://user-images.githubusercontent.com/25118004/55190195-af0c9c80-519f-11e9-825b-71225b2b0ced.png)
![wolf2](https://user-images.githubusercontent.com/25118004/55190199-af0c9c80-519f-11e9-8eb5-4fafa5f80b9d.png)
![wolf3](https://user-images.githubusercontent.com/25118004/55190201-af0c9c80-519f-11e9-8457-1d112c9857c1.png)

You will probably notice the differences, but if you have not:
- More farms, and included wheat farms
- More iron mines
- 1 less quarry
- Does not sell wheat and flour
- Keeps more food in stock
- Keeps more weapons in stock
- Produces both crossbows and bows with fletchers
- A lot more defensive units on the walls and patrolling
- A lot more sortie units
- Keeps more resources in stock (iron, pitch, stones, lumber, hops, wheat, flour, beer)

**Comment by Panbutt** [comment]
Very cool to see it in action, this opens a lot of doors for the future of SHC. I appreciate all the work you've poured into this. I can't even imagine the headaches going through all that Hex code can give.

**Comment by ByBurton** [comment]
Say thanks to @Sh0wdown . I only helped with the editor / came up with the idea. He's the real mastermind.

**Comment by Lolasik011** [comment]
Thank you @ByBurton and @Sh0wdown you did the impossible. Thanks again.

**Comment by ByBurton** [comment]
Nope. They aren't that great.

**Comment by Lolasik011** [comment]
@ByBurton if it `s not a secret. When will the new patch be released? :)

**Comment by Ralf-Schmidt** [comment]
,,Does not sell wheat and flour"
Gar nicht mehr? Eine angemessene Verkaufsgrenze sollte festgelegt werden, damit keine Probleme entstehen und das Vorratslager überläuft.

,,Keeps more food in stock"
Halte ich für wenig sinnvoll. Überschüssige Ressourcen sollten liquidiert und nicht gebunkert werden.

,,Produces both crossbows and bows with fletchers"
Ist ökonimisch tatsächlich ein klein wenig besser, als wenn die Bögen gekauft werden. ABER: Es werden weniger Armbrüste hergestellt und es kann passieren, dass der Wolf diese dann einkauft und diese Änderung letzlich sogar ökonomisch schädlich wird.

,,Keeps more resources in stock (iron, pitch, stones, lumber, hops, wheat, flour, beer)"
Auch das halte ich für wenig sinnvoll und wird die KI im early-game verlangsamen. Überschuss sollte immer verkauft werden und ich spreche mich eher für niedrigere Verkaufsgrenzen aus, als diese noch zu erhöhen.

**Comment by ByBurton** [comment]
@Ralf-Schmidt 
1. He sells wheat and flour, but keeps like 10 or 15 of each at max. in stock, in case of a siege, without access to his farms.
2. It does make sense. The Wolf is supposed to be an AI that is hard to siege, and if you can not just hunger him out so easily, that is just a plus.
3. I did not do this to make him stronger, just to prove some points.
4. No, as I said, the Wolf is supposed to be a slow opponent. And early game, he should never sell his wood or stone, because he has so much stuff to build. And again, more stock means he survives a lot longer in sieges.

**Comment by Ralf-Schmidt** [comment]
@ByBurton 

1. ,,He sells wheat and flour, but keeps like 10 or 15 of each at max. in stock, in case of a siege, without access to his farms."
OK

2. ,,It does make sense. The Wolf is supposed to be an AI that is hard to siege, and if you can not just hunger him out so easily, that is just a plus."
Just set the ratios to +0 or +4 like I described it in the other Thread. The Wolf doesnt need 3+ full Granary's. Thats way too much in my opinion.

3. ,,I did not do this to make him stronger, just to prove some points."
OK. The Wolf should only produce crossbows with his fletchers.

4. ,,No, as I said, the Wolf is supposed to be a slow opponent. And early game, he should never sell his wood or stone, because he has so much stuff to build. And again, more stock means he survives a lot longer in sieges."

I didnt said something about selling wood or stone, but I think there is no point to store even more iron, pitch, hops etc.
Lower stocks means a higher gold value -> more speed/aggression in early/medium game.

**Comment by ByBurton** [comment]
Then find out HOW to set rations, and I may do it, okay? And it is not too much for 160+ population.



> Lower stocks means a higher gold value -> more speed/aggression in early/medium game.
And that is what I exactly don't want, you see?

**Comment by J0J0Jo** [comment]
I know this is an annoying  questions  so sorry: Are you still planning to release it this week? ;)

**Comment by Rakso69** [comment]
Will it be possible to make AI use portable shields in defense(on towers) aswell as in the sieges(I believe noone knows how AI uses those btw, maybe you @ByBurton let us know of it's intelligence)? What about making it keep buying units all the time even while it does a siege? The population standing all the time on the fire without being used is pointless imo.

**Comment by ByBurton** [comment]
No, the AI Village Editor doesn't allow shields as spots.

**Comment by Rakso69** [comment]
@ByBurton I'm toking about AICE... lol It's AICE topic

**Comment by pwnasunt** [comment]
@Rakso69 He means that you can't put a portable shield marker at all, since there is no button for that in the AI Village editor (i.e. a Firefly Studios tool, which is used to edit AI castles).
