### ISSUE TITLE
 Bug in Installing Unofficial patch for Stronghold Crusader. !!!

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#298]
All this time I played on the English version of the Stronghold Crusade, and the Unofficial patch was installed normally. It was only worth upgrading to the Russian version of Stronghold Crusader, I got an error in the installation.

![Unnoficial Patch BUG (Russain Stronghold Crusader)](https://user-images.githubusercontent.com/41998977/55403244-13dc4400-555e-11e9-8765-7b676bd60f0f.png)

**Comment by Lolasik011** [comment]
need help ....

**Comment by Sh0wdown** [comment]
Get the HD patch http://www.strongholdcrusaderhd.com/patch.html

**Comment by Lolasik011** [comment]
@Sh0wdown Yes. But there is no Russian language there ...

**Comment by Sh0wdown** [comment]
Seems like the Russian version is very different from other versions in the "extended gamespeed" and "remove xtreme magic bar" settings. So either install without those settings or use a different language.

I will take a closer look later today.

**Comment by Lolasik011** [comment]
@Sh0wdown it's fine ... I will play in the English version for now.

**Comment by Lolasik011** [comment]
> I will take a closer look later today.

ok thank you

**Comment by Lolasik011** [comment]
@Sh0wdown 
By the way, I finished the translation ...

**Comment by Sh0wdown** [comment]
> @Sh0wdown
> By the way, I finished the translation ...

Thanks! But you missed the [UCP-Bugfix.aic](https://github.com/Lolasik011/UnofficialCrusaderPatch/blob/patch-16/UnofficialCrusaderPatch/AICs/UCP-Bugfix.aic).

**Comment by Lolasik011** [comment]
@Sh0wdown hmm ...

**Comment by Krarilotus** [comment]
seems liek this has been resolved, reopen if not!
