### ISSUE TITLE
Market place: Gold as building cost

### ISSUE THREAD

**Issue by Halbarad1** [Sh0wdown/UnofficialCrusaderPatch#299]
Hey, we now have the option that player and AI can build a market place with no resources. Problem is, that  even if an AI is without resources and another attacks it with catapults, it replaces its market nearly immediately after getting destroyed by enemy's catapults. My solution:

- Market place should cost some money (5 or 10 gold) instead of nothing.

**Comment by Lolasik011** [comment]
> Hey, we now have the option that player and AI can build a market place with no resources. Problem is, that even if an AI is without resources and another attacks it with catapults, it replaces its market nearly immediately after getting destroyed by enemy's catapults. My solution:
> 
> * Market place should cost some money (5 or 10 gold) instead of nothing.


It is a bad idea ...

**Comment by Monsterfisch** [comment]
if the ai has no gold and a market its just as much of a dead end through ;) i personally like the idea of the market costing gold after all if the taxing system of the game can be modified to where the ai can actually use their taxes in a smart way gold wouldn't be as much of an issue . After all you can get gold for free as well that way unlike wood

**Comment by Krarilotus** [comment]
market can be set to 0 cost now.
