### ISSUE TITLE
All AI opponents should be allowed to trade weapons

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#3]
I noticed that some AI opponents still do not buy weapons.
Mainly the Abbot, the Emir.

Edit: Both need bows.

**Comment by Swartonf** [comment]
Ive tested it aswell.  I agree that every AI has to be able to buy weapons.
Abbot is a special case though. He was never meant to have bows, he only relies on his Monks.

**Comment by Sh0wdown** [comment]
Fixed in 2.03
https://github.com/Sh0wdown/UnofficialCrusaderPatch/releases/tag/v2.03
