### ISSUE TITLE
Veränderung hinsichtlich der Burggräben

### ISSUE THREAD

**Issue by StrongholdFan** [Sh0wdown/UnofficialCrusaderPatch#30]
Wäre es möglich, dass die Burggrabenmarkierungen auch dann eingeblendet würden, wenn man normale Gebäude baut? Vanilla ist es ja so, dass die Markierungen nur dann gezeigt werden, wenn man die "Burggraben ausheben"-Schaltfläche betätigt oder Einheiten auswählt, um Burggräben zu graben bzw. umzugraben.
Wenn jedoch die Markierungen auch dann sichtbar wären, wenn man im Baumodus ist, sprich ein Gebäude ausgewählt hat, das man bauen will, wäre es einfacher zu verhindern, dass man in einen geplanten Graben baut.

**Comment by Sh0wdown** [comment]
Kommt in der kommenden Version.
