### ISSUE TITLE
 AICE Early version released! Thank you very much!

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#303]
@ByBurton and @Sh0wdown 
Thank you very much!

https://github.com/ByBurton/AI_Character_Editor/releases/tag/EarlyVersion

**Comment by J0J0Jo** [comment]
Thanks for the heads up.

**Comment by Lolasik011** [comment]
I have a 2 question:
1 How to embed .aic file into the game?
2 Need to wait for the next unofficial patch to be released?

**Comment by ByBurton** [comment]
@Lolasik011 
1. Please read my Readme on [the repository page](https://github.com/ByBurton/AI_Character_Editor/)
You have to create one with my editor, and then move that created file into the stronghold crusader installation directory into the aic folder.
2. Yes.

**Comment by Lolasik011** [comment]
> @Lolasik011
> 
> 1. Please read my Readme on [the repository page](https://github.com/ByBurton/AI_Character_Editor/)
>    You have to create one with my editor, and then move that created file into the stronghold crusader installation directory into the aic folder.
> 2. Yes.

Ok. 
Thanks again !

**Comment by Lolasik011** [comment]
@ByBurton and @Sh0wdown 
I have 2 more small questions :+1:  ^_^
1 Can I somehow translate your program into Russian?
2 Will the manual on the use of the program ?  (Not that I'm stupid, I just might not know. :D)

**Comment by ByBurton** [comment]
I don't plan on integrating any languages besides English.
I won't write a manual, but after I am done with the functions, I will add tooltips that are shown if you hover over an option in my editor.

**Comment by Lolasik011** [comment]
> I don't plan on integrating any languages besides English.
> I won't write a manual, but after I am done with the functions, I will add tooltips that are shown if you hover over an option in my editor.

Ok, I get it ... Thanks for the info.

**Comment by J0J0Jo** [comment]
So right now you can create and modify AIs but can't test them in-game yet?

**Comment by ByBurton** [comment]
@J0J0Jo Yes, the current UCP version has not yet been released.

**Comment by bonified2x** [comment]
@ByBurton @Sh0wdown 

Hey guys, I want to write up instructions for those that want to apply the Sh0wdown/UnofficialCrusaderPatch. There are many Mac OS X users that purchased Stronghold Crusader HD. I tried running the exe patch with Wine Bottler but it doesnt work. Is it possible to tell us where to copy all the files in needed directories?

**Comment by J0J0Jo** [comment]
You are teasing us :D

I hope @Sh0wdown doesn't add to many things and just releases the next patch soon. In my opinion, not every parameter must be deciphered for the first iteration. The ones you have found out already open up so many possibilities. I think the wait is killing most people here ;)

**Comment by ByBurton** [comment]
Haha, you know. He was sick this week, so please bare with him.

**Comment by Lolasik011** [comment]
> You are teasing us :D

Yes us tease :)

**Comment by J0J0Jo** [comment]
Yeah nobody is demanding anything, we are super grateful for the patches :)

**Comment by PitchNeeded** [comment]
Many thanks for this, will be testing it out for a while!

Was trying to change Phillip to create pikemen there for his sieges and it didn't work though :( I think its because you can't set his poleturners to create pikes yet and you can't set him to buy in pikes yet.

**Comment by Panbutt** [comment]
> Many thanks for this, will be testing it out for a while!
> 
> Was trying to change Phillip to create pikemen there for his sieges and it didn't work though :( I think its because you can't set his poleturners to create pikes yet and you can't set him to buy in pikes yet.

The next UTC version hasn't been released yet so the game atm has no way of reading the AIC files iirc.

**Comment by ByBurton** [comment]
@Panbutt That is true. Also you can't change workshops in my editor yet.

**Comment by PitchNeeded** [comment]
Unfortunately this doesn't seem to be working for me at all, I have tried simple changes such as giving Phillip archers as well as spearmen for his main attacks and giving Sultan slingers as well as Arab archers and Arab swordsmen for his attacks and I installed it in a new aic folder but the attacks are still just seem the same as vanilla.

**Comment by ByBurton** [comment]
How often do I have to write this: You would have to install it with the UCP, but the latest version is not out yet!

**Comment by PitchNeeded** [comment]
OK sorry I didn't realise, I had seen your statement before but I didn't know what you meant, I thought it would still make changes as a standalone feature.

**Comment by Russianstory** [comment]
Вообще-то. Мне кажется и я выржаю общее мнение, что вы делаете самый мощный и лучший мод в истории СТронгхолда. Так глубоко и тщательно его никто не изменял. Я восхищён вашими трудами. Я не обещаю, Но когда выйдет мой мод, надеюсь, вы смоежет взять всю звуковую часть мода. Она нейтральна к эпохам и времени. Звуки делал лично я давно. менял, подгонял и они сделаны классно. 

Хотел узнать а кто может мне конкретно объяснить и ответить, что из того, что я предлагал у себя в теме - будет сделано? И что можно ещё будет доделать? Например можно ли добавить звуки новые к уже существующим?  
----
Actually. It seems to me and I express the general opinion that you are doing the most powerful and best mod in the history of Stronghold. Nobody cheated him so deeply and thoroughly. I am delighted with your work. I do not promise, but when my mod comes out, I hope you can take the whole sound part of the mod. It is neutral to epochs and times. I personally made sounds for a long time. changed, customized and they are made cool.

I wanted to find out, and who can specifically explain to me and answer that what I offered in my subject line will be done? And what else can I finish? For example, is it possible to add new sounds to existing ones?

**Comment by Baummannn** [comment]
This may be a stupid question but what does EQ stand for in the market tap ?

**Comment by ByBurton** [comment]
@Baummannn Equipment.

**Comment by Mizo5119** [comment]
Checked the tool.

What are sortie units exactly?

And am assuming there can only be a max of 8 seige equipment for an attack or can there be more? Is it based on the number of engineers and then the AI divides them based on the ratio defined in the siege unit types? ( similar to crusaders 2).

Also what is the likelihood of finding out what controls tax levels and rations?

**Comment by ByBurton** [comment]
First of all, chill. Please head over to my repository, I will open an issue up there.
https://github.com/ByBurton/AI_Character_Editor/issues/13

**Comment by Mizo5119** [comment]
Will do. Didnt mean to come across as aggressive:D

**Comment by J0J0Jo** [comment]
@Mizo5119

I don't think we can have more than 8 siege engines at the moment, because even without the mod, saladin and wolf send more engineers than necessary for their siege engines. This however does not result in the remaining engineers to build more siege engines. They rather just stand around unfortunately.
