### ISSUE TITLE
 Theme for your AI scripts (.aic) !

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#309]
Waiting for your AI ...
Put your .aic scripts here...

**Comment by Russianstory** [comment]
I want to improve pig Rat snake WELL. Sultan to

**Comment by ByBurton** [comment]
[Kimberly_Balance.zip](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/3053675/Kimberly_Balance.zip)
