### ISSUE TITLE
Repair of towers and barbacans AI

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#31]
Is it possible to make a script for AI to repair barbaks and towers?

**Comment by ByBurton** [comment]
> barbaks 

?!?! What are barbaks?
Do you mean ruins? Walls? 

Repairing towers would be neat though, and deleting tower ruins.
And NOT deleting towers in a pinch

**Comment by Lolasik011** [comment]
barbaks (gate)

**Comment by PitchNeeded** [comment]
That would be great if it was possible!

**Comment by con-reforged-dev** [comment]
Thought about something similar where it would be cool to make engineers get the repair walls/towers etc feature they had in sh2 in a radius around them taking using stone from the players stockpile if available. not sure if that would be possible with the current tools.

**Comment by Monsterfisch** [comment]
Thought about something similar where it would be cool to make engineers get the repair walls/towers etc feature they had in sh2 in a radius around them taking using stone from the players stockpile if available. not sure if that would be possible with the current tools.

**Comment by Sh0wdown** [comment]
Don't close this, it's a good idea. :P

**Comment by Sh0wdown** [comment]
Will be fixed in the next version.
