### ISSUE TITLE
Bugfix Request: Fire Ballistae vs. Monks

### ISSUE THREAD

**Issue by AdmiralRigby** [Sh0wdown/UnofficialCrusaderPatch#313]
Fire ballistae don't attack monks on their own. Even when manually given the command to attack a monk, they won't attack other ones after the selected one has fallen.

I especially was able to "enjoy" this vanilla bug, as I was attacking the Abbot with an army of fire ballistae and crossbowmen. Not exactly the best choice against 200+ monks the Abbot had "saved" in his castle, because they weren't able to leave. (It was the mission of the 2nd trail, where the abbot locks himself in in the very south-west corner of the map. ;-) )

**Comment by Heroesflorian** [comment]
I think this might be as monks seem not to be treated as soldiers properly by the game. Killed monks also do not seem to count towards the endgame statistics. 
Both issues were already mentioned and discussed in earlier issues, so this one here is a duplicate.

**Comment by AdmiralRigby** [comment]
> 
> 
> I think this might be as monks seem not to be treated as soldiers properly by the game. Killed monks also do not seem to count towards the endgame statistics.
> Both issues were already mentioned and discussed in earlier issues, so this one here is a duplicate.

It is not a duplicate, because Sh0wdown closed the original "Bugs still ingame" issue thread and asked to create one new issue per topic/bug that's unsolved, yet. 
That being said, I'm curious how monks are really treated, cause every other weapon and soldier seems to atack them normally, or do they? I'm not sure about mangonels and tower ballistae. I don't think I ever noticed any strange behaviour from those siege engines.

**Comment by Heroesflorian** [comment]
Ah, I might have missed that closing... lots of new issues recently, I lost the overview :D 

> cause every other weapon and soldier seems to attack them normally, or do they?

Well, fire ballistae also do not attack hostile workers - a single woodcutter, hunter or even jester can demolish an entire group of fire ballistae due to that - unlike most/all other troops and siege engines. So far, I assume the monks somehow count as non-military units (like workers), which causes fire ballistae not to attack them.

**Comment by Sh0wdown** [comment]
Will be fixed in the next version.
