### ISSUE TITLE
AIC patching issue

### ISSUE THREAD

**Issue by Monsterfisch** [Sh0wdown/UnofficialCrusaderPatch#316]
I am getting this message twice during the install of the patch when trying to install  my own aic files with the patcher
once during the middle of the install and once at the end
![](https://i.imgur.com/pA3JDZh.png)

I am running SHCe steamversion 1.41 english language (modded in different gm files which shouldnt influence the install)

I tried adding quarries to phillip and some other stuff which even though it goes through with the install doesn't seem to apply the changes it should via the aic, everything none aic related else gets patched fine.

i tried using a clean .exe version of the game with the same result.

**Comment by Monsterfisch** [comment]
i have fixed the issue by patching it in a completely clean copy of the game and moving it over to the modded game. i will not close this for now in case something can be learned from it

**Comment by Sh0wdown** [comment]
Looks like your .exe was not so clean as you thought because the installer could not find any of the listed binary codes. It pops up twice, once for Crusader, once for Extreme. Still weird though, let me know if it happens again.

**Comment by Krarilotus** [comment]
seems like issues hasnt appeared again.
