### ISSUE TITLE
Questions About AIC Recruit Intervals

### ISSUE THREAD

**Issue by Truetobi91** [Sh0wdown/UnofficialCrusaderPatch#325]
I recently took a look into the AIC file and stumbled across the RecruitInterval parameters.

There are 3 of them that are somewhat explained by @Sh0wdown in the file itself that are 
- RecruitInterval (default)
- RecruitIntervalWeak (when the AI is destroyed really hard)
- RecruitIntervalStrong (when the AI is doing good and has reserves)

Yet there are some questions remaining especially concerning the exact values that I listed below. 

---

Now the values are:

Rat | Snake |   Pig  |   Wolf  |  Saladin | Caliph | Sultan | Richard 
:---: | :---: | :---: |     :---: |       :---: |        :---: |     :---: |       :---: 
 1   |     1    |     1   |     4    |      1      |     0     |     8    |     1 
 1   |     0    |     1   |     1    |      1      |     1     |     8    |     1 
 1   |     1    |     4   |     4    |      1      |     0     |     4    |     1 

Frederick | Philipp |  Wazir  |  Emir  |  Nizar | Sheriff | Marshal | Abbot
 :---: |              :---: |      :---: |    :---: |   :---: |      :---: |      :---: |      :---:
4       |     4     |     1     |     0    |     4    |     4    |       1      |    1
1       |     4     |     1     |     1    |     8    |     1    |       4      |    1
4       |     4     |     1     |     0    |     1    |     4    |       4      |    1

---

- We know that Rat and Richard values were used for an option in the patch to increase recruitment to Rat/Richard level - which is stated to be the lowest level. It is obvious that low values are for fast recruitment. Emir and Caliph even have a value of 0 and as far as I noticed it they are recruiting extra fast as well. Is 0 the truly highest level of recruitment or is it tied to special conditions?

- Sheriff has the fastest recruitment when he's on the ground. Does that make sense? I don't think he's slower in recruiting when he's doing fine or even very good. But it's always hard to really notice fast or slow recruitment as long as gold (and weapons) is the harder limiting factor. It's also not quite clear if the recruitment done while being "weak" is done under the value of weak or if the gold for recruiting is already enough to be treated as default. Same goes for Pig and Frederick. 

- Marshall has a faster recruitment on default than when he's doing very good. I noticed him to quickly recruit knights once he's ahead and has reserves. Are Knights maybe not involved in this? Is this value maybe only about direct attack forces?

- There are only the values of 0 | 1 | 4 | 8 so I'm not sure if other values in between are valid.

**Comment by Sh0wdown** [comment]
- The values of 0 and 1 are the same, meaning one recruitment per AI routine
- Any value should be valid as it always "recruitment every x AI routines", so a value of 2 would be every 2nd routine.
- from my knowledge the values concern all recruitment except when the AI is scared (then it's always the lowest value)

In the [wiki](https://github.com/Sh0wdown/UnofficialCrusaderPatch/wiki/AI-Personality) you get some concrete information when the different states set in. (These are not all conditions!)
The 'weak' state sets in if the AI is completely trashed. F.e. troops < 8, gold < 200, population < 15, ...
The 'strong' state sets in if f.e. the AI has troops >= 40, gold >= 200, population >= 40, ...

As you can see the weak state almost never sets in usually.

**Comment by Mizo5119** [comment]
Can the criteria for what is defualt/weak/strong states be changed or modified?

A good idea for intervals is to have strong state be something related to eco flourish ( maybe gold >= 5000 and atleast x troops)and have it be set to 1, so that the AI can build large armies faster only under *rich* state. Default state can have a higher interval as this is the phase in which the AI *develops their eco* and shouldnt be burning gold too fast.

Weak state can stay the same, maybe a few adjustments here and there etc..

**Comment by Heroesflorian** [comment]
> Can the criteria for what is defualt/weak/strong states be changed or modified?

Good question, I'd strongly hope for a "yes, eventually"^^

**Comment by Krarilotus** [comment]
original questions has been resolved, but we still need the option to change power state per AI's and define them specifically. The more possibilities to control the behaviour, the better!
