### ISSUE TITLE
Other Stronghold reimplementations...

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#328]
I think that these authors need to cooperate with the Unofficial patch.
And then it will bring greater success ...
I wrote to them. We wait...
1 https://github.com/fabian-arnold/stronghold-js
2 https://github.com/leidav/CastlekeepNew
3 https://github.com/Dwillnio/openStronghold

@Sh0wdown What do you think ?

**Comment by Truetobi91** [comment]
Maybe you could give a brief summary on what they were working on?

**Comment by Sh0wdown** [comment]
The UCP and Stronghold reimplementations are two completely different and not combinable things. Only thing that could happen is that I join/participate one of those projects. Except for CastlekeepNew they seem kind of inactive though.

Here is another one, even with recent activity:
https://github.com/metalvoidzz/Sourcehold

**Comment by Lolasik011** [comment]
@Sh0wdown ok 
Topic is closed
