### ISSUE TITLE
Explained: Recruiting Probabilities

### ISSUE THREAD

**Issue by Truetobi91** [Sh0wdown/UnofficialCrusaderPatch#332]
There are basically 4 groups of recruiting parameters with each group splitting into a **weak**, **default** and **strong** parameter. These parameters will be used depending on in what state of power an AI is at that moment. The **weak** parameters will less likely occure and if so the AI will most likely not even have the gold to do recruitment. So the more important difference is between **default** and **strong**. 

---

The **RecruitInterval** determines how frequent an AI will do any recruitment. 

>**RecruitInterval**
>**RecruitIntervalStrong**
>**RecruitIntervalWeak**

---

Then there are 9 other parameters that have a different order in the AIC but are easier to understand, especially regarding their vanilla values, when we rearrange them the following way. 

>**RecruitProbDefWeak**
>**RecruitProbRaidWeak**
>**RecruitProbAttackWeak**

>**RecruitProbDefStrong**
>**RecruitProbRaidStrong**
>**RecruitProbAttackStrong**

>**RecruitProbDefDefault**
>**RecruitProbRaidDefault**
>**RecruitProbAttackDefault**

Each group determines the priorities for recruiting units for one specific state of power. These values always add up to 100 so we can easily see them as percentage values. 

---

Examples:
**Richard**
- weak: 90% defense; 0% raid; 10% attack
- default: 30% defense; 0% raid; 70% attack
- strong: 10% defense; 0% raid; 90% attack

Richard as the highest priority to recruit his attack units, doing no raids at all but opting heavily into defense when he's weak. 

**Sheriff**
- weak: 100% defense; 0% raid; 0% attack
- default: 50% defense; 30% raid; 20% attack
- strong: 30% defense; 50% raid; 20% attack

Sheriff has a 100% defense priority when he's weak. Otherwise we see his high priority for raiding that is also always higher than his priority for attacks. When he's strong he recruits more than double the units for raids than he does for attacks. 

---

Conclusion: We can easily manipulate an AI's character and their tendency to attack, raid or simply defend themselves. We can also use these parameters for simple adjustments e.g. fixing the Rat's 0% defensive recruitment when NOT being weak. 

Note: Do not confuse these parameters with an AI's tendency to send sortie units - troops that are send to recently attacked farms and outer economy buildings.

**Comment by ByBurton** [comment]
> Note: Do not confuse these parameters with an AI's tendency to send sortie units - troops that are send to recently attacked farms and outer economy buildings.
Exactly, because sortie units always have 100% priority. No matter what, they are always recruited with the highest possible priority, until the maximum number is reached (for both ranged and melee, although ranged is preferred)

**Comment by Krarilotus** [comment]
for one specific state of power. <- are not clear yet?! neither defined anywhere
and the probabilites are not currently prooven to be working. Set defens probability on 1 still get more defense troops than just 1%!
