### ISSUE TITLE
Fernkämpfer Bug

### ISSUE THREAD

**Issue by panda821** [Sh0wdown/UnofficialCrusaderPatch#333]
Wenn die Burgen relativ nah sind kann es sein dass sich die Angriffstruppen auf Mauern und Türme sammeln. Problem ist dann dass die Nahkämpfer zwar zur Burg stürmen, die Fernkämpfer aber nicht. Ich habe sogar den Parameter von AttUnitBackup zu AttUnitRangedPush geändert, hilft aber nicht.

**Comment by ByBurton** [comment]
Kann ich nicht bestätigen. Was du meinst ist mir oft genug beim Wolf passiert, und ich habe ihm einige Fernkämpfer im RangePush zugeteilt. Bei mir bleiben die nicht auf den Mauern. Die RangedBackup bleiben zurück, ja.

**Comment by panda821** [comment]
Die Fernkämpfer, die auf der Mauer zurückbleiben, laufen bei mir erst zur Burg wenn sie offen ist. Wenn sie sich auf freiem Feld sammeln laufen sie mit zur Burg.

**Comment by DarkThief-Darek** [comment]
Ich glaube, bei sowas ist immer gut, die AIC und die Karte anzuhängen, damit man es gegebenenfalls selbst testen kann. Ich kann mir im ersten Moment auch nicht vorstellen, dass die RangedPush Einheiten nicht angreifen und sich wie BackUp Einheiten verhalten.

**Comment by Krarilotus** [comment]
#401, there are many issues open with this bug, i d say i close this one.
