### ISSUE TITLE
Kostenloser Markplatz wird nicht von der Feuerwehr gelöscht

### ISSUE THREAD

**Issue by Monsterfisch** [Sh0wdown/UnofficialCrusaderPatch#334]
Keine Ahnung ob das mit den entfallenen Kosten zu tun hat oder nicht, jedenfalls wird der Marktplatz im fFalle eines Brandes von der ki gänzlich ignoriert und dient somit als dauerhafter Brandherd bis er schließlich abgefackelt ist. 
Vermutlich kann das problem behoben werden wenn man den Marktplatz für die ki 1 gold oder so kosten lässt oder oder auch "kostenlose?" gebäude eine Löschpriorität zuteilt oder dem Markplatz Feuerschutz zuweist.

**Comment by Truetobi91** [comment]
Das war bei mir nicht der Fall. Hier hat die Feuerwehr solide arbeit geleistet.

**Comment by Monsterfisch** [comment]
ist bei mir jetzt schon zum wiederholten mal vorgekommen also so 20bis30 mal konnte ich das bei mir schon beobachten das der marktplatz fröhlich gebrannt hat und die feuerweher an ihren brunnen gesessen hat ganz nach dem motto "this is fine"

**Comment by Truetobi91** [comment]
Seit wann ist denn der Fehler aufgetreten? Denn der Patch mit dem kostenlosen Marktplatz ist ja schon eine ganze weile draußen. Hast du noch andere Datein z.B. AIC verändert bevor der Fehler aufgetreten ist?

**Comment by Monsterfisch** [comment]
ich hab den schonm eine ganze weile beobachtet wenn ich mich recht entsinne kam das auch schon bei einem kumpel von mir vor. wie gesagt das kommt nur bei den AIs vor nicht bei dem spieler marktplatz

**Comment by Monsterfisch** [comment]
hab nochmal recharchiert also bei meinem kumpel war das nicht der marktplatz aber eine baumeistergilde die nicht gelöscht wurde. Wie aber schon gesagt bei mir war das jetzt kein seperater einzelfall und dazu noch bei vielen verschiedenen kis und burgen.

**Comment by DarkThief-Darek** [comment]
Kannst du es denn leicht reproduzieren? Feuer anfällige Burg für KI, Feuerballiste/Sklaven und dann einmal mit und einmal ohne Patch ausprobieren?

**Comment by Monsterfisch** [comment]
hab noch nicht versucht das aktiv zu reproduzieren aber ich kann später mal ein paar versuche starten

**Comment by Monsterfisch** [comment]
scheinbar ist das in der tat ein vanilla problem zu sein wie mir von meinem kumpel bestätigt (bei ihm wurde zbauch eine brennende Baumeistergilde ignoriert) wurde vermutlich hat das mehr mit der feuerresistenz nach Neubau zu tun als mit den Baukosten die den Feuerlöschern verwirrt. 
Immerhin wird der Markt generell ziehmlich schnell wieder neu gebaut und ist dadurch öfter betroffen? Jedenfalls würde das das Verhalten irgendwo erklären.
