### ISSUE TITLE
Pros and cons about high and low weapon stocking

### ISSUE THREAD

**Issue by Truetobi91** [Sh0wdown/UnofficialCrusaderPatch#338]
This is meant to be more of an open discussion as I'd like to hear your thoughts about what setting is better for an AI and why. 

So there is the **MaxEquipment** parameter that determines how many weapons of one kind are being stocked in the armory before any of these are sold from overproduction. You can store up to 50 weapons per armory and you'd always take a somewhat lower number than that and devide it by the number of weapon types that is build be the AI. An AI that produces 2 types of weapons could technically store up to 25 of each, but there would be no room to temporarily collect more weapons to be sold, so weapon production would stagnate until units are being recruited. 

Importan thing to notice: choosing a high or low value should be representated in all castles (AIV) of the respective AI. 

---

Now the main question is: 

### Is it worth adding a 2nd armory and increase the amount of stocked weapons?

Pros: 
- Less repurchase of weapons sold for space (increased gold efficiency)
- Faster unit recruitment after an attack (no waiting time for a higher amount of equipment)
- Possibility of loosing an empty armory instead of a filled one (chance of decreased bombardment vulnerability)

Cons:
- ###### (2nd Armory wood costs and replacement costs)
- Additional space required (smaller castles possible)
- Selling weapons gives gold for other purposes (increased flexibility)
- Destroying a filled armory hurts the AI more (decreased average bombardment/fire vulnerability)
- Only makes sense if the weapon production is high enough for a real overproduction
- Too many unused goods (unused financial value)

**Comment by RafaelPin** [comment]
MaxEquipment isnt the only parameter that is important, MaxResourceVariance also affects it I guess. 
Just wanted to mention it , as nobody has written smth about it in the last two threads.

MaxEquipment can also be seen as MinEquipment, as the AI will only sell up to this amount of equipment.

Correct me if I am wrong.

**Comment by Truetobi91** [comment]
Any parameters involving Min[something] basically means the AI is buying this object until they have reached the limit. E.g. MinApples = 10 means that the AI will buy apples until reaching 10 once they fall below that value.

**Comment by Panbutt** [comment]
What exactly is ResourceVariance? Always wondered what it was.

Also I've noticed with Max(something) fields, the AI will wait until they have 5 more than the max before selling. With MaxEquipment if you set it to 25, they will wait until 30 and then sell back to 25. This is evident with Frederick, I think his MaxEquipment is 20 but he doesn't sell excess weaponry until 25.

**Comment by Truetobi91** [comment]
> 
> 
> What exactly is ResourceVariance? Always wondered what it was.
> 
> Also I've noticed with Max(something) fields, the AI will wait until they have 5 more than the max before selling. With MaxEquipment if you set it to 25, they will wait until 30 and then sell back to 25. This is evident with Frederick, I think his MaxEquipment is 20 but he doesn't sell excess weaponry until 25.

I think you pretty much answered your own question. The variance value seems to be the amount of goods that can be stored on top of the max value before they are being sold back to maximum. So the AI doesn't need to constantly sell values of 1 or 2 for goods they are producing.

**Comment by Monsterfisch** [comment]
ResourceVariance refers to the maximum amount of different type of resources stored in the stockpile (without specifying which ones in particular)  unless they are set to be sold (in most cases this was used to have some ai keep pitch in the stockpile.  		MaxResourceOther	= 10 in this case determains how many of the "other" resources are kept in the stockpile at a time

**Comment by Truetobi91** [comment]
Just some vanilla values:

**MaxResourceVariance**

Saladin: 2 
All others: 4 or 5

**MaxResourceOther**

Marshal: 12
All others: 10, 15 or 20

**Comment by ByBurton** [comment]
I altered a few of my AIs so that they keep a lot of weapons in stock, because they have a defensive character. I want them to hold out in sieges for as long as possible.

But I also have altered some AIs to be more aggressively, so I made them only keep the absolute necessary.

**Comment by Truetobi91** [comment]
Closed for low participation
