### ISSUE TITLE
Question about the next patch

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#34]
Dear developers. What changes to wait in the next patch? What are you working on right now?

**Comment by Sh0wdown** [comment]
- small redesign of the installer for space for explanations
- possibility to choose one's player color
- some new AI lord recruitment settings

Also maybe I will take a look at the ox tether spam and AI demolishing its buildings.

**Comment by Lolasik011** [comment]
Thank you ...
