### ISSUE TITLE
new GM1 files exporter/importer(need help)

### ISSUE THREAD

**Issue by Gaaammmler** [Sh0wdown/UnofficialCrusaderPatch#344]
Hello Guys,

id like to make a new GM1 files Exporter/importer for making new Texture packs in Stronghold Crusader. I found a link to the following webside (https://stronghold.fandom.com/wiki/GM1_file_format) where the GM1 File is listed which bytes to read and for what they are standing. But i have some troubles to understand all of it, maybe someone can help me to find out what bytes to read after the FileHeader.
![FileHeader](https://user-images.githubusercontent.com/5760157/56449738-1c829780-631e-11e9-8036-8a601d79a18d.JPG)

Thx for Helping

**Comment by Russianstory** [comment]
This is a very important and useful program will be! Milestones bless you! I am very glad that you are making a replacement for that program. She was buggy. Essentially, I unfortunately will not help. But thank you very much!
--
Это очень важная и полезная программа будет! Вех благ тебе! Очень рад что ты делаешь замену той программы. Она была глючная. По существу я к сожалению не помогу. Но большое спасибо!

**Comment by Monsterfisch** [comment]
upon my research to find a better program to work with the gm1 files I came upon this information as well granted i have no idea how to even start understanding it but the guys who made the stronghold europe mod might have some knowledge about it considering they managed to do a couple of things that didnt seem possible with the image toolbox program like resizing some images inside the gm1 files etc. (in case they are still active) https://www.moddb.com/mods/stronghold-europe

**Comment by Gaaammmler** [comment]
Hello Guys,

im back and i have now a little bit more i can read from the gm1 files:
    File Header 
    Palette 
    Image offset list 
    Image sizes list 
    Image Headers 
    Images as ByteArray.

The only thing I do not understand is how to use the Pallete, the byteArray from the img to create the rgb Picture, How are the palette, and the byte array connected? The Pallete have a size of 5120 bytes and store the RGB Colors, and somehow the Bytearray have the Index of the color. 

Maybe someone have an idea or a good website that explain how img stored in bytes with a palette? I tried now different Things. :/

If I get this done I have the pictures for editing :)

**Comment by Sh0wdown** [comment]
Maybe this helps you:
https://github.com/metalvoidzz/Sourcehold/blob/master/src/Parsers/Gm1File.cpp

**Comment by Gaaammmler** [comment]
Thank you Sh0down,

i didnt found the git on my research, that help me a lot now.

**Comment by Gaaammmler** [comment]
Hello Guys,

I can now open the GM1 Files. The Program have no functions yet, but I got a step closer for editing the images. Only one thing I’d like to know, how many of you use only Linux? Maybe I Code the program in Java or something like that so all of u can use it, not only windows User. ;)

A First Preview picture, it is not so pretty, because i used plenty time to decode that gm1 files and understanding it.

![FirstPreview](https://user-images.githubusercontent.com/5760157/56621772-15190200-662e-11e9-96ed-dceed7bc69f1.JPG)

**Comment by Lolasik011** [comment]
@Gaaammmler Wow !!! 0_0

**Comment by Gaaammmler** [comment]
I made now a git for the project so we can close the issue here now: https://github.com/Gaaammmler/Gm1KonverterCrossPlatform
