### ISSUE TITLE
Remove Progress Bar Upon Completion Of Installation

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#347]
For me, a progress bar indicates that some process for which progress can happen is currently running. 

![grafik](https://user-images.githubusercontent.com/12549394/56474953-9a12e880-6481-11e9-9a14-250dc31b935e.png)

When the process of installing the patch / patching the .exe files is finished and ends, so should end the progress bar display, imho. 
Otherwise it looks (misleadingly) like a "stuck at 99%" issue to me.

**Comment by Sh0wdown** [comment]
Coming in the next version.
