### ISSUE TITLE
Feature Request: Separate AIC files per character

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#350]
Considering it is possible to swap out all or individual AIV files for just one AI character, and this way combine different sets of AIVs, it would be nice to be able to separate AIC settings per character as well - either by having a separate AIC file per character, or possibly by extracting entries from multiple full AIC files, but only for the respective characters as specified in a patcher menu. I'd strongly suggest just using 1 AIC file per character, though. 

That way, you can easily exchange a single character's AIC file without having to bother with fiddling around with some more complicated patcher UI for mixing parts of larger files (which also would have to be created in the first place), don't have to bother with including AIC data for other unrelated characters, have no more searching for the desired character in the long list every time you want to edit that character, etc.

**Comment by Sh0wdown** [comment]
That's already possible. You can check multiple .aics in the UCP to loard/overwrite single characters. Load order is bottom to top (so the top ones will always overwrite the ones below)

**Comment by Heroesflorian** [comment]
Interesting... good to know, thanks!
