### ISSUE TITLE
Apple Farms building space 

### ISSUE THREAD

**Issue by Truetobi91** [Sh0wdown/UnofficialCrusaderPatch#354]
@Sh0wdown 
Ich schreibe mal auf Deutsch, weil ich gerade nicht weiß wie ich das auf Englisch formulieren sollte:
Ist es möglich die Apfelfarmen so zu ändern, dass sie zum platzieren nicht mehr dieses eine zusätzliche Feld benötigen? Sodass man auch Apfelfarmen problemlos ersetzen kann wenn diese eng an eng stehen ohne alles drum herum abreißen zu müssen?

**Comment by Russianstory** [comment]
Mein lieber Freund aus Deutschland. Ich schreibe auf Russisch))) aber auch auf Englisch durch einen Übersetzer.
Ich habe dieses Thema auch berührt, um den Platz zu reduzieren.
Schauen Sie, ich denke zwei Möglichkeiten:
1) Reduzieren Sie die Anzahl der Bäume und reduzieren Sie die Fläche
2) Lassen Sie alles so, wie es war, ABER fügen Sie ein oder zwei weitere Landwirte hinzu, um fruchtbarer zu arbeiten.

Ich dachte auch, dass es möglich sei, mit Kuhfarmen zu arbeiten oder einen anderen Landwirt zu bauen oder den Bereich der Koppel zu reduzieren. Aber so wie ich es verstanden habe, macht es uns unrealistisch.
--
Мой дорогой товарищ из Германии. Я пишу по-русски)))  но и по англицски через переводчика.
Я тоже эту тему трогал для уменьшения пространства.
Смотри я думаю два варианта:
1) Уменьшить количество деревьев и уменьшится площадь
2) Оставить всё как и было НО добавить ещё одного или двух фермеров для более плодотворной работы.

Так же я думал можно поступить и с коровьими фермами либо сделать ещё одного фермера либо уменьшить площадь загона. Но как я понял это сделать нам нереально.

**Comment by Heroesflorian** [comment]
@Russianstory I think what @Truetobi91 means is different from what you propose. 

When you place an apple orchard in Crusader, you need 11x11 tiles empty space for that. But after it was placed, the apple orchard will only be 10x10 tiles large. 

Interestingly enough, if you check in the AIV editor, the apple orchard is 10x10 tiles as well. 
![grafik](https://user-images.githubusercontent.com/12549394/57041807-6eeb7e80-6c63-11e9-9016-4e33eae5c05f.png)

It would definitely be nice to have a consistent size of 10x10 tiles for placing apple orchards as well.

**Comment by Truetobi91** [comment]
Done in the latest Patch (2.15)
