### ISSUE TITLE
Record matches

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#358]
Hi,
New fan of the UCP, I was wondering if it is possible/could be possible to record matches the way you can in Age of Empires 2, so that for example my friend plays a game, sends me the recorded file, and i can watch as a spectator. 
Just to clarify, I am not talking about recording a video of the game, I would like to be able to scroll the map myself, maybe select units and building to see their health bars, review lord rankings and gold/troop levels. In a perfect world even see all players' assassins, and notifications of resources being sent.
Let me know if this is valid.
I am a web developer and would gladly pitch in if someone can tell me what i need to learn to be able to be usefull.

**Comment by Sh0wdown** [comment]
That's way too complex without the source code, sorry.

> I am a web developer and would gladly pitch in if someone can tell me what i need to learn to be able to be usefull.
For the UCP mechanics you would need to be proficient in assembler.
Otherwise, maybe you are interested in this idea: https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/339

**Comment by GRhin** [comment]
darn, maybe if we can reignite popularity of this game firefly might consider it, one can dream

**Comment by GRhin** [comment]
Another idea of how to achieve this... maybe record whole map as a video, then have a viewer that can zoom in and move around the video...
Not a perfect solution, but its something?
