### ISSUE TITLE
Alerts stopped after installing Patch

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#359]
Just installed the Patch, and I am no longer getting alerts such as "The stockpile is full" or "your popularity is falling" etc.

**Comment by Sh0wdown** [comment]
Could you test which setting in the UCP produces this issue?

**Comment by GRhin** [comment]
sorry, had to reinstall everything, with default install values it works fine, cant remember what i had to test, maybe reinstalling fixed...
