### ISSUE TITLE
Marktplatz Autoverkauf ?

### ISSUE THREAD

**Issue by Blade1243** [Sh0wdown/UnofficialCrusaderPatch#36]
wäre es möglich im marktplatz eine option zu machen damit man sachen automatisch ab ner gewissen hohen menge verkaufen kann ? 

hab das in stronghold crusader 2 gesehen und dachte das wäre ideal für crusader :D

**Comment by ByBurton** [comment]
I doubt that that is possible...
It would be too much work probably, and I don't think he will give any focus to "extra" stuff like that.

But I would still like a feature like that....

**Comment by Sh0wdown** [comment]
Richtig mit integriertem Interface im Spiel wird schwer. Ich könnte mir vorstellen das mit einem externen Programm hinzukriegen, nur müsste man dann immer Crusader minimieren um was umzustellen.

**Comment by Lolasik011** [comment]
Same bug ... Pig. :(
![pig bug](https://user-images.githubusercontent.com/41998977/48576810-8ab5cf00-e926-11e8-8431-475a695157cb.png)

**Comment by Monsterfisch** [comment]
kannst ja machen das der markt sofern geld vorhanden ist immer die güter kauft die man gerade zum bauen oder zum produzieren benötigt wenn man die gewünschte ressource im markt ausgewählt hat müsse da nur eine häckchen im markt setzte

**Comment by Blade1243** [comment]
schade hätte gehofft das es irgendwie möglich wäre sowas hinzubekommen :D

**Comment by Blade1243** [comment]
> 
> 
> Richtig mit integriertem Interface im Spiel wird schwer. Ich könnte mir vorstellen das mit einem externen Programm hinzukriegen, nur müsste man dann immer Crusader minimieren um was umzustellen.

wäre das möglich das zu machen ? :D

**Comment by Heroesflorian** [comment]
> kannst ja machen das der markt sofern geld vorhanden ist immer die güter kauft die man gerade zum bauen oder zum produzieren benötigt wenn man die gewünschte ressource im markt ausgewählt hat müsse da nur eine häckchen im markt setzte

Ohne Sourcecode wird auch das vermutlich relativ schwierig zu machen sein. Aber die Idee gefällt mir.

**Comment by SimonRebholz** [comment]
Gefällt mir nicht;) Ist doch auch ein bisschen die Kunst seine Produktion in Balance zu haben. Und einen Überblick über sein Vorratslager

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Monsterfisch** [comment]
Hab mir zu dem Thema nochmal gedanken gemacht.

Es wäre vll auch eine Möglicheit via shift/strg (oder was sich halt so anbietet als taste) die Anzahl an Gütern, die man gerade im Marktplatz ausgewählt hat, "festzulegen" (die menge an festgelegten Gütern wäre abhängig von wie viel güter im vorratslager vorhanden an dem Zeitpunkt an dem man die taste drückt) sodas der Markt immer versucht die menge die man festgelegt hat immer wieder zu dem level auf zufüllen bzw automatisch zu verkaufen falls mehr angeliefert wurde.

**Comment by Halbarad1** [comment]
Ich würde mich schon freuen wenn ich vor Beginn eines großen Spiels festlegen kann, dass ab z. B. 200 Steinen jeder weitere Stein verkauft wird (ähnliches ab z. B. 20 Eisen) und bei weniger als 5 Holz immer entsprechend viel neues Holz dazugekauft wird (z. B. für Bogenmacher). Würde mir bereits einiges an Klicken ersparen. Wenn es die Option bei der Installation der Mod geben würde würde mich das schon sehr glücklich stimmen.

**Comment by DarkThief-Darek** [comment]
Ich habe in letzter Zeit auch wieder viel Crusader gespielt und da stimme @Halbarad1 zu: Der unkomplizierteste und erste Schritt wäre zu sagen, dass man eine Obergrenze von Gütern festlegen kann, die man definitiv nicht horten will. Das würde schon mal recht nahe an einen Autoverkauf drankommen.

Bier oder Eisen braucht man zum Beispiel nie wirklich im Überfluss (außer man spielt Wirtschaftskampagnen). Da macht eine etwas höher angelegte Obergrenze schon Sinn, die man nicht während dem Spiel ändern kann. Hilft halt viel im Lategame, wo man wenig baut, aber man bei wenigen Vorratslagern ständig nur noch verkaufen muss.

**Comment by Krarilotus** [comment]
This is getting worked on in #512, which has more infos about it. So closed for redundancy.
