### ISSUE TITLE
Tower ballista target choice

### ISSUE THREAD

**Issue by FurorGermanicus** [Sh0wdown/UnofficialCrusaderPatch#360]
Tower ballistas are the ultimate defense against catapults and trebuchets. 
Unfortunately they don't prioritize firing at those siege engines when there are other enemy troops in range.
I've tried this many times, you can cruise around in front of the enemies castle with your catapults in range of the tower ballistas and they won't get shot.

This is also a balancing problem:
The human player can choose the targets manually and destroy all siege equipment easily with ballistas, the AI can not and gets bombarded!
And in general, flying stones are overpowerd in Stronghold in my opinion, so improving ballista targeting also compensates here.

Tower ballistas should always prefer trebuchets and catapults as targets, this would balance the gameplay and buff AI opponents.

**Comment by PitchNeeded** [comment]
AI mangonels need to improve targets too. Sometimes they will be busy firing at an enemy farm even when an enemy siege force is approaching.

**Comment by Sh0wdown** [comment]
> Tower ballistas should always prefer trebuchets and catapults as targets, this would balance the gameplay and buff AI opponents.

But only in the defense. The AI is already incapable to construct proper siege equipment for attacks half the time.

**Comment by FurorGermanicus** [comment]
> 
> 
> > Tower ballistas should always prefer trebuchets and catapults as targets, this would balance the gameplay and buff AI opponents.
> 
> But only in the defense. The AI is already incapable to construct proper siege equipment for attacks half the time. I agree though, it would be a nice addition.

I totally agree with you, this is only for defense and improved siege behaviour would be wonderful for the game.

I see it this way with the targeting change:
In AI vs AI matches, the balance of siege/defense wouldn't change a lot, they are relying more on attack troops than equipment.
Rams and siege towers wouldn't be affected since they are moving targets.
AIs that attack human players are still as "good" (lol) as before.
But players besieging AI castles can't bomb them to the ground that easy.

AI catapults could also use that nice stop and go tactic of the crossbowmen (as they do it in some cases already) to improve their survival, that would buff attacking for compensation.

So all in all i think only sieges for the player get harder, which is a good thing for balancing.

**Comment by Krarilotus** [comment]
comment in newest issue for this topic. closed for reducing dublications.
