### ISSUE TITLE
Ai needs .more ranged troops when attacking

### ISSUE THREAD

**Issue by ilosevsrat** [Sh0wdown/UnofficialCrusaderPatch#361]
As title says, it would solve many problems like ai troops getting killed while they gather to attack and covering up siege engines.:)

**Comment by st3amli3n3** [comment]
This issue has already been solved with the AIC. 
You just need to increase the number of the ranged push units.

**Comment by ilosevsrat** [comment]
Well, yea i can do almost anything with editor but i was talking about new oatch :)

**Comment by ByBurton** [comment]
This can be closed I think.

**Comment by Krarilotus** [comment]
closed, no issue here
