### ISSUE TITLE
Question: Does this patch effect online play?

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#365]
Can anyone confirm if this effects playing online multiplayer? too scared to test it lol.

**Comment by Monsterfisch** [comment]
it will cause issues if your partners dont have the patch installed with the same settings etc. if they do have the patch installed with the same settings as you have it will play just fine (with the settings you use working as intended)

**Comment by GRhin** [comment]
so if we have 1 setting different it wont work?
I would have thought the ai tweaks would just behave according to hosts settings. 
What about the spectator mode setting? do we all need that if i want to use that to watch someone elses match without having my own castle? if we all have that will it put us all into spectator mode or only the host?

**Comment by Monsterfisch** [comment]
lets put it this way if you have different settings it works essentially the same way the game works when your partner doesnt have the same map or the same aiv files the game will start but it might display incorrectly or behave unexpectedly.
i do think through that the spectatormode should work no problem

**Comment by Sh0wdown** [comment]
If you send each other your settings via the ucp.cfg file, you can be sure that you apply the same settings.

> too scared to test it lol.
Well, it's the only way to find out. :)

**Comment by GRhin** [comment]
Reopening this as I have been testing with @Krarilotus at it does not work.
The game does not crash, it still runs properly, so heres the tests we ran (all with 3 players, 1 host, 2 players):
Host has spectator, players do not - Basically the hosts settings override the players, so all are spectating.
One player has spectator, host and otherplayers do not  - This was interesting. When the player joined the room (last, as the computer was slower) the sheilds dissappeared off the map, if host starts then, game starts with all players deceased, no keeps, but starting troops are there, and can be controlled, last man standing wins. If I change map, the shields come back, and game starts, but players cant control their units, the host can (after a delay),and while he has units selected, the other players can control his troops as well. The weirdest part of this test was after we came out, on the computer with spectator, it saw only himself as host (he was not host), on the host computer both himself and the spectator computer were marked as host, not sure about the other player (maybe krarilotus can update), but all 3 players could change maps, control alliances, kick players etc. however if they had different maps selected the game would start on an empty map and then crash, similar to if you tried to start on a map that not all players had.

@Sh0wdown is there any chance of this being looked at soon? Im already committed to doing some live matches this weekend to test the UCP, Im assuming it wont happen before then, but Id like to do this on a semi-regular basis.

**Comment by Krarilotus** [comment]
it might behave differently in the first sceario, i coudnt even start a game there.

in normal SHC HD the 'playerbanner shields' were gone from the preview map but the game started with lords dead and keeps vanished.
Tho ist would never end, cuz nobody coud kill anyone else, since its the dead lord glitch.
