### ISSUE TITLE
An Aic Modder (Kornspeicher Frage)

### ISSUE THREAD

**Issue by BonnieyTzw** [Sh0wdown/UnofficialCrusaderPatch#366]
Und zwar gibt es in der Aic Datei eine Zeile Unknown041 und Unknown042 die was mit dem Kornspeicher Rationen zu tun hat. Stellt man diese auf den Faktor auf null, setzt die Ki Ihre Rationen auf Neutral. Aber ich finde nicht den geeigneten Faktor heraus das die Ki die Rationen auf zum beispiel +4 stellt.
Sie Setzt diese immer nur auf 0 oder von -8 bis +8. Dies ist zwar schön und gut aber keine meiner Eigenen Ki,s benötigt eine extra Beliebtheit von bis zu +8. An Modder die schon weiter sind könnt ihr mir sagen welchen Faktor ich für +4 nehmen muss?

**Comment by ByBurton** [comment]
@BonnieyTzw in welchem Sinne haben die denn was mit Nahrung zu tun?! Richard hat da folgende Werte
		Unknown041	= 10
		Unknown042	= 40
Was genau bedeuten die Werte? Ist 041 minimal und 042 maximal? In was für Schritten geht das?
Könntest du mehr testen und mir Rückmeldung geben?
