### ISSUE TITLE
Laddermen disappearing ladders

### ISSUE THREAD

**Issue by xmaestro21** [Sh0wdown/UnofficialCrusaderPatch#37]
Hey i want to suggest a fix for the Laddermen.

After a Ladderman placed his ladder against a wall and dies, his ladder will also just disappear.
It would be nice if the ladder could stay on the wall permanently, like in Stronghold 2.
I have no idea if this is possible though, but i hope so :)

Anyway thanks for the great job, i'm really enjoying it!

**Comment by Sh0wdown** [comment]
That's not easily possible, since the ladders are part of the laddermen visuals, i.e. you cannot just split them without editing animations. You would also need additional code for this and even more, let the AI react to it. Without access to the source code, I won't put this on my list.
