### ISSUE TITLE
Running the patch on MacOS with „Wine“

### ISSUE THREAD

**Issue by iDjay** [Sh0wdown/UnofficialCrusaderPatch#370]
Hey,

Thanks for your patch! I‘m using v. 1.4.1 from Gog on MacOS Mojave and it works fine with .exe launcher like Crossover, Wine or PortingKit. But for some reason I can‘t get your patch to launch. Is there a specific requirement to get it running?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sh0wdown** [comment]
Sorry, I don't know what's stopping it. It runs on .NET 4.0 and uses WPF for the gui.
Compiling it with Mono also does not work.

**Comment by iDjay** [comment]
Thanks, I will try using net 4.0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
It launches after installing net 4.0 but the GUI is missing, where can I download WPF?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sh0wdown** [comment]
I don't know how or if it works on other OS.
https://en.wikipedia.org/wiki/Windows_Presentation_Foundation

**Comment by iDjay** [comment]
Hmm okay I don‘t think I can get this to work. I will stick with the original crusader version, if anyone still has an idea, let me know! 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Gaaammmler** [comment]
You can change the Stronghold exe on any windows Pc or virtual machine with Windows and than copy it after patching. The Problem is WPF(**Windows** Presentation Foundation) is for Windows and is not coded to run on MacOs or linux, i think. Maybe i can copy the hole Code from Sh0wdown and give you the programm in Avalonia(same as WPF but can run on all Platforms and is coded in C# and XAML), that should run on MacOS and Linux

**Comment by iDjay** [comment]
@Gaaammmler that would be great but actually I‘m running Stronghold with Crossover which emulates all the necessary Windows files to open .exe files on MacOS. There‘s no native stronghold Mac version 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by funghetto** [comment]
I've been able to run the installer by installing with winetricks dotnet40.

**Comment by iDjay** [comment]
>I've been able to run the installer by installing with winetricks dotnet40.

@funghetto can you explain me step by step how you did this please? :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by funghetto** [comment]
On the console
`WINEPREFIX=location/of/your/prefix winetricks dotnet40`
Start the installer

**Comment by iDjay** [comment]
> On the console
> `WINEPREFIX=location/of/your/prefix winetricks dotnet40`
> Start the installer

need a more detailed guide, I'm not really into the technical stuff 🙈

**Comment by iDjay** [comment]
@funghetto I found "Winetricks" inside Wineskin and was able to run dotnet40 but it still doesn't work. More details will be appreciated :)

**Comment by funghetto** [comment]
I'm on linux and there is no wineskin but I expect it to work likewise on macos.
I can guide you through installing it from the terminal if you want.

**Comment by PodeCaradox** [comment]
Maybe we can add in the future release .net core support so it should run on linux and mac. But i need to do some research on that.

**Comment by Git-Sakuba** [comment]
> Hey,
> 
> Thanks for your patch! I‘m using v. 1.4.1 from Gog on MacOS Mojave and it works fine with .exe launcher like Crossover, Wine or PortingKit. But for some reason I can‘t get your patch to launch. Is there a specific requirement to get it running?
> 
> Sent with [GitHawk](http://githawk.com)

Stronghold Crusader HD on Mac

First, buy and download the Game on https://www.gog.com/en/game/stronghold_crusader.
Install Porting Kit, then within Porting Kit, go to Library and search for Stronghold Crusader HD.

Wine (M1/M2) for Unofficial Crusader Patch:
1. Install Homebrew
2. “brew install samba“
3. “brew install --cask --no-quarantine gcenx/wine/wine-crossover“
    1. Or “brew install --no-quarantine gen/wine/wine-crossover“

Unofficial Crusader Patch:
1. First, open Wine Crossover (located in /User/Applications) by launching Terminal and typing "winecfg" (without quotes) and pressing Enter.
2. In the Wine Configuration window, go to the "Libraries" tab.
3. In the "New override for library" field, type "mscoree" (without quotes) and click the "Add" button.
4. In the "Existing overrides" field, select "mscoree" and click the "Edit" button.
5. In the "Edit override for library" window, select "Native (Windows)" and click the "OK" button.
6. Repeat the above steps to add and edit an override for "msxml6“, “gdiplus" and “msi“.
7. Once you have added overrides for these libraries, you can download and install the .NET Framework 4.6 redistributable package and the Windows Presentation Foundation (WPF) from Microsoft's website. You can find the download link for .NET 4.6 and the Windows Presentation Foundation (WPF) at https://www.microsoft.com/en-us/download/details.aspx?id=48137.
8. After the download is complete, locate the downloaded file and double-click it to begin the installation process.
9. Follow the prompts to complete the installation. During the installation process, you may be prompted to restart your computer. Now you should be able to run WPF applications within Wine.

Note that the installation process for .NET 4.6 and WPF in Wine may vary slightly depending on the specific Linux an Mac distribution and version of Wine you are using. If you encounter any issues or errors during the installation process, you can try checking the Wine website or forums for any known issues or troubleshooting tips.

Now open Unofficial Crusader Patch with the Wine Crossover application.
