### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Ih4al** [Sh0wdown/UnofficialCrusaderPatch#389]
I don't know what i am doing wrong. All the guides i ve seen talk about an exe file while mine is a sln. I tried to run it on visual studio, press "build" so i would make an executable but it doesn't work.

I am pretty ignorant at this kind of stuff, so excuse me if my question is idiotic.

Thanks in advance.

**Comment by Gaaammmler** [comment]
You need to go to the following page: https://github.com/Sh0wdown/UnofficialCrusaderPatch/releases and download the exe on the assets part.

**Comment by Ih4al** [comment]
I found a way to make the .exe part from visual studio, so it's all good now! Thanks tho!
