### ISSUE TITLE
Siege attacks and their aborting

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#39]
Sometimes, the AI does not send forward their attack army's ranged troops if the opponent castle walls are not breached by melee troops or siege engines. 
Then, the ranged troops can stay further back for quite a while (can sometimes be like 5 game years of effectively idling) before the AI finally aborts the siege and subsequently begins gathering a new army. 

It would be cool if the AI would use their ranged troops, or at least abort siege attacks instead of letting them continue without anything effectively happening. 

(If this has already been fixed, sorry, I must have missed it.)

**Comment by Panbutt** [comment]
This is something that's been bothering me as well. The AI is so sloppy when it comes down to siege forces in general.

-When choosing who to attack, the AI will sometimes send their siege forces past other enemy players resulting in the siege force dying before it can even reach it's intended target. (Especially on maps like Tilos. AIs do not take obstacles into account).
-Engineers are usually sent way too close to the enemy to build siege weapons. In some cases they're built way too far away. Lionheart seems victim of this the most.
-Ranged units are sometimes sent way too close to enemy towers (Looking at you, Sultan and Lionheart).
-Siege forces do not take tower ballista into account. Siege forces can be defeated simply by letting a single tower ballista pick them off at range.
-Siege tents will sometimes be made right next to one another and can block other engineers from entering their tents.

**Comment by ByBurton** [comment]
Or assassins attacking walls, instead of opening gates and killing defenders on the walls and towers......
Or the Snake melee attacking the walls with his archers... But I actually like that <3

**Comment by brotolisk** [comment]
I've noticed this with AI who attack with slingers.
Snake and the sultun.

The slingers will run back and forwards. Preventing any progression of attacks.

Usually blocking their path to the enemy stops this. Eg. Manual gate control at a choke point on narrow maps

**Comment by PitchNeeded** [comment]
> Sometimes, the AI does not send forward their attack army's ranged troops if the opponent castle walls are not breached by melee troops or siege engines.
> Then, the ranged troops can stay further back for quite a while (can sometimes be like 5 game years of effectively idling) before the AI finally aborts the siege and subsequently begins gathering a new army.
> 

Sometimes its a good thing for AI economies though, particularly for Emir and Wazir, if siege horse archers to get stuck in one place for a while as if they take a break from recruiting for a while they can accumulate a lot of gold in a short time which means it is harder for an enemy to ruin their economy with their increased funds and also gives them the money to create and roll more fire ballistae forward.

> Or the Snake melee attacking the walls with his archers... But I actually like that <3

Caliph does that too sometimes with his Arabian archers! And of course Saladin often does it with his horse archers!

**Comment by Heroesflorian** [comment]
> This is something that's been bothering me as well. The AI is so sloppy when it comes down to siege forces in general.
> 
> -When choosing who to attack, the AI will sometimes send their siege forces past other enemy players resulting in the siege force dying before it can even reach it's intended target. (Especially on maps like Tilos. AIs do not take obstacles into account).
> -Engineers are usually sent way too close to the enemy to build siege weapons. In some cases they're built way too far away. Lionheart seems victim of this the most.
> -Ranged units are sometimes sent way too close to enemy towers (Looking at you, Sultan and Lionheart).
> -Siege forces do not take tower ballista into account. Siege forces can be defeated simply by letting a single tower ballista pick them off at range.
> -Siege tents will sometimes be made right next to one another and can block other engineers from entering their tents.


> Or assassins attacking walls, instead of opening gates and killing defenders on the walls and towers......
> Or the Snake melee attacking the walls with his archers... But I actually like that <3


While I agree to those points, they do not really belong (except one, "Siege forces can be defeated simply by letting a single tower ballista pick them off at range") to the particular issue I mentioned in the original post of this issue thread - i.e. needless prolonging of incomplete sieges while doing nothing at all.

**Comment by Sh0wdown** [comment]
The next release will have a setting to let each AI always attack their nearest enemy. This should fix the mid-assault target switch as well as the sending of troops past an enemy castle.
