### ISSUE TITLE
Exclamation or an error ?

### ISSUE THREAD

**Issue by Admiral-Gumpert** [Sh0wdown/UnofficialCrusaderPatch#391]
Guys I face this quite strange message claiming the there are some differents in the game ,,,
![image](https://user-images.githubusercontent.com/50601775/58666732-d9fca380-833c-11e9-82f9-b42b97646efa.png)
![image](https://user-images.githubusercontent.com/50601775/58666745-e4b73880-833c-11e9-85e0-f1a3d441fc92.png)

**Comment by Admiral-Gumpert** [comment]
Also worth mentioning that I faced some bugs with AIVs after this error started to appear before fully installing the game and launching it

**Comment by MikillRosen** [comment]
Did you update the game?
