### ISSUE TITLE
What is "RaidUnitsRandom"??? 

### ISSUE THREAD

**Issue by Ariel644** [Sh0wdown/UnofficialCrusaderPatch#398]
Can anyone explaine??

**Comment by PitchNeeded** [comment]
I think its the amount of additional raiding units sent if the AI has a lot of gold or a lot of troops. I have certainly noticed that some AIs in vanilla Stronghold Crusader, particularly Emir and Caliph I have noticed, send bigger groups of raiders if they have a lot of troops or gold.

**Comment by ByBurton** [comment]
"aximum random addition to raid troops. Special cases: [gold > 5000 => multiplied by 2][gold < 1000 => set to 0][enemy gold < 500 => divided by -2]"

**Comment by Sh0wdown** [comment]
Like @ByBurton cited from the [Wiki](https://github.com/Sh0wdown/UnofficialCrusaderPatch/wiki/AI-Personality), the raid unit amount is increased by random value. RaidUnitsRandom sets the maximum of this random value.

- If the AI has more than 5000 gold, the value is doubled before consideration  
- If the AI has less than 1000 gold, the value is not considered at all  
- If the raid target has less than 500 gold, the value is divided by -2, i.e. the random value is _subtracted_.
