### ISSUE TITLE
SHC suddenly will not run as long as abbot1.aiv exists

### ISSUE THREAD

**Issue by Panbutt** [Sh0wdown/UnofficialCrusaderPatch#399]
So this is an extremely bizarre issue that just started out of the blue. My SHC will not run as long as abbot1.aiv is in the aiv folder. I've tested this on completely vanilla SHC and the patched SHC and the result is the same. When I delete abbot1.aiv or move it out of the folder, the game runs as normal. Thinking it was just a corrupted aiv I replaced it with different aivs, including those made by other people and even the vanilla abbot1.aiv but no change. Compatibility modes, running in Admin, running through a shortcut doesn't do anything either. Running on Windows 7.

I know this isn't really related to the patch itself but atm this place is the most active for SHC troubleshooting.

**Comment by J-T-de** [comment]
Just for completeness: Which Version of SHC are you running? Have you tied reinstalling SHC (save your saves!). Is it only abbot1.aiv or all abbots or all new characters?

**Comment by Panbutt** [comment]
Right, should've mentioned. Running on version 1.4 non-steam. Haven't done a complete reinstall yet; just reverted the vanilla exe and restored all vanilla settings. And yeah, it's _only_ abbot1.aiv, nothing else.

**Comment by Sh0wdown** [comment]
That's really a weird issue, but I think I will not look into it, sorry.
