### ISSUE TITLE
Game Speed Changes / Spielgeschwindigkeitsänderungen

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#4]
Ich habe im neuesten Video von Udwin zwar schon gehört, dass dir die Möglichkeit, die Spielgeschwindigkeitslimits zu ändern, prinzipiell bekannt ist und in diesen Patch mit einfließen soll. Allerdings weiß ich nicht, wie genau die Pläne diesbezüglich aktuell aussehen. 

Zum ersten Vorstellungsvideo hatte ich in den Kommentaren schon unter anderem Folgendes geschrieben: 

> Wenn man die .exe-File ohnehin schon anfasst... es ist möglich (sogar verhältnismäßig einfach und seit Jahren "bekannt" / Informationen öffentlich verfügbar), die minimale und maximale Ingame-Geschwindigkeit (normal 20-90), sowie die Änderungsrate (normal +-5 mittels Tasten +/-) zu verändern. Die maximale Geschwindigkeits-Bandbreite geht soweit ich weiß von 1 bis 127 _[Anm: selber schon getestet]_, und ich persönlich finde nach etwas Herumprobieren aktuell eine Min-/Max-Geschwindigkeit von 5 / 125 mit 15er-Änderungsraten durchaus angenehm in der Bedienung.
Eine Auswahl mehrerer "Geschwindigkeits-Werte-Setups" mit sinnvollen Werten sollte man mit relativ geringem Aufwand in den Launcher einbauen können, was z.B. für KI-Kämpfe oder manche Tests ziemlich praktisch wäre.

(#Edit: Ist es dir eigentlich allgemein lieber, Vorschläge, Probleme o.ä. hier auf Deutsch oder Englisch zu posten?)

**Comment by Sh0wdown** [comment]
Ja, das mit der Spielgeschwindigkeit ist eingeplant. Danke schonmal für den Ratenvorschlag,
vielleicht kann man die Rate auch dynamisch ändern, z.B. in 10er schritten über 90, etc.

Deutsch oder Englisch, schreib halt in welcher Sprache es dir mehr behagt. :P

**Comment by Heroesflorian** [comment]
Die Änderungsrate variabel zu gestalten klingt prinzipiell auch ganz nett, ja. Ich weiß allerdings nicht, wie aufwändig das umzusetzen wäre, ich hab bisher nur die konstanten Raten-Zahlenwerte modifiziert.

**Comment by Sh0wdown** [comment]
Ist im kommenden Release gefixt. Es geht jetzt
von 10 bis 90 in 5er-Schritten,
von 90 bis 200 in 10er-Schritten
und von 200 bis 1000 in 100er-Schritten.

**Comment by Heroesflorian** [comment]
Moment, was, über die bisherige Grenze von 127 bis hin zu 1000?! :o 

Das ist heftig, das kommt ja fast schon an die Werte ran, die ich anderweitig erreicht habe... 
(Per Speedup mit dem Programm DxWnd um Faktor 16 kann ich bei ingame-speed 127 effektive Spielgeschwindigkeiten von knapp über 2000 erreichen.)

Gibt es für das aktuelle Limit (1000) hier einen bestimmten technischen Grund, oder könnte man das noch weiter treiben?

**Comment by Sh0wdown** [comment]
Meine Tests haben ergeben dass die Spielgeschwindigkeit theoretisch so hoch sein kann wie man mag, nur ist sie praktisch bei hohen Werten nur so hoch wie der PC auch mit den "Crusader-Simulationsschritten" (kein Render-Frame sondern Gameplay-Frame oder so) nachkommt. Das ist zumindest mein Eindruck. Bei mir gab es zwischen 1000 und 2000 keinen sichtbarer Unterschied mehr, darum hab ich einfach 1000 als Limit gewählt.

**Comment by Heroesflorian** [comment]
Hmm okay. Wenn ich demnächst mal Zeit finde, werd ich das auch nochmal genauer in Kombination mit dem externen Speedup testen... 
Zumindest auf einem Laptop ist mir das auch schonmal aufgefallen, dass der bei so viel Geschwindigkeit nicht mehr hinterherkommt bzw. einfach nicht so schnell wird, aber mal schauen wie es am PC aussieht.
