### ISSUE TITLE
AI setting production buildings to sleep

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#40]
When the AI runs out of some resource, after some fixed amount of time, all buildings depending on that type of resource (e.g. bakeries for flour, fletchers and other wood-weapon workshops for wood, inns for ale) are set to sleep. And right after doing that, the AI tries to buy 2 units of the missing resource... 

Now, what would be really cool is if the AI would buy those missing resources **before** / instead of setting everything to sleep (and possibly buying more than just 2 units at once, but the ideal amount is probably too situational to easily find a one-fits-all value there...). 

Also, it could be helpful to simply increase the timer length until that setting-to-sleep behavior is invoked, in order to avoid situations where newly-bought resources are wasted right away by setting the corresponding buildings to sleep while they are still processing them.

**Comment by PitchNeeded** [comment]
> When the AI runs out of some resource, after some fixed amount of time, all buildings depending on that type of resource (e.g. bakeries for flour, fletchers and other wood-weapon workshops for wood, inns for ale) are set to sleep. And right after doing that, the AI tries to buy 2 units of the missing resource...
> 
> Now, what would be really cool is if the AI would buy those missing resources before / instead of setting everything to sleep (**and possibly buying more than just 2 units at once**, but the ideal amount is probably too situational to easily find a one-fits-all value there...).

Flour is quite expensive to buy in and if their wheat production is going badly for some reason, bread producing AIs would be probably be better off not buying in flour. Wheat is OK to buy in of course if they have enough gold, as the 20 wheat they buy in if lacking can be turned into a lot of bread, especially for Wazir and Abbot with their use of negative fear factor.

**Comment by Sh0wdown** [comment]
A setting to disable this will be in the next Release.
