### ISSUE TITLE
Kaufsystem

### ISSUE THREAD

**Issue by bySintexPL** [Sh0wdown/UnofficialCrusaderPatch#407]
Eine Funktion die es mir ermöglicht mehr als 5 Waren auf einmal zu kaufen (zb mit Shift)

Eine Funktion die es mir ermöglich automatisch waren zu verkaufen bis zu einem bestimmten punkt : ich haben 51 stein, 1 wird automatisch verkauft, ich habe 50 etc usw. Ich habe 10 Holz, es wird sofort 90 Holz nachgekauft. Ich habe 180 Holz, es werden sofort 80 holz verkauft (siehe Stronghold Crusader 2)

**Comment by Starshine575** [comment]
#379 Das gleiche habe ich auch schon einmal vorgeschlagen 😉

Wäre wirklich eine super Sache 😁

**Comment by Sh0wdown** [comment]
Ich schließ hier mal da es das Thema ja schon gibt.
