### ISSUE TITLE
What is "MaxResourceOther" & "MaxResourceVariance" ????? 

### ISSUE THREAD

**Issue by Ariel644** [Sh0wdown/UnofficialCrusaderPatch#411]

**Comment by Rakso69** [comment]
MaxResourceOther
-Iron, wheat, flour, hop, pitch.
MaxResourceVariance
-If AI buy, sell, or does buy while receiving the resource from a peasant causing it to go amount>MaxResource it leaves it being above-limit like that, or below limit. It's an value around the limit, it can be higher or lower, depends of the situation.
**Example:**
AI has **MaxResourceOther=15** means it can have as much 15 flour. If **MaxResourceVariance=5**, it means AI doesn't care about the flour if it's value is **15+5=20** or **15-5=10**. It just ignores it and leaves it nap like that. It's a kind of supportive mechanic for the AI to cause it to micromanage the economy less and don't "perfectionalize" everything by sensu stricto values by pointlessly selling&rebuying everything when it really isn't needed to.

**Comment by Panbutt** [comment]
Just to note: Wheat is controlled by MaxFood for ... whatever reason. I'd always recommend any AI that uses wheat to have a MaxFood of 40-50 or else the stockpiles overflow with wheat aha.

**Comment by Rakso69** [comment]
@Panbutt Just make enough mills. lol

**Comment by Krarilotus** [comment]
i havnt had the wheat issue yet. I recommend using more max food, since foodproduction is cheap but farms are harassed frequently and shoud be considered unsafe income. So having a bit extra food doesnt hurt. Also you canlet the AI change to double rations over the amount listed in Unknown042
