### ISSUE TITLE
Multiplayer client

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#412]
This is completely irrelevant to current UCP, just thought this might be a good place to get answers and potential solutions. 
Basically Id like to replace GameRanger for a couple reasons.
1. Id like to be able to track matches, see who was played and when (i forget names almost as soon as i leave a lobby) to be able to replay players who were challenging, and avoid players who are out of my league (and maybe try again when i get better or worse), either above or below in skill level. Which brings me to my second reason
2. Id like to see a rating system implemented, so that players can join matches with others of the same skill level.

I think these two things will allow the community to be a bit more reliable. And to be honest there is another platform that does it... for other games (AoE2 is the biggest game they support). They say they support SHC, but it doesnt, and they dont respond to my request for information: https://www.voobly.com/forum/thread/305313 (the chat support team required me to put my request in the forum, which has gone unanswered)
If anyone has knowledge on how to a) contact gameranger to potentially implement these ideas, b) contact voobly to implement this game, c) find another software that already supports, or could support, this game, or d) build a new custom client to handle SHC to achieve this, Id love to hear from you.

**Comment by Rakso69** [comment]
All you need to do is copy-paste good old Stronghold's Gamespy Arcade only.

**Comment by GRhin** [comment]
can you reword your suggestion?
Im only half understanding you. And that is Gamespy Arcade, which is the original software that is no longer runningand thus the move to gameranger. How that is usefull now I dont understand.

**Comment by GRhin** [comment]
If anyone understands this sort of thing, I found a potential start point... @Rakso69 gave me the idea of looking for a reimplementation of GameSpy Arcade. https://github.com/GameProgressive has a RetroSpy server and SDK. software development isnt my area of expertise so im not sure exactly how to go from finding that to seeing if it works lol.
