### ISSUE TITLE
.sav/.map file format documentation

### ISSUE THREAD

**Issue by void4** [Sh0wdown/UnofficialCrusaderPatch#414]
Do you have more information about how the savegame file is structured? It seems to be compressed, but I don't know how.

The program [Stronghold PNGer](http://stronghold.heavengames.com/downloads/showfile.php?fileid=67) can extract the map preview image from .map files (renamed from .sav). Unfortunately, I can't reach its author.

**Comment by PodeCaradox** [comment]
Here are some information and maybe someone can help him. https://github.com/metalvoidzz/Sourcehold/wiki/Stronghold-asset-formats

**Comment by void4** [comment]
It seems that , this entropy image

![Screenshot from 2019-07-01 19-03-01](https://user-images.githubusercontent.com/11392207/60454012-099c1580-9c33-11e9-9c27-af01fb0a3d15.png)
 (made [here](http://binvis.io/)) suggests that it may be compressed, possibly even with a custom algorithm (wouldn't suprise me, given .tgx and the other custom formats). I'm not sure though.

**Comment by void4** [comment]
Is there some discord or something where we can collaborate on this in realtime?

**Comment by metalvoidzz** [comment]
I created https://discord.gg/736X9H a while back for Sourcehold, but I mainly use it for notifications ;-)

**Comment by JuGGerNaunT** [comment]
@void4 map's image is stored inside map file so it is pretty easy to get it. Tool your mentioned doesn't create it from scratch. I have some knowledge about map file so if you don't need whole file structure but only some specific fields maybe I can help you.

**Comment by metalvoidzz** [comment]
About that compression, I think I have some info that could help determine the algorithm. First of all, the Stronghold.exe actually contains the copyright text for the PKWARE compression library, which could have been used for the map files. Secondly, the tool http://aluigi.altervista.org/mytoolz.htm#signsrch reports a lzari signature at offset 0x36c8. Both formats seem to be known.

Btw, maybe we should talk somewhere else, since this has nothing to do with the patch itself.

**Comment by JuGGerNaunT** [comment]
Whole issue has nothing to do with the patch but it is still open so I don't think project author has something against it.
Yes, some map fields are compressed with pkware compression (btw map preview image is among them). And this is the only compression used. But that is not the problem. Uncompressed fields still aren't human readable text data (who would doubt that). They are same binary blobs. And until you find which blob is responsible for what game data, they are as useless as compressed.

**Comment by metalvoidzz** [comment]
Cool, if there is an easy way to uncompress those fields, it's probably not too hard to figure out the structure by comparing to a changed version. How did you actually uncompress them?

**Comment by JuGGerNaunT** [comment]
I inject my code and use game's decompression method.

**Comment by J-T-de** [comment]
To give an update after one year, the map-file format (including the decompression and the preview image) is documented [here](https://github.com/sourcehold/sourcehold-maps) and [here](https://github.com/sourcehold/sourcehold-maps/wiki).

I think this can be closed now.
