### ISSUE TITLE
Question: Changing peasant names

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#421]
Hi all,
This isnt directly a patch question, I just want to know if its possible to change peasant names? I would assume it would beeasy to do so, but i cant find the file where they are specified, and cant find the string in the exe with cheat engine.
Names are currently things like "Jamie Brown" or "Roger Badbread", it seems to be generated from lists of first names and surnames. http://stronghold.heavengames.com/gameinfo/lists/people
If someone can point me to where I might be able to add my own names I'd appreciate it.
--GRhin

**Comment by Russianstory** [comment]
In my modification about Russia, the names of the peasants were not only replaced, but also changed to those ancient ones that we had in the 13th century. And the names too. So, what you say is no longer a news for me, like 10. You’re late to discover America))

**Comment by GRhin** [comment]
@Russianstory I think you have misunderstood, I was asking how it can be done, if you are doing it in your mod maybe you could let me know how you did it?

**Comment by J-T-de** [comment]
In the Stronghold Crusader Modding Utilities, there is a Text Compiling Tool and all text of the game, including peasant names. One can change the text, compile it and include it in-game.

**Comment by J-T-de** [comment]
http://stronghold.heavengames.com/cgi-bin/forum/display.cgi?action=ct&f=4,3820,,10 : Second Link seems to work, but no liability ;)

**Comment by GRhin** [comment]
Thanks @J-T-de, I'll take a look

**Comment by Russianstory** [comment]
No, my friend)) I just understood you correctly)). I do not remember exactly myself. Because I was another comrade. Everything can be enclosed in a file. cr.tex I was responsible for sounds, voiceovers and lyrics for voiceovers.

**Comment by GRhin** [comment]
J-T-de's suggestion worked, I probably should have looked there first lol
