### ISSUE TITLE
Priority goals... Ballista and Mangonel!

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#422]
Is it possible to put a high priority on shooting at siege weapons (Siege Towers, Catapults, Trebuchet, Ram)? 
I would like the AI ​​in the first place not to shoot at the infantry, but to start shooting at siege weapons so that they do not have time to destroy the walls. Because AI is very easy to fool. You can send a lot of slaves as a meat shield, and in the UTB time to destroy walls and towers. Balista and Mangoneli are distracted by the infantry mainly ...

This would greatly strengthen the AI.

**Comment by PitchNeeded** [comment]
And also not to keep shooting at random enemy farms in the other direction with mangonels too when siege forces are approaching (I have seen this happen).

**Comment by PitchNeeded** [comment]
And also not to keep shooting at random enemy farms in the other direction with mangonels too when enemy siege forces are approaching (I have seen this happen).

**Comment by Lolasik011** [comment]
> And also not to keep shooting at random enemy farms in the other direction with mangonels too when enemy siege forces are approaching (I have seen this happen).


For sure! I forgot...

**Comment by FurorGermanicus** [comment]
That is exactly what I said in #360 .
Catapults are too strong, enhanced balista fire balances that.
The AI would be much more difficult to attack.

**Comment by Krarilotus** [comment]
comment on the newest issue,
