### ISSUE TITLE
Siege Engines are described or known as numbers (At some lines)

### ISSUE THREAD

**Issue by Admiral-Gumpert** [Sh0wdown/UnofficialCrusaderPatch#423]
Idk if you guys know that or some of you only do , Raiding siege engines are known as 3 digits in the AIC file , and I Think some AIVs can recruit a BattleRam for example (As a kind of harassment or raiding) , But for now the only found codes for the siege engines are 
FireBallista : 358
Catapult : 190 

So if you open the AIC file and go to the lines from Unknown115 to Unknown122 You will find that every AI has atleast one of these whether it be 190 or 358 , And even some AIs has them both ,

while you can clearly see at this line (		SiegeEngine1	= unit   )  that the siege engines are not written in codes or numbers !

 Is there any probability of changing those numbers to units (text) or finding new codes for other siege engines?

**Comment by Sh0wdown** [comment]
Both properties are actually numbers. Alternative text input was introduced for known numbers. So you can actually use numbers or text for SiegeEngine1-8.

https://github.com/Sh0wdown/UnofficialCrusaderPatch/blob/master/UnofficialCrusaderPatch/AICharacters/PersonalityEnums/SiegeEngines.cs

For the harassment property the optional text input hasn't yet been implemented, but will be in the next version. Moreover if you compare the two enums in the link, the numbers vary, so you cannot just use the numbers of the SiegeEngine property for the Harrassment properties.

**Comment by Admiral-Gumpert** [comment]
Yeah I see , They differ as you said .

**Comment by ByBurton** [comment]
This issue can be closed, as it will be solved in the next update, right?

**Comment by ByBurton** [comment]
@Sh0wdown Siege engines should now be written in after updating it with the updater, right?

**Comment by ByBurton** [comment]
I'm closing this issue.
