### ISSUE TITLE
Multiplayer Testing: Volunteers Needed

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#424]
Hi Guys,
I am wanting to test the UCP in multiplayer conditions, and have decided to do it on a twitch stream in the form of a best of 3 showmatch - $20 for the winner (to make sure everyone is motivated). 
**So here I what I am looking for:**
-2 similarly skilled players
-They do not need to be expert level, but very skilled is preferable
-They need to be available this Friday night (26th July) at 1900 GMT, preferably a little earlier to test that everyone has the setup right before the match starts.

**How it works**
-No Peace time, 90 pop max
-UCP installed with default options (i.e. all options selected in the units and other tabs, except for spectator mode.)
-I will host the match with the UCP spectator mode to provide commentary to the twitch stream
-Each player selects a "home" map (preferably not a standard expert map, but those will be accepted) ahead of time (so we can ensure all players have it)
-First match will be played on a map I have selected from the vanilla game (probably "divided")
-Second match will be on the home map of the losing player of the first match.
-If the score is 1-1 at this point, the Third match will be played on the remaining home map.
-The player who wins two matches recieves $20

After this match completes, if people are around and wanting to continue I will host some friendly matches in open lobby.

Let me know if you are interested, or if you know someone who might be interested.
--GRhin

**Comment by Rakso69** [comment]
>90 pop max
>preferably no expert map
/lol
Omg xD

**Comment by GRhin** [comment]
Dude, can you be constructive for once? This is not testing the expert scene which does not use the ucp, it is testing the average guy playing, which rarely use the expert maps.

**Comment by Krarilotus** [comment]
I think, giving 90 max pop makes the games way more interesting, making huge click feasts a no winner, and real tactics more important. I guess that could also be a good buildin feature for the UCP for enable nice multiplayer gameplay
 :)

**Comment by Halbarad1** [comment]
I am interested. I would count myself as an average player but not as an expert, since I am better than everyone in my milieu (brothers, friends, ...) but have played less than 10 games online since I didn't like the style there. But since we aren't play under online conditions that should be fine I guess. 

I normally play with Stronghold Crusader Version 1.3. So I don't use the Steam Edition, hope that's alright. 
We are using Stronghold Crusader Extreme for higher troop limit, right?
Are there rules for the "home map"? I think it should be balanced  (witch doesn't mean for me that it doesn't have to look mirrored), without these troop spawn buildings and the player who didn't create it should decide whether he wants to take his spot first. Apart of that, anything else?
Any rules for playing? Like bug-using and these things are forbidden? 
That would include surround quarry so the stones do spawn at the ox tether, build two times crenellation to stop assassins and siege towers and these things?
 
Do we use GameRanger for playing?
If you want to follow us on twitch, should we talk while playing or something?

**Comment by GRhin** [comment]
Yes we will use GameRanger. No you dont need to talk while playing (its harder than i thought lol). Basically I will be a commentator during the match, and you can give extra feedback after the game. If your distracted by the need to talk you cant test the UCP effectively.

I realised the maps would need to fit certain criteria to keep the matches interesting, and need to be truely balanced considering I am offering money for it, So I am putting together a map-pack that you can choose from, most of them i have edited slightly to make more balanced, but are made by other players from HeavenGames. I can send that through to players ahead of time so they can look through and select their favorite.

**Comment by Krarilotus** [comment]
We should see if 1.3 and 1.4 can be compatible in any way in multiplayer. I dont have the 1.3 version lying around here, if i would take part, i would have to get that version somewhere, and i actually have no clue where to get that.
Also high towers in front of big towers are a feature i guess, fast workers glitch should be banned maybe, especially with max pop and also having faster rally speed for assassins i would count as a feature?

But you make the rules in the end

**Comment by GRhin** [comment]
im on 1.4 as well. It would be simpler for Others to update to 1.4 (free download from firefly) than to have to figure out how to downgrade. As for assassins rally speed, i think that is also fine, same with towers.

**Comment by Krarilotus** [comment]
This was a great success, as it proofs that multiplayer is way more fun with no rules like no fire or no rush or no stones.
90 max pop might be a good number, tho maybe we can try 122 next time. actually not capping population but housings.

bBut 90 worked well, as it seems everyone can micro more and focus on different troop compositions. But on narrow maps, catapults, horsearchers and shields still came out on top. Also assassins and pikeman aswell as Crossbowman. So making some small adjustments for balancing purposes, would give other troops like arabian wordsmen, spearman, european archers (little bit more range?) and siegetower/battering rams more usecases

See you soon :)

**Comment by GRhin** [comment]
Yes, it was a great success, I agree some balancing is needed, however the game can be very enjoyable without it. 
Id love to have the oppotunity to play with the balance to try improve it. I thinkmore many of the units you mentioned, a price increase is all thats needed. Catapults, horsearchers and assassins in particular, while the shields could do with a small speed decrease (so something like spears could catch them) and probably a health decrease. My head is swimming with ideas, not all of which would turn out to be best, but if the balance is looked at seriously please let me get involved.
