### ISSUE TITLE
Kann in die Liste aufgenommen werden

### ISSUE THREAD

**Issue by velyfrendly** [Sh0wdown/UnofficialCrusaderPatch#426]
Maximal.Ressource.Other gilt für Mehl, Pech, Hopfen und Eisen.

Maximal.Food gilt für die Gesamtmenge an Nahrung im Kornpeicher, aber auch für die Menge Weizen auf dem Lagerplatz. Ist der Wert zu hoch, verstopft das Lager mit Weizen.

Unknown041 bestimmt die Mindestmenge für Stein, Eisen, Holz, Mehl und Bier auf dem Lager. (Hier wird beim Unterschreiten nicht nachgekauft, es bezieht sich nur auf die Menge bis zu der ein Verbündeter Waren zusendet). So kann man zum Beispiel den Kalifen vom Geiz befreien ^^.

**Comment by Krarilotus** [comment]
nice, 
es gibt auch noch die beiden hier:
unknown068 ist die Zeit die Patrouillierende Truppen in der Burg haben um von einem Punkt zum nächsten zu kommen (z.B. Horsearchers)
Und unknown069 ist die anzahl dieser patroilien pro Einheit (maximal 10, da maximal 10 Punkte im AIV Editor gesetzt werden können.

Außerdem ist unknown009 die Steuerstufenzahl die die KI auf einen Schlag verstellt, wenn sie die Steuern anpasst (um z.B. nahrung auszugleichen auf 3, dann wird immer direkt von -8 auf +1 gestellt)
Unknown010 ist die maximale Steuerstufe, wobei 0 die Stufe +7 (großzügige Spende) und 3 die Stufe +1 keine Steuern, 7 die Stufe -8 und 11 die stufe -24 ist

Unknown042 ist die Anzahl an Nahrung ab der doppelte Rationen ausgegeben werden

**Comment by ByBurton** [comment]
Unknown041 kann irgendwie nicht hinhauen. Die Ratte hat da 0 und sendet sehr gerne Güter.

**Comment by Krarilotus** [comment]
> Unknown041 kann irgendwie nicht hinhauen. Die Ratte hat da 0 und sendet sehr gerne Güter.

@ByBurton hey, wenn er 0 hat, sendet er immer, das ist doch gerade der threshhold wie viel die KI behält, daher ab welchem wert sie sendet.

**Comment by velyfrendly** [comment]
Genau, das heisst er sendet die betreffenden Güter bis er keine mehr hat  Setz man die Zahl z.B auf 10, so sollte er solange helfen, bis er selbst nur noch 10+4 hat. 10+4 weil man nicht weniger als 5 erfragen kann.

**Comment by velyfrendly** [comment]
Unknown095 konnte ich auch enträtseln ^^
Zunächst dachte ich dies hängt mit der Patroullie zusammen was richtig ist. Ich glaubte es hängt mit der Anzahl erstellter Truppen zusammen, bevor diese zur Patroullie geschickt werden, aber obwohl sich das Verhahlten und die Mannstärke der Patrollie sich änderte, war diese selbst bei gleichbleibendem Wert oft unterschiedlich. Dieser Unterschied resultierte aus der Rekrutierungswahrscheinlichkeit, die bei einem anderen Parameter bestimmt wird, also konnte das nicht mit der Mannzahl zusammenhängen. Dann stellte ich fest, das bei stark veränderten Werten das Zeitintervall in der Patrollien entsendet werden, sich verschob. Bei dem Wert 500 verliess die erste Patroullie die Burg nach etwa 10 Jahren. Bei 50 nach einem Jahr. Macht Sinn, bei veränderter Anzahl Männer aufgrund der Rekrutierungswahrscheinlichkeit.

**Comment by ByBurton** [comment]
@Krarilotus Could you please test Unknown095?

**Comment by Krarilotus** [comment]
Btw, die Patrouillen die ich meine sind nicht die deff-truppen Patrouillen die er meint mit der 095. Ja ich kann mal etwas rumspielen :)

**Comment by Krarilotus** [comment]
Also ich kann es nicht exakt sagen, es könnte stimmen?
Ich habe gerade mal deff Truppen Rekrutierung auf 1% gestellt aber die KI schiebt fast nur deff Truppen raus, als ob sie nix besseres zu tun hätte. Die pumpt Deff ohne ende. Also evtl ist da auch bei den Wahrscheinlichkeiten noch was verkehrt. Wie habt ihr diese 'Wahrscheinlichekteiten' denn gemessen?

**Comment by Starshine575** [comment]
@Krarilotus wenn ich dass richtig verstanden habe, ist es korrekt, dass die KI nur Sortie und Raid-Einheiten produziert, da der Parameter **RecruitGoldThreshold** bei jeder KI auf 200 Gold eingestellt ist. 😯

Unter 200 Gold kann somit erst garkeine solche Einheit erschaffen werden. (wenn ich, wie gesagt, das richtig verstanden habe 😅🤔).

**Comment by Krarilotus** [comment]
@Starshine575 
Das Recruit-Gold-Threshold wird auch für Sortie und Raid Units nicht angefasst. Das Threshhold wird trotzdem unterschritten, sobald die Rekrutierung nach überschreiten freigegeben ist und die KI macht das Gold leer. Darunter kauft sie aber durchaus einige Ressourcen die sie braucht, daher ist das Threshold nützlich um die Eco hochzuziehen.

Schön wäre es, wenn man die Häufigkeit der Sortie Rekrutierung trotzdem einstellen könnte, bestimmt geht das auch irgendwo!

**Comment by Starshine575** [comment]
@Krarilotus Soso ... Danke für die Aufklärung. 👍✌️

Ist dann aber der dazugehörige Wiki-Eintrag nicht falsch? 🤔

**Comment by Krarilotus** [comment]
Das weiß ich nicht, ich habe im Wiki nix eingetragen, bloß selbst ausführlich getestet!

Die Rekrutierungswahrscheinlichkeiten scheinen ja auch nicht zu stimmen, man sollte immer mit ein wenig Vorsicht rangehen!
Also Augen auf und weiter testen :D
Hut ab vor denen, die schon so viele Werte vorher rausgefunden haben, das ist ne Menge Arbeit!

**Comment by velyfrendly** [comment]
Ich weiss nicht genau wie das mit den Wahrscheinlichkeiten berechnet wird, eventuell muss man die probs in relation zueinander bewerten. Also alle probWeaks müssen in der Summe 100% ergeben. Dasselbe für probdefault und probstrong.

Aber wenn ich mich nicht irre, sind die Sortie Truppen seperat zu betrachten, da diese die Burg nur verlassen, wenn ausserhalb Bauern und Truppen attackiert werden. Die OuterPatrollie zur Sicherheit der äussern Wirtschaft müsste zu Def-Gruppe gehören. Ochwerd das die Tage mal ausprobieren und berichten, wenn ich etwas feststelle.

Bezüglich Unknown095 habe ich den folgenden Test mit entsprechenden Beobachtungen gemacht. Herangezogen habe ich Richard. Die RecruitProbs habe ich nicht gross verändert. Die OuterPatroulGroupeCount habe ich auf eins gesetzt, damit es übersichtlich ist. DefTotal habe ich auf 200 gesetzt und DefWall auf 100. Als Resultat geht die Differenz von 100, also eine grosse Gruppe auf Patrollie (Outer Patroullie). Wenn ich nun Unknown095 auf 500 setze, verlässt diese grosse Gruppe den Bergfried erst nach 10 Jahren. Bei 50 verlässt die erste kleine Gruppen den Bergrief nach einem Jahr. Daraus schliesse ich das dieser Wert festlegt wann die bereits erstellten Einheiten der OuterPatrollie losgeschickt werden. Bei 50 jedes IngameJahr bis zur maximalen Grösse. Ich werde nochmal einpaar Tests ausgühren um das zu bestätigen.

**Comment by Krarilotus** [comment]
@velyfrendly Guter Test, aber du musst bedenken, dass Richards Wirtschaft vermutlich die Truppengröße limitiert. Ich hab meinen Test ganz ähnlich gestrickt. mit 2 Truppen zu je 100 auf äußerer Patrouille, die aber die Burg erst verlassen haben (obwohl 095 auf 10 war) als die restlichen 400 Defftruppen auf den wällen stand. Und das bei einer Deff Rekrutierungswahrscheinlichkeit von 1%. Die Summer der Rekrutierungsprobs habe ich natürlich auf 100% angesetzt, also daran liegt es nicht. Die Angriffstruppen waren bei 90% und die raid bei 9%, bzw je 10% weniger für default und weak. Trotzdem hat die KI selten angegriffen und Deff Einheiten gepumpt wie blöde. Vielleicht hängt das auch von der Gesamtgröße der Deff ab? Oder vll verfällt sie in den Status: Jetzt Defftruppen aufstocken, 10% der Defftruppen müssen aufgestockt werden jedes mal wenn deff rekrutiert wird...?) Also die 095 ist mir nicht so richtig klar bisher.

**Comment by velyfrendly** [comment]
@Krarilotus
Soeben den Test mehrfach wiederholt und das Ergebnis war immer gleich. DefWall bei 20, DefTotal bei 200. Startbedingung liegt natürlich zum Computervorteil bei 40.000 Gold, damit die Wirtschaft das nicht ausbremst oder anderweitig beeinflusst.

Unknown095: 
gesetzt auf 500 = ca. 10 Jahre Wartezeit
gesetzt auf 100 = ca. 2 Jahre Wartezeit
gesetzt auf 50 = ca. 1 Jahr Wartezeit
gesetzt auf 25 = ca. alle 6 Monate
gesetzt auf 10 = ca. alle 3 Monate in vielen kleinen Schüben....

Ich denke der Zusammenhang liegt auf der Hand. Eventuell besteht eine Wechselwirkung mit der Ökonomie der KI, den RecruitProb-Werten und sonstige Variablen, aber diese dürften dabei eher indirekt damit zusammenhängen.

**Comment by Krarilotus** [comment]
@velyfrendly 
Hört sich gut an!!!
Dann wünsche ich mir jetzt noch irgendwie die recruitment probabilities zu retesten. Ich denke eine sache liegt auf der hand: wenn die KI truppen baut die waffen benötigen, dann baut sie erstmal die truppen für die sie waffen hat, egal welche probabilities es gibt. 

Daher wird bei ner armbrust massenproduktion erstmal die Verteidigung voll besetzt nehme ich an... Zumindest denke ich, dass das bei meinem Test ausschlaggebender Punkt war! Mein Araber verhält sich dagegen recht den Probabilities entsprechend
Aber müsste man genauer untersuchen!

**Comment by velyfrendly** [comment]
Das mit den Waffen leuchtet ein. ich hab mal den Versuch gewagt, aber wurde einfach nicht schlau draus. Dabei habe ich wirklich alle möglichen Einflussfaktoren ausgeschaltet, die ich finden konnte.

Ich habe im AIV-editor die platzierung der truppen und den graben gelöscht. die defdigg-, attdigg-, backup-, sortie- und sonstige -Einheiten auf null gesetzt und für den Test nur Moslem-Söldner zur Auswahl gestellt. Bin dann wie folgt vorgegangen. Ich habe die AI so eingestellt, dass er für die def-, att-, raid-Truppen jeweils nur eine einzige voneinander unterscheidende Einheit in derselben maximalen Anzahl (50) erstellt und habe dann an den probs-Werten rumgeschraubt. DefWall=0 setzen, damit sich hier nichts aufteilt und weniger im Weg stehen bzw. sofort zur Patroullie raus gehen (dafür habe ich auf den kleinsten Wert gesetzt, unknown095 = 1). 

Truppenauswahl:
defTotal: assassin (max. 50) , defWall (max. 0)
raid: slinger (max. 50)
att: slave (max. 50)

Habe die probs für alle drei Variationen (weak, default, strong) immer gleich gestezt, damit das Verhalten sich niemals ändert und die Werte für recruitInterval ebenfalls für alle drei Varitationen auf 1, damit auch hier das Verhalten sich nicht ändert. Versuche mit Computervorteil (40k Gold) gestartet.

Versuch 1:
def: 20%
raid: 20%
att: 60%

Nun hätte ich erwartet, dass er die Truppen im Verhältis 1:1:3 erstellt, aber Fehlanzeige.

Ergebnis Versuch 1: 
Zuerst ca. 32 Assassins (Def-Unit)
Dann ca. 31 Slaves (Att-Unit)
Dann ca. 9 Slingers (Radi-Unit)
-- hier abgebrochen

Versuch 2:
def: 1%
raid: 90%
att: 9%

Ergebnis Versuch 2: 
Zuerst ca. 32 Assassins
Dann ca. 16 Slaves
Dann ca. 22 Slinger
Dann ca. 7 Assassins
Dann wieder ca. 22 Slaves
-- hier abgebrochen

Versuch 3:
def: 98%
raid: 1%
att: 1%

Ergebnis Versuch 3
Zuerst 32 Assassins
Dann 20 Slaves
Dann 5 Assassins
Dann 11 Slaves
Dann 23 Assassins
und wieder Slaves
-- hier abgebrochen

Was mir dabei auffällt:
Er beginnt immer erst mit den Def-Einheiten und erstellte in allen drei Versuchen zu Beginn die gleiche Anzahl (32). Erstellt als zweites Att-Einheiten in unterschiedlicher Zahl, aber nicht den Prozenten entsprechenden, eher leicht tendierend. Im dritten Versuch gibt es einen Ansatz der Richtigkeit in den Prozentwerten, da er in mehreren Rekrutierungsschüben keine Slinger erstellte (lg bei 1%, leider Att-Einheiten auch..????).

Was kann man draus schließen? Ich bin überfragt...

**Comment by Krarilotus** [comment]
@velyfrendly 
Was sind deine Werte für 072 und 073? Und welche KI hast du benutzt, könntest du einfach dein komplettes KI Array hier posten?
Versuch mal 8 unterschiedliche KI's mit den gleichen einstellungen auf ner map wo sie alle voneinander getrennt sind, also sich nicht gegenseitig behindern, free for all. Kannst ja einfach dick terrain einfügen.

Und mach mehrere Versuche für die Wahrscheinlichkeiten. Ich habe auch festgestellt, dass er immer ne bestimmte Anzahl von Units einer Gruppe auf einmal rekrutiert.

Womit diese Zahl zusammenhängt wäre gut zu wissen. Die 073 hat Swarton vermutet, könnte was mit dem Startrekruitment zu tun haben, daher vll die mal auf 1 setzen und nochmal testen.

Und evtl mal unterschiedliche Truppen in den unterschiedlichen Kathegorien. Also z.B. slaves mal für deff und Assassins für attack. Vll hat das auch was mit den Goldausgaben für die Units zu tun.

**Comment by velyfrendly** [comment]
Ich habe natürlich darauf geachtet, dass die Startbedingungen immer gleich sind. Das heißt gleiche KI´s, (2 x Nizar und ich mit einem Verbündeten), gleiche Startpositionen und Gold 40k Computervorteil. In diesem Fall sollten die Wechselwirkungen nicht zu komplex ausfallen.

Unknown072	= 200
Unknown073	= 10

Auch ich vermutete eine Startrekrutierungstruppe, konnte mir aber nicht ausmalen welcher Paramter dafür in Frage käme. Ich habe auch die Einheiten ausgetauscht, aber auch da habe ich keine Auswirkungen feststellen können, ausser dass de Rekrutierungsreihenfolge sich damit ändert. Er beginnt immer mit Def, dann mit Att und eventuell mal mit Raid (im dritten Versuch kam Raid nicht mehr vor).

Ich werde das mal so bald wie möglich austesten mit den verschiedenen KI´s und unknown073 auf 1 gesetzt und berichten.

------------------------------------------

AICharacter
{
	Index	= 13
	Name	= Nizar
	Personality
	{
		Unknown000	= 10
		Unknown001	= 0
		Unknown002	= 0
		Unknown003	= 0
		Unknown004	= 1
		Unknown005	= 1
		CriticalPopularity	= 4500
		LowestPopularity	= 5000
		HighestPopularity	= 9000
		Unknown009	= 2
		Unknown010	= 12
		Unknown011	= 10
		Farm1	= WheatFarm
		Farm2	= WheatFarm
		Farm3	= WheatFarm
		Farm4	= HopFarm
		Farm5	= None
		Farm6	= None
		Farm7	= None
		Farm8	= None
		PopulationPerFarm	= 3
		PopulationPerWoodcutter	= 7
		PopulationPerQuarry	= 20
		PopulationPerIronmine	= 10
		PopulationPerPitchrig	= 15
		MaxQuarries	= 1
		MaxIronmines	= 2
		MaxWoodcutters	= 12
		MaxPitchrigs	= 1
		MaxFarms	= 16
		BuildInterval	= 1
		ResourceRebuildDelay	= 20
		MaxFood	= 100
		MinimumApples	= 10
		MinimumCheese	= -1
		MinimumBread	= -1
		MinimumWheat	= 5
		MinimumHop	= 5
		TradeAmountFood	= 10
		TradeAmountEquipment	= 0
		Unknown040	= 12
		Unknown041	= 30
		Unknown042	= 30
		MaxWood	= 50
		MaxStone	= 40
		MaxResourceOther	= 10
		MaxEquipment	= 4
		MaxBeer	= 10
		MaxResourceVariance	= 4
		Unknown049	= 100
		BlacksmithSetting	= Swords
		FletcherSetting	= Bows
		PoleturnerSetting	= Spears
		SellResource01	= None
		SellResource02	= None
		SellResource03	= Iron
		SellResource04	= None
		SellResource05	= None
		SellResource06	= None
		SellResource07	= None
		SellResource08	= Bows
		SellResource09	= Crossbows
		SellResource10	= Spears
		SellResource11	= Pikes
		SellResource12	= Maces
		SellResource13	= Swords
		SellResource14	= LeatherArmors
		SellResource15	= IronArmors
		Unknown068	= 2
		Unknown069	= 3
		DefSiegeEngineGoldThreshold	= 100
		DefSiegeEngineBuildDelay	= 4
		Unknown072	= 200
		Unknown073	= 10
		RecruitProbDefDefault	= 98
		RecruitProbDefWeak	= 98
		RecruitProbDefStrong = 98
		RecruitProbRaidDefault	= 1
		RecruitProbRaidWeak	= 1
		RecruitProbRaidStrong	= 1
		RecruitProbAttackDefault	= 1
		RecruitProbAttackWeak	= 1
		RecruitProbAttackStrong	= 1
		SortieUnitRangedMax	= 0
		SortieUnitRanged	= None
		SortieUnitMeleeMax	= 0
		SortieUnitMelee	= None
		DefDiggingUnitMax	= 0
		DefDiggingUnit	= None
		RecruitInterval	= 1
		RecruitIntervalWeak	= 1
		RecruitIntervalStrong	= 1
		DefTotal	= 50
		Unknown093	= 1
		Unknown094	= 1
		Unknown095	= 1
		DefWalls	= 0
		DefUnit1	= Assassin
		DefUnit2	= None
		DefUnit3	= None
		DefUnit4	= None
		DefUnit5	= None
		DefUnit6	= None
		DefUnit7	= None
		DefUnit8	= None
		RaidUnitsBase	= 50
		RaidUnitsRandom	= 0
		RaidUnit1	= Slinger
		RaidUnit2	= None
		RaidUnit3	= None
		RaidUnit4	= None
		RaidUnit5	= None
		RaidUnit6	= None
		RaidUnit7	= None
		RaidUnit8	= None
		Unknown115	= 190
		Unknown116	= 0
		Unknown117	= 0
		Unknown118	= 0
		Unknown119	= 0
		Unknown120	= 0
		Unknown121	= 0
		Unknown122	= 0
		RaidCatapultsMax	= 0
		Unknown124	= 4
		AttForceBase	= 50
		AttForceRandom	= 0
		Unknown127	= 10
		Unknown128	= 50
		Unknown129	= 100
		Unknown130	= 0
		Unknown131	= 5
		Unknown132	= 50
		SiegeEngine1	= Catapult
		SiegeEngine2	= None
		SiegeEngine3	= None
		SiegeEngine4	= None
		SiegeEngine5	= None
		SiegeEngine6	= None
		SiegeEngine7	= None
		SiegeEngine8	= None
		Unknown141	= 10000
		Unknown142	= 0
		AttMaxEngineers	= 0
		AttDiggingUnit	= None
		AttDiggingUnitMax	= 0
		AttUnit2	= None
		AttUnit2Max	= 0
		AttMaxAssassins	= 0
		AttMaxLaddermen	= 0
		AttMaxTunnelers	= 0
		AttUnitRangedPush	= None
		AttUnitRangedPushMax	= 0
		Unknown153	= 0
		AttUnitBackup	= None
		AttUnitBackupMax	= 0
		Unknown156	= 0
		AttUnit5	= None
		AttUnit5Max	= 0
		AttUnitSiegeDef	= None
		AttUnitSiegeDefMax	= 0
		Unknown161	= 0
		AttUnitMain1	= slave
		AttUnitMain2	= None
		Unknown164	= 0
		Unknown165	= 0
		AttMaxDefault	= 200
		Unknown167	= 4
		TargetChoice	= Closest
	}
}

**Comment by Krarilotus** [comment]
@veryfriendly du kannst übrigens folgendermaßen KI-Mensch Karten erstellen (also Karten wie meine AI-Contest map, auf der du gleichzeitig spectator bist und für die KI gebäude platzieren und truppen rekrutieren und evtl sogar steuern kannst:

- Nimm dir Karte X die du modifizieren willst
- Nimm irgend eine Karte Y
- spiele Karte Y mit Zuschauermodus aktiv
- speichere das Spiel auf karte Y
- bennene die sav von Karte Y zu map um
- starte Crusader neu
- Nun öffne den Karteneditor:
- lade map die das Save von Karte Y ist
- gehe in die Karte und wähle Spieler 1 aus
- gehe aus der Karte raus ohne zu speichern
- lade Karte X
- gehe in die Karte wähle spieler 1 aus
- gehe zurück und speicher die Karte unter einem Namen deiner Wahl neu ab
Wollah, Zuschauermodus mit Aktiver KI beobachtung für die erste KI erstellt

**Comment by Krarilotus** [comment]
@velyfrendly ich habe gerade bemerkt, dass im Patcher ja die Option: Verstärkung der Burgverteidigung in bugfixes immer aktiv ist, vll mal den Haken rausnehmen, neu testen. Wenn ich etwas zeit hab schaue ich mir das auch nochmal an.

**Comment by velyfrendly** [comment]
@Krarilotus 

Cooler Trick. ich bleib aber bei dem Schritt lade Karte X im Editor, hängen. 
Indem ich die Karte x ins Verzeichnis Maps verschiebe, wird sie leider nicht auffindbar im Editor, oder mache ich etwas falsch?

Das funktioniert scheinbar nur mit Maps, die selbst erstellt sind, dafür müsste ich zunächst aber erst mal eine Karte x erstellen..??

**Comment by Krarilotus** [comment]
wenn du keine karte hast die du erstellt hast, sondern eine der originalkarten, dann nutze den map unlocker um die map zu unlocken...
Gibts hier auf heavengames:
http://stronghold.heavengames.com/downloads/showfile.php?fileid=6834

Ich würde an deiner stelle eine Karte erstellen die leer ist mit 8 keeps und alle keeps durch highground getrennt. Das geht super schnell (2 Minuten)

**Comment by velyfrendly** [comment]
@Krarilotus 

Danke dir, hat geklappt mit der Map. Dabei ist mir bei einem Test aufgefallen, dass Unknown009 und 010 wie du schon erwähntest mit den Steuern zu tun hat. Die 10 steht für die maximale Steuerstufe nach oben, was ich bestätigen kann, aber die 009 steht für die Untergrenze.

Stufen 0-11

BSP: 
009 = 0
010 = 5
Er pendelt zwischen +7 und -4 hin und her. Das ist dann sein Spielraum zum anpassen der Beliebtheit. Dabei ist mir aber aufgefallen, dass die KI unabhängig von der Steuerunter- und Obergrenze die Steuern immer auf +3 setzt, sobald er die kritische Beliebtheit unterschreitet. Ausprobiert habe ich das mit Ratte und Saladin. Weiterhin gibts doppelte Rationen beim Unterschreiten der kritischen Beliebtheit, bis er wieder die niedrigere Beliebtheit erreicht. Ab da an gibts nur noch Extra Rationen, bis die hohe Beliebtheit erreicht wird. Von da an gibt es nur noch normale Rationen, vorausgesetzt der Kornspeicher wird nicht schon viel früher durch 042 auf doppelte Rationen angesetzt. Außerdem wird beim Unterschreiten der kritischen Beliebtheit alles auf dem Lager bis auf  25% von der Summe der maximalen Mengen+ Ressourcenvarianz verkauft.

Die Infos nur so nebenbei, falls sie nicht schon bekannt sind oder wen interessiert :D

**Comment by Krarilotus** [comment]
@velyfrendly 
Woher nimmst du diese seltsame Annahme mit der Untergrenze?
Setz doch mal 010 auf 11 und 009 auf 10, du wirst sehen dass er immer von -20 auf +7  hin und her springt. Er geht immer auf +7, wohingegen er bei 0 oder 1 langsam schritt für schritt die stufen anpasst. (bei 0 macht die KI bei vielen werten was sie will, siehe 0 population per farm, wenn du 0 farmen angibst, baut er trotzdem farmen!) Das hat nix mit critical popularity zu tun. Die kannst du ja mal auf 0 setzten und dann lowest pop auf 20 und highest pop auf 98 oder so. Dann siehst du wie er die steuern umstellt. Aber ich werd es nochmal resteten wenn ich aufwache um deine Vermutung dazu zu belegen oder widerlegen, kann ja auch sein dass ich mich irre?!


Zu Ranged Sortieunits: warum werden immer mindestens 20 gebaut? Liegt das auch an dem haken in deff? Wenn man 0 einstellt werden trotzdem 20 Armbrustschützen gebaut wenn Armbrustschützen dort eingestellt wurden. Was bringt einem dann ranged Sortie max wenn es nicht wirklich max ist?
Vll das umbenennen in Ranged Sortie minimum, da man ja z.b. den Wert auf 100 stellen kann und er die dann nur aussendet wenn er mindestens 100 hat.

**Comment by ByBurton** [comment]
@Krarilotus nur weil die KI bei dir bei dem Wert 0 bei farms per population noch welche baut musst du nicht gleich davon ausgehen das das generell so ist.
Und ja,bei manchen Werten trifft es zu aber nicht bei farms oder andere resourcengebaude per population. 
Du musst übrigens diesen Wert auf 0 setzen nicht den maxfarms. 
Und Ausfalleinheiten werden auch unter dem threshold ausgebildet.

**Comment by Krarilotus** [comment]
> @Krarilotus nur weil die KI bei dir bei dem Wert 0 bei farms per population noch welche baut musst du nicht gleich davon ausgehen das das generell so ist.
> Und ja,bei manchen Werten trifft es zu aber nicht bei farms oder andere resourcengebaude per population.
> Du musst übrigens diesen Wert auf 0 setzen nicht den maxfarms.
> Und Ausfalleinheiten werden auch unter dem threshold ausgebildet.

@ByBurton ja genau :)
Nicht wert 0 bei farms per population sondern max farms. Der Wert, der eigentlich die maximalen farmen bestimmt. Dadurch sollte der farms per Pop wert ja wenn man einer inherenten wörtlichen Logik folgt, hinfällig sein. Insbesondere da farms per pop ja bedeuten würde mit 0 hebt man die Begrenzung aus daher bau unendlich viele farmen unabhängig von der Bevölkerung.
Es wäre gut sowas einfach irgendwie aufzunehmen im das Wiki oder allgemeine Infos.

Ausfalleinheiten im Allgemeinen nicht, bloß die ranged werden bis zu 20 wenn man z.B. von Armbrustschützen ausgeht ausgebildet, egal was das threshhold ist. Damit ist es kein Threshold mehr. Das wäre niir eins, wenn es auch etwas logisch begrenzen würde.
Aber das soll ja keine Kritik sein, eher ein Vorschlag die Beschreibung so zu ändern, dass sie dem Wert entspricht, und was er actually macht. 

Die KI baut auch gerne mal, nachdem sie ihre Ausfallrinheiten vorne verbraten hat, wenige nach und schickt sie zum Sammelpunkt wo bis eben noch die restlichen standen. Der Gesamtwert ist erst bei irgendwas über 20 durch dieses Raidunitsmax begrenzt und den ersten Ausfall macht sie erst, wenn sie mindestens Raidunitsmax hat, was eher Raidunitsmin bedeuten würde.

**Comment by ByBurton** [comment]
Ähm, nein?
Durch 0 teilen geht nicht und ich würde davon ausgehen, dass dann keine Farm gebaut werden kann.
Also merk dir einfach PerPopulation auf 0 setzen wenn du was deaktivieren willst, nicht das max.. Sieht man auch bei vanilla Phillip.

Das mit den Ausfalleinheiten kann ich so in etwa glauben und evtl. bestätigen. Aber müsste erst testen. Aber warum schreibst du RaidUnit wenn wir über Ausfalleinheiten sprechen?

Im Grunde wegen Beschreibungen und so zu mir kommen. Ich kümmere mich da drum..

**Comment by Krarilotus** [comment]
Ups: My mistake, ich meinte Sortieunit.
@ByBurton Ich weiß das doch. Sorry, ich glaub ich hab vll es nicht ganz klar ausgedrückt: es geht mir nicht darum dass ich das mir merke. Mir gehts eher darum, dass neue Modder die das benutzen, durch den Beschreibungs Eintrag alle Infos kriegen, die sie für das Verständis der Logik der Parameter brauchen.

Zum Beispiel mit den Farmen: 0 Population per farm hieße mit der aktuellen Beschreibung heißt nicht dass ich durch 0 teile, sondern dass ich lediglich 0 extra Population brauchen würde, um eine neue Farm zu bauen. Nach der Logik würde man also beliebig Farmen setzen bis Maximum an Farmen erreicht ist, sollte der Wert 0 sein.
Ich schlage daher folgende Beschreibung vor, für alle Ressourcebuilding per pop Variablen:
The current population count is devided by this number, rounded up to determine the amount of <ressourcebuilding> the AI is going to build.

Es geht hier nur um die wörtliche Logik der Beschreibung. Tut mir leid, vielleicht ist's auch für andere schon verständlich. Ich bin manchmal etwas genau... Mathematiker Angewohnheit ^^

**Comment by velyfrendly** [comment]
@Krarilotus

Also das war meine Beobachtung beim ändernvon 009 und 010.

Setze ich 009 auf 0, so verschenkt er Geld bis +7, bei 1 bis +5 und bei 2 bis +3, immer wenn ich den Kornspeicher abreisse und durch ne Mauer verhindere, dass er neue baut. Er versucht damit dem Abwärtstrend der Beliebtheit entgegen zu wirken. Nun setzt er aber unabhängig davon welcher Wert für 009 eingestellt ist, die Steuern immer auf +3 rauf bzw runter, wenn die kritische Beliebtheit erreicht war. Der lag sowohl bei Ratte sowie Salasdin bei 40.

042 war bei mir auf 500 gesetzt, so hat er niemals doppelte Rationen allein aufgrund der Nahrungsmenge vergeben. 

Dann habe ich die Mauer entfernt und er konnte wieder den Kornspeicher bauen. Er vergibt unterhalb der CriticPop doppelte Rationen und munder die maxLagermenge+Varianz auf 25%. Beim überschreiten der lowestPop wechselte er dann zu Extra Rationen und beim überschreiten der criticalPop zu  normalen Rationen.

**Comment by Krarilotus** [comment]
@velyfrendly 
> Ich werde nachher gern mal wieder testen. Dann können wir die Ergebnisse mal vergleichen.

Ok, vielleicht hast du Recht, ich sehe da einen Trend der mir entgangen ist. Ich hab grad noch keine Zeit zum testen, daher nachher, aber kannst mich auch gern in Discord anschreiben :)
Krarilotus#6749

**Comment by velyfrendly** [comment]
Wie nutzt man dieses Discord ? ^^ Kenn mich da nicht so aus.

Hatte noch keine Zeit zum Testen aber ich glaube ich kann mir deine Beobachtung erklären, weshalb er mit 009=10 und 010=11 zwischen -20 und +7 hin und her switcht. Müsste die Steuer bei Stufe 11 nicht bei -24, statt -20 liegen?

Für Steuerstufe 10 und 11 für 009 und 010 stelle ich mir das wie folgt vor. Er wechselt im Normalfall zwischen -20 und -24 hin und her. 
Bei -20 (Untergrenze 009 = 10) erhöht er aber nicht mehr weiter, sondern setzt die Steuer als Reaktion auf die massive Unbeliebtheit auf +7 (Hier wirkt vermutlich irgendein Befehl im Code, sowie die +3 beim Unterschreiten der criticalPop, die ich weiter oben erwähnt hab). 

In diesem Sinne, dann bis später..

**Comment by ByBurton** [comment]
Ich habe extra einen Channel der zum Besprechen von Variablen ist.
https://discord.gg/qdCcmR

**Comment by velyfrendly** [comment]
There are two Things i would like to changed, if possible.

1. Only ArabArcher can set up fire to the Pitch Traps. So AI that receuits europArcher only, cant set up fire. 

2. For AI the maximum of Wheat at stockpile is limited by the variable maxFood, which doesnt make sense. That is why saladin for example saves up little food, otherwise his stockpile gets full of wheat. Maximum of wheat should get limited through the variable maxRessourceOther like iron, flour, pitch..

**Comment by ByBurton** [comment]
@velyfrendly There's already a separate issue for your first point. #172 
And 2 is probably too complex and / or too time consuming.

**Comment by Krarilotus** [comment]
i think this has been solved, but reopen if you want to and think otherwise!
