### ISSUE TITLE
hotkey

### ISSUE THREAD

**Issue by Krarilotus** [Sh0wdown/UnofficialCrusaderPatch#430]
As i noticed, default settings is to overwrite the hotkey for the armory (A), and also messes up the writing in the Map editor, when you try to edit the maptext. WASD moving the cursor while writing makes it a pain.
So i suggest turning that off for default settings.

Maybe as it has to do with hotkeys, might it be possible, to change existing hotkeys with a config file?
And maybe even add a hotkey for the 'Greatest Lords' screen, which could be very neat to pull up? Aswell as the Stockpile?

Thank you for having me :D

**Comment by GRhin** [comment]
hotkey for Greatest Lords screen is a great idea

**Comment by Sh0wdown** [comment]
Okay, it's not set as a default setting from now on.

> Maybe as it has to do with hotkeys, might it be possible, to change existing hotkeys with a config file?
> And maybe even add a hotkey for the 'Greatest Lords' screen, which could be very neat to pull up? Aswell as the Stockpile?
That's possible but takes some effort, I suggest you create a separate issue for this though.
