### ISSUE TITLE
config

### ISSUE THREAD

**Issue by Krarilotus** [Sh0wdown/UnofficialCrusaderPatch#431]
The UCP Config is a great way to give settings set on your own PC to other players. I would like to have the option to actually use that feature. So i request, not completely resetting the config values, when selecting a path or a language for the patcher. That way, everyone can use the same settings if using the same config, even if they operate on another PC or in another language.

**Comment by Sh0wdown** [comment]
Well, that was a bug, not a feature. Should be fixed in the next version.
