### ISSUE TITLE
Add a Hotkey

### ISSUE THREAD

**Issue by Krarilotus** [Sh0wdown/UnofficialCrusaderPatch#433]
The Hotkey that i always wanted: Open and close the 'Greatest Lords' Screen. It contains valueable information, especially for multiplayer. But it is so clunky to click on it while you micro your troops.

It would help alot to asign a Hotkey for that screen. My suggestion would be something near the tab hotkey, as that is the usual hotkey for other games to do just that. Maybe the ^ would work best?

**Comment by GRhin** [comment]
@Sh0wdown is there any chance of this?

**Comment by an-accident** [comment]
Just wanted to remind that cathedral doesn't have hotkey, too.

**Comment by Krarilotus** [comment]
Should be included in the hotkey config file.
#432
