### ISSUE TITLE
Patch on SHC EXTREME??

### ISSUE THREAD

**Issue by DzikiGoblin** [Sh0wdown/UnofficialCrusaderPatch#437]
Hello guys, recently I tried to install this patch on SHC extreme. I started sigleplayer with Ai quick and everything looked fine. I started the game on this patch with my friends (everyone had same configuration). At the beggining everything looked good but after some time we noticed taht some Ai don't develope their castle properly and the game fps'es were getting lower and lower until it was like 1 game speed but with big delay. Did you try this in extreme too? Any ideas? Would be cool if it work in extreme cus population cap in basic stronghold while playing with 2 friends and 5 AI's is really strange low.

**Comment by GRhin** [comment]
I can't give too much advice, however I have been playing extreme multiplayer for a couple weeks with ucp without issue, we used default setting and no magic bar, our maps did not have outposts, and we had up to 4 human players, with AI it was 1v1 with a custom ai that krarilotus created. I believe krarilotus has done more with multiple ais as part of his AI competition,  but again he does not use outposts. Maybe you could try a map without those and see if the issue continues.

**Comment by DzikiGoblin** [comment]
Me and my friends don't like outposts so I created my own map as you without outpost. We have set "Increased number of additional troops in another attacks", "Increased recrutation speed" and pick "Upgraded castles by user Tatha" also removed "Extreme edition". As I said above that the issue appeared in multiplayer but a few minutes ago I started singleplayer skirmish with AI and I had the same problem in early game (sth like 5 minutes after start). Fps'es went down and game was unplayable. I started new game on the same map and everything was OK so I loaded the previous game but fps'es were still low.

**Comment by GRhin** [comment]
Just to rule out unlikely possibilities, Have you tried uninstalling the UCP and seeing if it still happens?
What AIC are you using? Multiplayer should not be effected by this, but if you include any AIs at all it might be. I have briefly played with UCP-bugfix, and Krarilotus's Agressive AI, along with alot of play with a custom trainer AI Krarilotus created, all without issue
Is it just your custom maps that have the issue? Maybe you could try one of the maps we use for my stream (can download from my discord https://discord.gg/jvYANtp - its on the "grhins-multiplayer-maps" channel on the left sidebar) and see if it happens there. we have played all the maps there several times except for Devils Lair without issue. As I say, we played it while my computer was also uploading a stream so any slowdown would definately be noticed.
If none of that reveals the problem, Im afraid I am out of ideas. Maybe you could send me the save of the game that was having issues, along with your config file, on discord (you can find me on the server linked above, or GRhin 9114)

**Comment by DzikiGoblin** [comment]
Yes, we uninstalled UCP from extreme and were playing without this but the game without ucp is not that funny and challenging :/  I don't think my map cause issue because we were playing on it without ucp.  When it comes to AIC, I don't know exactly what this option  change but I have marked default "UCP-bugfix.aic". Don't have idea what "vanilla.aic". Btw I will contact you on discord.

**Comment by Krarilotus** [comment]
@DzikiGoblin it sounds to me, as if you had different versions of the patcher or of the game. Try to make sure, that your maps are in the same folder, as in User/Documents/Stronghold Crusader/MapsExtreme

Also what seems strange is, that you had the issue in singleplayer aswell. Did you load a game, after changing settings in the ucp? I would advice against changing setting in between playing the same map and game. If you want to make sure, that you and your friends use the same settings, send him your ucp.cfg file and both install the patcher before the game starts. Also tick the exact same boxes in the AIC section, as that setting will not be transfered with the ucp.cfg.

So yeah, try post the game versions that you play on here and maybe you can uplpad the map in a zip, then we can have a look!

I played against Rakso yesterday on a map GRhin created, where i put it into Stronghold Crusader (without Extreme). I have the wierd bug, that you cant replace or delete any maps you ever put in the Maps folder for Stronghold Crusader. Which is really frustrating. We played that game and it became clear, that my mapversion was still an old one, while he had displayed the updated version with different grasland. It was strange that the game even startet and it startet to lag soon after. The game became clearly too laggy and unplayable to enjoy and my farms i placed on the farmland that i saw on my map just disappeared while his farms seemed to be not even on oasis. @GRhin i mean Hindukush with the map, if you are curious.

So i dont know if some bug like that exists for Extreme for you too, as it does work fine with extreme for me. But it puts me off using SHC ever in Multiplayer. Tho make sure you create the map with normal SHC to be compatible with others, sometimes maps created with extreme suffer some strange behaviour too.

**Comment by Krarilotus** [comment]
@DzikiGoblin also, you could try to delete/rename the aiv folder entirely and create a new empty aiv folder before installing the patch with custom aiv's. But usually the patcher should handle the backup and replacement process just fine.

Also Steam could have reverted some of the files you patched to its original state, so make sure to upload your version to the steamcloud

**Comment by DzikiGoblin** [comment]
@Krarilotus We have the same version of the game cus it's steam version (we normally play together without UCP) and I we have the same version of UCP and we have the map in same folder which you stated above. But I don't think it is the case becuase today I discovered that UCP on extreme works on default game's maps with outposts. So sorry for additional effort.... It seems that my map cause the problems but don't have idea why. Should I create the map with installed UCP or without it? Also what change the "AIC" option? I have had marked UCP-bugfix.aic as default.

You said that I should send them my ucp.cfg file but how to install patch by using this file?

In refere to your last paragraph, do you mean that I should create all the maps in baisc crusader and move them to ExtremeMaps folder when I want to play extreme?

**Comment by DzikiGoblin** [comment]
Here is link to my map, ucp.cfg and bugged saves: https://www.mediafire.com/file/er3m5m2waxubsty/bug.rar/file

**Comment by GRhin** [comment]
regarding the ucp.cfg question. basically you install the patch with your preferred options, then copy the ucp.cfg file thats automatically created in the same directory as the patcher exe file, and send that to your friends. They put this ucp.cfg file in the same folder as their patcher exe file (overwriting an existing file if necasary), then run the patcher. All the options you had set should now be set in their patcher and they just need to click "install" .

**Comment by Krarilotus** [comment]
@DzikiGoblin i might check your map, when i get back at my PC.
For now, you might want to avoid creating maps with the extreme editor. You can also create outposts with the normal Crusader Editor. Copy the maps just from normal to extreme, and it works. 

I ve had multiple problems with the extreme editor and to me it seems bugged.

Regarding the config (ucp.cfg), it doesnt save the aic boxes ticked. This might be, because it reloads all your custom aic's when the patcher starts. So keep in mind checking, if you have both selected the same aic. If you use tathas castles, i d recommend using xander's or tatha's aic file, as they are optimized for those castles i suppose.

If you use vanilla castles, then you could also use my agressive aic file, it makes the AI take part in the game way more.

Also, next time you upload files, just attach them to your post here inside of a zip file. Thats way easier to follow than mediafire ^^

**Comment by GRhin** [comment]
@DzikiGoblin maybe #444 is the issue?

**Comment by Krarilotus** [comment]
no further problems have occured
