### ISSUE TITLE
More Description for fireproof duration setting

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#439]
HI,
In the new UCP version, under other, is a new setting "Extend fireproof duration of extinguished buildings"
The default value for this is 6000, im just curious as to what this value is, milliseconds? is 6000 - 1minute? though that would only be the case at a certain speed, so i guess its a random value that the game interprets as in-game seconds, or days maybe?
Not a big issue, just curious.

**Comment by Krarilotus** [comment]
I would like to know, what the vanilla valaue for that was

**Comment by ByBurton** [comment]
2000 dude. It says so if you disable it..
