### ISSUE TITLE
Lower amount of speeds (20, 40, 65, 90, 150, 300, 600, 1000)

### ISSUE THREAD

**Issue by Silentraz** [Sh0wdown/UnofficialCrusaderPatch#44]
In vanilla and moded version there is a lot of speeds, and everyone needs to click "+" separatly. It is a lot of clicking.

What about larger steps between speeds? As wrote in topic, speeds are 20, 40, 65, 90, 150, 300, 600, 1000.
And maybe before 20 add 5 or 1 to build little faster (AI is improved, but no lower speed as compensation)

**Comment by Monsterfisch** [comment]
I recommend playing more difficult missions, you will have a lot less of a need to speed up time in those ;)

**Comment by Silentraz** [comment]
Even on higher difficulty it is a lot of clicking. At start almost everytime need to lowest speed, little later - average, later - fastest as possible. And it is problem that I need many clicks to increase from 90 to 300. And after won battle - need again to click "-" 20-30 times. After rework- it will be only 4-6.
It will be very helpful in recruting. For example need to recruit 50 macemen. So speed is 90, clicked all, twice "+", speed is 300, so 24 new people generated fast. After that twice "-" and recruit all. And I have these 50 macemen. Nowadays it is not worth to click +/-.


As I saw - all changes are optionally, so if someone do not need - simply not install.
