### ISSUE TITLE
assasins still not visible?

### ISSUE THREAD

**Issue by Monsterfisch** [Sh0wdown/UnofficialCrusaderPatch#440]
So I checked out the update (thanks again for keeping the stone rolling I really appreciate you doing this showdown) and I can't seem to be able to see the assassins when using the spectator mode is anyone else having the same issue or is it purely on my end? (tried it on savegames and newly set up matches) if there is more info I need to provide hit me up.

**Comment by Sh0wdown** [comment]
I just tried the spectator mode with three Nizar AIs and they were visible for me.
![image](https://user-images.githubusercontent.com/9576090/62539158-d9a8e900-b854-11e9-8b40-3fcad43d931c.png)

**Comment by Krarilotus** [comment]
Actually this feature is perfectly implemented, i can see the assassins as a spectator, while i play with the AI. I would be able to targetfire them out of the normal vision range, but the AI still doesnt attack the assassins, unless they are in the old vision range, which makes all my contestmaps still balanced and viable for watching, while beeing able to interact with the AI's. Thats awesome!!!!

**Comment by Monsterfisch** [comment]
mhm I changed the colors back/used a fresh exe and still don't see the assassins https://i.imgur.com/GCApw8e.jpg

While applying the patch I do get this info panel.  https://i.imgur.com/EZZPnGv.png through I believe showdown you said that's nothing to worry about in the past if I recall correctly? I am using the English steam version of stronghold and version  https://i.imgur.com/fFcWJ0j.png Only thing I can think of is try it on a completely new install of the game but just wanted to make sure it's necessary first?
