### ISSUE TITLE
Created a new AI

### ISSUE THREAD

**Issue by GrosserBauerr2** [Sh0wdown/UnofficialCrusaderPatch#442]
Hello Guys i created a new AI for SHC. It s just a german version but completed with sound files, binks and ingametext.
You can check it out, https://github.com/GrosserBauerr2/Stronghold-Crusader-AI.
It uses the bad soldier, animations and also his unused soundfiles.

**Comment by GRhin** [comment]
Do you have English ingametext?

**Comment by GrosserBauerr2** [comment]
Not at the moment, but i can translate my inserts and put them in the english file, but i am not sure if the soundfiles are right translate form the englisch version to the german.

**Comment by ByBurton** [comment]
How is this an issue? There are already discussion threads for things like that, please post your stuff there. Going to close this.
