### ISSUE TITLE
 1 question plz help :)

### ISSUE THREAD

**Issue by ilosevsrat** [Sh0wdown/UnofficialCrusaderPatch#446]
i cant find script that changes "attack force increase"

i can do it trough "unofficial crusader patcher 2.13", bit i cant find this script when i open it with text editor.

help plz :)

**Comment by Krarilotus** [comment]
@ilosevsrat i would like to know, what you opened with your text editor and what you are actually trying to do?
Maybe then i can help you

**Comment by Sh0wdown** [comment]
Should be **ai_attacklimit** if you mean the entry in the configuration file.

**Comment by ilosevsrat** [comment]
> @ilosevsrat i would like to know, what you opened with your text editor and what you are actually trying to do?
> Maybe then i can help you

troop quantity that is increased with every attack.  (how much troops ai adds after every attack in his attack force)

**Comment by Krarilotus** [comment]
> > @ilosevsrat i would like to know, what you opened with your text editor and what you are actually trying to do?
> > Maybe then i can help you
> 
> troop quantity that is increased with every attack. (how much troops ai adds after every attack in his attack force)

Maybe detail what you are trying to acomplish?
I mean, you could just do that with the patcher?

**Comment by ilosevsrat** [comment]
> > > @ilosevsrat i would like to know, what you opened with your text editor and what you are actually trying to do?
> > > Maybe then i can help you
> > 
> > 
> > troop quantity that is increased with every attack. (how much troops ai adds after every attack in his attack force)
> 
> Maybe detail what you are trying to acomplish?
> I mean, you could just do that with the patcher?

patcher will increase attack force for all ai lords, and i want to increase that number for only one of them.

**Comment by Sh0wdown** [comment]
Sadly, Crusader does not work that way. The number is increased by the same amount for all lords.

**Comment by ilosevsrat** [comment]
> Sadly, Crusader does not work that way. The number is increased by the same amount for all lords.

crap :(

**Comment by ByBurton** [comment]
Can this issue be closed?
