### ISSUE TITLE
splitting aic characters in multiple aic files is no longer supported

### ISSUE THREAD

**Issue by Krarilotus** [Sh0wdown/UnofficialCrusaderPatch#448]
Heroesflorian just found out, that its no longer supported to put your ai arrays in different files and check multiple boxes under 'aic'. Thats a bummer, but maybe there is some reason behind it?
I would like to know, if we could have the feature at least available for selfmade AIC's. I see the point, that it makes no sense for AIC's that come with the patcher, but selfmade aic files are easier to handle, when splitting all AI's in different files sometimes, as it allows to swap single AI's simply by putting in the different checkbox.

Hope we can have that for the next update,
greetings Krarilotus

**Comment by Heroesflorian** [comment]
Indeed, very unpleasant... guess I'll also re-open this older issue, as currently the feature isn't there (or not working) anymore: https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/350

**Comment by ByBurton** [comment]
You can copy them into one file for now.

**Comment by Krarilotus** [comment]
@ByBurton yeah, but that means a new file for each setup.
Just for example if i had 3 versions of the wolf, 3 of the pig and 3 of the rat, that would already result in 27 files instead of 9.
growing exponentially for more characters and designs. but yeah, its just the way to go right now, hopefully getting back to the way it was for custom aic's not coming with the patcher at least :D

**Comment by ByBurton** [comment]
That is why I wrote "for now". This is obviously just a "make do" suggestion. Ofc this needs to either be fixed or reintegrated in a different way.

**Comment by Sh0wdown** [comment]
Oh yeah, sorry for that unlisted change. I did it so people don't get confused by activating multiple .aics.
A new AIC+AIV interface is planned anyway.

**Comment by ByBurton** [comment]
@Sh0wdown If I can help you with that just be sure to let me know, okay? 👩

**Comment by patel-nikhil** [comment]
This was completed in PR #534 and added features are in PR #551 that just needs testing. I think this issue can be closed now.

**Comment by GRhin** [comment]
Not until its officially released.

**Comment by GRhin** [comment]
Can be closed with new release
