### ISSUE TITLE
Question about the removed no recruit sleep feature

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#449]
If I understood that correctly, the AI was supposed to recruit siege units while the current siege army was already attacking. Which would have been awesome. 
Problem was, that the AI sent the newly recruited units right to the enemy if I understood that correctly.
Is there a way to fix that? 
I think the feature would have been really cool. 
(Or to quote your code comment: 

> // disable sleeping phase for AI recruitment during attacks
    // this is no good, because the AI sends newly recruited troops instantly forth
    // while an attack is still going on, ending in streams of single soldiers

)

**Comment by Sh0wdown** [comment]
I tried to make the AI recruit troops while attacking with that change. But it seems to be very difficult since the AI is coded to always only have one attack force at a time.

**Comment by ByBurton** [comment]
Hm. Can you somehow make the AI prepare a second attack instead of adding the soldiers to the existing siege force?

**Comment by Sh0wdown** [comment]
That's exactly what I tried. It's not possible without lots of effort.

**Comment by ByBurton** [comment]
Okay, then I'm closing this for now. Thank you.
