### ISSUE TITLE
Ideas for new AI lords

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#45]
Discussed this in another 'issue' briefly but decided it would better discussed in its own 'issue'. Now that it may be possible to change the AI behaviour, that raises the hope that eventually it may be possible to make a new AI lord: here some ideas:

1. ByBurton mentioned this, but Robin Hood would be great as an AI character, according to legend he took part in the Crusades and with the Sheriff of Nottingham an AI character it would be apt to have his enemy there too. Both bandit videos on the invasion scenarios could be used for him as well, he would be the one with the green hood! Robin Hood would mostly use archers of course but to make him more unique as an AI lord, he could use some tunnelers for melee combat, they are quite fast to go with the archers, better than spearmen and also fit in with Robin's bandit personality with their appearance and makeshift use of picks as weapons. Of course a few of them can dig tunnels in sieges.

2. As I have mentioned before on here, I think bringing back Lord Woolsack from Stronghold 1 would also be good, specialising in pikemen (to counter his old rival Sir Longarm's knights 😃), he would send big groups of about 20 or 30 pikemen across the map in his raids to destroy enemy quarries and farms, but wouldn't do his main sieges until he had a lot of troops as he is a careful strategist. For his main sieges he would send pikemen, archers and monks, monks because he would use religion as part of his economy and also because he kind of sounds and looks rather like a monk so would fit with his personality.

3. Finally having a female AI character would be excellent for Stronghold Crusader though. Perhaps the Queen from Stronghold 2 could be introduced, in Stronghold 2 she was quite strong compared to most of the AIs, using a mix of horse archers, berserkers (which could be turned into macemen for Stronghold Crusader) and swordsmen. Macemen and horse archers would be an incredible combination for an AI siege I think, maybe she could use those in sieges in Stronghold Crusader, with swordsmen for defensive purposes.

**Comment by brooklynzsmac** [comment]
There are soundfiles saying "A message from the Boar" and "A message from the Hog" unused, found in the game files.

**Comment by brooklynzsmac** [comment]
Also, there are unused sound assets for characters titled "bad_arab" and "bad_soldier", also bink files for "good_soldier" (halberdier from historical campaigns"

**Comment by PitchNeeded** [comment]
> There are soundfiles saying "A message from the Boar" and "A message from the Hog" unused, found in the game files.

Those were used for the third mission of the Crusader States campaign I think, where you had to fight against the Truffe brothers, 'The Hog' and the 'Old Boar', which were both just The Pig of course!

**Comment by brooklynzsmac** [comment]
> 
> 
> > There are soundfiles saying "A message from the Boar" and "A message from the Hog" unused, found in the game files.
> 
> Those were used for the third mission of the Crusader States campaign I think, where you had to fight against the Truffe brothers, 'The Hog' and the 'Old Boar', which were both just The Pig of course!

Nope, they remain unused, I played this mission many times.  Hog and Boar are mentioned in the brief though. BTW. "Hog" could even mean "Hedgehog".

**Comment by Sh0wdown** [comment]
As much as I would like new AIs, it's probably not gonna happen in this patch, since the AIs seem way too hardcoded.

**Comment by Lolasik011** [comment]
I think you can only make Lord Woolsack as he has a video and audio track and icons.
