### ISSUE TITLE
Verbindungsprobleme via IP Multiplayer

### ISSUE THREAD

**Issue by LeChap** [Sh0wdown/UnofficialCrusaderPatch#455]
Hey,

mein Kumpel und ich wollten gestern den Patch im Multiplayer (LAN via IP) ausprobieren und es kam immer wieder oben das Fenster "Verbindungsprobleme", gepaart mit 1-4sek Lag, aber es erscheint immer nur so kurz das man es erst nicht erkennt, erst nach 5min als das Spiel dann aus selbigem Grund beendet wurde wussten wir was Sache war.
Wir hatten beide den Patch installiert (beide Crusader HD via Steam, also 1.41) und dieser hat an sich auch funktioniert, die KI war deutlich stärker.

Vor dem Patch und nach deinstallieren des Patches traten keine derartigen Probleme auf.
Hat wer eine Ahnung woran das liegen und wie man es fixen könnte?

**Comment by Starshine575** [comment]
Hey @LeChap 👋
Bin kein Experte aber das kann vielleicht damit zu tun haben, dass ihr beide Unterschiedliche Einstellungen im Patcher verwendet habt (wobei ich nicht sicher bin, on das Spiel dann überhaupt startet 😂).
Solltet ihr aber beim nächsten mal unbedingt beachten ✌️

**Comment by Krarilotus** [comment]
Questions has been solved
