### ISSUE TITLE
Having errors while editing the AIC

### ISSUE THREAD

**Issue by Admiral-Gumpert** [Sh0wdown/UnofficialCrusaderPatch#456]
Hello everyone ! 
I was trying to edit the AIC as I always do normally , But,,
I faced an error which says : "Input string was not in a correct format"
Now look , here's the thing :
This error shows up whenever there's an incorrect parameter format , for example you are setting an attack type for a character and then you type (100) instead of (weakest ,nearest ,etc.. )
And this error only shows up when I edit the line "AttUnitMain3" AKA "Unknown164" 
Wiki says that this undefined line is actually the "Main attacking unit 3" so I wrote "Spearman" as an example but this error showed up , Whenever I change this to a number the error disappears and everything is back to normal !
Could this be a wrong information ? or do we need a newer version of the patcher 

Thank you!

**Comment by Admiral-Gumpert** [comment]
![Untitled](https://user-images.githubusercontent.com/50601775/64974033-b9893280-d8b4-11e9-99e6-6fe59478cc58.jpg)

**Comment by ByBurton** [comment]
Are you using the latest version?
Also you are not using the latest version of the aic file dude. Because Unknown164 does not exist anymore.

**Comment by ByBurton** [comment]
Did you update the aic files with the updater?

**Comment by ByBurton** [comment]
@Admiral-Gumpert could you please upload your aic file here so I can take a look at it?

**Comment by Admiral-Gumpert** [comment]
Yeah sure I will upload it here

**Comment by Admiral-Gumpert** [comment]
[vanilla.TXT](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/3621571/vanilla.TXT)

**Comment by Admiral-Gumpert** [comment]
I just changed the extension to TXT so I can upload it here ,
And by the way I didnt know there was a newer version of the patcher , could you please send me the link? This might fix the problem

**Comment by Admiral-Gumpert** [comment]
Dont mind , I found the latest release , Thank you for your Time :)

**Comment by ByBurton** [comment]
@Admiral-Gumpert Can I close this? 💃

**Comment by Admiral-Gumpert** [comment]
Yes , No problem
