### ISSUE TITLE
Will Firefly ever share the source code?

### ISSUE THREAD

**Issue by AnonimusXD** [Sh0wdown/UnofficialCrusaderPatch#457]
What are the chances that Firefly will ever make the source code available? This game has great potential and can be easily turned into way better and harder game, but these changes would be probably impossible just by modifying .exe values.
For example, bigger maps, AIs calculating distance includes terrain, AIs repairing damaged turrets and gatehouses, recruiting more defense units of the same type (currently there is a limit I think) to a certain value, depending on how strong enemy is. Smarter quarry, ox tetcher, iron mine and farms placement. Calculating distance from nearest enemy fortification so they can place siege engines in safer places before engineers die, also sending heavy units like swordsman first and waiting for them to come nearer enemy before they send archers, so they dont die too fast, etc.
We just need source code. I wonder if Firefly even cares about this mod, maybe they can help us a little bit? Has anyone tried to communicate with them?

**Comment by GRhin** [comment]
No they wont share the code, I've asked.

**Comment by ByBurton** [comment]
No.
