### ISSUE TITLE
Monks mod

### ISSUE THREAD

**Issue by Admiral-Gumpert** [Sh0wdown/UnofficialCrusaderPatch#458]
I just wanted to share this file 
[body_fighting_monk.zip](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/3625875/body_fighting_monk.zip)
Monk's appearance seems a bit (colorless) that you even may not see the difference between a yellow or a blue monk , This file has some various colors for his staff , (Will at least help identify them) 
![Monk](https://user-images.githubusercontent.com/50601775/65141622-a9d72e80-da19-11e9-90b6-6773818a4f47.jpg)

Just extract this file into your "gm" folder

**Comment by GRhin** [comment]
That's good thinking, thanks for the work. Another thing you could change colors of is his belt.

**Comment by PodeCaradox** [comment]
Did you do your work with the Gm1Converter from me, if yes im happy to see people start using it :)

**Comment by Admiral-Gumpert** [comment]
Actually I started to work on his belt color before , but I figured this out by coincidence ,
I dont know if someone actually saw this before but the monks in Stronghold 1 appear to have different staff colors(same as the one above)

**Comment by PodeCaradox** [comment]
yea they have diffrent colors because they use diffrent colottables. There are 10 color tables with 256 colors each and color table 2-9 are the player colors the other 2 are for animals etc.

**Comment by Admiral-Gumpert** [comment]
I just wanted to tell you that in all of sudden the convertor stopped working unfortunately , Can you give me a link to download it again and if I need to do something after downloading it? Much appreciation

**Comment by PodeCaradox** [comment]
Here is the link just follow the guide on the Page: https://github.com/PodeCaradox/Gm1KonverterCrossPlatform
