### ISSUE TITLE
Great to find this community

### ISSUE THREAD

**Issue by forestleaves** [Sh0wdown/UnofficialCrusaderPatch#462]
Hi,I am a Chinese player.So excited am I to discover this place that remains the Crusader lovers.We have a no small group which has a lot of aiv makers.If we have a chance,We would be very delighted to communicate with you.
Thanks for your hard work and UCP.
![-2f45c0023a12a18e](https://user-images.githubusercontent.com/56231719/66273419-421b4300-e863-11e9-9bff-b74af6e54fe3.png)
![-be44accc833ca08](https://user-images.githubusercontent.com/56231719/66273420-421b4300-e863-11e9-8ae6-8de85f13129f.png)

**Comment by ByBurton** [comment]
Welcome to the western lands I guess ;D

**Comment by forestleaves** [comment]
I think our group has large amount of different AIVs.We discover some powerful way to improve the aivs,suring that it must be difficult to destroy the ai's castle.If possible,we can exchange our aivs to find the difference between us and even have a chance to hold a match.(we have more than 15 aiv makers)

**Comment by Lolasik011** [comment]
@forestleaves can you give us a link to your AIV?

**Comment by Krarilotus** [comment]
@forestleaves: For all you AI designers out there, i invite you to take part in the AI Design Contest, it is still running until end of October.
You can check all the instructions out in the videodescription of this Video:
https://www.youtube.com/watch?v=SOOG1bKbVKM

**Comment by cjp-luany** [comment]
Nice to meet you! I found this project last month and introduce to Chinese friends . We have some   very wonderful discoveries in the Aiv Editor about building walls in one second. Also we invented some structure to avoid arrow close to 99 percent(can't hurt unit in this structure by archer). We found some way to build walls that make HorseArcher can't attack the unit on that wall . As you can guess we make many wonderful things and very happy to meet who are interesting either.

**Comment by Krarilotus** [comment]
Nice inventions, tho i believe they were already known 6 years back in the Stronghold Heavengames Community. There might be even big summary papers sticking around the Stronghold Crusader Modifications Download Section :)
(As far as i know there are 2 main types for the Arrow safe units: crenels in front of stairs, or High towers in front of wall or lower towers, but the high tower method has still holes for some arrows coming threw!)
If you find any solution in making trebuchet safe castle design, let us know!
Feel free to post anything you know so far, or take inspirations by others. It never hurts to keep innovating!

If you want, you could take a look at this mega project, where most of the castle is build by multiple AI's:
https://www.youtube.com/watch?v=ZqM81sr4HwA

**Comment by cjp-luany** [comment]
We use  'Arrow safe units' to safe Fbal ,we put Fbal on the stairs and make it arrow safe by towers. Also we found something about towers which can make more fun. We found bug in the Aiv Editor and use it. Maybe you can see the following video and guess some.
https://www.bilibili.com/video/av63850675

Also this the collections of videos ,we make aiv competition games either.
space :  https://space.bilibili.com/87155277/
videos:  https://space.bilibili.com/87155277/video

Vpn maybe need to see above those.

**Comment by Krarilotus** [comment]
Ok i ll look into it :D
Which bug do you mean in the AIV Editor?
Ive made a video describing some tricks for the AIV Editor. I guess molding is the important part for the onesec wall trick.
Fireballistas on walls is a onetime thing unfortunatly, as they will be not rebuild after they got crushed by catapults or such things.

Thank you for the contribution! I ll look forward for more :D
And for your entry in the AI Design Contest

**Comment by cjp-luany** [comment]
Molding maybe just half way to onesec wall trick. There are other ways, more than three. But my friends want to keep it a little secret temporarily right now :D .Maybe we can begin with AIV and AI Design communication and have fun :D

**Comment by cjp-luany** [comment]
Another video link of onesec wall trick, we make it build easy and irregular, also fast enough.
https://www.bilibili.com/video/av58062436

**Comment by Krarilotus** [comment]
I d like to see the actual buildstep, tho it wasnt shown :(
But i believe you to have such a trick up your sleve.
So will you be taking part in the AI Design Contest? :D
It involves using the UCP too tho! So maybe you want to get familiar with the values it provides for modding your AI's

**Comment by forestleaves** [comment]
Aha,really,the video is made by our contest hoster,and the aivs in the video are designed by different designer,no one person.

**Comment by Krarilotus** [comment]
What are the criteria? 
Is there an english translation of your contest?

In my Contest, the criteria are a variaty of challenges for the AI, no human interaction, just randomnumbers from different games obviously and pure script :)
In the Contest you have one AI that has 4 challenges:
1. Challenge is to make a lasthit on an enemy AI
2. Challenge is to grind the most gold out of the AI's that are also on the same map
3. Challenge is for your AI to survive 12 ingame Years
4. Challenge is to win a Free for all under 50 Years

and there aree sidequests and multipliers for each map and challenge, to keep the challenges balanced and different ways to win open :)
You must be really creative to make your AI win more than one main Challenge, i havnt seen any AI's beating more than 2 yet! But maybe you can do it? End of Sentin Time is 31. october. this year

**Comment by forestleaves** [comment]
Our rules is very different,but no human interact,too.Our match is 3 vs 3,everyone uses three different AIVs to take part in.The game will last until one side'all ais are defeated or the game last too long.

**Comment by forestleaves** [comment]
Besides competition match,we also have many kinds of contesta,such as attack test,defend test and so on,

**Comment by Krarilotus** [comment]
Is there any english description or kinda understandable form for non chinese people?

**Comment by Krarilotus** [comment]
I would like to take part in one of these, what would i have to do and what would the prize for the winners be?

**Comment by forestleaves** [comment]
Actually,We have no prize for the winners,in our group we are because of inrerest to get together with each other,we do not regard the aiv design as a work that earns something,what the winners receive is honour,it is enough.

**Comment by Krarilotus** [comment]
ok, fair enough, so how could i take part anyways? IHonor is a great reward. And if i could learn more about aiv design on the way, sure i am in!

**Comment by forestleaves** [comment]
We are delighted to your join,I sure we have something powerful you have never touch,such as onestep wall and others.
If you want to take part in,you can sent your aivs to us,but mgq,the competition hoster,would firsrt  test your aivs.If you want to

**Comment by Krarilotus** [comment]
@forestleaves So what is this defense challenge, are we speaking about vanilla AI's or is the UCP Involved? Where do i get the maps that get used? Where can i reach your hoster? And how are we going to connect outside of this post? :D

Is there and official rules panel for the competition?
Which AI's am i allowed to use?
What do you mean by mainly defense/attack/raid... because the Vanilla AI does everything of each. So Do you mean that with using the UCP for raid/Attack/Defense units?

**Comment by forestleaves** [comment]
You can see your aivs' performance in mgq'test vedeo.I know language is a problem,maybe a few days later we would sent English rules to you?

**Comment by Krarilotus** [comment]
Yes please, over discord or mail (shc.aicontest@gmail.com)
For my contest, i uploaded a rules-sheet publicly if you consider to taking on another kind of AI Design Challenge on your own with another mindset :)
(Rules in english and german so far, but feel free to translate it to chinese for your friends and colleges...) I have beside the honour an analysation of the AI's + steamgifts as prizes planned. I ll also make another AI Contest after this one.
I know honour is enough for most, but i feel like a little extra drives more people to innovate and find out new stuff about AI design for this awesome game!

**Comment by forestleaves** [comment]
More things can be discussed a few hours later.You know, here is 2:20a.m. now...

**Comment by Krarilotus** [comment]
Oh i am sorry, sad to hear that. Just let me know, if you prefer any other communication plattform for personal messenges. I dont want to spam sh0wdowns Issues section with this ^^

**Comment by forestleaves** [comment]
@Krarilotus I think we may use mail to communicate or you can suggest some other ways?

**Comment by Krarilotus** [comment]
@forestleaves 
Ok, fine by me :D
i will wait for your mail to arrive at shc.aicontest@gmail.com
