### ISSUE TITLE
Multiplayer slowdown and desync

### ISSUE THREAD

**Issue by MarviB16** [Sh0wdown/UnofficialCrusaderPatch#464]
Hello,

I know that multiplayer seems not officially supported, but I tried with my friend nevertheless. 
The things we experienced were:

- desync about every 5 seconds (sending the information took less than a second at the start and increase with game length)
- Slowdown of the whole game (after about 5 min we had about 15 FPS and a 3 second delay when we build things) (With 4 enemies and 2 human players)
- Random crashing of the game of the (non-host) player

Is there a way to fix this(, yet)?

Thanks!

PS: We installed the patch with the standard options checked + the WASD option.

**Comment by GRhin** [comment]
Hi marvi, 
I have used the patch in multiplayer lots (mostly 1v1) and haven't had these issues. That is not to say that the patch did not cause them, but I would suggest checking without the patch with the same opponent just to be sure the patch is the cause of your problems

**Comment by Krarilotus** [comment]
@MarviB16 
I suppose, the settings of the ucp must be out of sync before installing it. I d suggest checking inside the AIC tab, as that would be the most obvious to check for, if it is only the AI's bugging you out.
Check the same box, and make sure, if you use custom AIC's that you have exactly the same file inplace to checkbox inside the patcher.

PLS answer if the issue has been fixed.

**Comment by MarviB16** [comment]
Hi,
yes it was a small difference in the installer.
Now it works perfectly, thanks
