### ISSUE TITLE
Game version change?

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#471]
SO i downgraded a version of the game to 1.3, then installed the unofficial patch over that, and noticed when i loaded the game that it now said it was 1.41 again. I uninstalled the patch and it still said it was 1.41.
Does the unofficial crusader patch automatically install the 1.41 patch? or is this a bug?

**Comment by Krarilotus** [comment]
I am unsure about it, as i am only on my smartphone right now, but could you check if a version number is hardprinted into the ucp.cfg config file?
If so, maybe remove the config file, before you install the patcher on a downgraded 1.3 version, as it will readout the version again.

I am not sure how sh0wdown handles it, but for me it seems, as he has a premade patched version for each crusader version of some kind and just replaces the executable while renaming the original
If so, by uninstalling, the original should still have the downgraded version in it, and theirfor it might have been upgraded by something else before installing the patch? But i am not entirely sure how it works, so dont quote me on that :)

**Comment by GRhin** [comment]
Nope, not in cfg file. 
It definately changed with the patcher. However, it is possible the original ucp_backup file was from before i downgraded, so when i uninstalled it recovered the old .exe file from before the downgrade...

**Comment by Sh0wdown** [comment]
Delete all .ucp_backup files after installing 1.3. Then apply the unofficial patch.

**Comment by Krarilotus** [comment]
this has been solved by sh0wdowns answer.
