### ISSUE TITLE
When New  Patch ?

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#472]
It's been a long time since there's been any news...

**Comment by Monsterfisch** [comment]
showdown mentioned in a different issue that he is short on time due to personal/study/work related reasons. your best bet is to enjoy what you have gotten so far. there is simply no rushing it if there is no time to spend

**Comment by J-T-de** [comment]
I know the answer: When its ready :P
No serious, no need to put pressure on him, I guess he does what he can, and here and there one can read a comment of him, so he is still around.

**Comment by GRhin** [comment]
Alternatively, learn to do it yourself and extend the patch, fork it or whatever.
Theres a couple minor bugs, but aside from that, the current patch is pretty darn good, I cant think of much more for him to do thats worth pushing for.

**Comment by Starshine575** [comment]
@Lolasik011 yes we all want news of course, so lets hope we get them in near future. 💖

**Comment by ByBurton** [comment]
Guys, just chill. I got contact with him (from time to time) and all I can say is that he is really busy.
And the next additions require a lot of work which he can not really spend on it right now.

Try to enjoy this beautiful peace of work and all the possibilities with it. 
Or try out all the beautiful AI mods that already appeared. 
I myself also have a [repository](https://github.com/ByBurton/Stronghold_Crusader_Kimberly_AI
) which you can check out.
