### ISSUE TITLE
Suggestion: Command Line arguements

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#479]
Hi Sh0wdown, 
Can I suggest in the next release of the patcher, that you allow for some commandline arguements?
Id like to be able to write a batch file that copies extra files to the right locations (maps, aiv, aic) and would love if i could add a command to install the patch with the settings in the provided cfg file (of course the bug of "Increase of the rate of additional attack troops" being messed up due to localization, and the AIC setting not always being transferred will also need to be resolved for this to work).
As a more intensive edit you could allow many of the settings to be set by commandline as well
Thanks for all your great work,
GRhin

**Comment by Krarilotus** [comment]
This is definitly a big plus. Just having the patch getting installed by commandline or other tools, to use it in any basic mod installation would be great!

I wonder what it would actually take for this to work?

**Comment by ByBurton** [comment]
Closed because @patel-nikhil implemented it.
