### ISSUE TITLE
When is the patch updated?

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#48]
When is the patch updated? Thank you for the answer.

**Comment by Lolasik011** [comment]
approximately ?

**Comment by PitchNeeded** [comment]
Have patience! 😄 Everything added, I am sure, has to be extensively play-tested before the release of a new patch update.

**Comment by Lolasik011** [comment]
Thank you for information !

**Comment by Lolasik011** [comment]
I'm just so excited about this patch that I can't wait for the next one. Sorry for the rush.
