### ISSUE TITLE
thread where we say how much we love :showdown" :3

### ISSUE THREAD

**Issue by ilosevsrat** [Sh0wdown/UnofficialCrusaderPatch#480]
i really think we need such thread where we thank people like him for everything he does for stuff that we care (like Crusader)

so i love show down   |===============================================|   <---- this much,  you?

**Comment by an-accident** [comment]
mucher

**Comment by Krarilotus** [comment]
He is definitly the best modder that SHC ever had. I am greatfull for the work he has put in so far

**Comment by ilosevsrat** [comment]
i will  establish religious movement  "Sh0wdown's Witnesses" (feel free to join)

**Comment by ByBurton** [comment]
This is not an issue, and I am going to close this. You can show your appreciation by following. You can write an e-mail or something to show your appreciation.
Sorry.
