### ISSUE TITLE
Merry Christmas

### ISSUE THREAD

**Issue by Krarilotus** [Sh0wdown/UnofficialCrusaderPatch#481]
Hey Guys,
I m happy that this Stronghold Community is so active, and i made a Christmas Calendar with 21 doors (3 more will come when i got time next year)...
I just wanted to say thank you, to all of you and especially @Sh0wdown, for making this possible. Only because of him i was able to create this skirmish campaign that truely teaches and exposes you to any inch of the game possible.

If you want to check it out, just join the stronghold official discord: https://discord.gg/pH3v295

Join thr dynasty, we will be active and get alpha demo access to their warlords game preview.

Ok sorry for anyone who sees this as advertisement. I hope i can contribute with good game content to the active thrive of the community for the game.

**Comment by ByBurton** [comment]
I still think the "issues" section should be reserved to issues, and not content sharing.
There are many other websites for this.
