### ISSUE TITLE
Many problems

### ISSUE THREAD

**Issue by Zelenium** [Sh0wdown/UnofficialCrusaderPatch#482]
Hi! I was trying to configure bots in some way and ran into certain problems:
1. How to adjust the power of the lord? I think everyone knows that our standard lord is much stronger than Lord Rat and at the same time weaker than Lord Wolf. Where is it configured?
2. How to set up the initial number of troops and their types (which are issued to a computer player at the beginning of the game).
3. In the settings of each AI there are various types of attacks. For example, AttUnitMain1 and AttUnitEngage. At the same time, an increase in AI attack strength acts ONLY on AttUnitMain1. How to make it work on all other subspecies of attacks? This is necessary so that the Wolf, for example, after a large number of attacks, would send not 200 swordsmen and pikemen + 20-30 crossbowmen to the enemy, but 200 swordsmen and pikemen + 100-150 crossbowmen. The option with increasing AttUnitEngage for example to 1000 is not suitable. Since in this case I will not be able to control the exact value of the crossbowmen in each wave (I need accuracy).
P.S. Sorry for my English.

**Comment by Russianstory** [comment]
Зелениум ты по-русски понимаешь?

**Comment by Zelenium** [comment]
Да

**Comment by Russianstory** [comment]
Ура слава Богу))  Согласен с тобой про Лорда. А про армию не понял )) хочешь увеличить количество?

**Comment by Zelenium** [comment]
Нет. Хочу сделать точное количество армии. Чтобы расли все значения, а не только AttMainUnit

**Comment by Russianstory** [comment]
Не совсем тебя понял

**Comment by ByBurton** [comment]
Thank you for opening up an issue. But several of these already have an issue related to them.
The power of the lord is probably not configurable in the AI parameters. The starting troops are also not found in there, 100% sure.
And about the attack increase. That is how the formula works right now. There is no way to change that without great effort and time.

**Comment by Zelenium** [comment]
Okay. You can still do without the first 2 things, but what about the 3rd? If it cannot be changed, then you need to at least understand it. I can not do it. If you put AttUnitPatrol for example 100000, then they will not go at all that amount, but about the same as AttMainUnit1. How does it all work ???

**Comment by Zelenium** [comment]
Generally speaking, are you already using? I mean AIC files and so on? With what? I just think that there I can find everything I need. Have you used HexEditor?

**Comment by J-T-de** [comment]
2. is suggested in https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/459 and https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/156 with a hint how to potentially implement it

**Comment by Zelenium** [comment]
Someone said "It is stored in a separate array gStartupTroopCount[19][3][20]
[StartupTroopGroupType (AIType or 18 + LordType for human)][GameType][StartupTroopType]
pgStartupTroopCount = (int*)0x00614358 for v1.3"
Where is this array located? How to find and edit it?

**Comment by GRhin** [comment]
That sounds like a hex editor array not yet implemented into the aic. If you know how to use cheat engine or idafreeware you might be able to figure out the exact value to change from that, but I've never figured out how to browse cheat engine or ida.
What was your solution to problem 3, just for others who might be having the same issue...

**Comment by Zelenium** [comment]
The solution was to understand how it all works.
I will describe now.


If you use AttMainUnit and only this, then the units from the AttForceBase section will go all to AttMainUnit. Example: you set the CPU to attack only AttMainUnit1-4, without others (such as AttUnitPatrol). In AttForceBase, set the value to 20. In AttMainUnit, you put Spearman.
Congratulations! Your bot will attack 20 Spearman.

If you use AttMainUnit and, for example, AttUnitPatrol, then AttForceBase will split in half between these 2 types of troops.
For example, you added to the previous example
AttUnitPatrol = EuropArcher
and
AttUnitPatrolMax = 10000.
Congratulations. Now in the first attack, the CPU will attack at ~ 10 archers and ~ 10 spearmen (there is a small spread in one direction or another).
In this case, with an increase in attack power over time, the proportion will remain 1: 1.


If in the last example you put no
AttUnitPatrolMax = 10000
but
AttUnitPatrolMax = 10
then such a proportion will be observed only in the first attack (where there are only 20 units). In the next attack, the number of archers will remain no more than 10, but everything that grows in AttForce will go to AttMainUnit

That's how it all works.

**Comment by Zelenium** [comment]
But guys, please help me with questions 1 and 2. It is VERY important. Let me at least find out what programs you used to extract information? As far as I understand it is not HexEditor since in it I could not do something interesting.

**Comment by GRhin** [comment]
ByBurton has answered those two, they are currently not possible using this patcher, you would have to modify the exe or process yourself with a hex editor type program, cheat engine for example. I believe both are on sh0wdown's radar to implement in future versions, but that depends on how much time he has, and how much time it will take to sort out, there are also several other things ppl have requested for future versions and I'm sure he has his own ideas as well, so dont rely on your requests being here soon.

**Comment by Zelenium** [comment]
As for the 2rd problem - I completely figured it out. It is no longer relevant.

**Comment by Zelenium** [comment]
And first too. Ty for help, guys!
