### ISSUE TITLE
Unknown130 Parameter Solved

### ISSUE THREAD

**Issue by Xebenkeck** [Sh0wdown/UnofficialCrusaderPatch#484]
Hey guys,

I have figured out what Unknown130 Parameter is.

It is the Delay the AI will use to send units to attack the walls if SiegeEngines are alive during the Assault.

I tested this with The Snake, where his default is set to 0. I changed it to 50 and tested it and while he has his 1 catapult alive he would not sent his units to attack the wall for a very long time. I don't know what unit of measurement is used, game ticks, seconds, mins, months etc? But 50 is a long time before he will send units in while his catapult is alive.

-Once his catapult dies, he will then revert back to the "normal" delay he uses to send in units to attack the wall.

-If his engineers are killed before the assault
-Or his equipment doesn't get manned because of a delayed engineer,(this is a glitch that if one siege engineer enters the tent and builds it before the other one enters the tent, then they won't man the equipment) 
-or one of the two engineers die
Then this parameter is completely ignored and the AI will go on with his "normal" attack delay.

-If the Siege equipment breaches the wall they will proceed normally as when any breach is created.

Other things to note:
-AttUnitEngage are unaffected, they will attack nearby enemy units the moment the assault starts regardless of the SiegeEngines status.
-AttUnit2 will also engage, but they will not send units to attack the wall until the delay is over or the catapult dies.
AttUnitPatrol - will still engage no matter what.
AttUnitBackup will go to their normal spot upon beginning of the siege. 
AttUnitSiegeDefence - will go to their spot by the SiegeEngine units while they engage.
Laddermen won't engage until the delay is met or the SiegeEngine units die.
Tunnelers didn't test.
Assassins - won't engage until the delay is met or the SiegeEngine units die.
AttDiggingUnit - won't engage until the delay is met or the SiegeEngine units die.
AttUnitMain - won't engage until the delay is met or the SiegeEngine units die.

I also did not test what constitutes as siege equipment, I assume anything under the SiegeEngine Array will count but I didn't test that. So I don't know if it is the same for Catapult as it would be for Battering Rams or Siege Towers.

If it is, I think it would be really good for some AI's to wait a bit and see if their Battering Rams/Catapults can knock down a gatehouse before they throw their lives away running in to assault the walls by hand, or get killed by their own Catapults(cough Pig cough Abbot)

These are the vanilla Values for all the AI
RAT - 0
SNAKE -0 
PIG - 5
WOLF - 12
SALADIN - 4
CALIPH - 2
SULTAN - 0
RICHARD - 20
FREDERICK - 20
PHILLIP - 0
WAZIR - 4
EMIR - 0
NIZAR - 0
SHERIFF - 5
MARSHAL - 0
ABBOT - 0

Something like ATTSIEGEEngUnitsDELAY would be what i'd call the parameter.

**Comment by ilosevsrat** [comment]
wow
, great to know that, thanks alot buddy!!!

**Comment by Lolasik011** [comment]
Wow!!!

**Comment by Krarilotus** [comment]
this is a greated and detialed description, love it :D
i am looking forward to you finding out even more abt this in the future :D

**Comment by ByBurton** [comment]
I completely missed that you wrote an issue for this. Sorry about that. Uhm yeah, sure I can add it. But first I want to know a few more things.
1. How much is the delay in ingame years (does not have to be 100% accurate, but an estimation tested with at least 5 different values)
2. Do all 8 engines have to be destroyed? 
3. What if there are more engineers than engines?
4. Do for some reason HarassingSiegeEngines count? (They count for the patrols from the SiegeEngineDef units)
5. What happens if the AI loses engines by building on top of them?
6. What happens if the delay is 100?
7. What happens if the delay is a negative value?
8. What happens if you set a delay without siege engines?

If you can answer all these questions I'll add it.

**Comment by Xebenkeck** [comment]
I will test tonight, and have answers for you.

**Comment by Xebenkeck** [comment]
1.
100 = ~FEB 1184 to ~FEB 1186 or ~2 in game years
50 = ~OCT1187 to ~NOV1188 or `1 in game year
25 = ~JAN1183 to ~AUG1183 or ~7 in game months
20 = ~FEB1183 to ~AUG1183 or ~6 in game months
10 = ~JAN1183 to ~APR1183 or ~3 in game months

2. Yes all engines have to be destroyed. This includes ones that have been created but are not manned(I.e. 1 engineer died before making it to the tent and making a catapult)
3. Has no effect. Extra engineers do not cause the delay to activate. If all SiegeEngines are destroyed and there are extra engineers, the main army commences normally.
4. No they do not, if all SiegeEngines are destroyed it doesn't matter if HarassingSiege units are alive.
5. I can't really reliably test this sorry.
6. If the Delay is 100 they wait ~2 in-game years
7. Has the same delay as if it was 0.
8. Has no effect. Has the same delay as if it was 0
9. Tunnelers are unaffected by the delay.

**Comment by Krarilotus** [comment]
this is really nice. The map dependancy is exactly what bugged me and why i couldnt confirm it with exact numbers. But what you have done here is a good job. I am expecting more of it in the future :D

Now my question would be on how we can find out the total delay until an attack times out? could that be 129? So if units are inactive for like some delay, they go back to the castle. I would think that is also about 2 ingame years or a bit more?

Maybe we can test that :D But i believe, they even stand around, if 129 is 0. So that might not be it. Lets see and find out!

**Comment by Xebenkeck** [comment]
Its good that you mention that,

The attbackupunits are interesting because they will retreat when the main army dies. but only sometimes. There is a timer in which they will retreat if they just stand around, but it is incredibly long.

In my experience if the AttBackup group is small, they will usually retreat when the main army dies, but if the group is big, they will wait for that timer to expire before they retreat.

This leads me to believe that the "retreat" is a percentage based value, meaning if over 15% of the total remaining army is dead they will retreat, but if they make up over 15% of the army they won't retreat.

Its interesting indeed.

**Comment by ByBurton** [comment]
@Xebenkeck you can test point 5 by playing a map where you control the AI (ask @Krarilotus for that) and then build a woodcutter on top of it. Didn't read the rest of it yet :D

**Comment by Krarilotus** [comment]
I am pretty confident when i say: building something over anything inflicts for the AI the same behaviour as if it was killed. Thats what i have seen and tested with any AI's so far.

**Comment by J-T-de** [comment]
> I am pretty confident when i say: building something over anything inflicts for the AI the same behaviour as if it was killed. Thats what i have seen and tested with any AI's so far.

But for example, the harassing siege engines, when they get overbuilt, don't get replaced... So it seems that at least in this case, the AI thinks it is still alive (or does not realize, that it can place a new harassing siege engine).

**Comment by Krarilotus** [comment]
@J-T-de i can think of 2 likely reasons for harassing siegeengines not getting build again:
1. reason could be, that if it dies, no matter if it was overbuild or not, the engineers will be still counted toward the AI's units, and it detects those engineers to be available for harassing siege engines. If it then tries to build harassing siege engines with those, it will just not build them. But to find out more about those engineers, you would have to be able to detect their values and what the AI does with cheat engine or such a tool, which i have no clue on how to do as of right now.

2. reason could be, that the building spot, that the AI thought would be available to build harassing siege engines, gets occupied. Or there is no such spot next to the engineers guild anymore. Detection of buildable spaces is definitly a thing, that should be bugfixed somehow.

You can see for attacking siegeengines, that they might not get build anymore, and a huge pile of engineers stacks at the training grounds of their guild. This makes me think, that unbuildable spots might have to do sth with siegeengines not getting setup properly, and engineers are not detected the right way, after the setup of a siegeengine failed. 

I have goneover to a castle design tactic, where i let the AI build their engineers guild outside of their castle, in some path of enemy attacks. The easiest way is to setup some pitch next to the training grounds, and then when enemies come along, they will trigger the pitch, therefore resetting all the pending engineers by burning them to crisps.

Also sometimes the AI's DO build harassing siegeengines over and over again, without them beeing missdetected. Not sure if that is unique to some AI's like the sheriff, but its definitly worth to investigate that behaviour further. Maybe after all, the overbuilding makes a difference, but i dont see right now how that could be.
One example of a harassing catapult that gets rebuild even in later stages of the game is the AI contest 2 - map 3 video i made of skysouls castle. 
https://www.youtube.com/watch?v=ZoOOsj0MK6c

**Comment by J-T-de** [comment]
I don't remember where I saw it, but some AI (with up to 3 harassing catapults in the aic) overbuilt two of them with new harassing catapults, so in the end this AI only had one remaining harassing catapult.

So I am rather sure there is some kind of broken counter, either harassing siege engines or harassing siege engine engineers...

**Comment by Heroesflorian** [comment]
> But for example, the harassing siege engines, when they get overbuilt, don't get replaced... So it seems that at least in this case, the AI thinks it is still alive (or does not realize, that it can place a new harassing siege engine).

> I don't remember where I saw it, but some AI (with up to 3 harassing catapults in the aic) overbuilt two of them with new harassing catapults, so in the end this AI only had one remaining harassing catapult.
> 
> So I am rather sure there is some kind of broken counter, either harassing siege engines or harassing siege engine engineers...

I've also seen the AI build new harassment catapult tents over existing harassment catapults, though, and then still continuing to build new ones up to their regular max amount as according to the AIC, after those incidents. So even if I cannot rule out it may possibly have _some_ effect _some_ times, I can say for sure that it is not as simple as just "whenever AI overbuilds them, AI will never replace them". 
Besides... this here is the wrong issue to discuss that particular behaviour anyway, right?

**Comment by Krarilotus** [comment]
Parameter 130 got solved, for discussing the ghost engineers, there are plenty of other issues currently open.
