### ISSUE TITLE
New Missions / Armory&Marketplace Weapon Order Fix

### ISSUE THREAD

**Issue by LordHansCapon** [Sh0wdown/UnofficialCrusaderPatch#487]
Hey guys,

So I have replaced all 50 missions in the Crusader 'First Edition' Trail with custom ones made out of custom community maps. I have posted my custom patch to Stronghold Heavens, but as of today (9th January) it hasn't got approved.

Mission Image:
https://imgur.com/a/sJqMboZ

Would anyone want to see it included as an option on the UnofficialCrusaderPatch?

I have also looked into fixing the annoying weapon mismatch order in the amory and the marketplace.

There are 3 UIs where you can "interact" with weapons:
1. Amory
2. Marketplace Trade Weapons
3. Marketplace

Currently:
https://imgur.com/a/beoK5Kt

Fixed:
https://imgur.com/a/LXk0aSH

Selecting the Leather Armor now results in having the Crossbow on one side, and the Mace on the other, while selecting the Plate Armor now results in having the Polearm on one side, and the sword on the other. Much easier to navigate the shop this way.

**Comment by J-T-de** [comment]
In general, I don't think putting content into the UCP is desirable. Content in the UCP will have a massive advantage over other content, which might be as good or even better. It is user friendly, but not content creator friendly. Independent, how good it is.

Regarding your rearrangement of the weapons: Really nice, this was something which was really bothering me, and at some point I just accepted my fate. The stockpile and the marketplace has a similar problem. I think this would be a nice addition to the patch, but maybe not as default.

**Comment by LordHansCapon** [comment]
AI castles can be viewed as content replacements such as my "Mission Pack", but I get your point. Could be an independent patch, or if I solve how to render a third Crusader Trail that'd be even better.

I dug into how rendering works in this game, as I had to cause of the Marketplace. The game's code is really weird, the Armory and Marketplace were written by different people as far as I can tell from the Assembly code. There is a function to render the Armory's title text, icons and Amory item count texts. But the Marketplace renders differently, there are 2 functions which render the Marketplace. One renders the Marketplace's Trade Weapons title text and the item count texts, but the icons are not just simple images as in the Armory, they are some kind of button instances, as they have hover states, so they are rendered independently from the marketplace render function. They also use different structures to render the items. The Armory uses 3 "arrays", whereas the Marketplace uses 1 "array" to render item count, and Button instances which are 50 bytes long to render the buttons.

The easiest way to find render points and modify them is to find the corresponding spritesheets. I was able to add more items aswell via allocating a new memory segment then injecting a code which sets the address the armory rendering function reads from. This knowledge is quite useful when it comes to adding more UI elements.

I also found the function which renders every text in the game. I identified its parameters and could render any text anywhere on the screen.

----

I'm more of a "the more configurable, the better" person, so I'd prefer everything to be configurable in UCP, including this order fix if it gets added.

The stockpile/marketplace item order never bothered me, but items could be re-arranged better in that case that well I suppose.

**Comment by Krarilotus** [comment]
oh, this looks interesting. Do you have a git repository to share your custom trail?
If you can render a third skirmish into the game, that would be awesome! I bet your trail is much harder than the base game ones. 
As you can read and write assembly, maybe you can work directly with sh0wdown, as he asked for people who know assembly.
These are great news :D
If you happen to have any tutorial suggestion, who to learn these things, i would love to see that, as i would love to have more people contribute to the patcher and work in all the great options suggestied so far by the community!

**Comment by J-T-de** [comment]
When I finished working on my small mod (this will be very soon), I will write down a small tutorial/summary/link collection how to find, edit and most importantly, how to include changes to the patch.

Starting for me was just a pain (even though I had a solid background in the underlying concepts) due to a lack of vocabulary (no vocabulary, no way to google it). Also, there is very little documentation how to include your changes to the UCP (if you know how, it makes sense, if not, not). I wasted many hours on very, very easy stuff. Lowering the threshold to start working on an edit might result in more participation, which would be nice ;)

**Comment by ilosevsrat** [comment]
can you post few screenshots from missions :)?

**Comment by LordHansCapon** [comment]
@Krarilotus I do not have a repository for it yet. The custom trail has a difficulty curve aswell, but its much more steeper and it kind of gets hard from mission 11, and gets really hard by mission 30, I don't even know if its even possible to beat certain missions. There are missions where rushing the enemy is just not viable. See these two for example:
https://imgur.com/a/2iY2yhS

------

I have looked into running events in skirmish mode, and as far as I can tell, it is way easier than it sounds. The game keeps track of what type of game we are in, skirmish, invasion, economic scenario etc. The event tick is only ran in a certain game type, so I can just bypass that and tell the game to run pre-configured Events such as Crops dying.

The game also only runs events for Player 1, but that can be easily offsetted. I have created a random number generator function and just selecting a random player for the event before running it. Certain events do not require selecting a Player, which makes them easier to implement. The most fun I had is with the Food stealing Event, where the granary loses some % of its content and a video message plays. I have that implemented in SinglePlayer Skirmish so that a random player may lose some food.

I also played around with random fire spreading. That's a lot of fun... except for those AI who do not build wells... ouch.

@ilosevsrat Here you go, I have yet to beat these missions:
https://imgur.com/a/2iY2yhS

Keep in mind that I use UCP with the default settings regarding the AI, so its pretty tough. Also the case why I use Emir a lot in the missions, because he became really hard when he attacks the player with a huge army.

**Comment by Krarilotus** [comment]
i would be happy to test your mission, to rate them by difficulty. I am still needing some inspiration for my last 3 mission of my christmas calendar. I have them planned out almost completely but feel like they are lacking some....

If you want to try out whats possible right now, you can try those out too, i have them uploaded to the warlords discord (stronghold official discord server from firefly).

https://discord.gg/PtG6G9
(pick dynasty as your faction :D)

I d love to test those missions with my custom AI and current aic if possible, but vanilla will be definitly doable by the pictures you sent.

i am definitly looking forward to the tutorial and to all the great stuff that gets contributed. If you lessen the initial setup time for newcomers, that will help alot. I am definitly interested in contributing and working in some general ideas like custom hotkeys, changing more of the behaviour of the AI's and some bugfixes for multiplayer.... (like disable double worker glitch, or fast workers, or despawning bakers)

**Comment by LordHansCapon** [comment]
I have forked this repo to add my Armory/Marketplace order fix, you can check it here:
https://github.com/LordHansCapon/UnofficialCrusaderPatch

I will make a basic tutorial on how to add custom changes to this repo, just the basic stuffs.

**Comment by ByBurton** [comment]
@LordHansCapon I'd love to play your custom skirmish trail, but adding new things into the UCP ... Idk. 
Let's at least wait 'til our master, Sh0down is back. Is there a way to play it already?

**Comment by LordHansCapon** [comment]
@ByBurton Yeah, I doubt I'll ever request a pull for the new missions. I didnt even add it into the fork. I haven't uploaded it anywhere, I mean I tried to upload it to stronghold heaven but they probably rejected it cause it was weeks ago. I might rework some parts of it because I found a bug in it, but not in the near future because I rather fix stuff in the game right now.

**Comment by ByBurton** [comment]
Sure, you already helped a ton

**Comment by GRhin** [comment]
Can be closed with new release
