### ISSUE TITLE
Camera forced to building on hotkey select

### ISSUE THREAD

**Issue by LordHansCapon** [Sh0wdown/UnofficialCrusaderPatch#490]
Have you guys ever wished that pressing M would never force the camera to the marketplace? I think it should be an option to stop these forced camera movements. I just hate it when I'm in battle, the stockpile is full and I have to sell, but it draws away my attention from the battle.

Feels like economy management and the battles do not work well together... how about making the hotkeys only force the camera if pressed twice? So when you press M, the marketplace opens, but it does not force your camera to the marketplace, but if you press it again, now it does. Same would go for Barracks, Mercenary camps and basically everything.

Any thoughts?

**Comment by GRhin** [comment]
That is already implemented in vanilla.... just press Shift + M.
If you forget and press M on its own, press Ctrl + M to return the camera to its previous position

**Comment by J-T-de** [comment]
I think this should be a choice for a general hotkey customization as mentioned in https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/473 or suggested in https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/432. But for only this, the vanilla version is enough for me.

**Comment by LordHansCapon** [comment]
Really? I have never knew about it. I still think it should be vice-versa though, for me at least. Thanks for the info!

**Comment by Krarilotus** [comment]
this issue was more like a question, that has been solved.
for looking at a list of hotkeys, go here https://steamcommunity.com/sharedfiles/filedetails/?id=491097896
issue will now be closed.

**Comment by LeSpec** [comment]
> Really? I have never knew about it. I still think it should be vice-versa though, for me at least. Thanks for the info!

If you still want this, i have it as a branch on my clone of the repo. The branch is called "personal/keybinds/o_ctrl_toggle".
