### ISSUE TITLE
Ladderman cost

### ISSUE THREAD

**Issue by LordHansCapon** [Sh0wdown/UnofficialCrusaderPatch#495]
Is it just me or the ladderman costs 20, but it displays 4 in the engineers guild. I know there is an issue about this already, but that's quite old and it states that it costs 38 for them. I guess one of the official patches changed that or something as I use Steam 1.41, and it costs 20 for me.

I have prepared a change for this in my fork, so if you guys notice this aswell in your Steam 1.41, let me know and I'll send a pull request to merge that fix. If the cost differs across version, then maybe I will change the displayed gold to be the actual cost. Because the game stores two different values.... why wouldn't it.

**Comment by Krarilotus** [comment]
Look into the Units tab for the UCP: Increased armor of ladderman against ranged units. They usually cost 4, but with this their cost was changed to 20. I guess its just the display text that is still 4, as that is handled in the cr.tex

**Comment by LordHansCapon** [comment]
Yeah I think I will just grab the buying price and display that. God knows why they did it this way.

**Comment by LordHansCapon** [comment]
Ah yeah, I forgot that UCP changes the cost of laddermen, in which case I could just merge my laddermen cost display fix into the laddermen unit change section. That'd make sense.
