### ISSUE TITLE
UCP no longer works with Stronghold Europe mod

### ISSUE THREAD

**Issue by meisanon** [Sh0wdown/UnofficialCrusaderPatch#50]
Not a big problem as this was never meant to be a feature of the patch, but before the latest commit you could rename the 'Stronghold Europe.exe' to 'Stronghold Crusader.exe' and get all of the nice patch fixes and additions in the glorious SH1 setting!

Tried troubleshooting it a bit and it seems only the 'Units' edits work in the installer. Selecting anything else gives a ctd when running Stronghold Europe. 

Guess I'll have to get used to the desert.

**Comment by Lolasik011** [comment]
I think they will soon make a patch for Stronghold Europe. Anything can happen.

**Comment by meisanon** [comment]
> 
> 
> I think they will soon make a patch for Stronghold Europe.

**Comment by meisanon** [comment]
> 
> 
> I think they will soon make a patch for Stronghold Europe. Anything can happen.
> Although I like the desert too.

We can only hope.

**Comment by Lolasik011** [comment]
Already waiting for a new patch ^ _ ^

**Comment by meisanon** [comment]
Seems like the patch is once again working for Stronghold Europe! Not sure what you fixed, but the new 2.05 release has no problems and seems to be working fine with it. Will reopen if the issue comes back in the future.
