### ISSUE TITLE
Multiplayer settings

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#506]
Can we please have an option to change the settings for multiplayer games?
In particular:
- Default speed (id prefer it to be 50, its annoying changing it every match)
- Starting gold (id like to try a game with 1k gold, or even 0 gold)

That second one isnt really usefull against AI as i doubt the ai can even work with it, but human vs human i think will be very good. Maybe having the AI still having original start gold would be fine, or making "computer advantage" give the human less gold instead of the AI more....

**Comment by LordHansCapon** [comment]
I was just considering adding 4 arrows into the skirmish menu where you could add / substract 500 gold from the player or the AI. As for the default speed, I don't think that's big of a deal to make an option for that.

**Comment by LordHansCapon** [comment]
@GRhin I have added the default speed option you wanted, you can get the build here:
https://we.tl/t-20nyPAxJun

**Comment by GRhin** [comment]
Thanks man, appreciate it. Any chance of the start gold option being implemented too? Even if it's just a tick box in the patcher for 0 gold.

**Comment by Admiral-Gumpert** [comment]
There's a huge problem in multiplayer which Idk actually if its me only or not : I can no longer send a specific map to the other play as the button is completely missing ,, Any solutions ?

**Comment by Monsterfisch** [comment]
true that i didnt have that button as well anymore figured it got removed in an update of the game a workaround would be to send the map files to the other players manually

**Comment by LordHansCapon** [comment]
Is that related to UCP or is that how it is in Extreme?

**Comment by Monsterfisch** [comment]
thats a good point it very much likely is related to that through that is still a feature that would be good to have there regardless in case it is just disabled and not taken out fully

**Comment by GRhin** [comment]
The button was removed in 1.3 I believe.  Another ticket for that would be good.
For my stream I share maps in a zip that has the patcher, my config, an aic for when we play against ais, an aiv folder, a maps folder, and a batch script that makes backups and copies the files to the right place, then the player just has to open the patcher, check a couple things that dont always share well with the config file, and install. 
The "problem" with using the patcher to introduce the send map function is that you already have to share the patcher and config outside the game, so you may as well share the maps at the same time.

**Comment by J-T-de** [comment]
> The button was removed in 1.3 I believe.

I think it was removed in 1.4, this is the reason why 1.3 is still in use. 1.3 also has different scrolling speed (when scrolling over the map).

**Comment by Admiral-Gumpert** [comment]
I thought that was related to the UCP

**Comment by GRhin** [comment]
So I have been playing with the default speed feature,  it is great, only problem is that after a game ends, it resets to 40 again. it did this originally too.

**Comment by GRhin** [comment]
This is implemented in new release
