### ISSUE TITLE
Fireballistas dont automatically shoot at Tunnelers 

### ISSUE THREAD

**Issue by Admiral-Gumpert** [Sh0wdown/UnofficialCrusaderPatch#508]
Hello everyone ! I dont know if someone noticed this before but in earlier UCP fireballista was fixed and it now shoots automatically at Monks , but it doesn't do the same to Tunnelers .
![image](https://user-images.githubusercontent.com/50601775/73191094-0240da00-4138-11ea-8ae7-8605be73dfb7.png)

Sorry for posting this if it kinda annoys you (you kind of fixed that ballista thing and now it's back etc)
If anyone also can suggest me a good hex editor to edit the exe

**Comment by J-T-de** [comment]
It was only fixed for monks, so this is something different. (As far as I remember, the fireballista also does not target civilians, but I could be wrong). This is definitely something fixable, as it was already fixed for monks.

Regarding firebalista in general: Is there a known priority list, like ranged units have (1. other ranged units, 2. melee units, 3. civilians)? Maybe one could 'just use this'? (or even switch 1. melee units 2. ranged units). What is for AI the priority for burning down buildings?

Regarding a hexeditor, the goto is probably Cheat Engine (okay, it is not a hex editor in the sense, but it is the thing you want to use). When I find some time I will write a small Intro. See https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/488 and especially https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/488#issuecomment-574815006

**Comment by Starshine575** [comment]
@J-T-de to answer one of your questions: AIs always target the closest building with fire balistsa. 🤔

**Comment by LordHansCapon** [comment]
Why would one get upset about it. We are here because we love this game and want to make it better. 

So I looked into it, and it seems that there is a specific check whether the target is a Tunneler, because if it is, then it probably checks which state the tunneler is I suppose. But it's probably bugged hence it never attacks it. Now, because it is just a compare, I could just skip that and not tell the program not to think about it as a Tunneler, however, that could bug it out probably... like the ballista would fire at it even if it was digging a tunnel maybe? Not sure, gotta investigate it.

**Comment by LordHansCapon** [comment]
Well, it looks like it has NOTHING to do with the Tunneler's state, and I can't get my head around what the hell is it even doing. Simply making the Ballista to attack the tunneler works fine. So I think I'll be patching that as I see no bugs occuring.

**Comment by LordHansCapon** [comment]
@Admiral-Gumpert I have added the option to fix the tunneler bug, you can get the latest build here:
https://we.tl/t-snrpLFdpIL

If you notice any new bug related to tunnelers, please let us know.

**Comment by J-T-de** [comment]
That was fast, very nice!

**Comment by Admiral-Gumpert** [comment]
> @Admiral-Gumpert I have added the option to fix the tunneler bug, you can get the latest build here:
> https://we.tl/t-snrpLFdpIL
> 
> If you notice any new bug related to tunnelers, please let us know.


Thank you so much , That was faster than what I thought haha , I will tell if I find any bugs about it

**Comment by Admiral-Gumpert** [comment]
> It was only fixed for monks, so this is something different. (As far as I remember, the fireballista also does not target civilians, but I could be wrong). This is definitely something fixable, as it was already fixed for monks.
> 
> Regarding firebalista in general: Is there a known priority list, like ranged units have (1. other ranged units, 2. melee units, 3. civilians)? Maybe one could 'just use this'? (or even switch 1. melee units 2. ranged units). What is for AI the priority for burning down buildings?
> 
> Regarding a hexeditor, the goto is probably Cheat Engine (okay, it is not a hex editor in the sense, but it is the thing you want to use). When I find some time I will write a small Intro. See #488 and especially [#488 (comment)](https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/488#issuecomment-574815006)

Answer to your Question : Yeah but it changes depending on the player or the AI as Starshine575 said , And in general fireballista will shoot any ranged unit first I think.

**Comment by Admiral-Gumpert** [comment]
![image](https://user-images.githubusercontent.com/50601775/73261902-13dcbd00-41de-11ea-8f94-be90f2205e40.png)
It works like a charm ! Much appreciation

**Comment by JuGGerNaunT** [comment]
@LordHansCapon you just replaced unique fire ballista targeting behavior with common one. Monk fix is useless with this one.
btw
https://github.com/Sh0wdown/UnofficialCrusaderPatch/blob/master/UnofficialCrusaderPatch/CodeBlocks/u_ballistatunneler.block
just to avoid misleading, ballista is another machine that is placed on top of square and round towers.

**Comment by LordHansCapon** [comment]
@JuGGerNaunT Thank you! Looked into it and instead of overriding the targeting behaviour, I just change the tunneler's ID when targeted to a different unit's.

**Comment by Krarilotus** [comment]
@JuGGerNaunT what would it take, to get you on board with the UCP, bringing all those nice features of your v1.3 mod to it?

**Comment by ByBurton** [comment]
Yeah, those features in that mod are so awesome. Especially the aiv viewer.

**Comment by JuGGerNaunT** [comment]
@Krarilotus UCP is very limited in what is possible to do with such approach that it uses (patching game executable file). Besides, I can work only with v1.3. All memory addresses i have are for this version and I can't afford myself to waste time on searching AOB to support other versions, even Extreme v1.3. But I don't see a problem here, since UCP is mostly targeted on AI improvements and shcplayer mostly on multiplayer improvements (at least that was my initial idea). They barely intersect each other, so I think such separation is pretty fine.

**Comment by Krarilotus** [comment]
@JuGGerNaunT ah yeah, that explains everything. Tho could you patch in Full HD for Multiplayer and the feature with the siege equipment? To build up those siegetents? Maybe even making moat respond faster and not lag while placing it, leaving ugly gaps...

but who am i to complain... I just wish there was a mod for both at once, as i love to play multiplayer with AI aswell :D Maybe thats rare tho.

**Comment by J-T-de** [comment]
Yeah, but maybe some cooperation on the intersecting parts (your multipatch; UCP general bugfixes) might be interesting... But I fully respect that you are doing your own thing, and you already helped the UCP and other projects in the past, so you did your part ;)

(amazing levels of off-topic reached ^^ )

**Comment by ByBurton** [comment]
@JuGGerNaunT The UCP is first of all a bugfix patch. So if you could help us with any of all your awesome bugfixes it would be really appreciated (e.g. your fix for the apple orchards, the bakers being stuck)
