### ISSUE TITLE
Strongholdify - slower peasant spawning

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#510]
@J-T-de  Could you also try adding the option to disable the faster spawning of peasants in skirmish matches?

I've noticed that in missions or Stronghold 1 the peasants spawn slower. I kinda like that. 
Right now it seems even on low popularity (< 60) peasants spawn faster than on high popularity (> 80) in a mission.

**Comment by J-T-de** [comment]
I will take a look into it soon, I already have an idea how to introduce it ;)

**Comment by ByBurton** [comment]
@J-T-de Thank you so much! <3

**Comment by ByBurton** [comment]
@J-T-de I'm gonna close this issue. If you have future plans / issues please open up a new one. I love you for this.
