### ISSUE TITLE
AI wave attack

### ISSUE THREAD

**Issue by LordDerMoff** [Sh0wdown/UnofficialCrusaderPatch#53]
To fix the entire pathfinding of stronghold crusader, there is no way to do this by editing some hexdata in the exe. BUT maybe there is still some tweaks possible to improve a couple of things:

1. The AI always attacks in stupid waves... seems like there is a maximum of one attacker per wall at anytime. As much as i like those big endgame armies, as usless they are if you always just have to shoot down a group of 50 at the same time. If the ai counts one man per wall, would it be possible to buff this as something like 5 per wall? Sadly this would overpower our little candle infidel to some kind of industrial pyromanic INFIDEL!!!. So if by chance there really is a tweak for the number of waves it would be awesome to limit them to 2 or 3. 

(2. The engineers should build there siege equipment just outside the usual range of a mounted ballista. It would be important to know IF and how the ai decides where to place the siege equipment. If it does it by evaluating the distance to the nearest wall this could be quite an easy task, else just forget about it...
PS: those tents should have some space aswell - two siege engines are better than one with a nice little tent to it side)

(oh and assassins actually USING there ability to climb rather to try scratching down a stone wall with a simple sword) 

(double oh, just attacking the nearest opponent instead of walking through the enemies line, to finally attack with one lonely half dead ladderman. I know this somehow touches the caracteristic of the different ais, but to be honest to implent this caracteristic firefly should have handled the pathfinding issues in advance) 

Gracias!

**Comment by Swartonf** [comment]
Today i've made some 1-1 AI fights. Saladin was using armies with 200+ men. But he attacked with about 7 fighters at once.  That is the biggest wave-splitting i've seen so far o.O
