### ISSUE TITLE
UCP discord server : announcement

### ISSUE THREAD

**Issue by Krarilotus** [Sh0wdown/UnofficialCrusaderPatch#539]
This issue will just be up here temporarily, to announce the official UCP discord. A place to take your discussions to a faster form, so we can use the issues section for what it was actually ment for: issues. That are bugs in the game and the patcher, and future project ideas. We will sort those out in the near future, and if you still find things, you are always wellcome to put them up here. We just want to reduce dublication and the amount of stuff posted here, that way we can actually focus on getting more done and searching for what was mentioned where and how to find all the great ideas in here less.

So here is the link to the discord:
https://discord.gg/vmy7CBR

I also want to tag some people i know who might want to join:
@LordHansCapon @J-T-de @cjp-luany @Truetobi91 @Russianstory @Zelenium @PitchNeeded

you can also inform your friends who use the patcher to join there, or anyone who has any input or wants to discuss how to improve and move forward, before having their topic worked out to a point, where they can create an issue with the fundamental information. The discord is also a place to ask basic questions, that we have seen often pop up here, like how to use and setup the patcher. If you cannot figure things out by yourself, you might aswell check the wiki or the discord for that.

**Comment by forestleaves** [comment]
aha

**Comment by ByBurton** [comment]
Server is not ready for public yet. Will reopen it later. @Krarilotus please remove the link for now.
