### ISSUE TITLE
Update wiki for latest implementations

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#540]
E.g.: The commandline / gui split with the additional dll might require additional installation instuctions.

**Comment by Krarilotus** [comment]
put it on my List :D
Definitly up before next release!

**Comment by J-T-de** [comment]
What would be cool if there would be version control for the wiki, so everybody can propose changes or writes some new articles...

**Comment by patel-nikhil** [comment]
That's basically one of the main purposes of github pages (as I proposed in the discord)

**Comment by patel-nikhil** [comment]
This can be closed now, with the new website, which contains installation instructions and is version-controlled using the gh-pages branch

Will add link here for anyone who may come across this issue in the future:
https://sh0wdown.github.io/UnofficialCrusaderPatch/getting-started.html
