### ISSUE TITLE
Verweigerter Zugriff. Fehler bei der Installation

### ISSUE THREAD

**Issue by Truncatus** [Sh0wdown/UnofficialCrusaderPatch#542]
Hallo.

Ich habe Probleme bei der Installation des unoffiziellen Patches 2.13
Beim Start der Installation bekomme immer wieder diese Fehlermeldung:
![fehler](https://user-images.githubusercontent.com/21343649/75092721-e2f06d80-557a-11ea-8829-6a7f0a786b33.png)

Habe dazu schon den vorherigen Beitrag durchgelesen. Das heißt, ich habe bereits versucht, die Installation als Administrator auszuführen, selbes Ergebnis.
Heck, ich habe sogar den Ordner freigegeben, selbes Ergebnis

Ich habe das HD-Update von Stronghold Crusader Extreme auch drauf. Im Hauptmenü der normalen Version steht die Version auf V1.41, in der extreme-Variante steht sie auf 1.41.1-E.

Die Datei icp_error_dump sagt Folgendes:
_System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\Program Files (x86)\Steam\steamapps\common\Stronghold Crusader Extreme\aiv\marshal1.aiv" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   bei UCP.Patching.Patcher.RestoreAIVs(String dir)
   bei UCP.MainWindow.pButtonUninstall_Click(Object sender, RoutedEventArgs e)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.Controls.Primitives.ButtonBase.OnClick()
   bei System.Windows.Controls.Button.OnClick()
   bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
_

Würde mich über Hilfestellung wahnsinnig freuen.^^

**Comment by PodeCaradox** [comment]
Versuche mal Stronghold auf einen anderen Pfad zu installieren. Oder alle Dateien und unter Ordner von firefly Ordner frei geben. Sonst könnte noch sein das ein anderer Prozess auf die Datei zugreift während du versuchst zu patchen?

**Comment by Truncatus** [comment]
Okay. Habe nun einige Dinge getan, doch es brachte mich alles nicht weiter. :(

- Sämtliche Ordner/Unterordner sind freigegeben(hab sogar den Schreibschutz weggemacht, damit einfach nix mehr im Weg steht.
- Startete den Patch ohne und mit Administrator-Rechten
- Habe das Spiel komplett deinstalliert und wieder neuinstalliert. Sie haben auch beide dieselben Versionen wie vorher.

Ich muss noch anmerken, dass bei mir das Spiel in der Steam-Datenbank ist und somit einen  Pfad besitzt. Weiß leider nicht, ob ich den überhaupt ändern kann.

**Comment by PodeCaradox** [comment]
Wen nicht kopiere den Ordner aus dem steam Ordner(C:\Program Files (x86)\Steam\steamapps\common\Stronghold Crusader Extreme) in ein anderes Laufwerk, z. B. E:\Games und probiere diesen mit dem patcher zu ändern.

**Comment by Truncatus** [comment]
Okay. Soweit gemacht. Hab auch soweit alles mögliche an Freigabe ermöglicht, was mir bekannt ist.
Leider hat sich am Ergebnis nicht viel geändert:
![fehler](https://user-images.githubusercontent.com/21343649/75106310-7d07f280-561b-11ea-9cbb-38892f31d9c8.png)
Ich habe nun sogar sämtliche künstlichen Ordner entfernt(Wo beispielsweise Custom-Burgen oder auch der aiv-editor war). Vielleicht gibt es ne Art von Freigabe, die mir nicht bekannt ist, aber ich hatte bei nichts Anderem so Probleme. Was auch erstaunlich ist, ist dass sich der Text as dem icp_error_dump keinen anderen Dateipfad nennt außer den ersten.

**Comment by GRhin** [comment]
Have you tried running in Administrator mode?
-----------------------------------------------------------------------
Haben Sie versucht, im Administratormodus zu arbeiten?

**Comment by Truncatus** [comment]
> 
> ## Have you tried running in Administrator mode?
> 
> Haben Sie versucht, im Administratormodus zu arbeiten?

Jepp. Sowohl ohne als auch mit Administrator-Rechten

**Comment by Truncatus** [comment]
Sorry für den Doppelpost. Aber ich habe es gelöst bekommen.
Aus einem mir nicht wirklich ersehenswerten Grund wird beim Starten von Steam automatisch eine Instanz von Stronghold Crusader gestartet, die aber....wie soll ich sagen...nicht ausführt. Also kein schwarzer Bildschirm, der dann ins Spiel übergeht. Auf diese Weise blieb die ganze Zeit eine Instanz bestehen, nachdem ich das Spiel einmal selbst gestartet und später wieder beendet habe, weshalb auch der Fehler kam, dass etwas bereits auf das Spiel zugriff.

Ich konnte nun den Patch installieren. :dancer: 

Vielen Dank für eure Hilfe. :)

**Comment by Krarilotus** [comment]
issue has been resolved, you can join our official discord server by following this link, for any further questions:
https://discord.gg/vmy7CBR
