### ISSUE TITLE
UCP document structure changes

### ISSUE THREAD

**Issue by Krarilotus** [Sh0wdown/UnofficialCrusaderPatch#544]
how to update our document structure for the Patcher going forward, i suggest this:
We won't have an aic folder inside the Crusader folder anymore but:
- use a 'ucp' folder as the download that you get when you download the patcher (exctract it from a zip), which is the folder where the patcher sits in.
-> You would just copy that into your stronghold Crusader directory. 
-> UCP would then read the path of your installation automatically as its already in the right location.
->You could name the ucp folder any name you want, ucp would detect the parent folder and set it as path for the game if the Stronghold Crusader exe is found.
->Else it asks for the path, and you hand it to it.
- The UCP will then create a sub folder for each configuration cathegory we have. So currently an aic folder and shortly coming an aist or aistart folder for ai starting configurations.
-> We could easily extend for each type of config, like units for unistats changes or buildings for buildings stat changes and so on and forth
-> it would make it easier to have multiple aic folder up and switching between multiple configurations without renaming any folder
-> its easier to handle for the user, who wont just leave his ucp.exe in the downloads folder, getting confused each time someone mentions a config or wants to set them up for a multiplayer game
-> command line would just work well with this, as it could relate to the structure much easier if its all in one place.

To convert old aic's into the new json format aswell, organizing it like this is my proposal for that:
-> Make a button on the AIC-tab (next to refresh): add older version UCP  .aic files.
-> you just get prompted with a select file window where you then select a folder from which all subfolder's aics will be taken and converted and put as jsons into your new folder
-> that way you never get autopromted or anything, users can easily get their old files, and you would never worry again.
-> it would not bother anyone who didnt use previous versions an its giving backwards compatibility without extra trools needed.

**Comment by GRhin** [comment]
Can you put the paragraph starting "To convert old aics...." into another issue? maybe one that addresses the change to json format as well (this is the first mention of json format on the github project). Currently that paragraph is unrelated to everything prior to it or the issue title.

**Comment by GRhin** [comment]
Can be closed with new release
