### ISSUE TITLE
How can i add more than 40k money to myself or to the AI? IF the patch doesnt include it, iam suggesting it as a new feature!

### ISSUE THREAD

**Issue by raix28** [Sh0wdown/UnofficialCrusaderPatch#550]
So im doing AI 1v1 videos but money is sometimes the problem, i want to add more than 40k sometimes!

**Comment by J-T-de** [comment]
The patch does not include this feature yet.

However, the starting gold parameters (as well as starting units and starting resources) are already identified and will be included in future versions of the UCP. If you know how to use CheatEngine, you could simply cheat some gold as intermediate solution (and if you are more proficient in CE, you get all addresses out of [CrusaderData](https://github.com/J-T-de/CrusaderData/blob/master/data/crusader_data.CT)).

**Comment by Truetobi91** [comment]
You can also use custom maps and edit them. Place a few cathedrals and destroy them again, effectively adds 500 gold each time to that specific position that is being add to any starting gold value.

**Comment by Krarilotus** [comment]
this is now done and merged.

**Comment by GRhin** [comment]
Can we close only after it is released?

**Comment by Krarilotus** [comment]
hm? i thought we should close things that are done, as its not an issue. You can still view it here in the closed issues.

**Comment by GRhin** [comment]
Raix can still not do what he wanted to do until the next release, so for
him, it is still an issue...

**Comment by raix28** [comment]
GRhin has a point though, my videos are on a hiatus as its a big problem!
