### ISSUE TITLE
Webpage for UCP?

### ISSUE THREAD

**Issue by patel-nikhil** [Sh0wdown/UnofficialCrusaderPatch#555]
I have proposed a simple webpage design for UCP [here](https://patel-nikhil.github.io/UnofficialCrusaderPatch/index.html). Complete with [installation instructions](https://patel-nikhil.github.io/UnofficialCrusaderPatch/getting-started.html), information on aic values, contributing info, and all the current wiki information.

It can be put under version control in this repo by using gh-pages branch (will be separate from the rest of the code base)

**Comment by J-T-de** [comment]
Definitely yes!

Due to the technical limitations, the wiki sadly sucks. Additionally I see new people getting lost if they do not directly land on the github releases page with the way too small download buttons. Maybe put the mod additionally on moddb.com for more people to notice this project?

**Comment by patel-nikhil** [comment]
Glad you like the idea 😃 
If help is needed with initial setup, let me know here or in discord.

If yourself or anyone wishes to contribute to a section, or suggests feedback or adding of a new section -> feel free to let me know and I can add it in :)

Regarding moddb.com, I am not familiar with it, but at a glance sounds like a good idea, perhaps around the timing of the next release.

**Comment by Lolasik011** [comment]
> I have proposed a simple webpage design for UCP [here](https://patel-nikhil.github.io/UnofficialCrusaderPatch/index.html). Complete with [installation instructions](https://patel-nikhil.github.io/UnofficialCrusaderPatch/getting-started.html), information on aic values, contributing info, and all the current wiki information.
> 
> It can be put under version control in this repo by using gh-pages branch (will be separate from the rest of the code base)

Wow!
Thank you !!!

**Comment by GRhin** [comment]
It's not responsive...

**Comment by patel-nikhil** [comment]
@GRhin added sizing breakpoints and fixed word wrap on buttons - should look fine on mobile now except for the AI Personality Values page (/aic/detailed.html). Not sure why the table breaks it so badly. Have to look into how to fix that.

On desktop should be fine though.

**Comment by patel-nikhil** [comment]
Updated the features page to include descriptions of all the different selectable features in the UCP.

I'm no expert at localization unfortunately. I could add say, a dropdown to allow language selection but not sure of a good way to choose and populate text (especially if formatted into a list) based on language. Unless someone comes with an idea it'll stay English-only for time being.

Pages left to add content to:
- Add in the values for aic enums such as FarmBuildings, etc.
- The entire aiv section as I have very little experience with aiv editor
  - If someone could write a few paragraphs would be awesome
- FAQ section
  - I can think of one common question to put in here (increasing map size past 400x400 to which answer is currently no). 
 - More content is better so if you have some to add, then great

**Comment by GRhin** [comment]
Faq should be more along the lines of
- "does this work with multiplayer?" A: yes, as long as everyone playing
has the same options selected
- "Can you include such-and-such a feature" A: search in the issue section,
if it hasn't been asked, ask away. If a developer likes the idea they may
look into it, no promises though.
- "Im a programmer how can I get involved?" A: look through the issues and
find ideas you want to fix or implement. Follow this link to a getting
started article for our codebase.
- "Am I allowed to modify this for personal use?" A: Of course!
- "Where can I get community ais?" A: there are a few bundled with the
installer, or you can check out the content creation channel on our discord
- "I'm not a programmer, is there any other way I can help?" A: testers are
always welcome. Let us know in discord if you want to test. If you follow
this github repository you will get an alert when someone submits new code
to be used. See what the code is supposed to do, ask for an installer, and
test the changes in game to ensure it works as intended.
- "is there a tutorial on how to make my own AIs?" A: there are a few,
check this one out by krarilotus (if there are others link them here too)
- "I'm having trouble installing, can anyone help?" A: of course, pop into
discord and ask on the help-and-issues channel.

Those are just off the top of my head. Of I think of more I'll message you
on discord.

**Comment by patel-nikhil** [comment]
Good ideas, I've updated it.

Yes, @Krarilotus has a fairly in-depth video tutorial for aic and aiv creation that's objective (ie. no advertising, etc.) and therefore suitable - I hope you don't mind me embedding it in the page (I can remove or link it if you'd rather not)

I'm not aware myself of any other videos/tutorials for aic/aiv creation. The page written by Kimberly in the wiki is good, however would like to update the images to reflect the json changes before putting it in

**Comment by Russianstory** [comment]
Sorry to interfere. Tell me please what is the latest information on UCP? Will there be continued work to improve UCP. I just need information.

**Comment by J-T-de** [comment]
we are currently working on it, we are planing to release an update soon (TM)

**Comment by Russianstory** [comment]
Dear friend! Tell me please, what exactly will you add and correct in the new version of UCP? Where can I read the new?

**Comment by GRhin** [comment]
You can see from the tickets that many new features are being worked on for next release. When it is released you can get it from the same place you got the current release. If you have questions please ask on a new issue instead of taking an existing unrelated issue on a tangent.

**Comment by Russianstory** [comment]
Where is? where i can read and learn more. Show me. I asked Specifically. What exactly is planned and when will the release be? What is not clear?
And something that is off topic - so any message can be deleted if you still do not know about it

**Comment by GRhin** [comment]
This issue you are commenting on is specifically about the webpage. You are
asking about a new release. If there is not an issue for that, create one.
You know how to do that, you have created issue before, you dont need me to
give you instructions on how to do that.

**Comment by Krarilotus** [comment]
> Where is? where i can read and learn more. Show me. I asked Specifically. What exactly is planned and when will the release be? What is not clear?
> And something that is off topic - so any message can be deleted if you still do not know about it
@Russianstory 

You can access the webpage on the link that patel-nikhil postet.
If you want to know more prior to release of the next update of the UCP, join the official discord server. Link is on the Wiki page.

**Comment by Lolasik011** [comment]
> we are currently working on it, we are planing to release an update soon (TM)

I'll be waiting ! 
Thank you !

**Comment by patel-nikhil** [comment]
Website has been added to UCP repo in #573 - closing this issue as resolved now.
