### ISSUE TITLE
AIC JSON change documentation

### ISSUE THREAD

**Issue by patel-nikhil** [Sh0wdown/UnofficialCrusaderPatch#556]
Documentation will need to be updated to reflect upcoming aic change to json format and should ideally be present at same time as the changes come into effect.

Brief summary of changes:
- AIC files will now be in JSON format and have file extension .aic.json
- **Inside the aic file the naming of fields must be correct (match the documentation, and documentation will be updated as applicable) and also values with confirmed and well-defined ranges are now given sanity checks**
- **The files must be placed within an aic subfolder of the same directory that the patcher is in**
- The patcher will provide you the option to convert old aic files to the newer format
- The patcher will support selecting individual AIs from the aic file

*Note: this summary is of changes currently in a PR and in testing, and is not a promise of functionality until it has been tested, approved and merged.*

Builds on issue #544 and the aic change is in PR #551

**Comment by patel-nikhil** [comment]
Adding an update to this issue to reference PR #551 which has now been merged into master.

- Adding the ability to select individual AI characters has been postponed
- The use with the patcher the AIC files must now be placed within a 'resources\aic' subfolder of the patcher. i.e. If you have the UnofficialCrusaderPatchGUI.exe in 'Desktop' then AIC will go into `Desktop\resources\aic'
- There will be a red button shown when the patcher detects a .aic file using the previous format. Click that button for a prompt to convert your AIC file to the newer JSON format. The .aic file will be renamed to .aic.bak and a new file named <your filename>.json will be created. Click refresh and you will see the file in the patcher

-Alternatively when there is a new release (or if you build the project yourself) you may use the AICUpdater.exe to convert one or multiple .aic files to the newer json format

- The ability to select multiple AIC definitions is still there. If you select multiple then they are given priority in the order they are selected and conflicting AIC will have a yellow box shown to the right which if you hover over it will show which AIC from it will not be used

- The AIC descriptions shown in the patcher are now limited to 1000 characters and use the key AICShortDescription within the JSON file, and the descriptions go in there per language ie. 

```json
"AICShortDescription": {
	
  "German": "Dies is die ungeänderte .aic-Datei von Crusader.",
  "English": "This is the .aic file from vanilla Crusader.",
  "Polish": "To jest plik .aic z oryginalnego Krzyżowca.",
  "Russian": "Это файл .aic от ванильной Stronghold Crusader."

}
```

**Comment by GRhin** [comment]
Can be closed with new release
