### ISSUE TITLE
Boosted to the maximum AI

### ISSUE THREAD

**Issue by Rakso69** [Sh0wdown/UnofficialCrusaderPatch#56]
I decided I'll move this post here, on a new topic, so it might be more visible, and perhaps there is going to be a discussion underneath.

I think that additionally to the patch there should be added a mini-mod to-mark option allowing one of the AI lords to do it's absolute best to the maximum of modding possibilities(being capable of doing all troops and using multiplayer-like gameplay economic behavior, additionably if possible: act like a smart online human-player).
Myself I've had such a thing in mind 2 years ago. That's when I've made a Wolf AIV manage to do a prospering 250 population economy consist of 54 workshops, 10 breweries, 10 Inns and both cathedrals. All this stuff mixed alltogether had allowed him to gain tons of gold quicky by running whole game on between -22 to -24 tax, selling also the over-produced weaponry and apple baskets - gathering a whole ton of these even on such a high population, by tricking their income and consuption through accurate regular purchase of cheese and bread.

PS: A wolf capable of doing bread would be even better and more fitting for most maps. Sadly his behavior doesn't allow him to build wheat farms. Even if I place these for him directly in the map editor he declines using the wheat, taking rid of by selling it immediatly as quickest it gets dropped on the stockpile, causing bakers doing nothing whole game.

At any case, he was capable or earning more gold than current top online players! when I was testing him play against them. Definately -24 tax whole game on 250 pop is more efficent than -24 tax on 460+ pop for a while period of time.

READ THIS:
I know how alot of players don't enjoy the hardcore-like stuff and multiplayer pro way of gameplay, but I think that modding shouldn't be limited only for singleplayer-fans. I don't insist on buff a "regular or Evrey's mod" Wolf to the maximum, but (I repeat), as a mini-mod to-mark on the installer option for the part of the community, which simply is being too good for singleplayer AI-fighting, as a great additional challenge to exercise on.
I'm aware that a challenge might aswell be achived by playing AI 1vs7, but having a strongest possible AI in a 1vs1 environment, that could work for itself on a better way than the 7 allied alltogether definately looks better and less messy.

Think about that, how great would it be to modify an AI to play better than even the greatest multiplayer legends to walk across this game from over a decade back, like: {{DHK}} HolyLord, Gx_S0ck3tz`, @rm@, XXoDDu$$, FireDragon, Bartholo, Luis7, Blacky... and way more... These do not play anymore, but remained in memory as icons of multiplayer passion and addiction to develop all possible aspects of gameplays.

Slowly more and more players are playing with each next year. Even if they do so, they're taught already differently, than they would be past on Gamespy Arcade, in the community of the upper mentioned.

Knowledge about the game is also dying. On 2007 probably 99% of possible in-game bugs were discovered. Now probably 1/3 of these got fogotten.

Creating a challenging AI opponent playing at the peek level of any of the old top players would surely bring interest to the game, and the mod. Similar situation as in Chess with Kasparov vs Deep Blue AI, where AI first time whooped a legend's butt :)

That's my own old Wolf. I won't share him yet, as now as I have just seen this Unofficial Patch going on, I'll be up to come back over my 2 years old works over him to provide him a couple multiple variations of this castle to be fitting on more maps. For now You can see my 2 years old Wolf pictures over here dealing with the Rat on the only 400x400 map in the game I was working over him. His eco & stats.
(They started from 3000 gold both. I would have 40k, but I self-suicided myself with lions)

The biggest flaw of my Wolf AIV for the current moment is exacly that he isn't flexible to being capable of playing efficently on other maps and some gold settings. He works great and efficent on any starting gold except for 40k, where he tends to spam buildings so fast, that the Inn workers don't come and without them raising up his popularity and taxes in order to expand quicker gets lost...

So I'm going to emphasis my AIV editing over making him multiple-map compactible, by making more versions of his AIV files(Curretly he has still one) on my free time. Especially fit for the multiplayer maps such as EventMap07 or Aw-lub. Any tips from higher experienced AIV editing professionalists especially welcome! Cheers.
![wolf1](https://user-images.githubusercontent.com/45049934/48720391-e54d7480-ec1f-11e8-8b13-2f1532e4907f.jpg)
![wolf2](https://user-images.githubusercontent.com/45049934/48720406-eb435580-ec1f-11e8-81d8-88610e9695bf.jpg)

**Comment by Lolasik011** [comment]
0_0 Beautiful idea !!!

**Comment by PitchNeeded** [comment]
> 0_0 Beautiful idea !!!

Yes but I think each AI should still have its own identity and not create just any troops. It would be nice if there was a hard mode though for AI with the use of portable shields on towers for AI eventually.

**Comment by Lolasik011** [comment]
And I am for the almighty AI. But I can not imagine it on ordinary maps, since it is large and may not fit on the map.

**Comment by Mizo5119** [comment]
I really dont want to offend you, and this is probably a bias and a subjective opinion, but why does every player builds on multiplayer builds their castles like a freaken factory, and not well an actual castle? :D

**Comment by Sh0wdown** [comment]
That's a bit to specific imo, I'd rather improve the AIs in general.
