### ISSUE TITLE
PEOPLE WANT TO KNOW!

### ISSUE THREAD

**Issue by Russianstory** [Sh0wdown/UnofficialCrusaderPatch#562]
Yes, yes, we want to know what plans the esteemed Showdown has about continuing the modding of UCP and the game of Stronghold Cruzader 1 itself?
I, and we will all be very happy if you tell us
What will be real (specific) in the new fashion?
What are you really planning to do yet?
Will you take into account the opinions and ideas of the community on certain issues? (Well, I have a lot of such ideas in my discussion thread)))).
Yes, sorry for the translation through the translator.

I will be very grateful to the author of the mod and those who really help him if you tell as much as possible about your mod and about the nearest plans. =)

**Comment by ilosevsrat** [comment]
They gonna add new bot in upcoming Patch,  Richard LemonHarth, he is weaker than Rat but more Agressive than Caliph, he attacks with mass Shields and Woodcutters (backed up with Hunters)

**Comment by J-T-de** [comment]
Sh0wdown is currently not working on the project, but new devs are. I think there are many hints scattered around the different issues what comes next, and with the latest [commits](https://github.com/Sh0wdown/UnofficialCrusaderPatch/commits/master) you might guess what actually is going to be implemented ;)

The problem with stating what changes come when is, that people get their hopes up and if things don't go as planned, people get sad/upset/angry... this is why noone of the devs makes any fixed statements. Sh0wdown left some big shoes to fill, but I guarantee it, we will do so ;)

And I come out of cover: Release is very soon!

**Comment by Lolasik011** [comment]
@J-T-de Thank you for not quitting your work  patch.

@ilosevsrat :) 

@Russianstory Зайди в Дискорд группу там вся инфа по Патчу и последние Тестовые сборки. Да и попроси у Krarilotus или Kimberly чтобы они тебе дали роль тестера !

**Comment by Krarilotus** [comment]
@Russianstory i would love to see you on the discord server of the patcher. You can find an invitation link on the front page of the Wiki or on the readme when you open the github page itself.

**Comment by Russianstory** [comment]
@Krarilotus I D LIKE TOO))) where is ?

**Comment by Krarilotus** [comment]
@Russianstory 
> @Krarilotus I D LIKE TOO))) where is ?

> You can find an invitation link to the discord on the front page of the Wiki or on the github wiki page

just click on that :) you are wellcome!

**Comment by GRhin** [comment]
I think this can be closed now that the a new release is out.
