### ISSUE TITLE
KI reißt alle Gebäude ab (Version 2.05)

### ISSUE THREAD

**Issue by Dark-Delu** [Sh0wdown/UnofficialCrusaderPatch#57]
Hallo,
es scheint, als ob bei der Funktion, das Abreißen von Gebäuden zu deaktivieren noch ein Fehler vorhanden ist. In einem Test den ich startete um die neuen Änderungen sehen zu können, haben 2 KI's (Richard und Abt) alle Gebäude, einschließlich Bergfried, abgerissen. 
Fehler war bei mir reproduzierbar. Anbei eine Savedatei, die kurz vor dem 2. mal erstellt wurde. 
Im Save beim Abt zu beobachten (etwa 10 Sekunden nach dem Save).

Neueste Version natürlich installiert und Funktion auch mit installiert.

[Test.zip](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/2597617/Test.zip)

Freundliche Grüße DarkDelu

**Comment by Sh0wdown** [comment]
Danke, da hab ich wohl nicht lang genug getestet. :P

Mit diesem Hotfix sollte es nun funktionieren wie geplant:
https://github.com/Sh0wdown/UnofficialCrusaderPatch/releases/tag/v2.05a

**Comment by Evrey** [comment]
Kleiner Nitpick: Nach [SemVer](https://semver.org/) kommt die Version `2.05a` vor `2.05`. Solche Anhängsel sind für Test-Versionen. Korrekt wäre hier `2.05.1`.
