### ISSUE TITLE
Schwarze Spielerfarbe, Tribokmannschaft blau (Version 2.05)

### ISSUE THREAD

**Issue by Panaminion** [Sh0wdown/UnofficialCrusaderPatch#58]
Hey, ein echt toller Patch! wie der Titel bereits sagt ist mir nur aufgefallen dass bei schwarzer Spielerfarbe die Baumeister wenn sie ein Tribok bemannen blau werden.. vermutlich ein einfacher "Farbendreher"? 

Viele Grüße und ich hoffe es hilft :)

**Comment by Sh0wdown** [comment]
Stimmt, und blaue Baumeister werden schwarz. Danke für die Info, gibt bestimmt noch ein paar kleine Stellen an denen die Umfärbung noch nicht ganz richtig ist, die mir nicht aufgefallen sind.

**Comment by Sh0wdown** [comment]
Wird mit dem nächsten Release gefixt.
