### ISSUE TITLE
About messages from Rat, Snake, Pig and Wolf!

### ISSUE THREAD

**Issue by raix28** [Sh0wdown/UnofficialCrusaderPatch#581]
You know when sometimes they message you and its the Servant, maybe you can find a way for their own quotes( i mean the binks also)! You guys can take quotes from stronghold 1 and make them somehow fitting, i think its a good idea!

**Comment by ByBurton** [comment]
We have like ten open issues wishing for this or kinda this.
Please make an effort looking through all the existing issues before posting in the future. 

I'm closing this.
