### ISSUE TITLE
Erhöhen des Truppenlimits für KI-Angriffe

### ISSUE THREAD

**Issue by J0J0Jo** [Sh0wdown/UnofficialCrusaderPatch#6]
Ganz nach Udwins Idee: Es wäre super, wenn das Truppenlimit eines jeden Angriffs durch die KI deutlich erhöht oder an das maximale Truppenlimit des Spiels angehoben werden könnte. 

Nochmal im Namen aller Crusader Fans, Danke für den tollen Mod.

**Comment by ByBurton** [comment]
Ist doch bereits hinzugefügt. Nur nicht in der Release-Version.

**Comment by Swartonf** [comment]
Wie kann man denn darauf schon zugreifen? Sehe nur einen Code.

**Comment by ByBurton** [comment]
>           Wie kann man denn darauf schon zugreifen? Sehe nur einen Code.

Hast du Visual Studio installiert? Wenn ja, dann einfach kompilieren, nachdem du die Evrey Burgen in den richtigen Ordner kopiert hast.

**Comment by Swartonf** [comment]
Dafür bräuchte ich wohl erst eine genaue Anleitung :D

**Comment by ByBurton** [comment]
Downloade die zip von dem Patch hier und entpacke sie. Öffne in dem Ordner die .proj datei (oder .vsproj?). Dann öffnet sich visual studio und die Projektmappe. Dann klicke mit Rechts auf das Unterprojekt Unofficialpatch oder so, und wähle "build" oder "rebuild".

**Comment by Sh0wdown** [comment]
Gibt jetzt auch ein Release zu dem Feature:
https://github.com/Sh0wdown/UnofficialCrusaderPatch/releases/tag/v2.02
