### ISSUE TITLE
AI raids

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#60]
I know this has been discussed a bit elsewhere but some of the AIs need to send more troops in raids they send to destroy quarries, mines and farms etc. . Marshall, Phillip, Emir and Wazir are all excellent raiders who send strong forces of raiding troops and their raids are good enough as they are, but some of the other lords could do with a boost to numbers of raiding troops they send at one time, particularly Lionheart who only sends a couple of pikemen at one time to raid. Perhaps it wouldn't be in Lionheart's personality to send big raiding groups (as of course he prefers sieges) but it would be nice to increase the number of pikemen he sends on a raid a bit.

**Comment by Lolasik011** [comment]
I would like to see this...

**Comment by PitchNeeded** [comment]
Even Rat should send bigger groups of spearmen to try and destroy quarries I think! :D  (they are only spearmen after all and easy to counter with archers so wouldn't make Ratty too good a player for his character).

**Comment by Heroesflorian** [comment]
On a similar note: Saladin only sends horse archers for the same purpose (economy raids)... who priorities hostile troops (including those on enemy towers) over hostile workers, and do not attack hostile buildings at all. 
It would be awesome if he'd send some slaves or swordsmen alongside his horse archers, to actually attack hostile economy buildings.

**Comment by PitchNeeded** [comment]
> On a similar note: Saladin only sends horse archers for the same purpose (economy raids)... who priorities hostile troops (including those on enemy towers) over hostile workers, and do not attack hostile buildings at all.

Indeed, same with Wazir and Wolf too who also send horse archer raids, and Sultan with his slingers, although they do manage to kill some workers sometimes.

> It would be awesome if he'd send some slaves or swordsmen alongside his horse archers, to actually attack hostile economy buildings.

Great idea!  It would also be good if Sultan could send some groups of Arabian swordsmen occasionally too to try and destroy enemy buildings.

**Comment by PitchNeeded** [comment]
> It would be awesome if he'd send some slaves or swordsmen alongside his horse archers, to actually attack hostile economy buildings.

Was watching an AI only match last night and Saladin did send a few Arabian swordsman to destroy an enemy farm. So it can happen. I think though they weren't an intended raiding party, but a counter attack force responding to an archer attack on his own farms.

**Comment by Sh0wdown** [comment]
More raiding also means less investment in attack forces though.

**Comment by PitchNeeded** [comment]
> More raiding also means less investment in attack forces though.

Lionheart only needs a few more pikemen in his raids I think then as he still needs to siege frequently, to go with his character, even a few more pikemen would make his raids more effective than they are currently.

Abbot and Sheriff however could afford raiding groups double the size they are currently as they have excellent economies (and Sheriff doesn't like to siege that frequently anyway really).

**Comment by Heroesflorian** [comment]
> and Sheriff doesn't like to siege that frequently anyway really

When he has enough gold and either a constellation where he does not lose a lot of crossbowman patrols, or increased recruiting speed to compensate for that, then even the Sheriff attacks quite frequently. 
He has bigger attack forces than some other AI characters from the start (similar to a Saladin), thus he isn't the AI that attacks most frequently, but still quite frequently when he can. 

---

>On a similar note: Saladin only sends horse archers for the same purpose (economy raids)... who priorities hostile troops (including those on enemy towers) over hostile workers, and do not attack hostile buildings at all.
It would be awesome if he'd send some slaves or swordsmen alongside his horse archers, to actually attack hostile economy buildings.

And I just searched open (and closed) issues as I had thought I had mentioned assassins as another potential harassment / raiding unit for Saladin as well somewhere, but didn't find anything... hmm... anyway, I just thought of this topic here again when I saw this in a game (orange is Saladin):
![image](https://user-images.githubusercontent.com/12549394/50740732-24954c00-11f3-11e9-8a73-3f40a34cb178.png)
During siege attacks, Saladin used slaves, assassins and part of his swordsmen to attack the hostile economy - once the walls are breached... if Saladin used (some of) those in addition to his usual horse archers for raids as well, he would be just so much better!

**Comment by PitchNeeded** [comment]
I think Saladin should use various tactics for raiding, sometimes he could send slaves (combined with horse archers), sometimes assassins like Nizar, and sometimes big groups of Arabian swordsmen like Emir. It would make Saladin more unpredictable and clever.

I think Saladin should also use big groups of Arabian swordsmen to counter-attack like Emir does. Saladin only uses about 7 Arabian swordsmen to counterattack at the minute, which is a bit pathetic. Emir can often counterattack gathering siege forces effectively with his big groups of counter-attacking Arabian swordsmen and it would be good if Saladin could do this too!

**Comment by Sh0wdown** [comment]
Closing this, as it is now editable with the AIC files.
