### ISSUE TITLE
Scrambled service provider menu

### ISSUE THREAD

**Issue by davidhealey** [Sh0wdown/UnofficialCrusaderPatch#611]
It's not caused by the UCP but since you guys are the crusader experts I thought you might have an idea about what might cause this. It happened after I installed the official 1.41 patch.

![image](https://user-images.githubusercontent.com/14021202/81497845-1eb4ec80-92b9-11ea-9c8b-5e97d7ad89b1.png)

**Comment by GRhin** [comment]
Ive never seen that... are you still able to play multiplayer?

**Comment by davidhealey** [comment]
Unfortunately not, clicking the host button doesn't do anything. I should mention I'm running this through WINE on Linux Mint so I suspect something is happening there. But it was all fine before the 1.41 patch.

**Comment by GRhin** [comment]
hmmmm... could be that the updater software is not good on linux.... do you have a windows pc you can copy the original game to, then update it there, and copy the updated files back?

**Comment by davidhealey** [comment]
Actually that's how I did it, I got my friend to install and update it on his Windows computer and it works fine, then I copied the files to my system.

**Comment by davidhealey** [comment]
Just wanted to let you know that I solved the issue. I needed to use a 32bit WINE prefix, I was using a 64bit one.
