### ISSUE TITLE
Caliph weapons

### ISSUE THREAD

**Issue by HerrSpaten** [Sh0wdown/UnofficialCrusaderPatch#613]
Caliph doesnt buy weapons. Is there a way to fix this?

**Comment by Admiral-Gumpert** [comment]
Try changing "TradeAmountEquipment" values to whatever you want under caliph's config.

**Comment by Truetobi91** [comment]
And also don't forget to set the respective SellResource[Weapon] to None or the AI will constantly sell and rebuy those weapons.

**Comment by HerrSpaten** [comment]
Thanks to both of you
