### ISSUE TITLE
AI farms

### ISSUE THREAD

**Issue by Rakso69** [Sh0wdown/UnofficialCrusaderPatch#62]
If possible to do:
- AI apple orchards and cheese farms should be build as closest possible to eachother and to the granary "castle side"(quickest trail), and wheat & hop farms aswell, but closest possible to the stockpile "castle side".
(If one grass area on a map for player, then food priritized over resources in distance matter.)
- Also: In order to make the AI less annoying: It shouldn't build farms on human player location. I think best way would be set some "area range limit" based on the size of a map and ammount of players taking part in the match. Cheers :D

**Comment by Rakso69** [comment]
If AI uses apple orchards, then it should do the "Season pass" trick. It's a multiplayer strategy used to cause apple orchards workers never take a nap, but work limitless beacuse there are always atleast a little of apple tress whole time from which food could be gathered(24/7).
- Note that in Stronghold 1 it works differently than in Crusader. Here it's used to generate more apple instead Crusader, where it's used for create the "endless cycle" of seasons.
These screenshots should explain it better:
![apple blooming order](https://user-images.githubusercontent.com/45049934/48788867-04b1d380-ecec-11e8-8b2c-3a13906ac969.png)
![blooming workers effect](https://user-images.githubusercontent.com/45049934/48788878-0bd8e180-ecec-11e8-8e9f-28fb98b1b1bb.png)

**Comment by Lolasik011** [comment]
Very good idea ! 
I would like to see it.

**Comment by PitchNeeded** [comment]
> Also: In order to make the AI less annoying: It shouldn't build farms on human player location. I think best way would be set some "area range limit" based on the size of a map and ammount of players taking part in the match. Cheers 🗡
 
Although on a map like 'The Last Stand' with the player in the middle against 7 Ais they would all have to have farms quite close to the player so the range mustn't be too big.

> AI apple orchards and cheese farms should be build as closest possible to eachother and to the granary "castle side"(quickest trail), and wheat & hop farms aswell, but closest possible to the stockpile "castle side".
> (If one grass area on a map for player, then food priritized over resources in distance matter.)

It's annoying with quarries, as sometimes the AI will have a nearby stone or iron source big enough for all their quarries but still sometimes place one or more of them on a further away source of iron or stone, reducing efficiency.

**Comment by Rakso69** [comment]
@PitchNeeded It happens beacuse the AI has a "matrix" layout of placement for iron mines and stone quarries on each map at the start of the match.
If the condition isn't feetable for the matrix, then the AI ignores the stone and iron deposists totally. I'm not sure how works the matrix of stone quarries, but Iron mines placement order for an AI is like a whole map 400x400 made of only iron mines whole with 1x1 pixel distances keept between eachother. So, if Iron is placed unfitting for the matrix-mine(in the pixel passages between), then the mine won't be placed, beacuse the matrix requirement hasn't been meet.
Definately also a thing worth work on, but it's tricky, beacuse the iron mines can't be attached to eachother, as they could block entrances to them through other iron mines!

**Comment by Lolasik011** [comment]
In general, this is a very interesting idea.

**Comment by Sh0wdown** [comment]
Good idea, but too complex without source code.
