### ISSUE TITLE
Visual errors

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#65]
In the latest version I have found that a lot of visual bugs / errors occur.

![untitled](https://user-images.githubusercontent.com/25118004/48799774-4ea8b280-ed08-11e8-8fcc-fee891af12f3.png)

This happens in 2 out of 3 matches, and it also already happened in the non bugfix version of 2.5

Edit: Others encountered this issue as well.

**Comment by Rakso69** [comment]
I've noticed that changing the 1st player colour doesn't affect the colour of the trebuchet model engineers(maybe some more troops too, I'm not sure), also spawning workers firstly are of original colour, on their "showing up" phrase, and after they're ready to move, that's when their colour changes correctly as the mod settings are. It also affect of course the other player(the original one, from whoom we took it's colour for the 1st player).

**Comment by Lolasik011** [comment]
So far I have not met such a bug...

**Comment by Panaminion** [comment]
@ByBurton I encountered that as well.. but it seemed to only happen at high game speed (~700 or higher maybe)? Was that the same for you? Also: Saving and Reloading fixes it.

**Comment by ByBurton** [comment]
@Panaminion That is right. Both of your points.

@Rakso69 This issue is already opened #58

**Comment by PitchNeeded** [comment]
Poor Nizar :(

**Comment by Rakso69** [comment]
@ByBurton Oh. I don't understand german, but I'll keep in mind it would be wise to translate it before type anything. Thanks

**Comment by Sh0wdown** [comment]
Could you send me your modified Stronghold Crusader.exe where this happens via email (on my profile)?

**Comment by ByBurton** [comment]
@Sh0wdown Will do, I guess.

**Comment by Swartonf** [comment]
Thats the bug i got with the unfixed 2.05 version. Doesn't happen anymore though

**Comment by ByBurton** [comment]
> Thats the bug i got with the unfixed 2.05 version. Doesn't happen anymore though

For me it still does.

**Comment by Lolasik011** [comment]
Today I caught the exact same bug :(

**Comment by Sh0wdown** [comment]
I haven't managed to reproduce this yet. Could someone upload a save file where this happens?

**Comment by Lolasik011** [comment]
@Sh0wdown I uploaded here the link https://drive.google.com/file/d/1YyFdsIMpRlZKMKhuzev_9JPCVzt2OneJ/view?usp=sharing

**Comment by Sh0wdown** [comment]
Thank you, at least I could see it now myself. But it vanishes quickly after loading.
I am not sure what causes this. Could you who experience this, test around a bit with what Patch-Settings this happens?

I suspect one of the following settings:
- Player 1 color change
- Increase of the total/general troop limit
- Only AI mode

**Comment by Lolasik011** [comment]
@Sh0wdown Ok I'm testing.

**Comment by Lolasik011** [comment]
@Sh0wdown I tested and got Bug again :(
![bug 2](https://user-images.githubusercontent.com/41998977/48909569-af59fb80-ee7e-11e8-9a21-4fe65573f50a.jpg)
https://drive.google.com/file/d/1uiyDEwHMPQ1h5OuWuRZfpLmy_NwGfib5/view?usp=sharing

**Comment by Lolasik011** [comment]
Player 1 color change
Increase of the total/general troop limit
Only AI mode

**Comment by Sh0wdown** [comment]
Could you test whether it happens when you _only_ have "AI only mode" enabled?

**Comment by Lolasik011** [comment]
I played 1 match. There was no graphic bug. I think it happened either because of the choice of color or because of AI mode only. Because I increased the limit of troops.

**Comment by Heroesflorian** [comment]
@Sh0wdown I just tried the patch, and got the same glitches...

![image](https://user-images.githubusercontent.com/12549394/48924258-7dfd2200-eeb6-11e8-86e5-c6a8a1e7754b.png)

No color change, but "pure AI mode" as well as the increased general unit limit to 5000 (which is the default value). 

My bet would be on the unit limit, as color change would seem fully unrelated, while higher unit limit seems more likely to be related to additional "ghost units" appearing. Maybe some overflow or pooling issue?

**Comment by Heroesflorian** [comment]
@Lolasik011 I edited my above post after some further testing. 
I agree it looks as if the "AI only" mode causes the issue, and high amounts of actual units in the game may cause it to occur more frequently / easily / heavily.

**Comment by Heroesflorian** [comment]
Also, I got the "We are under attack!" message a couple times with AI-only mode - sometimes even when player red was long dead and gone. Possibly some surviving chickens got shot at?

**Comment by Lolasik011** [comment]
@Heroesflorian Yes, he gives the hidden features :) Personally, I had a graphical bug only in AI mode vs AI. In other modes, everything is fine.
We will wait while @Sh0wdown fix this problem.

**Comment by Heroesflorian** [comment]
@Sh0wdown I tested with "AI only mode" activated and without increased troop limit, and otherwise default mod settings, so far. Dunno if any of the "older" default-checked mod features are relevant, though.

**Comment by ByBurton** [comment]
@Heroesflorian Try deactivating the max. limit of units on a map (to the default ones).

**Comment by PitchNeeded** [comment]
Being able to control an AI lord's troops and 'play in co-op mode' with them is very interesting. I noticed that when I reloaded an AI only game too. This feature should be kept if possible!

**Comment by Heroesflorian** [comment]
> Being able to control an AI lord's troops and 'play in co-op mode' with them is very interesting. I noticed that when I reloaded an AI only game too. This feature should be kept if possible!

I agree this has potential. Although I'd prefer if there was a more "clean" way in future patch versions, if possible, to let you start a game that way already. Anyway... 

@ByBurton I probably won't have time for further tests for a couple days I'm afraid. But feel free to test yourself in the mean time, possibly you can find out more! :)

**Comment by ByBurton** [comment]
@Sh0wdown The last three things, which you said should get new issues are in one of the very first issues I have opened up here. It is a list of bugs I noticed. At least the quarry stockpile.

**Comment by ByBurton** [comment]
> It could be that the AI still wants money and since it cannot destroy walls or the economy it goes to the next level of destroying things, i.e. barracks and resource buildings. Maybe I should have another look at this and add even more options.

https://youtu.be/75NJ5ayozZU?t=196

Here this happened to Udwin.

**Comment by ByBurton** [comment]
Haven't had this happen since basically forever. Will close this, but if someone experiences this again I will open it again.
