### ISSUE TITLE
Announcing the mod to the community over gameranger.

### ISSUE THREAD

**Issue by Rakso69** [Sh0wdown/UnofficialCrusaderPatch#66]
@Sh0wdown 
![announcement](https://user-images.githubusercontent.com/45049934/48800574-6aad5380-ed0a-11e8-9c9e-8adfe4e40aab.jpg)
- Also: one of the players noted a compatilibity problem with players using the mod online!

- Two of popular pro players are on about to write a really large post soon: featuring probably over a hundred of known in-game bugs. Examples: Fast workers bug, Double workers bug or bakers disappearing once entering the stockpile, when there is more than an ammount of  less than 35 flour on it.

**Comment by Lolasik011** [comment]
By the way, my friend also wrote the news in VK in 6 Strongholds Group!

**Comment by Lolasik011** [comment]
And contacted the developers of GMB mod and mod Russia

**Comment by PitchNeeded** [comment]
> Two of popular pro players are on about to write a really large post soon: featuring probably over **a hundred of known in-game bugs**. Examples: Fast workers bug, Double workers bug or bakers disappearing once entering the stockpile, when there is more than an ammount of less than 35 flour on it.

Oh goodness, the patch creators are going to be busy!

**Comment by Mizo5119** [comment]
2 Things is required to be properly tested :

1 / All the settings adjusted per player are exactly the same ( Disable color picking).
2/ All the settings adjusted per player are exactly the same ( enable color picking, same color, to see what happens).
3/ All the settings adjusted per player are exactly the same ( enable color picking, different color to see if this causes network mismatch).

I have a feeling anything that is related to game speed or player color could be the reason why the game mismatches.
