### ISSUE TITLE
Bugfix small wall cost

### ISSUE THREAD

**Issue by GRhin** [Sh0wdown/UnofficialCrusaderPatch#663]
So in the original crusader (v 1.0) a small wall cost 1 at one per tile, same as a tall wall. In a later version the cost was updated so that small wall cost 0.5 stone per tile, however to this day when you place small wall it treats it as 1 stone per tile, so if you have 12 stone, you can only place 12 tiles of small wall at a time, let go, and you have 6 stone left, place 6 tiles, have 3 left, and so on.
Can we fix it so that we can actually place all the small wall we can afford? So 24 tiles when we have 12 stone.

**Comment by LordHansCapon** [comment]
What do you mean? I have a 1.41 HD client which asks for 1 stone per 4 small wall tiles.

**Comment by GRhin** [comment]
I got the numbers wrong. Test how much low wall you can place with 12 stone (1 ox delivery) or even 10 stone. If its 4 tiles per stone, then you will only be able to place 24, or 20, tiles, even though you have enough stone to build double that

**Comment by Krarilotus** [comment]
this will be released with the next version.
