### ISSUE TITLE
Richard ist weird

### ISSUE THREAD

**Issue by TheSnowyChickens** [Sh0wdown/UnofficialCrusaderPatch#67]
Hi,

seit dem Patch von Heute stelle ich fest, das Richard irgendwie anders ist:

- er baut 0 oder maximal **eine** Eisen Produktion

Patch: 2.5 - hotfix
Getestet auf 2 verschiedenen Maps mit unterschiedlich großem Eisen vorkommen.

**Comment by Sh0wdown** [comment]
Also bei mir nicht. Schonmal die Maps ohne Patch oder mit anderen Einstellungen getestet?

**Comment by TheSnowyChickens** [comment]
Auf der Map: "Grenzpatrouille" (das meine lieblings Map ist), ist mir das zuerst aufgefallen (das er nicht eine Mine baut). (im Patch 2.04 war da alles normal)

Dann hab ich im Patch 2.04 eine neue Map gebaut, (und dann auch eine partie mit einem Richard gemacht und da war auch noch alles okay) und nu mit 2.05 - hotfix baut er da nur eine.

An den Einstellungen hab ich quasi nix geändert (außer klar nun die neuen sachen mit dem Schiebe Regler) und den Ochsenjoch-Spam fix aktiviert und meine Farbe auf Blau gesetzt. (Richard war somit Rot, falls das vielleicht irgendwie damit zusammenhängt)

Ich teste dann im verlaufe des Abends/Tages, was passiert wenn ich den Patch deinstalliere und neu installiere.

**Comment by Swartonf** [comment]
Habe schon einige Kämpfe gemacht, habe auch keine Bugs mit Richard. Das einzige was nur noch lästig ist, ist bei mir das steigende Splitten der Angriffswellen von so ziemlich allen AI's. Saladin und Abbt gefühlt am schlimmsten :D

**Comment by TheSnowyChickens** [comment]
So, habs getestet: (Patch is deinstalliert)
- auf der eigen erstellten Map baut er bis zu 4
- auf der Grenzpatrouillen Map hat er, anstatt 0, 2 Gebaut

**Comment by TheSnowyChickens** [comment]
Ahh, ein neu installieren des Patches hat das anscheinend gefixed, er baut wieder welche. Danke. :)

Ich schließ den Issue dann.
