### ISSUE TITLE
[GER] Fehler beim Installieren der eigenen aic-Datei im UCP v2.14

### ISSUE THREAD

**Issue by R3dsleeve** [Sh0wdown/UnofficialCrusaderPatch#678]
![fehlermeldung beim installationsversuch der aic im crusader patch v2 14](https://user-images.githubusercontent.com/46421206/97913205-4a87cb00-1d4e-11eb-9676-2f9a8bb7bc53.png)

Die Aic-Datei hab ich mal hier hochgeladen:
https://www.file-upload.net/download-14345261/red2020.json.html

Vllt kann mir jemand helfen, hocke schon seit einigen Stunden an der selben Stelle :(
Vielen Dank im voraus.

Gruß
Redsleeve

**Comment by Truetobi91** [comment]
Das sieht nicht so aus als sei der Fehler in der AIC. Hast du SHC auf der aktuellsten Version?

**Comment by R3dsleeve** [comment]
ich hab den fehler gefunden, hatte wazir 2x als char drin.. wohl ein copy and paste fehler..
