### ISSUE TITLE
Version Differences in Stronghold Crusader.exe

### ISSUE THREAD

**Issue by ihy1993** [Sh0wdown/UnofficialCrusaderPatch#679]
Hey, whenever i try to install the patch, i get this message:

"Version Differences in Stronghold Crusader.exe: o_playercolor_ai_order_menu_emblem BlockNotFound"

In the end of the installation process i get the same message for Stronghold Crusader Extreme.exe

When in game, there are no changes being visible and the patch does not work.

Can somebody help me out? Thank you!

**Comment by Truetobi91** [comment]
What language to you play the game and what version do you have installed? You can usually see the version number in the bottom left corner in the main menu.

**Comment by ihy1993** [comment]
I have the 1.3 Version, but installed the 1.4.1 Patch from Firefly. After i install the UCP it somehow switches back to 1.3 in the menu. Language is German.

**Comment by J-T-de** [comment]
The switch back happens because the UCP backup exe is still the old version

 You need to uninstall the patch, then update to 1.41, and then patch.

**Comment by ihy1993** [comment]
Thanks! That worked! However, Starting Troops and Starting Goods does still not work for me

**Comment by Krarilotus** [comment]
resolved
