### ISSUE TITLE
Another Apple Farm Bug

### ISSUE THREAD

**Issue by Truetobi91** [Sh0wdown/UnofficialCrusaderPatch#682]
This stone wall renders the apple farm useless. Work for other inaccessable tiles as well, e.g. the dairy farm fence. The stone wall ist directly adjacent to the farm but leaves a 1 tile gap between the apple next apple tree. The worker will just continous to stand up from his chair and sit back down. However he can still collect apples from other apple farms. 

![grafik](https://user-images.githubusercontent.com/48789759/98106006-0ce38900-1e99-11eb-9d95-257ba79edda8.png)

**Comment by LordHansCapon** [comment]
That happens because you blocked the first destination of the farmer, this could be changed by moving the destination inside the apple farm.

**Comment by Truetobi91** [comment]
Adding a starcase indeed makes the farmer go up there and get apples from on top of the wall. 

Adding to my original investigation: The farmer with the blocked farm can still collect from other farms (as I said) and other farmers can still collect from the other farms.

**Comment by Krarilotus** [comment]
fixed already :)
