### ISSUE TITLE
Troop command waypoints

### ISSUE THREAD

**Issue by MaxVonMustermann** [Sh0wdown/UnofficialCrusaderPatch#693]
Since the pathfinding in Stronghold is not the best to say the least, I think it would be cool, if there was a way to have waypoints in the game. What I mean by that is that you hold (for example) the Shift-key, when commanding troups you set a waypoint and then set another one while keep holding the Shift-key. 
Currently, your troops will go the shortest way possible in order to reach a certain location. By adding the ability of creating several waypoints (which is a quite common one to exist in strategy games), this issue might become a little bit less annoying. I guess this might be implementable, since the basic mechanic (gathering points, patrol points) are already in the game.
Hope it became clear what I have in mind. Thanks.

**Comment by Halbarad1** [comment]
There is already a way: Click shift and then doubleclick with left mouse. For patroling its (when activated) just shift and one click on left mouse. But yes, would be nice if you wouldn't need that doubleclick.

**Comment by GRhin** [comment]
Um, that double click isnt needed. 
If you give an instruction before starting giving waypoints you will be unable to give waypoints , just deselect the units and select them again and then give waypoints. No problem. I have a YouTube video on it if you would prefer that, just search my username and movement

**Comment by Halbarad1** [comment]
Oh yeah you are right, doubleclick isn't needed.

**Comment by MaxVonMustermann** [comment]
I didn't know about that. Thanks for the advice. This actually shows that it would've been better for Firefly to implement a list of key combinations into the settings.

**Comment by MaxVonMustermann** [comment]
I didn't know about that. Thanks for the advice. This actually shows that it would've been better for Firefly to implement a list of key combinations into the settings. 
**Shift + leftclick** does the job.

**Comment by GRhin** [comment]
It's actually in the manual. Which is in the support folder in the game install folder
