### ISSUE TITLE
Spielerfarben

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#7]
Ich weiß nicht genau, ob sich das praktikabel umsetzen lässt, da gewisse Informationen zu den Spielerfarben ja pro Map-Datei gespeichert werden... aber... 

- Ein Ansatz wäre, bei Spielstart die ausgewählte Karte (im Speicher) zu kopieren, dort die Spielerfarben-Nummern wunschgemäß (z.B. Spieler in lila, oder "Teamfarben") zu verändern (also nur temporär / ohne Veränderung der Original-Kartendatei), und dann ingame mit den Wunschfarben zu spielen. 
Setzt allerdings voraus, das Format von Kartendaten genau genug herauszufinden, um zuverlässig die Farben zu finden und entsprechend ändern zu können, und außerdem ist das vom Ablauf her evtl nicht ganz leicht zu integrieren. Und bei Karten mit bereits vom Kartenersteller angepassten Farben stellt sich die Frage, ob man das dann überschreibt oder nicht. 

- Ein anderer Ansatz wäre ggf, die Farbwerte für die Spielerfarben zu ändern, die vermutlich in der .exe selbst gespeichert sind. Also quasi... nicht zu sagen "Spieler 3, nutze die Farbe, die normal Spieler 8 hat", sondern zu sagen "Farbe Gelb, du bist jetzt Grün!" - unabhängig davon, welche Spieler auf verschiedenen Maps "die Farbe, die normal Spieler 8 hat" dann letztendlich nutzen.

**Comment by ByBurton** [comment]
@Heroesflorian Das halte ich eher für letzte Priorität, nach allen Bugfixes und Balancing.

Trotz allem wäre es durchaus angenehm.

**Comment by Sh0wdown** [comment]
> "Spieler 3, nutze die Farbe, die normal Spieler 8 hat"
Also ich würde da genau diesen Ansatz versuchen. :P
Allerdings bräuchte man dann auch ein Interface oder sowas, wo man die Spielerfarben festlegen kann.

**Comment by Heroesflorian** [comment]
@ByBurton Klar, ist nicht besonders wichtig, aber nach einer kurzen Kommentardiskussion auf YT, kam mir der Gedanke. 

@Sh0wdown Naja, der andere Ansatz würde halt, wenn das so prinzpiell funktioniert, kartenunabhängig bzw. kartenübergreifend funktionieren... (und man müsste sich nicht damit befassen, beliebig geänderte Farbzuordnungen in Spielerkarten finden und anpassen oder überschreiben/ignorieren zu können). 
Wenn dann auf einer Missions- oder Skirmish-Szenarienkarte z.B. eingestellt ist, dass z.B. die Spieler 6-8 allesamt die Farbe von Spieler 8 nutzen sollen (sprich alle normalerweise Grün sind), weil sie sich eine große Burg teilen, und man per Patch eingestellt hat, dass das, was standardmäßig "Grün" ist, stattdessen "Orange" ist, dann wären eben entsprechend Spieler 6-8 auf der Karte allesamt Orange, und damit nach wie vor farblich gleich. 
Wenn man stattdessen einfach nur ändert, dass Spieler 8 die Farbe von Spieler 2 hat, wäre Spieler 8 auf der Karte Orange und 6-7 immer noch Grün... bzw in welcher Farbe auch immer durch den Patch eingestellt wurde... und damit wäre die vom Szenarienersteller getroffene "Farbgruppierung" mehrerer Gegner nicht mehr sichtbar. 🤔 

Wobei das erstmal natürlich alles nur Theorie auf der grünen Wiese eines Mapmakers ist, der selber noch nicht wirklich tiefer in die Materie des Debuggens oder Disassemblens der Crusader.exe im Speziellen eingetaucht ist...
