### ISSUE TITLE
HOW TO INSTALL THE PATCH !!!! English,Русский,Deutsch.

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#70]
I apologize for the curvature :D 
(English) :dagger: 
1 Need a Steam version of Stronghold Crusader 1.41 (English or German).
P.S Pirate version may not work !!!
2 Download the patch and click on it.
3 Choose a language (English or German). Click OK
4 In the window that appears, select Continue if the game directory is automatically selected, if not, then specify the game directory.
5 Select the options you like in the tabs.
6 Click Install and then click Finished.
7 Go to the Stronghold Crusade and check the result!
By the way, check whether the patch is installed by looking at the lower left screen of the main menu. It shows the version or by increasing the speed with the + button!

(Русский) :dagger: 
1 Необходима версия Steam Stronghold Crusader 1.41 (Английский или Немецкий).
P.S Pirate версия может не работать !!!
2 Загрузите патч и щелкните по нему.
3 Выберите язык (английский или немецкий). Нажмите ОК.
4 В появившемся окне выберите «Продолжить», если каталог игры выбран автоматически, если нет, укажите каталог игры.
5 Выберите нужные параметры на вкладках.
6 Нажмите «Установить», а затем «Закончить».
7 Идите в Stronghold Crusade и проверьте результат!
Кстати, проверьте, установлен ли патч, посмотрев на нижний левый экран главного меню. Он показывает версию или увеличивая скорость с помощью кнопки +!

(Deutsch) :dagger: 
1 Benötigen Sie eine Steam-Version von Stronghold Crusader 1.41 (Englisch oder Deutsch).
P.S Piratenversion funktioniert möglicherweise nicht !!!
2 Laden Sie den Patch herunter und klicken Sie darauf.
3 Wählen Sie eine Sprache aus (Englisch oder Deutsch). OK klicken
4 Wählen Sie im angezeigten Fenster Weiter aus, wenn das Spieleverzeichnis automatisch ausgewählt wird. Andernfalls geben Sie das Spieleverzeichnis an.
5 Wählen Sie die gewünschten Optionen auf den Registerkarten aus.
6 Klicken Sie auf Installieren und dann auf Fertig stellen.
7 Gehe zum Festungskreuzzug und überprüfe das Ergebnis!
Überprüfen Sie übrigens, ob der Patch installiert ist, indem Sie auf den Bildschirm unten links im Hauptmenü schauen. Es zeigt die Version oder durch Erhöhen der Geschwindigkeit mit der + Taste!

1 ![11](https://user-images.githubusercontent.com/41998977/48866781-162ad680-ede5-11e8-95da-0d0829ae31cf.png)
2 ![2](https://user-images.githubusercontent.com/41998977/48860773-ebd01d80-edd2-11e8-8f37-8933c487c6be.png) 
3 ![33](https://user-images.githubusercontent.com/41998977/48861670-410d2e80-edd5-11e8-8e48-1d85abaedfab.png)
4 ![44](https://user-images.githubusercontent.com/41998977/48862521-a82be280-edd7-11e8-9376-a7b02612d4d6.png)
5 ![5](https://user-images.githubusercontent.com/41998977/48861088-c859a280-edd3-11e8-92ce-5feccd9bd9b3.png)
5.1 ![6](https://user-images.githubusercontent.com/41998977/48861242-2ab2a300-edd4-11e8-9a68-145913675c27.png)
6  ![5 1](https://user-images.githubusercontent.com/41998977/48861563-eb388680-edd4-11e8-8958-7ac8e400d3b2.png)
7 ![result](https://user-images.githubusercontent.com/41998977/48861287-43bb5400-edd4-11e8-8721-525ece73036a.png)

**Comment by Lolasik011** [comment]
I apologize for the curvature: D

**Comment by zilanko** [comment]
thank u man; i facepalmed myself when i read it because its so easy actually

**Comment by Evrey** [comment]
That looks an awful lot like Google translate, but the overall effort and screenshotting is worth appreciating.

**Comment by Lolasik011** [comment]
@Evrey I just don't know English very well. But I don’t know German at all :(. So I’m using a translation.

**Comment by Heroesflorian** [comment]
Well, so far it is the best guide we have, so thanks for the effort! Others can still submit an improved version later if there is the need for it.

**Comment by Krarilotus** [comment]
I dont think this is an issue, you can still refer to it or make an updated wiki page if needed. For now i will close this issue.

**Comment by zimpley** [comment]
Hi, I can't run the program, nothing happens when I click on the program
