### ISSUE TITLE
Feature: Place buildings on workers/peasants

### ISSUE THREAD

**Issue by Krosstack** [Sh0wdown/UnofficialCrusaderPatch#709]
Hello! I think it would be nice to be able to place your buildings on workers as the AI does in order to delay the construction of the castle(the way you like it) as little as possible. It's most annoying with walls and huge buildings like the cathedral. I know it's not "natural" but if the AI can do that, I think we should be able too.

**Comment by Truetobi91** [comment]
You might want to check for existing issues because this has been brought up multiple times before, has open issues allready and has been solved for the next release as far as I can tell.

**Comment by Krosstack** [comment]
> You might want to check for existing issues because this has been brought up multiple times before, has open issues allready and has been solved for the next release as far as I can tell.

Well these are great news! Thanks a lot! I checked the existing issues but I didn't see it.

**Comment by J-T-de** [comment]
I think this can be closed, since the same topic already exists https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/595, and is fixed here https://github.com/Sh0wdown/UnofficialCrusaderPatch/pull/639 .
