### ISSUE TITLE
Changing DefUnits to crossbowman for philip...

### ISSUE THREAD

**Issue by R3dsleeve** [Sh0wdown/UnofficialCrusaderPatch#711]
Hi there, so i am changing the KI philip to something stronger and giving him "crossbowman" as Def units only, but if i do that, he doenst use them to defend the towers... (see screenshot) if i switch crossbowman with "EuropArcher" it works... any ideas how to fix that?

(I also figured something out similar with emir, if i say he uses 1-7 "defunits" for "ArabArchers" and the 8 slot is "EuropArchers", he still uses a ton of "EuropArchers" compared to the others, so something else must set the priority for the def unit recruting.)

![01](https://user-images.githubusercontent.com/46421206/100387692-01fbbe80-3029-11eb-9d9d-19268a2c538a.jpg)
![02](https://user-images.githubusercontent.com/46421206/100387695-032ceb80-3029-11eb-8b78-ba4ee1e5ee2d.jpg)

**Comment by R3dsleeve** [comment]
![01](https://user-images.githubusercontent.com/46421206/100387869-628afb80-3029-11eb-9826-a262f6a2a067.jpg)

**Comment by R3dsleeve** [comment]
edit: works, but it taks way longer than usual, but the problem stays with emir.

**Comment by Fufudrache** [comment]
Did you change the aivs (castles) of philip? His vanilla castles don't use crossbowman.

Also did you change the aic so that philip does not sell crossbows and leather armors?

**Comment by R3dsleeve** [comment]
> 
> 
> Did you change the aivs (castles) of philip? His vanilla castles don't use crossbowman.
> 
> Also did you change the aic so that philip does not sell crossbows and leather armors?

in the picture you can see the crossbowman :)
it just took much longer for him to sent them to their spots.
