### ISSUE TITLE
Unistall Patch Removes AIVs

### ISSUE THREAD

**Issue by GrosserBauerr2** [Sh0wdown/UnofficialCrusaderPatch#715]
Hey guys I noticed that, if you unistall the UCP the Patcher removes the AIVs. The problem is, if you never changed some AIVs with the patcher you never got an backup folder. It would be nice if the patcher checks, if an backupfolder exists and if there are files inside.

**Comment by GRhin** [comment]
This is implemented into the new gui which has a pr up for testing. Feel free to test that out.

**Comment by GRhin** [comment]
#710

**Comment by J-T-de** [comment]
Might also be related to https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/643.

**Comment by Krarilotus** [comment]
this will most likely be fixed with the next version 2.15 coming up!
