### ISSUE TITLE
Can't add Human Player to Match

### ISSUE THREAD

**Issue by felicedanieli** [Sh0wdown/UnofficialCrusaderPatch#744]
Hi Team,

I am a firtstime UCP user so maybe the solution is easier than worth your time. So appolagies in advance :) 
But for some reason I cant seem to add myself "Human" to matches (or even appear in the first place).

Below screenshots of the lobbies. Tried reinstalling the patch or look for options in the General Menu, but no luck. (and couldn't seem to find the issue in a previous thread)

Thanks in advance for your help and looking forward trying a more advanced game experience!

SinglePlayer Lobby
![Einzelspieler Lobby](https://user-images.githubusercontent.com/77408139/104492919-9cfa2900-55d4-11eb-9a8b-57cf108b0795.png)

Crusade Lobby 
![Kreuzzug Lobby](https://user-images.githubusercontent.com/77408139/104492926-9e2b5600-55d4-11eb-9486-061bb3eb1d6f.png)

**Comment by Truetobi91** [comment]
Did you by any chance activate the option "Spectator Mode enabled" which literally removes you from the game?

**Comment by felicedanieli** [comment]
See, it's the god damn simple things in life that can have the largest impact...
You were 100% correct! Thank you very much for lending me your brainpower... thought I was losing my mind for some time.

Have a great rest of the week and also a good 2021 :)

**Comment by Monsterfisch** [comment]
you might want to close the issue ;)
