### ISSUE TITLE
Economics of AI

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#77]
@Sh0wdown I noticed that the Arab Lords are quickly recruiting an army and are left with good economics and the European Lods are recruiting  troops and staying with poor economics.

I think this is due to the fact that European Lords need resources to create an army, and the Arab Lord needs only gold.

**Comment by PitchNeeded** [comment]
I notice the opposite in fact, Arabian lords (apart from Sultan who has a slow recruitment rate) tend to spend their money faster on a 40,000 gold map unless they are in an excellent economic position.

European lords don't need resources to create an army necessarily, they can also buy in weapons if lacking (although it is of course quite expensive to do so).

**Comment by Lolasik011** [comment]
@PitchNeeded Yes, but when they buy weapons from them economics weakens even more.

**Comment by Sh0wdown** [comment]
What improvement does this issue exactly aim at? Better economy for the AIs?

**Comment by PitchNeeded** [comment]
Also on the subject of AI economies, as I discussed before in another issue, for Sultan (whose economy can struggle if he starts with 2000 gold and the quarry isn't that close by), buying in 4 food types could really help him raise his tax income, as well as fit in with his character of enjoying feasting and making his people happy.

**Comment by Lolasik011** [comment]
@Sh0wdown I think. In order not to change the entire economics of AI, you can enter the function 2x 3x 5x and infinite resources for AI. Then you do not have to rewrite the entire economy. And so that these functions are  in the launcher. And to be these functions were to choose from in the launcher.

Or add a few economic buildings with  for AI and it will be necessary to rewrite the economy.

**Comment by Panbutt** [comment]
> Also on the subject of AI economies, as was discussed before in another issue, for Sultan (whose economy can struggle if he starts with 2000 gold and the quarry isn't that close by), buying in 5 apples, 5 cheese, 5 meat and 5 bread instead of 10 apples as he does currently could really help him raise his tax income, as well as fit in with his character of enjoying feasting and making his people happy.

I would actually love this tbh. I would love if Sultan was actually good economist but he spends all of his gold on his people. Buying in good food, lavish ale for taverns, strong warriors to protect them, etc. I like the idea of a Lord that buys in things more than they produce and Sultan fits the bill. Granted, he'd likely need some sort of industrial boost as 2 quarries with 50% positive fear factor won't be able to fund it all.

**Comment by PitchNeeded** [comment]
> > Also on the subject of AI economies, as was discussed before in another issue, for Sultan (whose economy can struggle if he starts with 2000 gold and the quarry isn't that close by), buying in 5 apples, 5 cheese, 5 meat and 5 bread instead of 10 apples as he does currently could really help him raise his tax income, as well as fit in with his character of enjoying feasting and making his people happy.
> 
> I would actually love this tbh. I would love if Sultan was actually good economist but he spends all of his gold on his people. Buying in good food, lavish ale for taverns, strong warriors to protect them, etc. I like the idea of a Lord that buys in things more than they produce and Sultan fits the bill. Granted, he'd likely need some sort of industrial boost as 2 quarries with 50% positive fear factor won't be able to fund it all.

Yeah Sultan could do with another quarry and less woodcutters (Sultan sells a lot of wood but as you know selling wood doesn't make much money compared to selling stone). Ale would be good for Sultan, he would only need 2 or 3 hops farms and a brewery and inn, and an inn would look good in his vanilla castle too.

**Comment by Sh0wdown** [comment]
Issue with the same topic:
https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/63

**Comment by PitchNeeded** [comment]
@Showdown Can you maybe consider Sultan buying in 5 apples, 5 bread, 5 meat and 5 bread (instead of buying in 10 apples) in the next patch, I would really like to see it in the game. It would give him a decent economic boost without changing his vanilla castle and would fit with his personality of enjoying feasting.

**Comment by PitchNeeded** [comment]
Another point to do with AI economics, if bread AIs run out of wheat and flour, they will buy in either 2 flour or 20 wheat depending on how much gold they have. 

Buying in 2 flour is what they seem to do if they don't have enough gold to buy in 20 wheat and isn't the best thing economically. It is quite expensive and doesn't make a big amount of bread. They would be better buying in smaller amounts of wheat (such as 5 wheat at a time).
