### ISSUE TITLE
Polish Translation

### ISSUE THREAD

**Issue by Sh0wdown** [Sh0wdown/UnofficialCrusaderPatch#78]
I noticed there are quite many Polish Stronghold fans around here for which I would like to add more translations to the installer. Since I don't speak any Polish it would be nice if some of you people could help out. I will explain the structure of the translation file below. It would be great if you could cooperate  between each other to provide a single localization file in the end (not that everyone creates his own).

If you have questions about the meaning of some texts you can always ask me and I will try to elaborate a bit.

[The Polish localization file can be found here.](https://github.com/Sh0wdown/UnofficialCrusaderPatch/blob/master/UnofficialCrusaderPatch/Localization/Polish.txt) You can simply download/copy the text file to edit and reupload it here or if you know how to use GitHub, fork the repository.

The structure works as follows:

```
Name  
{  
	"Nieoficjalny Crusader Patcher"  
}
```

This is one translation element. "Name" is an identifier for the program to know where to put the text. Do not change it! The text of this element which you have to translate is the one between the quotes " ". Edit this one.

If you think your line becomes too long for your editor, you can put a "&" before a line break, and the program will ignore the line break when showing the text. Example (with google translate):

```
ui_chooseLang  
{  
	"Wybierz &  
język dla  
tej konfiguracji z poniższej listy."  
}
```

As you can see, the line break after "Wybierz &" is ignored, but the line break after "język dla" is shown.
![image](https://user-images.githubusercontent.com/9576090/48942218-d1a35600-ef1e-11e8-9ef6-21c78ce3fa65.png)

**Comment by Rakso69** [comment]
I can do that later. I'm polish.

**Comment by Radek2019** [comment]
:D

**Comment by Sh0wdown** [comment]
I merged your edits into my branch, Radek. Thank you very much!
I also added some new entries today, it would be great if you could take another look.
Everything new or changed is at the bottom of the file.

**Comment by Sh0wdown** [comment]
@Radek2019 New texts for 2.07 are added.

**Comment by Sh0wdown** [comment]
Thanks! :)

**Comment by Krarilotus** [comment]
@Radek2019 pls reopen if this issue is still necessary, or if you dont find the time to support the patcher with current polish updates.
