### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Sh0wdown** [Sh0wdown/UnofficialCrusaderPatch#79]
Since I will extend the language options for the installer, I would like to know whether there are also Russian Stronghold Fans around here who would be willing to help with a Russian translation?

**Comment by Lolasik011** [comment]
I wish I could do this. But I dont know how. Is this just a launcher translation?

**Comment by Sh0wdown** [comment]
The translation is written into a text file, of which I will explain the structure below. If you have questions about the meaning of some texts you can always ask me and I will try to elaborate a bit.

[The Russian localization file can be found here.](https://github.com/Sh0wdown/UnofficialCrusaderPatch/blob/master/UnofficialCrusaderPatch/Localization/Russian.txt) You can simply download/copy the text file to edit and reupload it here or if you know how to use GitHub, fork the repository. 

The structure works as follows:

```
Name  
{  
	"неофициальный Crusader Patcher"  
}
```

This is one translation element. "Name" is an identifier for the program to know where to put the text. Do not change it! The translated text for the element is then put between quotes " " which you have to edit.



If you think your line becomes too long for your editor, you can put a "&" before a break, and the program will ignore the break when showing the text. Example (with google translate):

```
ui_chooseLang  
{  
	"Пожалуйста, &  
выберите язык  
для этой настройки из списка ниже."  
}
```

As you can see, the line break after "Пожалуйста, &" is ignored, but the line break after "выберите язык" is shown.
![image](https://user-images.githubusercontent.com/9576090/48947847-e25dc700-ef32-11e8-9247-473d99c31897.png)

**Comment by Lolasik011** [comment]
@Sh0wdown And how do I edit the localization file.

**Comment by Lolasik011** [comment]
@Sh0wdown I have already finished Translation !!!

**Comment by JuGGerNaunT** [comment]
I think author know what google translate is and he asked to make human translation.

**Comment by Lolasik011** [comment]
@JuGGerNaunT What ??? I translated myself. Do not know Russian do not speak.

**Comment by Sh0wdown** [comment]
Thank you, I will add it in the next release and post here if more translations are needed in the future.

**Comment by Sh0wdown** [comment]
There are some new entries to translate on my branch. I put everything new or changed to the bottom of the file. It would be nice if you could take another look.

**Comment by Lolasik011** [comment]
@Sh0wdown Ok

**Comment by Sh0wdown** [comment]
@Lolasik011 There are some new changes, could you take another look (at the far bottom)?

**Comment by Lolasik011** [comment]
@Sh0wdown No problem

**Comment by Sh0wdown** [comment]
@Lolasik011 New texts for 2.07 have been added.

**Comment by Lolasik011** [comment]
@Sh0wdown What do you need to translate?

**Comment by Lolasik011** [comment]
https://github.com/Sh0wdown/UnofficialCrusaderPatch/compare/master...Lolasik011:patch-7
@Sh0wdown 
translation updated

**Comment by Sh0wdown** [comment]
thank you very much!

**Comment by Lolasik011** [comment]
@Sh0wdown no problem

**Comment by Sh0wdown** [comment]
@Lolasik011 There are a few new texts for a hotfix.

**Comment by Lolasik011** [comment]
https://github.com/Sh0wdown/UnofficialCrusaderPatch/compare/master...Lolasik011:patch-8
@Sh0wdown translation is complete

**Comment by Sh0wdown** [comment]
@Lolasik011 New texts added! Also, could you send me a simple mail to the e-mail address on my [GitHub Profile](https://github.com/Sh0wdown) so I have yours?

**Comment by Lolasik011** [comment]
@Sh0wdown https://github.com/Sh0wdown/UnofficialCrusaderPatch/compare/master...Lolasik011:patch-9
translation is complete

**Comment by Lolasik011** [comment]
@Sh0wdown 
translation is complete https://github.com/Lolasik011/UnofficialCrusaderPatch/blob/patch-10/UnofficialCrusaderPatch/Localization/Russian.txt

**Comment by Lolasik011** [comment]
Sorry was busy. Translation is done!

**Comment by Lolasik011** [comment]
https://github.com/Lolasik011/UnofficialCrusaderPatch/tree/patch-13 
translation is complete !

**Comment by Lolasik011** [comment]
@Sh0wdown 
Did I translate everything?

**Comment by Sh0wdown** [comment]
> @Sh0wdown
> Did I translate everything?

Yes, I think so. Thank you very much! :)

**Comment by Lolasik011** [comment]
@Sh0wdown 
I am glad that I can help.

**Comment by Lolasik011** [comment]
@Sh0wdown New translation 2.13
https://github.com/Lolasik011/UnofficialCrusaderPatch/blob/patch-17/UnofficialCrusaderPatch/Localization/Russian.txt

**Comment by Lolasik011** [comment]
@Sh0wdown https://github.com/Lolasik011/UnofficialCrusaderPatch/tree/patch-18
Small Fix!

**Comment by Krarilotus** [comment]
I believe Lolasik011 is now able to contribute and update translations himself.
