### ISSUE TITLE
Patch 2.15 Ladderman patch options dosen't work

### ISSUE THREAD

**Issue by Mrragger2** [Sh0wdown/UnofficialCrusaderPatch#838]
since the last patch the Ladderman cost 4 not 20 gold and there Armor is much weaker.

**Comment by GRhin** [comment]
And you absolutely guaranteed have the first option clicked in the units tab that enables these specific changes? This was not modified so it should work as long as the option is selected.

**Comment by Truetobi91** [comment]
Udwin also stated that in his latest video about the UCP

**Comment by Mrragger2** [comment]
just installed it again now it's works fine.
