### ISSUE TITLE
Shortcut to save, autosave

### ISSUE THREAD

**Issue by Silentraz** [Sh0wdown/UnofficialCrusaderPatch#84]
Now saving game needs Esc and few precise clicks.

Idea is simple - add shortcut to autosave (for example F5) and autosaving (every choosen few minutes).

Second one will be very useful when improving mod - naturally more ways to crashing.

**Comment by Heroesflorian** [comment]
Hmm... considering that autosaving is an option for multiplayer games already, I guess that could be quite possible for singleplayer as well...

**Comment by Sh0wdown** [comment]
The next Release will implement quicksaving.
