### ISSUE TITLE
Another 'improved AI castles' setting for the installer

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#85]
It would be good to introduce another separate 'improved AI castles' setting in the installer for the patch, which would be the same as Evrey's fixed vanilla castles but with ballistas added to the free towers for Nizar, Wazir, Emir and Pig's castles. Pig would also have one mangonel though along with a ballista or that would fit with his brutal personality. Emir would still keep his existing mangonel or mangonels but have three ballistas on his big towers that don't have mangonels (preferably on the closest mangonel-free towers to the front in his biggest castles).

The Evrey's fixed vanilla castles setting would still exist too for people who just want to use the vanilla castles without added ballistae.

I know you can change the AIV files easily but it would still be good to have this as a setting for those that like using the vanilla castles but want them to be a little bit better defensively at destroying siege engines.

**Comment by Sh0wdown** [comment]
I don't know how to edit AIV files but I am willing to add more (complete) mod castles to the installer if people send them to me.

**Comment by MostWanted38** [comment]
@Sh0wdown for modifying the AIV Files you can use the "Stronghold Crusader Modding Utilities". There is an AIV Editor inside where you can create own files & modify existing castles. The game only uses the <ai_name><1-8>.aiv files, so all files in range of rat1.aiv until rat8.aiv for example

**Comment by Heroesflorian** [comment]
> @Sh0wdown for modifying the AIV Files you can use the "Stronghold Crusader Modding Utilities". There is an AIV Editor inside where you can create own files & modify existing castles. The game only uses the <ai_name><1-8>.aiv files, so all files in range of rat1.aiv until rat8.aiv for example

@MostWanted38 I suspect he knows how to edit AIV files using the AIV editor. Modifying AIVs (e.g. the Evrey vanilla fixed castles) programmatically during the installation process of the patch is on a completely different level, though. 

And generally speaking, if you want to have a version of a specific AIV with specific modifications in the game, and know yourself how to modify AIVs, you can always do that yourself. 

I see more potential for extending the patch to specify arbitraty AIVs to use from a separate folder where one can put the customized set of castles one would like to have, once, and then just let the patch apply those castles to the game's aiv folder upon (re)installation automatically. 


> I don't know how to edit AIV files but I am willing to add more (complete) mod castles to the installer if people send them to me.

@Sh0wdown Do you mean "sets of full 128 mod castles, 8 for each AI" from one particular author?

**Comment by Evrey** [comment]
> I am willing to add more (complete) mod castles to the installer if people send them to me.

In case you for example extend the tool to also download Tatha's modded AIVs, you might want to have an eye on whether they work with regular skirmish matches. In general it would make sense to mark all patch settings that would break regular skirmishes. Most modders don't compromise their design for the good ol' 100 missions.

**Comment by Sh0wdown** [comment]
> @Sh0wdown Do you mean "sets of full 128 mod castles, 8 for each AI" from one particular author?

More or less yes. At least I don't want to add hundreds of castle mods which only change like one single aiv file.

**Comment by PitchNeeded** [comment]
> > I am willing to add more (complete) mod castles to the installer if people send them to me.
> 
> In case you for example extend the tool to also download Tatha's modded AIVs, you might want to have an eye on whether they work with regular skirmish matches. In general it would make sense to mark all patch settings that would break regular skirmishes. Most modders don't compromise their design for the good ol' 100 missions.

Evrey, could you add a couple of ballistas to the vanilla Wazir, Emir and Nizar's castles and add both mangonels and ballistas to the vanilla Pig castles and make a new Evrey's improved vanilla castles patch. Also try and give Frederick a ballista too in his castles with the mangonels if that is possible! I could edit the AIVs easily myself but the problem is that I don't know how to upload the files to here for the use by the patch :(

**Comment by Lolasik011** [comment]
@PitchNeeded really looking forward to your castle

**Comment by PitchNeeded** [comment]
> @PitchNeeded really looking forward to your castle.

That's great, I think it would be a great option to be able to have Nizar, Emir, Wazir and Pig still having vanilla castles but using more of their big towers for siege engines.

I will see if I can give Frederick's vanilla castles with the front mangonels another tower with a ballista. He needs one, especially with the talk of reducing mangonel power in the next patch.

> Do you need help ?

Not with modifying the AIVs but I do need to know how to send the AIVs to Sh0wdown for use in the patch...

**Comment by PitchNeeded** [comment]
> @PitchNeeded Try putting files on google disk. And give the link @Sh0wdown.

Don't know how to do that, but I will upload them to Stronghold Heaven and then post it here for Sh0wdown to use in the installer.

**Comment by Evrey** [comment]
[Stronghold Heaven](https://stronghold.heavengames.com/) doesn't know how to HTTPS. At least I'm highly against adding insecure download sources to the patch tool.

**Comment by PitchNeeded** [comment]
@Sh0wdown Here are the edited Evrey's fixed vanilla AIVs for Nizar, Emir, Pig and Wazir with ballistae finally being used by all of them and mangonels for Pig (as he likes brutality) so you can put this optional modification for Evrey's fixed vanilla castles on the patch. These four AI lords finally use towers more effectively.

https://drive.google.com/drive/folders/1-IoNFop-ZoTKzF-FtryQP3msKffryekD?usp=sharing

**Comment by Sh0wdown** [comment]
Will be included in the upcoming release.
