### ISSUE TITLE
Patch Compatibility with Crusader Extreme / Custom Skirmish Trail Missions? 

### ISSUE THREAD

**Issue by Heroesflorian** [Sh0wdown/UnofficialCrusaderPatch#86]
It would be cool if the patch could also be applied to Extreme. 

Considering Crusader Extreme and regular Crusader are almost the same anyway, I think the required effort for that wouldn't be particularly big, and it would not only allow players to enjoy the Extreme-only content with Patch improvements, but also make AI battles in Extreme with Patch improvements possible. 

Now you may ask why that would be any relevant? 
Well... in Crusader, one cannot really specify what particular AIV castles an AI should use in a particular game, which makes it pretty much impossible to realize custom battles with several same-type AI players who use specific, different castles in a reliable way (i.e. as it is for the skirmish trail missions). 
In Extreme on the other hand, this is very well possible - by setting up custom skirmish trail missions including custom start gold settings, alliances, maps, map positions, ai character types, aivs and ai/human advantage levels. 
All one needs to do for this is adjust a few values in the "extremeTrail.csv" (a human-readable text/table file), and it opens up a bunch of new possibilities for AI battles (or even just custom singleplayer skirmish games with AIs).

**Comment by ByBurton** [comment]
I can not find this "extremeTrail.csv" file, is it not in the Stronghold Crusader installation directory?

**Comment by Sh0wdown** [comment]
You can by renaming "Stronghold_Crusader_Extreme.exe" to "Stronghold Crusader.exe", applying the patch and then reverting the name change. It might be possible that some settings do not work so you have to test which ones give an error message and not use those.

**Comment by Heroesflorian** [comment]
@Sh0wdown Well, the troop limit increase in particular wouldn't surprise me actually, considering Extreme has a different regular value, which probably won't match the regular Crusader's value the Patch is searching for... on the other hand, the regular 10k unit limit makes that particular patch setting redundant anyway, so if the other stuff mostly works, that will do well! :)
But anyway, will try to test it this weekend. 

@ByBurton Never mind the duplicate files, they are leftovers from a previous test from a while ago... but anyway, as you can see, the extremeTrail.csv resides in the regular installation directory. For my 1.2 non-Steam Crusader Extreme installation at least. Would have to check on my other machine whether the Steam version behaves differently, but in theory it should just be there. 
![grafik](https://user-images.githubusercontent.com/12549394/49052029-81f8af00-f1ea-11e8-94a3-03b9482ef23e.png)

**Comment by Sh0wdown** [comment]
Closing this, contiued in Issue https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/210.
