### ISSUE TITLE
Kleine Anmerkung an Release 2.05a 

### ISSUE THREAD

**Issue by dot3x3** [Sh0wdown/UnofficialCrusaderPatch#87]
Erstmal danke für die tollen neuen Features!

Kleine Anmerkung:
Die Einstellung für die Spielerfarbe ist für mich nicht ganz logisch. Man kann die Checkbox nicht setzen, was mich im ersten Moment verwirrt hat. Sie wird automatisch gesetzt wenn man ein andere Farbe wählt.

Kann die Checkbox dann nicht komplett weg (bzw versteckt werden, falls du sie abfragst)?

**Comment by Sh0wdown** [comment]
Hab die CheckBox jetzt (visuell) "deaktiviert". Stattdessen geht nun das Untermenü zur Farbauswahl auf wenn man draufklickt. Ich werde sie aber dort lassen damit man sieht ob die Option aktiv ist, wenn das Untermenü zugeklappt ist.
