### ISSUE TITLE
Sachen, die ich gefunden habe durch testen mit dem KI Zuschauermodus

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#88]
Ich schreibe das hier mal kurz auf Deutsch:

Ich hab den AI only modus aktiviert, und einen Spielstand geladen, wodurch man volle Kontrolle einer KI bekommt, diese aber keine Gebäude mehr bauen kann.

Einige Sachen, die ich herausgefunden habe:

-Die KI wechselt permanent mit den Rationen und Steuern hin und her, viel zu oft. Sehr ineffizient
-Die KI steckt alle Truppen, die man für sie ausbildet, und die über das Limit der Angriffsarmee geht, auf Verteidigungspositionen. Beispiel: Richard hatte schon genug Bogenschützen für seine Angriffsarmee. Ich hab mehr für ihn ausgebildet, und er hat seine Türme endlich mal anständig bemannt!
![untitled](https://user-images.githubusercontent.com/25118004/49168743-7c10e400-f338-11e8-9b89-91075e9ce30a.png)

-Man hat einen Pseudo-Autoverkauf wenn man in diesem Modus spielt, was ich richtig geil finde <3
-Richard kann leider keine Leiterträger benutzen..... dachte, vlt. hat Firefly dass zwar programmiert, aber wieder rausgenommen... hätte ja sein können... Daher die vielen Leiterträger im Bild oben

**Comment by PitchNeeded** [comment]
> The AI ​​is constantly switching back and forth with rations and taxes, far too often. Very inefficient

I noticed this, when I tested the AIs, Abbot, Marshall and Saladin were switching between -20 and -24 taxes constantly :( Emir seemed be OK though, and only switched between the -20 and -24 taxes occasionally.

> The AI ​​is putting all the troops you train for them, going beyond the attack army's limit, to defensive positions. Example: Richard already had enough archers for his attacking army. I trained more for him, and he finally manned his towers decently!

I wonder will King Phillip do the same....

**Comment by ByBurton** [comment]
Richard was even more drastic with switching. From +3 to -20 like crazy...

**Comment by Lolasik011** [comment]
@ByBurton  Interesting observations. 
It will be necessary to play more with this mode.

**Comment by Heroesflorian** [comment]
> **It ist not a bug it is a feature**:) Maybe implement the mode for "playing as Richard"
> For finding bugs, or just for annother playing mode beside the normal, KI mode, KI assisted mode.

@Sh0wdown are there any plans for a "coop with AI" mode, currently? 
And do you happen to know if there is any other (open) issue where this has been proposed / discussed yet?

**Comment by Sh0wdown** [comment]
> > **It ist not a bug it is a feature**:) Maybe implement the mode for "playing as Richard"
> > For finding bugs, or just for annother playing mode beside the normal, KI mode, KI assisted mode.
> 
> @Sh0wdown are there any plans for a "coop with AI" mode, currently?
> And do you happen to know if there is any other (open) issue where this has been proposed / discussed yet?

Haven't gotten it to run in Multiplayer, only in SP. I think there is no issue yet.
