### ISSUE TITLE
Shortcut für Belagerungsgeräte, Shortcut um mehr Einheiten pro Klick zu rekrutieren

### ISSUE THREAD

**Issue by Halbarad1** [Sh0wdown/UnofficialCrusaderPatch#89]
Soweit ich weiß gibt es bislang keine Shortcuts um Belagerungsgeräte im Baumeistermenü auszuwählen. Gerade wenn man größere Mengen an Schilden, Katapulten und Feuerballisten bauen möchte würden entsprechende Tasten sehr angenehm sein, um nicht immer zwischen dem Klick zur Auswahl und dem Klick zum Platzieren des Zeltes wechseln zu müssen.

Auch schön wäre es, wenn (falls möglich) mit einem Shortcut in einem Rekrutierungsgebäude nicht mehr nur eine Einheit, sondern gleich 10 auf einmal rekrutiert werden würden um häufiges Klicken zu ersparen.

**Comment by Panbutt** [comment]
I agree with siege engine shortcuts. If a shortcut key for each siege engine isn't doable, would it be possible to have a system where you can place multiple siege engines when holding down a specific key, like Shift?

**Comment by Sh0wdown** [comment]
In der kommenden Version werden Zelte nicht mehr abgewählt, nachdem man eines platziert hat. Dadurch muss man die Geräte nicht immer wieder neu auswählen und kann fröhlich Zelte spammen. Ich denke das sollte dieses Problem lösen. 

Das mit dem Rekrutieren werde ich wohl nicht einbauen. Erstell dir doch ein Makro/Skript dafür. :p
