### ISSUE TITLE
Zusätzliche Erklärung zum Reverse Engineering für Stronghold Crusader

### ISSUE THREAD

**Issue by realvictorprm** [Sh0wdown/UnofficialCrusaderPatch#9]
Hoi Entwicklerkollege ;)

Kannst du hier erklären mit welchen Tools du Stronghold Crusader auseinander ninmst und mit welchen Ideen du auf die jeweiligen Code Abschnitte in der Exe gestoßen bist?

**Comment by ByBurton** [comment]
Versch. Hexeditoren können dir Zugriff auf den Binären (Hexadezimalen) Code des Spieles im Ram geben.
Geht auch mit Cheat engine glaube ich.
Man muss immer gucken, was sich wann verändert, hat sehr viel mit unglaublichem Durchhaltevermögen und Genauigkeit zu tun, was ich gar nicht habe :)

Für mich wäre das unmöglich, dabei habe ich selbst schon einige Sachen versucht, bin aber kläglich gescheitert.

Ich wollte u.a. damals ändern, wie viele Verteidiger eine KI auf eine Position setzt..

**Comment by ByBurton** [comment]
Hast du schonmal Spiele im Nachhinein editiert? Der bekannteste und einfachste Anfang wäre sowas wie Super Mario im Ram zu editieren, z.B. Gegner durch Pilze ersetzen, o.ä.

**Comment by Sh0wdown** [comment]
Ich benutze IDA, Cheat Engine (und OllyDbg).
Besonders [IDA's Graph View](https://www.researchgate.net/profile/Jennifer_Baldwin3/publication/220998403/figure/fig3/AS:339599600701443@1457978262353/The-Graph-View-in-IDA-Pro.png) hilft sehr die Funktionsabläufe zu verstehen.
Cheat Engine ist sehr hilfreich um zu sehen was sich für Werte verändern, wenn man etwas bestimmtes macht.

Für das Kaufen von Waffen habe ich zB erst selbst Waffen gekauft und in der Cheat Engine geschaut in welcher Funktion sich meine Waffenanzahl dadurch ändert. Diese Kauffunktion habe ich dann weiter verfolgt: wodurch wird sie aufgerufen, wann ruft die AI sie auf, wann nicht, etc.

**Comment by realvictorprm** [comment]
Jep, ich kenne die Tools um Reverse Engineering durchzuführen wie auch den Trick Code Snippets abzuspeichern und für die Ersetzungssuche zu benutzen, um einen versionsunabhängigen Modifikationsalgorithmus zu erstellen. Primär interessiert mich hier, ob es für die Stronghold Exe bestimmte Tricks gibt um schneller an die relevanten Stellen zu kommen.

**Comment by realvictorprm** [comment]
@Sh0wdown  An den Tools hat sich bisher wohl nichts geändert 😄

**Comment by Sh0wdown** [comment]
> Primär interessiert mich hier, ob es für die Stronghold Exe bestimmte Tricks gibt um schneller an die relevanten Stellen zu kommen.

Da in Crusader so ziemlich alles hardcoded ist, schätze ich gibt es keine einfachen Tricks.
Außer vielleicht wenn die Debug-Infos mitgeliefert wären, aber das ist hier ja nicht der Fall. :P

**Comment by ByBurton** [comment]
Warum wird das Problem / die Frage hier nicht geschlossen?

**Comment by realvictorprm** [comment]
Gibt es einen Sammelthread für Tipps und Tricks bereits?
E.g. Auflistung wie manche Mechaniken funktionieren in Stronghold Crusader und wie diese verändert werden können? (Mit theoretischen Ausblick)

Oder auch Erklärungen dazu wie die KI's bisher editiert werden können

**Comment by ByBurton** [comment]
@realvictorprm Dafür ist ein "issue" aber denkbar falsch.
Das kann man auf den discord server verschieben, oder einen eigenen anlegen oder andere Foren nutzen.
Also ich würde es nicht hier auf GitHub machen..

**Comment by Sh0wdown** [comment]
> Warum wird das Problem / die Frage hier nicht geschlossen?

Für den Fall von zusätzlichen Fragen.

> Gibt es einen Sammelthread für Tipps und Tricks bereits?

Nicht das ich wüsste.
