### ISSUE TITLE
When a new patch ?

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#90]
When will the new patch be released? And what will be new ?

**Comment by Monsterfisch** [comment]
I know its hard to be patient considering this is great. But we waited 12+ years for this mod to happen to begin with some days/weeks should be a fair tradeoff considering its a one-man project who has to make a living as well ;)

as for whats coming Showdown has not been that revealing about what's coming in the past either and i would argue a surprise is always nicer than getting spoiled

**Comment by Lolasik011** [comment]
Sorry for the stupid question...
