### ISSUE TITLE
Thanks for the cool patch !!!

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#98]
Thanks for the cool patch !!!

**Comment by PitchNeeded** [comment]
Thanks a lot indeed for the new patch....going to test it out now!

**Comment by Monsterfisch** [comment]
love the siege tent feature its fantastic

**Comment by Panbutt** [comment]
The siege tent placement and enemy soldiers attacking towers/gatehouses now are a blessing.
